### ISSUE TITLE
Can't get a che workspace created over OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#100]
This issue was opened by @pkettman: https://github.com/eclipse/che/issues/5283

Reproduction Steps:
After successful creation of a new project/codebase in OSIO, I initiated creation of a che workspace for it via 'Create workspace', but got following message: 'Failed to create workspace' and no workspace is shown on OSIO GUI.

OS and version:
Tested on OpenShift.io, using Google Chrome on Fedora

Diagnostics:
Output from Che server pod on OpenShift console shows that a workspace was created but afterwards a NullPointerException was thrown, see:
https://gist.github.com/pkettman/62ef8a9edc67f24b1dabfdef6466d41d

**Comment by pkettman** [comment]
This issue was experienced on che 1.0.154, today I executed OSIO Tenant upgrade to version 1.0.166, on which is this issue not present anymore!

**Comment by l0rd** [comment]
Ok thanks @pkettman. I'm closing this one but you can of course re-open it if you think we still should address something.
