### ISSUE TITLE
Need to enable che server monitoring  on prod / prod-preview via Jolokia & jmx_exporter

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1004]
This issue is about finalizing the work that has been started as part of the https://github.com/redhat-developer/rh-che/pull/950

**Comment by l0rd** [comment]
Based on [a discussion on mattermost](https://chat.openshift.io/developers/pl/xpws1wz6njrsjp6j1b9su7x6ga) with @fche, a prometheus endpoint may be more suited to export JVM metrics if this work will ever be ported upstream.

**Comment by ibuziuk** [comment]
Closing since JVM metrics are currently exposed as prometheus endpoints on prod and prod-preview
