### ISSUE TITLE
Che: 2 workspaces created instead of one 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1006]
Placeholder for https://github.com/openshiftio/openshift.io/issues/4416

**Comment by rhopp** [comment]
The openshiftio/openshift.io#4416 is now mostly about fabric8-ui to behave correctly, when there is not a correct answer from other services.

For the 504 - Gateway Timeouts, Lucia created housekeeping issue for servicedelivery team to investigate that: openshiftio/openshift.io#4416
