### ISSUE TITLE
Bug: Che doesn't show analytics error when opening it

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#101]
_From @luebken on June 9, 2017 10:6_

- If you add a vulnerable dependency an error is shown
- If you close Che and reopen it the error is not shown. 

_Copied from original issue: openshiftio/openshift.io#210_

**Comment by samuzzal-choudhury** [comment]
#### Steps to recreate:
1. Either create a new workspace or restart existing workspace from [Openshift console](https://console.starter-us-east-2.openshift.com/console/project/) (_go to <your username>-che project_).
2. Open Che IDE and if prompted to restart workspace, do that.
3. After the workspace restart is successful and the project appears on the "Project Explorer", open the pom.xml with the vulnerable package.
4. No CVE warning or recommendations will be shown in the pom.xml.
5. Enter a new line in the pom.xml to view the expected warning.

**Comment by l0rd** [comment]
Thanks @samuzzal-choudhury and @luebken for opening this issue. I've noticed that too yesterday. We will need to understand why this is happening.

**Comment by tsmaeder** [comment]
The behaviour seems to indicate that the language server computes errors on didChange,  but not on didOpen.

**Comment by l0rd** [comment]
@msrb Can you confirm if `didOpen` has or has not been implemented in recommendation LS?

**Comment by msrb** [comment]
> Can you confirm if didOpen has or has not been implemented in recommendation LS?

The LS should handle `didOpen`  as well, but this report indicates that there is a bug somewhere (in LS). I will open a separate issue in the fabric8-analytics/fabric8-analytics-lsp-server repository.

**Comment by msrb** [comment]
I am quite confident that this is a bug in LS, so this issue can be closed.

**Comment by ibuziuk** [comment]
closing. Related LS issue - https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/issues/13

**Comment by tsmaeder** [comment]
Did a call with @invincibleJai and we noticed that no diagnostics are emitted upon opening a particular pom file: https://github.com/invincibleJai/test-my-space19/blob/master/pom.xml
Note that the pom file is malformed (opening "<" missing on line 37).

**Comment by invincibleJai** [comment]
@tsmaeder thanks , have corrected it (it was a typo) still behaviour is same and this pom is generated when we choose basic vertx project template in osio.

CC @msrb
