### ISSUE TITLE
Need to compare Che 7 workspace startup time when using images from docker registry deployed in the user namespace in comparison with dockerhub / quay

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1014]
The idea is to deploy docker registry to the user namespace (similar approach is used for deploying custom   `che-plugin-registry` [1]  in the user namespace and using it instead of the default plugin registry deployed on OSD) and start Che 7 workpace based on the images from this custom `che-docker-registry`. After that it would be required to compare workspace startup time with the setup when Che 7 images are used from dockerhub / quay. 

**NOTE:** need to compare not only image `pulling` time, but rather pod `startup` time in general. There is an assumption that image extraction could be much faster when using custom docker registry in comparison with  dockerhub / quay.

[1] https://youtu.be/v92h4JV-bS8

**Comment by ibuziuk** [comment]
@l0rd maybe you have some hints how it should be possible to deploy custom docker registry to the user namespace on oso ?

**Comment by ibuziuk** [comment]
@amisevsk could you please also provide the list of different operations during workspace startup that take most time ?

**Comment by riuvshin** [comment]
@ibuziuk Can you please elaborate on why do you think that extraction of image pulled from custom registry would be faster?

**Comment by amisevsk** [comment]
@riuvshin The answer is that it doesn't, after all :). I think that the idea was to try and avoid some of the issues involved in the [AlwaysPullImages admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages).

In short: there's less than 5% difference between the two cases.

**Comment by amisevsk** [comment]
A general breakdown of start time:

### Che 7 Workspaces (ephemeral, but without https://github.com/eclipse/che/pull/11786 so normal PVC is still used for broker):
- Broker start: ~7.5 seconds average
- Pulling images: ~100 seconds on average (che-dev, che-machine-exec, che-hello, che-theia).
- Start Theia: ~10 seconds, sometimes quite a bit longer
![Che7](https://user-images.githubusercontent.com/16168279/48209446-35d0f200-e343-11e8-84b4-a11fdb9f3062.png)

### Che 6 workspaces (ephemeral):
- Setting up container: ~3 seconds
- Pulling image: ~20 seconds average (image is centos_jdk8)
- Starting agents: ~25 seconds (exec, terminal, wsagent) -- sometimes *much* longer for unclear reasons)
![Che6](https://user-images.githubusercontent.com/16168279/48209561-80526e80-e343-11e8-9350-7bdaf8f759af.png)

Also note that sometimes pulling takes no time at all -- not clear on why this happens, as it definitely should not be.

**Comment by amisevsk** [comment]
Closing as I think all information we're going to get at the moment is here, and there's no PR to be made.

**Comment by amisevsk** [comment]
Also as an example of how the AlwayPull admission control affects Che startup: The quickest Che 7 startup time was 28 seconds (where no actual pull seems to have happened). The slowest Che 7 start (with the pull) was 138 seconds.

**Comment by ibuziuk** [comment]
@riuvshin when we discussed this with @l0rd there was just an assumption that potentially extraction of 
could be much faster and we wanted to check it (but this does not seem to be the case) 

@amisevsk thanks for the data provided, but as I understand those graphs represent the startup time when images are pulled not from a local registry deployed in the user namespace, but from external one, right? Would it be possible to provide some data about workspace startup for local vs external registries or there is no difference at all ?

**Comment by ibuziuk** [comment]
> Also as an example of how the AlwayPull admission control affects Che startup: The quickest Che 7 startup time was 28 seconds (where no actual pull seems to have happened)

I also noticed that sometimes pulling is blazingly fast and sometimes really slow. I commented about it in the HK issue [1], but there has been no answer so far. @riuvshin maybe you can clarify how it is possible that pulling times vary so dramatically for the same image (workspace staring is done by the same user, in the same namespace)  ?

[1] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2350#note_432591

**Comment by gorkem** [comment]
I think the pull variance is because of the node level caches. So if the startup of a workspace happens on a node that has pulled an image earlier the image is served from the node's cache.

**Comment by ibuziuk** [comment]
Separate issue for making image pulling phase blazingly fast for predefined stacks have been created, so we can continue discussion there - https://github.com/redhat-developer/rh-che/issues/1056
