### ISSUE TITLE
Allow running Che 7 Workspace with development tooling but without recipe

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1025]
Placeholder for https://github.com/eclipse/che/issues/11690

**Comment by ibuziuk** [comment]
@garagatyi could you please provide an estimate for this issue ?

**Comment by garagatyi** [comment]
@ibuziuk have no idea actually. I would spend some time investigating and if the task was hard, create a separate issue and close this as investigation phase.

**Comment by amisevsk** [comment]
@garagatyi Could you add an estimate for this issue? (Even though it's an estimation in hindsight)
