### ISSUE TITLE
Che: Import context-assist offering an invalid import

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#103]
_From @burrsutter on June 9, 2017 13:52_

https://screencast.com/t/hUwgyV5SqDM
why is it offering io.vertx.rxjava.* as option?
https://github.com/burrsutter/vertxbasic23/blob/master/pom.xml

_Copied from original issue: openshiftio/openshift.io#212_

**Comment by l0rd** [comment]
I need to try to reproduce it but I think this issue exist in https://github.com/eclipse/che too. If this is the case we should move it there.

@eivantsov do you have an idea?

**Comment by l0rd** [comment]
For current sprint (n.135) we just need to know if that's an upstream issue or not

**Comment by benoitf** [comment]
The project is including vertx-web
https://github.com/burrsutter/vertxbasic23/blob/master/pom.xml#L41

And if I list content of the vertx-web jar :
jar tvf ~/.m2/repository/io/vertx/vertx-web/3.4.1/vertx-web-3.4.1.jar | grep StaticHandler
   259 Wed Mar 15 14:53:08 CET 2017 io/vertx/ext/web/handler/impl/StaticHandlerImpl$1.class
  2341 Wed Mar 15 14:53:08 CET 2017 io/vertx/ext/web/handler/impl/StaticHandlerImpl$CacheEntry.class
 24129 Wed Mar 15 14:53:08 CET 2017 io/vertx/ext/web/handler/impl/StaticHandlerImpl.class
  2721 Wed Mar 15 14:53:08 CET 2017 io/vertx/ext/web/handler/StaticHandler.class
  5491 Wed Mar 15 14:53:08 CET 2017 io/vertx/rxjava/ext/web/handler/StaticHandler.class

We can see that it includes  io.vertx.rxjava classes so it's normal that StaticHandler is proposed with this package as well

**Comment by benoitf** [comment]
@l0rd ok to close the issue as "works as expected" ?

**Comment by l0rd** [comment]
@benoitf yes let's close that thanks
