### ISSUE TITLE
Jdt.ls Need to investigate how adding `m2` and `javadata` volumes would affect startup of the workspaces on openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1030]
There are 2 "optional" volumes that have been added to java based stacks due to jdt.ls switch [1] :
 
>               "volumes": {
>                 "m2": {
>                   "path": "/home/user/.m2"
>                 },
>                 "javadata": {
>                   "path": "/home/user/jdtls/data"
>                 }

`.m2` is "optional" , but it would be required to re-download all maven deps at startup.
`javadata` is also optional, but no project info would be added, but no metadata will be shared between runs of jdt.ls. For small workspaces, it doesn't matter, but for big workspaces like `che-in-che` the affect is dramatic - 10 minutes cold start and < 1 min hot start. 

However, with utterly slow gluster storate mounting 2 volumes would likely create another set of performance issues, since FS acces would be really slow and downloading maven dependencies for relatively big project could take forever. Need to investigate how adding `m2` and `javadata` volumes would affect startup of the workspaces.
 
[1] https://github.com/eclipse/che/pull/10863/

**Comment by ibuziuk** [comment]
@tsmaeder could you please point me to the doc or provide some info about `/home/user/jdtls/data` ? I have started a workspace and see that there are only empty `bin`& `src` folders under `jdt.ls-java-project`. It would be great to understand what type and quantity of files are typically located under those folders and why it is important to preserve those files between workspace restarts in order to speed up the subsequent workspace starts ?

**Comment by amisevsk** [comment]
@ibuziuk My understanding was that moving to OpenShift 3.11 would alleviate some of the gluster issues, as it would include Florent's chown change.

**Comment by ibuziuk** [comment]
@amisevsk sure, but it will not solve problems with gluster FS access - it will be as slow as before the update. We need to compare cold build time with mounted `.m2` vs. `.m2` being part of the container FS

**Comment by garagatyi** [comment]
We need to take a look at this one more time. Development of any non-dummy multi-module project without preserving m2 would be pretty unusable.

**Comment by garagatyi** [comment]
We might need to add an ability to bring volume for a plugin. Another thing we can work on is a configuration of sidecar with JDT.LS or another LS where we already can specify volumes.

**Comment by ibuziuk** [comment]
Closing as outdated, currently we reuse devfile from upstream

**Comment by tsmaeder** [comment]
@ibuziuk the javadata folder contains an Eclipse workspace. The interesting part is in the ".metadata subfolder: many small files.

**Comment by ibuziuk** [comment]
@tsmaeder wondering what happens when workspace is removed? Does `javadata`get cleaned from PVC ?

**Comment by tsmaeder** [comment]
I have no idea, but since workspaces can define volumes, the volume itself should be deleted.

**Comment by amisevsk** [comment]
I'm fairly certain (though I haven't tested) that the `javadata` folder will get handled correctly. E.g with the common PVC strategy, the PVC itself looks like
```
/
├── workspacexxxxxx
│   ├── .m2
│   └── projects
├── workspaceyyyyyy
│   ├── .m2
│   └── projects
```
When we delete a workspace, the corresponding subfolder is deleted.
