### ISSUE TITLE
Image pulling for predefined images should always be fast on che.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1056]
### Che 7 Workspaces (ephemeral, but without https://github.com/eclipse/che/pull/11786 so normal PVC is still used for broker):
- Broker start: ~7.5 seconds average
- Pulling images: ~100 seconds on average (che-dev, che-machine-exec, che-hello, che-theia).
- Start Theia: ~10 seconds, sometimes quite a bit longer
![Che7](https://user-images.githubusercontent.com/16168279/48209446-35d0f200-e343-11e8-84b4-a11fdb9f3062.png)

### Che 6 workspaces (ephemeral):
- Setting up container: ~3 seconds
- Pulling image: ~20 seconds average (image is centos_jdk8)
- Starting agents: ~25 seconds (exec, terminal, wsagent) -- sometimes *much* longer for unclear reasons)
![Che6](https://user-images.githubusercontent.com/16168279/48209561-80526e80-e343-11e8-9350-7bdaf8f759af.png)

Graphs are borrowed from https://github.com/redhat-developer/rh-che/issues/1014#issuecomment-437043526

According to the chart sometimes pulling of the same image is blazingly fast (~1s) and sometimes utterly slow (~30s) which dramatically affects workspace startup. It looks like pull variance happens because of the oso node level caches. So if the startup of a workspace happens on a node that has pulled an image earlier the image is served from the node's cache [2] . The images pulled are always the same for pre-defined stacks. so if they can be cached somehow we need to do it aggressively on all tenants nodes, so that pulling image would always be blazingly fast.

[1] https://github.com/redhat-developer/rh-che/issues/1014#issuecomment-437094198
[2] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2350

**Comment by riuvshin** [comment]
interesting, after moving to quay.io it was constantly 1s for every time I run this. I did it like 10 or even more times for different stacks

**Comment by ibuziuk** [comment]
@riuvshin I have just tried `.NET` stack (image `quay.io/openshiftio/che-centos_dotnet20`) on che.openshift.io and for me pulling took ~26 seconds:

![image](https://user-images.githubusercontent.com/1461122/48441693-776efc00-e78c-11e8-94ae-d769ae92e999.png)

There was a suggestion from @l0rd and @kbsingh that we should setup a call with someone from SD team in order to better understand why pulling of images is sometimes fast / slow and triage this issue. It should be possible to do the following tricks:
 - force workspace pod to be started always on the same node (cluster admin could tune node selector) and start workspace a few times in order to see if node caching works properly
 - get node metrics (CPU & memory consumption) when image pulling / extraction happens. Theoretically, particular node could be under some load which could potentially affect pulling / extraction time.

**Comment by amisevsk** [comment]
Just tested on 2a now that `k8s-image-puller` is deployed, and images in the caching list are pulling + starting in 500ms. 

Closing this issue as resolved for now; further issues can be tackled separately.
