### ISSUE TITLE
Che 7: Need to use distroless images (or FROM scratch) for brokers, editors and plugins in order to reduce image size and speed-up pulling

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1061]
"Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution.

https://github.com/GoogleContainerTools/distroless

**Comment by ibuziuk** [comment]
Using `From scratch` for brokers should be easy and be a first thing to do as part of this issue. 
For Theia image moving to Distroless might be tricky and can be postponed (once java will be removed )
For plugins we can also switch to `From scratch`

**Comment by benoitf** [comment]
hello, please note that plug-ins container still require nodejs runtime so it may not use scratch images (but nodejs library images)

**Comment by garagatyi** [comment]
I'll make brokers distroless in my PR https://github.com/eclipse/che-plugin-broker/pull/14
