### ISSUE TITLE
Make Theia webpack-based bundle packaging customizable

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1065]
Currently, the Theia webpack configuration file, as well as the main HTML file that loads the packaged JS bundle file, are generated during Theia build.

In order to provide enable bundle caching in a way that can be customized by the theia distributrion packager, we should introduce a way to customize:
- the webpack configuration, at least providing an option to enable a typical caching-compatible configuration (see https://webpack.js.org/guides/caching/)
- the generated HTML using the HtmlWebpackPlugin, in order to let the user provide its own template during the `theia build` call, as well as additional html template parameters through command line arguments.

The result of this work should be to have the related PR merged in the upstream Theia repository.

**Comment by davidfestal** [comment]
The following PR has been opened in the Theia repository: https://github.com/theia-ide/theia/pull/3522

**Comment by ibuziuk** [comment]
I agree, let's postpone it in favour of https://github.com/redhat-developer/rh-che/issues/1119

**Comment by ibuziuk** [comment]
Closing as outdated
