### ISSUE TITLE
Analyse the required actions to also enable caching of VSCode/Monaco-related JS files

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1070]
The first step of Theia bundle caching support focused on the main Theia JS bundle files.
It would be great to enable caching of additional downloaded files such as the monaco editor-related JS files or the `.wasm`, and `.woff2` files.

**Comment by davidfestal** [comment]
This has bee done and tested on branch https://github.com/eclipse/che/compare/theia-cdn-support.
Will be integrated with the rest of the work described in issue https://github.com/redhat-developer/rh-che/issues/1066

**Comment by ibuziuk** [comment]
should we close this issue in that case ?

**Comment by davidfestal** [comment]
well, it's not merged...

**Comment by ibuziuk** [comment]
ok, sure. Just though that this issue is more about analyzing and actual work would be done as part of the https://github.com/redhat-developer/rh-che/issues/1066 . But if you think it would be better to close this issue once PR is merged, let's do it that way

**Comment by davidfestal** [comment]
You're right indeed. Let's close it: The analysis was done and the found solution was validated by @benoitf
