### ISSUE TITLE
Unable to import projects on 3.11.1 update (prod-preview)

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1072]
**Issue problem:** 
Workspaces don't import quickstart projects.
The manual import is also broken, the UI doesn't load.

**Red Hat Che version:** 

Version: 1.0.0-SNAPSHOT       
Build Time:  2018-11-14 11:15:54  
Revision:    2c6626bcd859c626 

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Quickstart:
*  Create a new workspace (stack doesn't matter)
*  In the quickstart projects section import a sample project
*  Run and open the workspace

Results:
*  The project is not imported
*  Unable to import project notification pops up

Manual import:
*  Click on `import-project` button in the now empty workspace

Result:
*  Import screen opens up but there are no options or buttons visible

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)
![firefox_2018-11-14_10-48-51](https://user-images.githubusercontent.com/16451875/48484387-45a27780-e816-11e8-9c9f-e471a5f0c4b0.png)
![firefox_2018-11-14_11-41-00](https://user-images.githubusercontent.com/16451875/48484393-4c30ef00-e816-11e8-9a35-35d706a03a23.png)

**Comment by ibuziuk** [comment]
@ScrewTSW could you please provide more info: 
  - against which accounts does this problem happen ?
  - what is the PVC state when the problem is reproducible ?
  - does removal of `claim-che-workspace` PVC manually and restarting workspace fixes the issue ? 
  - Are there are any che-server logs from kibana when the issue occurs?

**Comment by amisevsk** [comment]
@ScrewTSW Do you have any adblockers / similar plugins in your browser? I had a similar issue until I disabled them.

**Comment by ibuziuk** [comment]
@amisevsk @davidfestal I can not reproduce this problem on prod-preview against 2 accounts ? could you please give it a go ? @ScrewTSW am I correct that not all accounts are affected and for some of the accounts import works just fine ?

**Comment by amisevsk** [comment]
If it's not reproducible reliably, I'm 90% certain a browser plugin is blocking connections.

**Comment by ibuziuk** [comment]
@amisevsk funny thing that as I understand @ScrewTSW can not reproduce the same issue on prod (and on prod-preview it is also not reproducible for some accounts)? We could probably share credentials for some generic account e.g. `osio-ci-preview-testper` and try to reproduce from different environments

**Comment by ScrewTSW** [comment]
@amisevsk @ibuziuk Will try to create the workspaces without the add-ons

**Comment by ScrewTSW** [comment]
Strange. It looks like indeed it has been caused by the ad-blocker. Now the project pulled without any issues.

The question is, why should adblocker prevent project pull. That's a really strange behavior and possibly an implementation error. Should we look into this? I'm sure multiple users could be affected.

**Comment by amisevsk** [comment]
@ScrewTSW It doesn't prevent pull, it prevents the browser interacting with the IDE. If you were to disable adblocking for the site and refresh, the projects is there, correctly imported.

**Comment by ibuziuk** [comment]
@ScrewTSW are you going to continue investigation or should we close it as not-reproducible ?

**Comment by ScrewTSW** [comment]
@ibuziuk we can close this issue. I think it was just an odd quirk of my network connection.
