### ISSUE TITLE
Need to carry out a test in order to get information about the time required for pod startup if image streams from the user namespace are used in deployment configs created in *-che namespace 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1084]
This test can be carried out on any oso starter cluster and requires:
- creation of image steam in user namespace
- creation of deployment config in *-che namespace which would reference to the image stream from the previous step
- get info about how fast pod startup would be  (there is an assumption that switching to image streams / deployment configs for workspace creation on openshift infrastructure might have better performance due to caching)

**Comment by ibuziuk** [comment]
@amisevsk thanks for detailed document. The only thing that I am wondering is that @l0rd @jfchevrette were suggesting that image streams should be created in `user` (not che) namespace and used by deployments / deployment-configs created in `che` namespace. As I understand you created image streams and deployments both in the same *-che namespace, right ?

**Comment by jfchevrette** [comment]
My initial idea was to create the imagestreams in a single new namespace, such as `che-images` and then grant read access to the imagestreams from that namespace to all tenants. Creating ImageStreams under each tenant means we will end up with hundreds if not thousands of copies of the same images in the internal registry which could prove problematic with regards to storage and will not add much value.

**Comment by amisevsk** [comment]
@ibuziuk Yeah, these ImageStreams were created in the same namespace as the workspace (i.e. `amisevsk-preview-che`).

**Comment by ibuziuk** [comment]
@jfchevrette @l0rd during the tests that @amisevsk carried out it looks like there is no sufficient differences between usage of images vs imagestreams. Do you think we should continue investigation in this direction ?

@jfchevrette by the way does `IMAGE PULLTHROUGH` is enabled on starter clusters ?

[1] https://docs.openshift.com/container-platform/3.11/install_config/registry/extended_registry_configuration.html#middleware-repository-pullthrough

**Comment by l0rd** [comment]
@ibuziuk @amisevsk it doesn't look like there is any interest in going forward with the investigation on imagestreams
cc @gorkem

**Comment by ibuziuk** [comment]
Closing. Please, reopen if we should consider to continue investigation of potential switch to image streams
