### ISSUE TITLE
Provide a way to test upstream Che PR against RhChe on dev cluster

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1087]
**Issue problem:** 
Sometimes I want to test changes that I contribute to upstream Che against RhChe. This would help me to be sure that I didn't break any RhChe related flow.
It is possible to do that by manually deploying custom RhChe on dev cluster but this is time-consuming thing that hardly can be used by red hatters outside of osio-che team.
Would be cool if we allow to use comment in PR [test] image=garagatyi/rh-che:noenv to do CI with the specified image on dev cluster. 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by rhopp** [comment]
I'm not sure I know exactly what you mean by this...
You expect to have some trigger in __upstream__ repository, which builds upstream che (PR branch), then rhche (master), deploys it to dev cluster and runs our suite. Right?

Basically what we have now as the "compatibility job", but triggered from PRs in upstream repo. Right?

**Comment by garagatyi** [comment]
@rhopp no, I want to be able to build image myself, push it to dockerhub and being able to trigger a deployment with this image from RhChe PR. So, I would be able to create PR here to check upstream work. And not only me would be able to do that since it wouldn't require a lot of work to get access to dev cluster and stuff like that.
Flow:
1. there is a PR X in upstream Che
2. I build PR X
3. I build RhChe with snapshots from that upstream PR X 
4. I push image of RhChe to my dockerhub account
5. I comment `[test]` and see results of tests execution.

> Basically what we have now as the "compatibility job", but triggered from PRs in upstream repo. Right?

I don't think so. We have something like that (check of compilation only) for upstream Che master branch, not PRs. So, we know when something goes wrong only when PR is merged and upstream Che is not compatible with RhChe anymore

**Comment by garagatyi** [comment]
But having a fully automated flow would be superb. 
For example, some external contributor creates a PR with changes in Che server. 
I'm a reviewer and code looks OK, but I'm not sure whether it would break something in RhChe.
I create a PR in RhChe and somehow points that I want to test RhChe against upstream PR #xxx.
CI:
1. checks out upstream PR branch
1. builds it
1. change RhChe version to it
1. builds RhChe
1. run functional tests

This would allow us to keep RhChe way more stable and prevent the situation when incompatibility was merged without us knowing about that.
And Che platform team would be able to check their changes in RhChe before the merge. Whereas it would be very hard to persuade them to do all the manual steps they would need to do to achieve that now.

**Comment by ibuziuk** [comment]
Closing as outdated
