### ISSUE TITLE
Move new .theia plugin broker from wsskeleton repo to eclipse org

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1088]
**Issue problem:** 
We have a couple of branches in wsskeleton/che-plugin-broker that are used in RhChe at the moment but they are out of upstream. We need to merge that work.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Closing as duplicate of #1003
