### ISSUE TITLE
Can we have a SA on dev cluster that has access to the team members tenants only and thus would be secure enough from the SD team view

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1091]
**Issue problem:** 
Can we have a SA on dev cluster that has access to the team members tenants only and thus would be secure enough from the SD team view?

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
Now we use user tokens on dev cluster because we don't have real prod SA since it is not secure.
What if we can specify an SA that has access to our own tenants only? It can be an opt-in process to request adding your tenant to that SA at HK gitlab, so it would be considered safe if we request to allow access with that SA to our tenants.

**Comment by garagatyi** [comment]
@ibuziuk @rhopp @tdancs @Katka92 WDYT?

**Comment by ibuziuk** [comment]
@garagatyi this sounds relevant, but we also need to think about emulating toggle functionality on dev-cluster. Currently, che-server talks with toggle by service name + port, which means that it is expected that oso-proxy will need to be located in the same namespace as che-server, which is not the case for dev-cluster

**Comment by garagatyi** [comment]
I see. This is a problem, indeed. 
But, in general, shouldn't we use on CI step approach that is used on prod?

**Comment by ibuziuk** [comment]
well, yeah it would be better to use Che SA token approach for testing, but it it still will not be exactly the same approach that is used on prod / prod-preview due to limitations described above. So it would be tradeoff in any case.  

What would be the process for adding new tenant ?

> It can be an opt-in process to request adding your tenant to that SA at HK gitlab, so it would be considered safe if we request to allow access with that SA to our tenants.

**Comment by ibuziuk** [comment]
>  what limitations do you mean?
I mean it would be not the same token that is used in prod, and not the same mechanism for obtaining this SA token, and not the same toggle (this is what I mean by tradeoff)

> Create an issue in HK to add your personal tenant (or account) to the list of tenants that are allowed to be accessed by that dev cluster SA

Yeah, it is probably possible, but not sure that SD would be happy with this approach. You have probably seen an email that they are not going to grant edit rights manually on request basis anymore and what us o use some self-service for that.

**Comment by garagatyi** [comment]
Self service would be also just fine!

**Comment by ibuziuk** [comment]
Closing as outdated
