### ISSUE TITLE
The Centos Go stack is pretty unusable

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1100]
**Issue problem:** 
Currently, upon starting, the Go stack we're using has to download/unpack thousands (~4800) of files into `/projects/.che/src` upon first start, even if no projects are imported.

- For a normal workspace, this makes the PVC timeout on future mounts due to file count
- For ephemeral workspaces, this has to happen on every launch, which takes a long time and makes start take a *long* time.

![centos-go ephemeral with lang server](https://user-images.githubusercontent.com/16168279/49062772-43132b00-f1e3-11e8-915d-d274115d3ea1.png)
![centos-go with lang server](https://user-images.githubusercontent.com/16168279/49062773-43132b00-f1e3-11e8-8d69-f2dff2b29307.png)

**Red Hat Che version:** 

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Create and start a Che 6 Go stack, in either ephemeral mode or not.
- In ephemeral mode workspace start takes ~70 seconds due to golang language server start
- In normal mode, first start takes ~180 seconds (since Gluster is slow), future starts can timeout on PVC mount due to number of files (mounting takes ~100 seconds)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by eivantsov** [comment]
@amisevsk yeah, and I am open to suggestions :) 

Go language server requires a handful of deps. We can put them in GOPATH outside volume mounts. However, all your go deps will go away after each workspace restart.

We may also want to remove dep fetching from installer script: https://github.com/eclipse/che/blob/master/agents/ls-golang/src/main/resources/installers/0.1.7/org.eclipse.che.ls.golang.script.sh#L183

My question is, should we do it for Che 6 or look at Golang VS Code plugin?

**Comment by amisevsk** [comment]
@eivantsov Yeah I agree, we would need to look at what would be necessary and if it's a lot of work. This issue is mostly for tracking for now :)

**Comment by ibuziuk** [comment]
Should be closed once we update to Che 7 GA
