### ISSUE TITLE
Initial support of CDN support in che-theia-generator

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1119]
Integrate the work done on branch [theia-cdn-support](https://github.com/eclipse/che/compare/theia-cdn-support) into this new repository: https://github.com/ws-skeleton/che-theia-generator

Also include the ability to enable / disable CDN support in the generated image through an environment variable.

**Comment by ibuziuk** [comment]
WIP PR - https://github.com/ws-skeleton/che-theia-generator/pull/3

**Comment by ibuziuk** [comment]
@davidfestal are you ok to close thus issue ?

**Comment by davidfestal** [comment]
To be fair this also includes some work on the upstream `che` side:

> Also include the ability to enable / disable CDN support in the generated image through an environment variable.

But this is mainly finished,and the PR I'll open will also include the work about pushing the CDN artifacts during CI build. So maybe we could close this one anyway.
