### ISSUE TITLE
Che fails to provision images : memory limit is out of bounds for user project in OSIO

### ISSUE THREAD

**Issue by sr229** [redhat-developer/rh-che#1124]
**Issue problem:** 

Making a stack with 2048MB limit with Theia Sidecar and Che exec plugin enabled seems to cause issues.

Checking at OpenShift console - it seems to deal with memory requests being out of bounds

>Time | Name | Kind | Severity | Reason | Message
>-- | -- | -- | -- | -- | --
>9:05:54 PM | workspacek7ikvieuc02e87vl.dockerimage | Deployment | Normal | Scaling Replica Set | >Scaled down replica set workspacek7ikvieuc02e87vl.dockerimage-785cf94978 to 0
>9:05:34 PM | workspacek7ikvieuc02e87vl.dockerimage-785cf94978 | Replica Set | Warning | Failed Create | (combined  from similar events): Error creating: pods  "workspacek7ikvieuc02e87vl.dockerimage-785cf94978-95zc4" is forbidden:  [maximum cpu usage per Pod is 6, but limit is 8106m., maximum memory  usage per Pod is 3Gi, but limit is 4352770048.]

**Red Hat Che version:** 6.14.2

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

- Use this [Stack](https://gist.github.com/sr229/8002738c9fcc573b2dbddb82fffc8e36) as for reference.
- Monitor logs on Monitoring during the workspace creation process
- Expected for pod(s) to create with actual limit, Got pod(s) created over the limited.

**Runtime:** 

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by sr229** [comment]
Update: even switching to 1024MB didn't do well.

**Comment by garagatyi** [comment]
It is a known bug in Che 7 flow https://github.com/eclipse/che/issues/11424

**Comment by garagatyi** [comment]
Please, close this issue in favor of the upstream project. Thanks!

**Comment by sr229** [comment]
Closing as known issue already in Che
