### ISSUE TITLE
Intermittent - Workspaces fail to start on prod

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#1126]
openshift.io issue - https://github.com/openshiftio/openshift.io/issues/4626
**Issue problem:** 
Yesterday, we started observing, that workspaces fail to start... Initially it was pretty rare, but as of today it seems it's getting more and more often.

It behaves like this:
1) User starts workspace
2) Workspace pod is created
3) Bootstrap runs fine
4) Workspace agent is started without error
5) Workspace in browser is stuck on loading:
![image](https://user-images.githubusercontent.com/1215011/49524464-15e20f00-f8ac-11e8-97e0-4fc3f506c823.png)
6) After some time, workspace startup times out with message:
```
Error: Failed to run the workspace: "Bootstrapping of machine dev-machine failed. Cause: Timeout reached while execution of command"
```
And with this error message in che-master logs:
```
Failed to start Kubernetes runtime of workspace workspace1bfhd4oxe8fshsr3. Cause: Waiting for Kubernetes environment 'default' of the workspace'workspace1bfhd4oxe8fshsr3' reached timeout
```

What's really puzzling in this issue is that I cannot find anything suspicious in logs. Nothing in che-master logs, nothing in bootstraper logs, nothing in ws-agent logs... That's why I didn't report this issue yesterday already... Because I basically don't have any 100% steps to reproduce and I don't even have any error message/logs. But as it's happening pretty often today, I'm creating this issue.

**Red Hat Che version:** 

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Comment by ibuziuk** [comment]
@rhopp no suspicious openshift events ?

**Comment by garagatyi** [comment]
Is Angel's change of liveness probes provisioned on prod?

**Comment by rhopp** [comment]
@ibuziuk Nope :-( The workspace pod starts completely normally... PVC was bound in short time, container pulled, ...

**Comment by ibuziuk** [comment]
@garagatyi no AFAIK, prod pod has not been restarted with new interval / threshold

**Comment by amisevsk** [comment]
I think the liveness probe changes are live on prod at the moment, but this seems to be coming from the Che 6 machine bootstrapping process, which involves a bunch of `exec` commands in the workspace pod. Could it be an issue related to the kubernetes-client update?

**Comment by garagatyi** [comment]
Shouldn't we make it blocker and stop working on anything else since this is major service outage for prod?

**Comment by ibuziuk** [comment]
@garagatyi this is already a P1 / SEV1 issue https://github.com/openshiftio/openshift.io/issues/4626

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW  @Katka92  are you still able to reproduce this problem on prod ? we have changed a few che-server configs [1] that should fix the problem. I currently can not reproduce it (Note on prod-preview we have not changed anything)

[1] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2476

**Comment by amisevsk** [comment]
It looks like the error is being thrown because of an `exec` command [timing out](https://github.com/eclipse/che/blob/49280a495c8c945a5ca034f77e68cfab44fcfb82/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java#L971).

**Comment by rhopp** [comment]
@amisevsk Where did you see this exception? I couldn't find anything like that anywhere in the logs...

**Comment by ScrewTSW** [comment]
@amisievsk yes, it's reproducible on dev cluster as well. Our tests running against dev cluster sometimes fail with the same error

**Comment by ibuziuk** [comment]
@amisevsk well, there are only 26 hits for the last 4 days on prod - `kubernetes.labels.app:"rhche" AND kubernetes.namespace_name:"dsaas-production" AND "Timeout reached while execution of command"`

And 0 on prod-preview. Might be wrong, but for me it sounds like a different problem

**Comment by ibuziuk** [comment]
@rhopp cloing since https://github.com/openshiftio/openshift.io/issues/4626 was closed
