### ISSUE TITLE
Private registry not working

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1139]
**Issue problem:** 
Adding private registry doesn't work. 
Even if docker registry with credentials is set in ```Administration```, it still returns an error:

![screenshot from 2018-12-12 12-43-42](https://user-images.githubusercontent.com/29278800/49867775-be8ff180-fe0b-11e8-91a9-d2d6303fd9ae.png)

**Red Hat Che version:** 
I can reproduce it in production and prod-preview environment. Latest upstream che on minishift works fine.

**Reproduction Steps:**
When reproducing that issue I followed this video step-by-step:
https://www.youtube.com/watch?time_continue=8&v=Ch10gqb3dNU

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by Katka92** [comment]
I tried to create a workspace with private repository on production. [Here](https://logs.dsaas.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-12T13:11:40.473Z',mode:absolute,to:'2018-12-12T13:26:40.473Z'))&_a=(columns:!(message),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:workspaceicffyrtaqk0tiqm6)),sort:!('@timestamp',desc))) you can see logs.
What cough my eye was [this request](https://logs.dsaas.openshift.com/app/kibana#/doc/project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*/project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.2018.12.12/com.redhat.viaq.common?id=NzkxYjk0MmItZmMwYS00YWVlLWE0YjItZDRjMzU5OGEwYTU3&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-12T13:11:40.473Z',mode:absolute,to:'2018-12-12T13:26:40.473Z'))) trying to delete secret 
```"RequestLine":"DELETE /api/v1/namespaces/kkanova-che/secrets/workspaceicffyrtaqk0tiqm6-private-registries HTTP/1.1"``` 
but there wasn't any message about its creation.

**Comment by ibuziuk** [comment]
@Katka92 I think the problem is fixed, could you please verify against Che 7 CR1 on che.openshift.io ?

**Comment by Katka92** [comment]
I've tried on che.openshift.io and seems to work fine. Thank you for pinging me. Closing :+1:
