### ISSUE TITLE
Workspaces sometimes stuck in a stopping phase 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1142]
**Issue problem:** 
Workspaces sometimes stuck in a stopping phase 

![image](https://user-images.githubusercontent.com/1461122/49941530-13526b80-fee3-11e8-8532-99dff43deee0.png)

in some cases they are finally stopped after 16 minutes (2 times workspace start timeout), and in some cases only restart of che server helps.

The las 2 reports where  from `vparfono` (`3344454d-05ae-4184-ac31-ef7199a29e56`) and `slemeur` (`376f3238-a2ab-46c5-b766-078f9a595d49`) users on prod.

**Red Hat Che version:** 

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@sleshchenko please, find the doc with logs - https://docs.google.com/document/d/1ifqymxm7s5gwczYQr7CsmOeRrnJVh-__FbmY3BzyXxo/edit

**Comment by sleshchenko** [comment]
What I see from logs:
Vitalii's workspace:
There are two times when `activity-checker` initialized workspace stopping but there are not log that workspace is stopped.
Logging that workspace is going to be stopped https://github.com/eclipse/che/blob/b8f0844052eabe8804bddda5ff4c9a8b5430a5b1/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L461-L466
Loggins that workspace is stopped that is not present in the document https://github.com/eclipse/che/blob/b8f0844052eabe8804bddda5ff4c9a8b5430a5b1/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L461-L466
So, need to investigate more why `activity-checker` didn't stop workspace correctly.

Stevan's workspace:
The workspace is recovered as STARTING on new Che Server, stop is initialized on old Che Server.
I think such use-case was not well thought out and a separate issue should be created to investigate and fix such cases. New Che Server should be notified that workspace is going to be stopped when it was recovered as STARTING. It's just guessing which should be investigated more.

**Comment by ibuziuk** [comment]
fixed after 7.3.1 rollout to production. Closing
