### ISSUE TITLE
ws-agent takes a long time to start up, when there are lot of files in `/projects` folder

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#1144]
**Issue problem:** 
Once the PVC mount issue is fixed (at least on `1a` cluster so far), another issue gets exposed.
ws-agent can take a long time to start up, when there is lot of files.

Steps to reproduce:
* Have account on 1a
* Create nodejs workspace with project `https://github.com/angular/quickstart`
* Once workspace is started (this one takes normal time to start up), do `npm install` in the quickstart... This will generate lot of files ~19000
* Stop that workspace
* Start that workspace - observe, that this startup takes significantly longer, then the first one.

From ws-agent logs it seems, that the tomcat took long time and was restarted few times in the process:
https://pastebin.com/mtmHnzLq

This issue is not reproducible on other clusters because there it fails on the PVC issue.
We've also tried this scenario on upstream che deployed to minishift and we didn't observe any slowness there.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Should be closed once we update to Che 7 GA. (ws-agent will cease to exist)
