### ISSUE TITLE
[Proposal] White-label Che Dashboard to look more uniform with the rest of the OpenShift.io SaaS

### ISSUE THREAD

**Issue by sr229** [redhat-developer/rh-che#1145]
I think while the current Che UI is nice, its mostly a basis to customize the UI further.

It would be nice if the Dashboard will be having a white-labeling as I believe it would fit more on OSIO in a design sense.

**Comment by ibuziuk** [comment]
@sr229 there is already opened issue for that in openshift.io https://github.com/openshiftio/openshift.io/issues/1161

@slemeur @l0rd wdyt ?

**Comment by sr229** [comment]
@ibuziuk thanks for the heads up

I believe there's documentation regarding whitelabeling Che AFAIK, my knowledge about the docs is outdated however so I might be wrong.

**Comment by ibuziuk** [comment]
@sr229 oh, ok. AFAIK there are no options for modifying dashboard. You should probably create an issue upstream in order to start the discussion there.

**Comment by sr229** [comment]
Alrighty, will leave this issue open until there's a way to implement it.

**Comment by l0rd** [comment]
@sr229 @ibuziuk We are considering reworking the dashboard right after Che 7 release (first part of 2019). I am afraid we won't be able to support dashboard white labeling before that.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/12195 
Let's continue this discussion in the upstream
