### ISSUE TITLE
[rhche-dockerfiles] Thorntail boosters are disabled on osio

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1149]
### Issue problem:
Commits https://github.com/fabric8-launcher/launcher-booster-catalog/commit/74bf75a112b146ac130e809d93a94be70a15e7c8 and https://github.com/fabric8-launcher/launcher-booster-catalog/commit/3d866c229a6d868f297d4dd37865a73639000de3 disable the Thorntail boosters on OSIO.

This issue is for tracking, so that they can be re-added to the [relevant dockerfile](https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/dockerfiles/wildfly-swarm/Dockerfile) once they are back.

**Comment by amisevsk** [comment]
You can check which thorntail boosters are available on osio using the command

```
curl -H "X-App: osio" \
      https://forge.api.openshift.io/api/booster-catalog \
      | jq '.boosters | .[] | select(.runtime == "thorntail")'
```

**Comment by ibuziuk** [comment]
@amisevsk I believe we can close this one, once Che 7 GA will be promoted to prod
