### ISSUE TITLE
503s are back

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#115]
This issue was originally reported by @jfchevrette [via email](https://gist.github.com/l0rd/12a6f7fc6397b4156eb24e9a6d21d886#file-jf-email-md)

The suspect is that an error 503 is returned when che-server is idled and its route receives an HTTP request. Here is a short video that shows the behavior (note that 503s are preceded by a 504 (timeout) and that 302 is normal because we are not authenticated):

![che-demo](https://user-images.githubusercontent.com/606959/27389508-e40028c4-569e-11e7-9eec-05c4285f626e.gif)

There are a couple of work in progress that may have an effect on this issue though:
1. Platform should soon consume che-starter responses asynchronously (c.f. https://github.com/redhat-developer/che-starter/issues/163)
2. A new PR for new implementation of Che workspace idling may be merged soon (https://github.com/redhat-developer/che-starter/issues/163)

**Comment by l0rd** [comment]
A comment about 503 errors we had in the past: https://gist.github.com/l0rd/12a6f7fc6397b4156eb24e9a6d21d886#file-503-issues-we-had-before-summit-md

**Comment by l0rd** [comment]
cc @ibuziuk

**Comment by mlabuda** [comment]
After some failure in Che functional tests I dedicated to look why I have those failures. Basically Che starter does not wait until Che server pod is really running. Che server pod is in starting state but not running and Che starter proceed, that is the reason why some "Service" throws 503 in Che starter log

**Comment by ibuziuk** [comment]
@mlabuda closing. realated PRs to `fabric8-online`  and `che-starter` have been merged and promoted to prod.
