### ISSUE TITLE
WorkspaceRuntimes getContext should recover runtime

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1161]
**Issue problem:** 
We have plenty of next errors on prod:
```
Could not get runtimeIdentity for workspace 'workspacektg6ndkwtpmesz18', and so cannot verify if current subject 'c35997d8-a8cf-485d-b961-6471c164ca01' owns workspace
```
Which occur when RuntimeIdentity is not found for a workspace.
But [retrieving](https://github.com/eclipse/che/blob/b8f0844052eabe8804bddda5ff4c9a8b5430a5b1/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L802) RuntimeContext doesn't do runtime recovering which means that we can have such an error on every restart of a Che master (because of failure or update).
We need to make `WorkspaceRuntimes#getRuntimeContext` recover runtime.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by sleshchenko** [comment]
> We need to make `WorkspaceRuntimes#getRuntimeContext` recover runtime.

It should be investigated more. I think it makes sense to have two separated method for `fetching if present` (needed for during preparing a list of users workspaces [[1](https://github.com/eclipse/che/blob/0ce23f5155a0034f5bccf8c562e7462368595660/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceLinksGenerator.java#L96)]) and `another fetch or recover`

[1] https://github.com/eclipse/che/blob/0ce23f5155a0034f5bccf8c562e7462368595660/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceLinksGenerator.java#L96

**Comment by ibuziuk** [comment]
Closing as outdated
