### ISSUE TITLE
Add PR number to PR check namespace display name

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1166]
**Issue problem:** 
I see on dev cluster:
![image](https://user-images.githubusercontent.com/1851863/50597251-7f573c80-0eaf-11e9-8897-6d3e9c4b9b9d.png)

It would be useful to have PR number in the namespaces name to differ them

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 @rhopp could we call namespaces based on PR # ?

**Comment by Katka92** [comment]
Hi Ilya, I'll take a look on that. :+1:

**Comment by Katka92** [comment]
@ibuziuk I've created PR for that. Could you PTAL? https://github.com/redhat-developer/rh-che/pull/1440

**Comment by ibuziuk** [comment]
Fixed - https://github.com/redhat-developer/rh-che/pull/1440#issuecomment-498149687
Closing
