### ISSUE TITLE
Include CI deployment link to CI failure comment

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1169]
**Issue problem:** 
When CI deployed Che successfully but functional tests failed CI comment only failure.
To investigate we have to manually go to dev cluster and find Che namespace to try to start a workspace manually. 
Instead, we could include deployment link to the CI failure comment on Github.  

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by Katka92** [comment]
PR with required change was merged. Closing.
