### ISSUE TITLE
Cleanup prod and prod-preview config map from old properties

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1176]
**Description:**
After the merge of https://github.com/redhat-developer/rh-che/pull/1163, we won't need some properties

HK issue  https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2509

**Comment by ibuziuk** [comment]
@garagatyi could you please link related HK issue (also one for removal `che` cm on dsaas - probably would be better to do all the cleanup in one go)?

**Comment by garagatyi** [comment]
Those are 2 different cleanups since different CMs would be affected.

**Comment by garagatyi** [comment]
Added link to HK issue

**Comment by ibuziuk** [comment]
Cleanup has been done on both dsaas / dsaas-stg. Closing
