### ISSUE TITLE
Create docs with description on how to monitor Che on prod

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1188]
**Description:**
This doc should include useful tips and links on how to monitor: 
- RAM
- CPU
- Threads
- file descriptors
- Workspace and master parameters such as workspaces in different states
- How to get a graph of metrics
- How to find logs of some kinds
- Sentry
- How to get traces of some kind

This would help us to recover context when someone needs to work on load related stuff on prod. 
After that team would need to add info about new things everytime something useful is added upstream.

**Comment by ibuziuk** [comment]
PR sent - https://github.com/redhat-developer/rh-che/pull/1285

**Comment by ibuziuk** [comment]
@garagatyi are you ok to close or you think some important info is still missing in the doc?

**Comment by garagatyi** [comment]
yes, we can close it
