### ISSUE TITLE
Create technology oriented commands per stack

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/rh-che#119]
Copied from https://issues.jboss.org/browse/CHE-295:

At the moment we have quite general commands among stacks. We have e.g. "mvn clean install" or "java -jar target/*.jar" etc. We could have more technology oriented commands.

For example, vertx booster has maven vertx plugin with goal vertx:run. This would improve UX, because now, user has to at first build, then run. With vertx:run, it is one-click-to-go command.

Same could apply for other stacks as well (springboot, wildfly...).

**Comment by ibuziuk** [comment]
@mlabuda could you please specify all the commands that are needed as check list to this issue ?

**Comment by mlabuda** [comment]
There is no full check list and it also depends on stacks.

E.g. for the vert.x stack it is "mvn vertx:run", for springboot stack it will be "mvn spring-boot:start" and "mvn spring-boot:stop" and maybe also "mvn spring-boot:run". Good lead could be documentation of stack specific maven plugin.

**Comment by ibuziuk** [comment]
- spring-boot
- [ ] mvn spring-boot:start
- [ ] mvn spring-boot:stop
- [ ] mvn spring-boot:run
- vert.x
- [ ] mvn vertx:run

@mlabuda ok let's start from those

**Comment by l0rd** [comment]
Fixed
