### ISSUE TITLE
Workspace files are not removed when Common PVC strategy if configured

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1195]
Placehoder for https://github.com/eclipse/che/issues/12445
Also related to https://issues.jboss.org/browse/CRW-69

**Comment by amisevsk** [comment]
Added comment explaining issue [upstream](https://github.com/eclipse/che/issues/12445#issuecomment-457372375).

**Comment by amisevsk** [comment]
The fix on our side for this issue would be to change CM values on prod/preview to pre-create subpaths. Before we do that, we should make sure there isn't an impact due to PVC weirdness (this requires a mount before starting the workspace pod).

**Comment by ibuziuk** [comment]
@amisevsk am I correct that we need a PR for changing `CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS` in cm, verifying it on dev cluster and creating HK issues for changing cm on dsaas / dsaas-stg ?

**Comment by amisevsk** [comment]
@ibuziuk Sorry I missed the notification for this -- I opened https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2541 for dsaas-stg to make sure there weren't any PVC issues resulting, but haven't been able to follow up.

A PR should also be made to our cms, I can do that soon; I've been stuck in upstream land for the past week.
