### ISSUE TITLE
 Allow multiple Che 7 workspaces to run at the same time

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1197]
Placeholder for https://github.com/eclipse/che/issues/12238

**Comment by rhopp** [comment]
Just to be sure... this is not going to affect rh-che, as we will stick with 1 workspace policy until custom openshift cluster support is in place, right?

**Comment by amisevsk** [comment]
My understanding is that this is more of a structural issue in Che (e.g. in single namespace deployments). We don't hit it on rh-che.

**Comment by slemeur** [comment]
Is this issue assigned and started already?
