### ISSUE TITLE
[spike] Adapt e2e registration flow to recent changes done for Red Hat developers Auth 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1199]
Need to figure out how new registration flow affect current e2e che.openshift.io registration flow

**Comment by davidfestal** [comment]
I tested the `che.openshift.io` end-2-end registration flow, and it is not that impacted by the new RHD unified registration.
We should probably review the page of the Che activation step, which was initially copied on the look and feel of the previous RHD Openshift.io login.
But for now the best is probably to wait for the final look and feel of the future customized CodeReady regsitration (if customization there is), before updating the Che account activation page.

@slemeur Any thoughts about that ?

**Comment by ibuziuk** [comment]
As I understand registration with a new flow works just fine. For changing UI (if needed) we need to create another issue or focus on - https://github.com/redhat-developer/rh-che/issues/817 cc: @slemeur
