### ISSUE TITLE
Minishift addon deployment - Login from OKD fails

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1211]
**Issue problem:** 
I'm using the latest version of minishift-addons form rh-che master branch, with `minishift v1.30.0+186b034` and a brand new virtual machine with 4GB of RAM and 2 CPU cores.

The deployment works as intended (first installing `rhche-prerequisites` addon and then the `rhche` addon)

Upon opening the dashboard I'm redirected to the OKD login page and after successfully entering the credentials I'm redirected back to dashboard with this error:
![screenshot from 2019-01-22 09-06-04](https://user-images.githubusercontent.com/16451875/51541149-601d5080-1e58-11e9-9166-6e9e1ce82a25.png)

There are no errors in the rhche logs, only exception being thrown is in the keycloak logs:
```
08:28:41,450 WARN  [org.keycloak.events] (default task-20) type=LOGIN_ERROR, realmId=che, clientId=null, userId=null, ipAddress=172.17.0.1, error=identity_provider_login_failure
08:31:16,680 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-7) Failed to make identity provider oauth callback: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
...
```
![screenshot from 2019-01-22 15-28-00](https://user-images.githubusercontent.com/16451875/51542044-9b208380-1e5a-11e9-8547-0349ea21f843.png)
![screenshot from 2019-01-22 15-28-21](https://user-images.githubusercontent.com/16451875/51542046-9bb91a00-1e5a-11e9-955a-610c9f4b0eab.png)

**Red Hat Che version:** 

version: minishift quay.io/openshiftio/che-rh-che-server:df0c632
(cannot get exact version as I cannot get to dashboard)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**
* create new minishift VM with 4GB of RAM and 2 CPUs
* minishift addon apply rhche-prerequisites
* minishift addon apply rhche
* wait for deployment
* open rhche in new tab
* try to login

**Runtime:**

runtime used:
   - [x] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by eivantsov** [comment]
@ScrewTSW  You will probably have to need to add self signed cert to Java truststore

**Comment by ibuziuk** [comment]
@eivantsov is there any instructions for this.

**Comment by ibuziuk** [comment]
@davidfestal I believe we can close this issue now, right ?

**Comment by ibuziuk** [comment]
verified against 
minishift v1.27.0+707887e
minishift v1.27.0+707887e
