### ISSUE TITLE
Remove init plugin broker image configuration from dev, prod and prod-preview CMs

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1216]
**Description:**
Remove entry `CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE` from dev, minishift addon, prod, prod-preview CMs after update to 6.18 upstream.

**Comment by ibuziuk** [comment]
`CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE` cm entry was removed from prod / prod-preview
