### ISSUE TITLE
Rename Che 7 model fields that don't follow camel case

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1217]
Placeholder for eclipse/che#12501

**Comment by garagatyi** [comment]
If we change the code in the brokers Che 7 workpsace of OSIO won't start until we deliver that version of upstream Che.
I think we can:
1. Add compatibility with new fields names to plugin brokers (and leave compatibility with the old ones)
2. Add compatibility with new fields names on Che master side (and leave compatibility with the old ones) 
3. Update editors/plugins that use old fields to have both versions of names
4. Update registry
5. After a couple of releases remove compatibility stuff

@ibuziuk @l0rd @slemeur WDYT?

**Comment by l0rd** [comment]
> 3. Update editors/plugins that use old fields to have both versions of names
> 4. Update registry

That means that we will have 2 copies of the same plugin. How will we handle this? Shouldn't we do these only after a couple of releases (i.e. prepare the PR but merge it after release of 6.19)?

**Comment by garagatyi** [comment]
@l0rd I'm not going to duplicate the plugin in the registry, I want to duplicate just a couple of fields in the che-plugin.yaml of those plugins.

**Comment by garagatyi** [comment]
Issue fixed in upstream Che
