### ISSUE TITLE
Docs for PR check details are currently in a bad state

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1225]
Docs for PR check details [1] are currently in a bad state:
- links to sequence diagram is broken
- details are not provided
- CI job for `DEP IMAGE` is broken

[1] https://github.com/redhat-developer/rh-che#pr-check-details

**Comment by ibuziuk** [comment]
@ScrewTSW would you be able to handle this task in the next sprint ?

**Comment by ibuziuk** [comment]
@Katka92 @tdancs any plans to fix this issue by the end of Sprint 162 ?

**Comment by Katka92** [comment]
@ibuziuk I can take it.

**Comment by ibuziuk** [comment]
thank you!

**Comment by Katka92** [comment]
PR [1] for fixing sequence diagram was created. Some additional info was added. Fixing the build of dependency image would require more investigation and is not part of this PR. 

[1] https://github.com/redhat-developer/rh-che/pull/1258

**Comment by ibuziuk** [comment]
@Katka92 are you going to close this issue and create another one for build fixing ?

**Comment by Katka92** [comment]
@ibuziuk I would prefer to wait few more days. There is PR from @amisevsk https://github.com/redhat-developer/rh-che/pull/1268 so I would wait when it is merged to see if it solve the problem. If not, I would close this issue and create one about deeper investigation of failing build. Are you ok with that?

**Comment by ibuziuk** [comment]
@Katka92 any updates ^ ?

**Comment by Katka92** [comment]
@ibuziuk It seems that everything which is important was fixed. There are some minor issues left, so we created separate issues on our side to track that. I think this issue can be closed.
