### ISSUE TITLE
Migrate the Woopra telemetry main component in a dedicated service for Che 7 

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1229]
**Description:**

The content of this issue is to implement the migration of the telemetry wsagent plugin, to now provide the same feature as a standalone small REST service that can be made available as a side car container and contacted by sibling CHE 7 side car containers to submit telemetry events.

The guidelines of the implementation are provided in the related spike issue:  #1154

**Comment by ibuziuk** [comment]
We plan to either finish telemetry for Che 7 in rh-che OR prepare docs / code to the phase once someone from Che OSIO team would be able to take over
