### ISSUE TITLE
rh-che/dockerfiles build is failing

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1234]
Build of rh-che/dockerfiles https://github.com/redhat-developer/che-dockerfiles is failing on - https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/

> [2Bunauthorized: access to the requested resource is not authorized

**Comment by amisevsk** [comment]
Build has been failing for over two months -- issue is that there's no repo for `che-centos_nodejs_community` on quay.io.

Repo is created, PR https://github.com/redhat-developer/che-dockerfiles/pull/47 sent to clean up CI output (remove progress logging)

**Comment by ibuziuk** [comment]
@amisevsk great job - build is passing now -https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/ \o/ Wondering maybe would be great to  add a few lines about how to  add dedicated repo in https://github.com/redhat-developer/che-dockerfiles README ?

**Comment by amisevsk** [comment]
@ibuziuk Good idea -- added to https://github.com/redhat-developer/che-dockerfiles/pull/47

**Comment by ibuziuk** [comment]
@amisevsk thank, great job! PR is merged. Closing

**Comment by amisevsk** [comment]
Build is now failing due to timeout -- no idea why.

**Comment by ibuziuk** [comment]
looking through commits I do not see any obvious reason of what could potentially slow down the build. Probably we just need to increase timeout for the time being.

**Comment by ibuziuk** [comment]
increasing timeout to 180 minutes - https://github.com/openshiftio/openshiftio-cico-jobs/pull/964

**Comment by ibuziuk** [comment]
timeout increase seems to help -  https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/ \o/
Closing
