### ISSUE TITLE
Investigate how prometheus metrics could be used on statuspage.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1237]
Need to investigat if statuspage support prometheus [1] format e.g. will it be possible to display status based on API endpoint which provides data in the prometheus format. Major use-case is the following - API endpoint provide a set of metrcis in prometheus format, will it be possible to configure status page, so that if metric `m` is lower than predefined value `n`, the realtime incident is created by the status page?

[1] https://prometheus.io/

**Comment by ibuziuk** [comment]
Update from statuspage.io support team:

> At this time we do not have any formal integration available with Prometheus, and in fact this looks like the first such request we have received on the topic. While we don't have an official integration with the service, you may still be able to pull in the desired data to a custom System Metric using our API. The following links will provide some more documentation on how that would work:
> - https://help.statuspage.io/knowledge_base/topics/introduction-1
> - https://developer.statuspage.io/#tag/metrics
>

**Comment by ibuziuk** [comment]
Another update from support:

> I'm afraid that we do not do any sort of calculations or post processing of data that you submit to a metric - all of that would need to be done on your end, and then the final values passed into the Statuspage API.

**Comment by ibuziuk** [comment]
Basically, statuspage.io does not provide support of prometheus. In general, all data processing would need to be done on our end and send via POST request using statuspage API:



[1]

**Comment by fche** [comment]
statuspage.io's custom-metrics machinery is push-based (making webapi calls to push metric series/samples) https://doers.statuspage.io/api/v1/metrics/ .

**Comment by ibuziuk** [comment]
Closing, since all the required investigations have been done.
