### ISSUE TITLE
Simplifying and speeding up CI

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1244]
**Description:**
We use CICO as a CI platform which provides bare VMs for each job iteration. 
This let us to the installation of different software needed for the build of rhche: NodeJS, Golang, Java, Maven, Docker etc.
Installation of this software makes our build process longer and since we already have Docker installed there we could just lunch build inside of a docker image with all the needed software preinstalled.
Usage of a docker image would also simplify CICO scripts. And this is also very important because RhChe team agreed on not being very familiar with what is going on at the CI execution time.
Why it is needed:
- CI execution time can be significantly improved
- CI scripts are complex and RhChe team is not very familiar with its internals whereas it should own processes for the project

What can be done:
- Use pre-built docker image to cut the time needed for software installation
- Simplify scripts since a lot of code would not be needed with the usage of Docker image for build
- Investigate if CICO provides a single CPU or multiple to decide whether we can enable maven parallel build

**Comment by ibuziuk** [comment]
WIP PR by @tdancs - https://github.com/redhat-developer/rh-che/pull/1204

**Comment by ibuziuk** [comment]
@tdancs will you be able to finalize the draft PR during the sprint ?

**Comment by ibuziuk** [comment]
@tdancs @ScrewTSW any plans to finalize the initial PR in this Sprint?

**Comment by ibuziuk** [comment]
Closing as obsolete
