### ISSUE TITLE
Bayesian for pom.xml not working on reopening file

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1256]
When adding vulnerable dependency, bayesian error is shown. When closing a reopening the file, this error is not present.

**Red Hat Che version:** 

version: che.openshift.io (current version 6.18.2)

**Reproduction Steps:**
Create workspace with Eclipse vert.x project. Open pom.xml. Add dependency
```
      <dependency>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-core</artifactId>
          <version>1.1.10</version>
      </dependency>
```
Wait for bayesian error to appear. Close file. Reopen file. Error is not present.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
Closing as outdated. This issue used to be Che 6 specific
