### ISSUE TITLE
Update RhChe to 7 beta 2 and adapt configuration 

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1261]
**Description:**
PR https://github.com/eclipse/che/pull/12673 should be merged in 7 beta 2. It changes service executor configuration which we use to avoid OOM of Che master and successful start of workspaces. Our configuration needs to be adapted.
What to take into account:
- there are 2 endpoints which are processed by 2 different executor services - major and minor
- Bootstrapper logs **should** (not sure it is checked) go to the minor endpoint. These messages could be safely discarded
- Bootstrapper statuses **should** go to major endpoint. These messages **should not** be discarded.
- Messages queue configuration is added
- 2 executor services consume more RAM than 1, so we need to ensure services are properly configured to avoid OOM

**Comment by ibuziuk** [comment]
First step for this issue https://github.com/redhat-developer/rh-che/pull/1294/

**Comment by ibuziuk** [comment]
Looks like there is a problem with che 7 beta 2 related to exec execution - https://github.com/redhat-developer/rh-che/pull/1294

**Comment by ibuziuk** [comment]
PR for adding `CHE_WEBSOCKET_ENDPOINT__MINOR` - https://github.com/redhat-developer/rh-che/pull/1326
Once merged that should hopefully make https://github.com/redhat-developer/rh-che/pull/1294 to pass
Second step would be updating cms on dsaas / dsaas-stg

**Comment by ibuziuk** [comment]
PR for correctly processing `CHE_WEBSOCKET_ENDPOINT__MINOR` on PR check side https://github.com/redhat-developer/rh-che/pull/1328

**Comment by ibuziuk** [comment]
che.openshift.io has been updated to 7 beta 2. Pending actions:
- [ ] @ScrewTSW is going to provide clear documentation related to JSONRPC queue  settings and stress tests related to OOM / DOS / DDOS
- [ ] @ScrewTSW will update https://github.com/redhat-developer/rh-che/pull/1323 and provide optimal settings for che.openshift.io

**Comment by ibuziuk** [comment]
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/274 is merged so closing this issue
partial docs have been provided in the `Change rhche JSONRPC queue settings` [1] description.
@ScrewTSW @rhopp could you please clarify what is the plan with the docs and https://github.com/redhat-developer/rh-che/issues/1337 in the next sprint?


[1] https://github.com/redhat-developer/rh-che/pull/1323
