### ISSUE TITLE
Need to add ephemeral toggle (hidden by default) on the workspace creation view of UD

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1263]
Placeholder for https://github.com/eclipse/che/issues/12776

**Comment by ibuziuk** [comment]
@amisevsk tested on prod and toggle is enabled by default, but looks like still pvc is used instead of empty-dir volumes:

![image](https://user-images.githubusercontent.com/1461122/54267451-8b2f4100-4579-11e9-960f-f6afeabe228d.png)

Am I correct that we need to wait 7 beta 2 where ephemeral toggle logic was fixed in the upstream ?

**Comment by ibuziuk** [comment]
hmmm.. looks like no matter if toggle is enabled / disabled pvc (not empty dir) is still used ¯\_(ツ)_/¯

**Comment by amisevsk** [comment]
So from checking on prod, it looks like the default state isn't propagated to the config (I didn't catch this in testing because the switch to `enabled` by default was a late fix). It works as expected if you toggle ephemeral mode to disabled and back again.

I'll work on it.

**Comment by amisevsk** [comment]
PR here: https://github.com/redhat-developer/rh-che/pull/1292

**Comment by ibuziuk** [comment]
Closed as done

**Comment by ibuziuk** [comment]
verified on prod - works like a charm \o/
![image](https://user-images.githubusercontent.com/1461122/54699272-fefcbb00-4b30-11e9-82b9-19cc85e73b85.png)
