### ISSUE TITLE
Support running multiple VS Code extensions in the same sidecar

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1265]
Placeholder for https://github.com/eclipse/che/issues/12395

**Comment by garagatyi** [comment]
I'm finishing adding an ability to create Che pluginwith several VS Code extensions as Thomas suggested. See my comment https://github.com/eclipse/che/issues/12395#issuecomment-473314966
Here is the explanation that automatical collapsing of plugins into a sidecar would require more work https://github.com/eclipse/che/issues/12395#issuecomment-472527140.

@ibuziuk @l0rd Should I work on that automatic stuff or it is better to start investigating issue with the marketplace rate limit?

**Comment by ibuziuk** [comment]
Closing as done
