### ISSUE TITLE
Automatically build any PR to get to fabric8 CI and make it testable on OSIO for reviewers

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#127]
see - https://issues.jboss.org/browse/CHE-177

**Comment by ibuziuk** [comment]
CI job for pr verification in rh-che distro

**Comment by l0rd** [comment]
After discussion during sprint planning we have considered using the new link in PRs opened in repo https://github.com/fabric8-services/fabric8-tenant-che. So as soon as a PR in rh-che is created a build should be triggered and a PR in https://github.com/fabric8-services/fabric8-tenant-che opened. A reviewer would then be able to test the PR on OSIO.

When the PR get approved the commits included are merged to rh-che master branch and a new build is run.

**Comment by sunix** [comment]
Would it be possible to have this very same kind of hook in our rh-che repo:

rh-che when a PR is created:
 1. it triggers the build of rh-che.
 2. if the build is successful it triggers the same hook that is using the "fabric8-tenant-che" master branch deployment and generate the link.

**Comment by l0rd** [comment]
With multi-tenant Che it's not possible for the reviewers to test Che in their user namespace
