### ISSUE TITLE
Workspace not started on prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1282]
**Issue problem:** 
When creating and running workspace on prod-preview, it failed with that message in console:
![screenshot from 2019-03-07 09-16-09](https://user-images.githubusercontent.com/29278800/53941920-b4ebf200-40b9-11e9-9e13-990468ed1ee8.png)

Seems like a problem of 2a cluster - I was able to see that on prod and prod-preview when using users provisioned on us-east-2a cluster. Users I've used ```kkanova-preview``` on prod-preview and ```osiotest2aProd``` on production.

**Red Hat Che version:** 
prod and prod-preview using 2a cluster

**Reproduction Steps:**
Create new workspace via Dashboard and click ```Create & Open``` button

**Runtime:**
che.prod-preview.openshift.io
che.openshift.io

**Comment by Katka92** [comment]
I was not able to reproduce this error on production with user accounts provisioned on 2, 1a and 1b cluster.

**Comment by amisevsk** [comment]
There was a SNOW ticket created: INC0837585

According to that, issue should be resolved now -- @Katka92 can you confirm?

**Comment by Katka92** [comment]
@amisevsk I've tried again with user account on production 2a cluster. Workspace was created and started successfully. The import of project takes incredibly long time, but it is probably another issue.

**Comment by ibuziuk** [comment]
@Katka92 closing. I believe @rhopp already created an issue for long cloning  https://github.com/redhat-developer/rh-che/issues/1289
