### ISSUE TITLE
Need to contribute 2 system metrics to statuspage

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1286]
Need to contribute 2 system metrics to statuspage - https://che.statuspage.io/

 - Successfully started workspaces ratio https://github.com/eclipse/che/pull/12852
 - Average workspace start time https://github.com/eclipse/che/pull/12859

**Comment by ibuziuk** [comment]
@fche @gorkem so how do you think we should proceed with this issue to make the impl reusable as much as possible also for 4.0 ?  Is creating a separate dsaas-service right away is the way to go?

**Comment by fche** [comment]
Re. metrics, would need the actual prometheus-level metric names.
Re. where to put statuspage.io outbound code -- it could be anywhere:
- inside rhche proper, write some new code in java and bob's your uncle
- inside osd-monitor, just a new small component we can write, as outlined in email two weeks back
- inside some brand new peer pod to osd-monitor

**Comment by ibuziuk** [comment]
> where to put statuspage.io outbound code -- it could be anywhere:

@fche sure, I just wondering about the best approach, I just do not know if we should opt for osd-monitor or brand-new service taken into account operator / OpenShift 4 switch. I'm ok to put it the outbound code to osd-monitor for now as a prototype, but what is the mid term / long term approach is going to be ?

**Comment by ibuziuk** [comment]
@l0rd @slemeur based on the discussion during IC I believe we do need to contribute `Successfully started workspaces ratio` as the first metric to che.statuspage.io

**Comment by ibuziuk** [comment]
the second metric most likely should be time required for route to become accessible,  but here I'm not sure how exactly this should be implemented since this is cluster specific thingy

**Comment by l0rd** [comment]
@ibuziuk ok for `Successfully started workspaces ratio` as first metric

**Comment by amisevsk** [comment]
Instead of route accessibility, would it make sense to have a more general "average time for workspace to start" metric? It should be pretty simple to implement along the lines of the successfully started metric (Look for starting event, start timer, look for started / failed event, stop timer).

**Comment by fche** [comment]
Please let me know when these metrics are exported, and under what names.

**Comment by l0rd** [comment]
And yes `average time for workspaces to start` metric is good candidate as well. Probably better then the route one (even if I have been asking for the route metric).

**Comment by ibuziuk** [comment]
Moving to `P2` pipeline since it is not a priority atm

**Comment by ibuziuk** [comment]
It does not look like this is going to happen. Closing.
feel free to reopen if this becomes a priority again
