### ISSUE TITLE
Need to add additional "FAQ" link to the UD which would point to the adoc in the rh-che repo

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1287]
Need to add additional "FAQ" link to the UD which would point to the adoc in the rh-che repo:
![image](https://user-images.githubusercontent.com/1461122/54195368-c882c880-44be-11e9-8c26-fcec09b0df50.png)
- the content of adoc is planned to be provided by the docs team via PRs: cc @rkratky

**Comment by rkratky** [comment]
> which would point to the adoc in the rh-che repo

Would it be possible to have the rendered adoc hosted somewhere like che.openshift.io/faq or similar? Two reasons:

- linking to GH looks like WIP, like something temporary
- GH rendering is not very good, and we can render the doc, so that it would use the official RHD branding

**Comment by ibuziuk** [comment]
> Would it be possible to have the rendered adoc hosted somewhere like che.openshift.io/faq or similar

This would require much more work / customizations, so I would rather opt for adoc on github.

> GH rendering is not very good

Could you provide some examples, I find it quite good and use on a regular basis e.g. https://github.com/ibuziuk/docs/blob/master/che_plugin_brokers.adoc also all rh-che docs are in adoc format

**Comment by ibuziuk** [comment]
@amisevsk as a pro on UD overriding could you please clarify how easy/difficult would it be to add an extra link in the footer ?

**Comment by rkratky** [comment]
> This would require much more work / customizations, so I would rather opt for adoc on github.

OK

> Could you provide some examples, I find it quite good

It's OK when only basic mark-up is used. Which what we should do anyway -- disregard my previous comment.

**Comment by amisevsk** [comment]
Adding the link shouldn't be hard at all -- the footer is probably a less invasive and more common sense modification than we usually do.

Given a link, it'd be a 5 minute change.

**Comment by ibuziuk** [comment]
@rkratky any ideas/proposals about FAQ content?

**Comment by ibuziuk** [comment]
PR with FAQ.adoc - #1324

**Comment by ibuziuk** [comment]
@amisevsk great job, I believe we can close the issue now:

![che openshift io FAQ](https://user-images.githubusercontent.com/1461122/54819527-7438cf00-4c9c-11e9-8411-181fabbe3612.gif)

@rkratky looking forward for doc team contributions ;-) - https://github.com/redhat-developer/rh-che/blob/master/FAQ.adoc
