### ISSUE TITLE
Rhche on pruduction spammed by Web socket session error

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1291]
**Issue problem:** 
There is a huge amount of messages saying that ```Web socket session error``` is present and then ```Closing unidentified session``` which is related with that (at least this is my opinion). 

Example from rhche log:
```

{"@timestamp":"2019-03-13T16:17:22.525+00:00","@version":1,"message":"Closing unidentified session","logger_name":"org.eclipse.che.api.core.websocket.impl.BasicWebSocketEndpoint","thread_name":"http-nio-8080-exec-3","level":"WARN","level_value":30000}
{"@timestamp":"2019-03-13T16:17:22.534+00:00","@version":1,"message":"Web socket session error","logger_name":"org.eclipse.che.api.core.websocket.impl.BasicWebSocketEndpoint","thread_name":"http-nio-8080-exec-13","level":"WARN","level_value":30000}

```

There is one more message which is probably related but occurs less often:
```
{"@timestamp":"2019-03-13T16:17:19.564+00:00","@version":1,"message":"Processing messing within unidentified session","logger_name":"org.eclipse.che.api.core.websocket.impl.BasicWebSocketEndpoint","thread_name":"http-nio-8080-exec-10","level":"WARN","level_value":30000}
```
  
**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by amisevsk** [comment]
I agree that these logs are not useful.

FWIW I can reproduce `Closing unidentified session` semi-reliably locally on minishift by
1. Open dashboard to running instance of Che
2. Start new deployment of Che while leaving the dashboard open.
3. After Che starts, a lot of the time `Closing unidentified session` is logged ~30 times

**Comment by Katka92** [comment]
When I reported it, it was really logged in very high speed. Today it seems not be logged that much, anyway it still appears.

**Comment by amisevsk** [comment]
I believe a lot of the `Closing unidentified session` occur around when the server is restarted.

**Comment by garagatyi** [comment]
Upstream issue https://github.com/eclipse/che/issues/11571 is quite old. Nobody has prioritized it yet

**Comment by ibuziuk** [comment]
Still happens on Che 7
