### ISSUE TITLE
Need to switch to Auth logout v2 in che.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1298]
Partially related to https://github.com/redhat-developer/rh-che/issues/1290#issuecomment-473382270

OSIO Auth team  actually implemented a new version of logout endpoint in auth service. Che should really switch to that v2 endpoint for logout. 

Sorry, we forgot that che also using logout and didn't notify you about that change:

http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/logout/logout_logoutv2
fabric8-services/fabric8-auth#746
fabric8-ui/fabric8-ui#3513 (this is a PR to OSIO UI with some details about how the new logout v2. endpoint works)

@sbryzak can help you if you have questions and also @rohitkrai03 can help if you have any questions about how it should be implemented in UI.

**Comment by ibuziuk** [comment]
@alexeykazakov is this issue still relevant?

**Comment by alexeykazakov** [comment]
Yes, it's still relevant if the logout v2 is still not used.

**Comment by ibuziuk** [comment]
Closing as outdated
