### ISSUE TITLE
Self Hosting on openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#130]
see - https://issues.jboss.org/browse/CHE-127

**Comment by ibuziuk** [comment]
related to https://github.com/eclipse/che/issues/5529

**Comment by l0rd** [comment]
Instruction to install upstream osio (fabric8 platform) on minishift are [here](https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md)
