### ISSUE TITLE
VS Code marketplace rate limit error

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1300]
Placeholder for eclipse/che#12840

**Comment by ibuziuk** [comment]
need to investigate the possibility of redistribution of vscode extensions + discuss legal aspects about redistribution of extensions/rate limit with vscode legals.

**Comment by ibuziuk** [comment]
Closing since workaround has been implemented and promoted to prod https://github.com/eclipse/che/issues/12840#issuecomment-486663799
