### ISSUE TITLE
Make unified broker accept list of plugins ID:version s and download meta.yaml from plugin registry

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1305]
**Description:**
Instead of processing JSON with meta.yaml content as list entries Unified Broker should accepts list of plugin id:version entries and download meta.yaml content from Che plugin registry.

Flow:
- Add parsing of parameter with registry address
- Add parsing of plugins id:version entries. Probably from an environment variable.
- Download meta.yaml from plugin registry
- Support downloading of meta.yaml from custom plugin registries, e.g. `https://raw.githubusercontent.com/eclipse/che-plugin-registry/shareSidecarWithDebug/plugins/org.eclipse.che.vscode-redhat.java-and-xml:0.38.0` which represents https://raw.githubusercontent.com/eclipse/che-plugin-registry/shareSidecarWithDebug/plugins/org.eclipse.che.vscode-redhat.java-and-xml/0.38.0/meta.yaml
- proceed with the regular flow

Depends on https://github.com/redhat-developer/rh-che/issues/1304

Related to https://github.com/eclipse/che/issues/12908

**Comment by garagatyi** [comment]
@amisevsk Unfortunately I'm not sure that it is very clear on what exactly [issue](https://github.com/eclipse/che-plugin-registry/issues/55) about new naming convention would involve. There are open questions about [breaking existing workspaces on existing Che 7 instances](https://github.com/eclipse/che-plugin-registry/issues/55#issuecomment-475217440), about [naming convention details](https://github.com/eclipse/che-plugin-registry/issues/55#issuecomment-475577834).
Because of that I would suggest working on this issue without taking into account changes that are supposed to be brought by that issue and we will have to adapt later. This would simplify work for you and allow us to iterate faster.

**Comment by amisevsk** [comment]
Merged upstream.

**Comment by amisevsk** [comment]
Deployed to prod
