### ISSUE TITLE
WS master should send plugin IDs instead of plugins metas to unified broker

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1307]
**Description:**
Flow:
- Inject Che plugin registry endpoint as an environment variable to plugin broker
- Inject plugins id:version list as an environment variable to plugin broker
- Remove downloading and parsing meta.yaml files from Che plugin registry and passing it to plugin broker

Depends on https://github.com/redhat-developer/rh-che/issues/1305, https://github.com/redhat-developer/rh-che/issues/1305
Depends on https://github.com/redhat-developer/rh-che/issues/1306, but can be collapsed if https://github.com/redhat-developer/rh-che/issues/1305 is done 

Related to https://github.com/eclipse/che/issues/12908

**Comment by amisevsk** [comment]
Merged into upstream; should be in next release.

**Comment by amisevsk** [comment]
Deployed to prod
