### ISSUE TITLE
Process additional fields in meta.yaml

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1308]
**Description:**
See detailed explanation here https://github.com/eclipse/che/issues/12908#issuecomment-474312103

Flow:
- Add apiVersion field to meta.yaml model
- In case `apiVersion: 2` do:
  - Unified broker should be able to parse and process new fields (inside of spec field) of meta.yaml and not process deprecated fields (extensions, attributes, url). See example here https://gist.githubusercontent.com/garagatyi/0ae0f6a05b76e504c9152e6eef160917/raw/meta.yaml
  - For VS Code plugins also process extensions field, see https://gist.githubusercontent.com/garagatyi/0ae0f6a05b76e504c9152e6eef160917/raw/plugin-vscode-with-ram.yaml
  - For Theia plugins process `plugins` field instead of extensions in VS Code plugin case. Limit to support of 1 plugin since multiple plugins support can bloat the implementation, which is not needed at this point.
- In case `apiVersion: 1`: fail - should be tackled in  https://github.com/redhat-developer/rh-che/issues/1310

Related to https://github.com/eclipse/che/issues/12908

**Comment by amisevsk** [comment]
@ibuziuk I'm closing this issue as fixed in https://github.com/eclipse/che-plugin-broker/pull/55, please reopen if this is inaccurate (I wasn't around for planning this sprint)
