### ISSUE TITLE
Add unified plugin broker compatibility with the old meta.yaml flow

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1310]
**Description:**
https://github.com/redhat-developer/rh-che/issues/1308 is suppose to add extended meta.yaml support when `apiVersion: 2`. For simplicity and iterability backward compatibility with `apiVersion: 1` can be tackled in separate, this, issue. 

Flow:
In case `apiVersion: 1` or empty (suppose string value) or field is missing convert old meta.yaml flow to `apiVersion: 2` representation and proceed with processing as in `apiVersion: 2` case.
  - Che plugin type only related:
     - Download file by URL from field `url` in meta.yaml. It can be meta.yaml content or tar.gz archive with it.
     - Remove files copying functionality in common Che plugin type since it is unused.
  - VS Code/Theia plugin types: convert `apiVersion: 1` model to `apiVersion: 2` which is very easy:
     - if meta.attributes.containerImage is present add container entry with image
     - move meta.extensions to meta.spec.extensions for VS Code
     - put meta.extension to meta.spec.extensions for VS Code
     - put meta.url to meta.spec.extensions for VS Code
     - put meta.url to meta.spec.extensions for Theia plugins

Depends on https://github.com/redhat-developer/rh-che/issues/1308

Related to https://github.com/eclipse/che/issues/12908

**Comment by garagatyi** [comment]
We discussed this with Mario and Ilya and agreed not to support backward compatibility yet since Che is in beta and not heavily used at the moment.

@ibuziuk can we close this issue?

**Comment by ibuziuk** [comment]
yes, I believe we can close it now
