### ISSUE TITLE
Fix issue with Getting Started in the email registration template

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1320]
Fix issue with Getting Started in the email registration template https://user-images.githubusercontent.com/1461122/53915886-1df34b80-4061-11e9-80e3-128495545f01.png

**Comment by ibuziuk** [comment]
I believe this issue would be fixed during major branding update related to openshift.io -> che.openshift.io transition

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW I know you checked the registration flow just after the registration. Could you please shed some light on how email template looks now for a newly provisioned users? Also would be great to provide info about registration flow when user is provisioned for the first time via factory from https://www.eclipse.org/che/getting-started/cloud/ e.g. Spring Boot - https://che.openshift.io/f?id=factorypedk0ijio2y27tzf 
what is the registration UX in this case

**Comment by Katka92** [comment]
@ibuziuk I've created an account for a red hat user yesterday on production and email looks like that:
![Screenshot from 2019-04-24 08-04-07](https://user-images.githubusercontent.com/29278800/56635986-b53f4d00-6667-11e9-9222-189447d2dc4b.png)

So today I created new user using the link to Spring Boot factory you posted. It redirects me to the login page, so I click ``` Create one now ```. I filled information and created new account. I got an email:

![Screenshot from 2019-04-24 08-15-56](https://user-images.githubusercontent.com/29278800/56640133-84b0e080-6672-11e9-83a1-fb0f02937b9e.png)

Which sends me to verification:
![Screenshot from 2019-04-24 08-16-11](https://user-images.githubusercontent.com/29278800/56640154-94c8c000-6672-11e9-85e7-4fbff85a3743.png)

Then informs me that account was verified:
![Screenshot from 2019-04-24 08-16-40](https://user-images.githubusercontent.com/29278800/56640175-a14d1880-6672-11e9-96b2-642fb71183f8.png)

I was asked to fill a captcha, but the css for this page seems broken:
![Screenshot from 2019-04-24 08-16-58](https://user-images.githubusercontent.com/29278800/56640226-c3df3180-6672-11e9-9a6c-b44bda5de514.png)

After filling captha, I continued. Then I was waiting for provisioning of the user.
![Screenshot from 2019-04-24 08-17-42](https://user-images.githubusercontent.com/29278800/56640295-f1c47600-6672-11e9-8b42-14c59a493439.png)


After while when I did refresh I could click a button to access web console. I was redirected to ```https://openshift.io``` so I needed to log in again.
![Screenshot from 2019-04-24 08-17-58](https://user-images.githubusercontent.com/29278800/56640273-e7a27780-6672-11e9-93e1-05705198b16f.png)

The email was sent with info that the user was provisioned:
![Screenshot from 2019-04-24 09-26-15](https://user-images.githubusercontent.com/29278800/56640345-115b9e80-6673-11e9-9380-e20b3899bc9f.png)

During this process I was asked to log in few times and some new windows were opened. After the last log in, when the user was provisioned, I was redirected to dashboard [1] and no factory was opened. The user was provisioned on cluster 1b.
From my point of view the workflow of creating a user is the same using factory or not. Maybe if I will not continue in the new opened window but instead close it and refresh the previous window with the link to the factory, I could get factory created, but I would not say that this is something that real user would do. 
If you want me to try some other way please let me know. 

[1] ![Screenshot from 2019-04-24 09-28-02](https://user-images.githubusercontent.com/29278800/56640458-5da6de80-6673-11e9-8cbc-947cb5ee1cf2.png)

**Comment by ibuziuk** [comment]
thanks, @Katka92 
I see 2 issues here:
1. email template is still Openshift.io centric (nothing about che.openshift.io / Hosted Che) not sure if it is expected from marketing / PM perspective cc: @slemeur @bmicklea
2. if a user is registered via factory link he is not redirected to the factory link after registration

**Comment by bmicklea** [comment]
1. The email template needs to be changed with the OpenShift Online group - they've got other changes going through (this week I think) that should include these fixes
2. I'm not sure who has to address this...

**Comment by ibuziuk** [comment]
@bmicklea 2 is smth we should take care in che.openshift.io e2e registration flow - once user is provisioned this page should be refreshed automatically and a workspace creation  based on factory should start 
![Screenshot from 2019-04-24 08-16-58](https://user-images.githubusercontent.com/29278800/56640226-c3df3180-6672-11e9-9a6c-b44bda5de514.png)
This does not happen atm, right @Katka92 ?

**Comment by Katka92** [comment]
@ibuziuk I think that during the registration process you are redirected to newly opened tab two times. So if you continue in that tab, you probably lose the information about URL which you visited first time. I can try that again and pay attention on that.

**Comment by ibuziuk** [comment]
This one should be fixed and verified as part of the 7 GA updated https://www.eclipse.org/che/docs/che-7/hosted-che/#registering-to-hosted-che_hosted-che
