### ISSUE TITLE
Verify dashboard build works right given upstream changes intoduced in che 7 beta 3

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1325]
**Description:**
PR https://github.com/eclipse/che/pull/12955 changes the dashboard build process somewhat. Since we are duplicating and modifying the upstream build to a large extent, we should verify that the changes in upstream work on our end and port them to our build.

**Comment by ibuziuk** [comment]
looks like it started to fail - https://github.com/redhat-developer/rh-che/pull/1312#issuecomment-476587501

**Comment by ibuziuk** [comment]
>      [exec] $ yarn run typings
>      [exec] [91mmodule.js:550
>      [exec]     throw err;
>      [exec]     ^
>      [exec] 
>      [exec] Error: Cannot find module '/dashboard/node_modules/.bin/yarn'
>      [exec]     at Function.Module._resolveFilename (module.js:548:15)
>      [exec]     at Function.Module._load (module.js:475:25)
>      [exec]     at Function.Module.runMain (module.js:694:10)
>      [exec]     at startup (bootstrap_node.js:204:16)
>      [exec]     at bootstrap_node.js:625:3
>      [exec] [0m[91merror Command failed with exit code 1.

details in https://github.com/redhat-developer/rh-che/pull/1333

**Comment by amisevsk** [comment]
I can take a look at this, it's likely a matter of copying the upstream build changes.
