### ISSUE TITLE
Init tenant should set the correct Keycloak URL

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#133]
see - https://issues.jboss.org/browse/CHE-282

With commmit in fabric8-online[1] we have introduced two new configs for che-server:

- keycloak-oso-endpoint
- keycloak-github-endpoint

These are currently hardcoded in fabric8io configuration with KC production URLs. That's an issue because we may need to use a distinct instance of KC based on which cluster Che will be deployed to. These 2 config maps should be configured by the tenant init script as it's already done for hostname-http

[1] https://github.com/redhat-developer/rh-che/commit/148fc268b6a7b26574220ad1de715ff6140fb5ce

**Comment by ibuziuk** [comment]
Might be fixed via `api/keycloak/settings/`

**Comment by davidfestal** [comment]
This endpoint will also be useful to provide some of the Keycloak configuration settings that, for now, are hard-wired in the client-side or server-side code of the Keycloak integration:
- WsMaster web application:
    - server-side configuration for the Keycloak servlet filter: [keycloak.json](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/keycloak.json)

- WsAgent web application:
    - server-side configuration for the Keycloak servlet filter: [keycloak.json](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-wsagent-war/src/main/webapp/WEB-INF/keycloak.json)

- GWT IDE web application:
    - server-side configuration for the Tomcat valve in front of the GWT application: [keycloak.json](
https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-ide-war/src/main/webapp/WEB-INF/keycloak.json)
    - client-side configuration in Javascript code: [IDE.jsp.patch](https://github.com/redhat-developer/rh-che/blob/d89bed0e4f1a4cfc30e11b09235731120ccc75c1/builds/fabric8-che/assembly/assembly-ide-war/src/main/patches/src/main/webapp/IDE.jsp.patch#L15)

The settings that should be configurable are mainly:
- the Keycloak server URL:
    - `url` in client-side Javascript configuration
    - `auth-server-url` in server-side Java configuration

- the Keycloak realm:
    - `realm` in client-side Javascript configuration
    - `realm` in server-side Java configuration

- the Keycloak client ID:
    - `clientId` in client-side Javascript configuration
    - `resource` in server-side Java configuration

The idea is to add these 3 properties in `rh-che.properties` :
- `che.keycloak.auth-server-url`
- `che.keycloak.realm`
- `che.keycloak.client-id`

the same way as `che.keycloak.disabled` already exists.

These properties would be made available in the `/keycloak/settings` endpoint provided by class [KeycloakService](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/plugins/keycloak-plugin-server/src/main/java/com/redhat/che/keycloak/server/KeycloakService.java)
  
Then, to be available in the WsAgent, we would add the corresponding property providers that will request this endpoint to get the setting values (as already done for the `disabled` property)

Finally, these properties would be used in the Keycloak configurations as follows:
- for the client-side Javascript configurations, they would be retrieved through a XHR and injected during Keycloak initialization (the structure is already in place to get the `disabled` property)
- for the server-side Java configuration, we could use the `${…​}` system property placeholder (described [here](https://keycloak.gitbooks.io/documentation/securing_apps/topics/oidc/java/java-adapter-config.html)) and set the corresponding system properties server-side in the tomcat applications (probably in the valve).

**Comment by ibuziuk** [comment]
@davidfestal for now keycloak endpoints are set in `fabric8-online` [1]. So, the plan is to remove `keycloak-oso-endpoint` & `keycloak-github-endpoint` and configure those via properties [2] which will be possible to obtain using `api/keycloak/settings/` endpoint. Note: those properties are used in **KeycloakTokenProvider** from `che-keycloak-plugin-token-provider` plugin


[1] https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/cm.yml#L20
[2] https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/rh-che.properties

**Comment by skabashnyuk** [comment]
keycloak-github-endpoint - need for what?

**Comment by ibuziuk** [comment]
@skabashnyuk for obtaining github token

**Comment by skabashnyuk** [comment]
@ibuziuk  Have you think about to reuse Eclipse Che https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticationService.java#L166

**Comment by ibuziuk** [comment]
@skabashnyuk I think there is an issue for this - https://github.com/redhat-developer/rh-che/issues/108

**Comment by ibuziuk** [comment]
@davidfestal I have created a separate issue for init tenant - https://github.com/fabric8-services/fabric8-tenant/issues/228
Should we close this one ?

**Comment by ibuziuk** [comment]
@davidfestal closing. feel free to reopen if needed
BTW, fabric8-services/fabric8-tenant#228 is also closed
