### ISSUE TITLE
Need to create dsaas service for deploying Prometheus / Grafana stack with dedicated dashboards implemented in the upstream che 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1336]
Need to create dsaas service under redhat-developer [1] for deploying Prometheus / Grafana stack with dedicated dashboards implemented in the upstream che [2] to prod-preview / prod:

![Знімок екрана  о 15 42 36](https://user-images.githubusercontent.com/1614429/54205784-ad748080-44df-11e9-92de-cf144c03d4a3.png)
![Знімок екрана  о 15 42 53](https://user-images.githubusercontent.com/1614429/54205788-b06f7100-44df-11e9-928c-3cbcafda85ab.png)
![Знімок екрана  о 13 56 31](https://user-images.githubusercontent.com/1614429/54122371-83e72680-4405-11e9-88f0-cd4ce081a3ee.png)

[1] https://github.com/redhat-developer
[2] https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-monitoring.yaml

**Comment by fche** [comment]
If we're running rh-che on recent enough ocp 3.11, then you can make this happen with an invocation of prometheus-operator / grafana-operator.  Is this your plan?

**Comment by ibuziuk** [comment]
@fche no, it would be just a matter of applying template - https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-monitoring.yaml

**Comment by fche** [comment]
OK, in that case go for it!  While we're using the old OSIO CICO build/deploy system, you'll need to work through the internal housekeeping and external github.com/openshiftio/saas repos.

**Comment by ibuziuk** [comment]
repo created - https://github.com/redhat-developer/che-monitoring

**Comment by ibuziuk** [comment]
PR with template from upstream - https://github.com/redhat-developer/che-monitoring/pull/1

**Comment by ibuziuk** [comment]
fixed and metrics are available for both prod and prod-preview
