### ISSUE TITLE
Need to verify if rh-che is stable with the upstream CHE_CORE_JSONRPC setting and 1 GB of RAM

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1337]
PR introduced a few changes of CHE_CORE_JSONRPC which are most likely not needed and upstream values can be safely used - https://github.com/redhat-developer/rh-che/pull/1323

>   CHE_CORE_JSONRPC_MINOR__PROCESSOR__CORE__POOL__SIZE: '5'
>   CHE_CORE_JSONRPC_MINOR__PROCESSOR__MAX__POOL__SIZE: '100'
>   CHE_CORE_JSONRPC_MINOR__PROCESSOR__QUEUE__CAPACITY: '1000'
>   CHE_CORE_JSONRPC_PROCESSOR__CORE__POOL__SIZE: '30'
>   CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE: '100'
>   CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY: '500000'

Need to verify if che.openshift.io works stable without sideeffects with 1Gb of RAM and upstream settings of `CHE_CORE_JSONRPC`.

**Comment by ScrewTSW** [comment]
About default upstream values, I was able to cause the OOM crash on upstream defaults as well. They will require some tweaking (namely message queue size)

**Comment by ibuziuk** [comment]
cc: @skabashnyuk ^ wdyt shoud upstream values be adjusted. IMO it would be great if che.openshift.io would use upstream setup for `RAM` / `CHE_CORE_JSONRPC`

**Comment by skabashnyuk** [comment]
I agree with @ScrewTSW ```CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY``` has to be adjusted to fit in the 1G limit. @ScrewTSW what would be your suggestion?

**Comment by ScrewTSW** [comment]
> I agree with @ScrewTSW `CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY` has to be adjusted to fit in the 1G limit. @ScrewTSW what would be your suggestion?

I would try 200k at most. I think 150k is the safer value here.

**Comment by ibuziuk** [comment]
@ScrewTSW are you planning to provide upstream PR for review as part of this issue?

**Comment by skabashnyuk** [comment]
Already doing some adjustment https://github.com/eclipse/che/pull/13034

**Comment by ibuziuk** [comment]
@skabashnyuk wdyt, once the adjustments are done upsteam - does it makes sense to fall back on those defaults in rh-che?

**Comment by skabashnyuk** [comment]
Some data from  real-life  server
<img width="804" alt="Знімок екрана 2020-03-02 о 11 23 12" src="https://user-images.githubusercontent.com/1614429/75667768-752dfb00-5c78-11ea-93b2-9f6d3dc03bf9.png">
<img width="785" alt="Знімок екрана 2020-03-02 о 11 22 11" src="https://user-images.githubusercontent.com/1614429/75667843-95f65080-5c78-11ea-9a44-34ce7ba53630.png">
I think upstream defaults should be enaught for this type of load.
```
# Maximum size of the JSON RPC processing pool
# in case if pool size would be exceeded message execution will be rejected
che.core.jsonrpc.processor_max_pool_size=50

# Initial json processing pool. Minimum number of threads that used to process major JSON RPC messages.
che.core.jsonrpc.processor_core_pool_size=5
```

**Comment by ibuziuk** [comment]
PR sent - https://github.com/redhat-developer/rh-che/pull/1927

**Comment by ibuziuk** [comment]
applied on production
