### ISSUE TITLE
Build Wildfly project fails

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1342]
**Issue problem:** 
The default and manual build of the Wildfly project fails with message: 
```
Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.2:war (default-war) on project thorntail-rest-http: Error assembling WAR: Problem creating war: Execution exception: Java heap space -> [Help 1]
```
![Screenshot from 2019-04-02 09-05-42](https://user-images.githubusercontent.com/29278800/55382664-8b8e7c80-5526-11e9-8c3a-2284e6d8ca63.png)

**Reproduction Steps:**

Create factory by clicking on the link: https://che.openshift.io/f?id=factoryuhcji9p0z72f43gc. Wait for run command to be triggered. Wait for failure to be present.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
Need to play with `MAVEN_OPTS='-Xmx100m'`

**Comment by ibuziuk** [comment]
Closing as Fixed. 
Thorntail devfile from https://www.eclipse.org/che/getting-started/cloud/ works just fine:

![image](https://user-images.githubusercontent.com/1461122/81553213-07dbcc00-9385-11ea-93d3-7731c0395f1a.png)
