### ISSUE TITLE
che-theia terminal is empty on Firefox #117

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1343]
che-theia terminal is empty on Firefox #117 - https://github.com/eclipse/che-theia/issues/117

**Comment by ibuziuk** [comment]
@davidfestal just created an issue for tracking upstream work. Could you please add an estimate?

**Comment by davidfestal** [comment]
done
FIY I already started working on it and will continue on it tomorrow.

**Comment by ibuziuk** [comment]
@davidfestal awesome. Thank you!

**Comment by ibuziuk** [comment]
Closing in favor of https://github.com/eclipse/che/issues/13736
