### ISSUE TITLE
redhat-developer/che-dockerfiles periodic CI is broken 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1345]
https://github.com/redhat-developer/che-dockerfiles
https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/

> Cloning into 'nss_wrapper'...
> [91mCMake Error at CMakeLists.txt:2 (cmake_minimum_required):
>   CMake 3.5.0 or higher is required.  You are running version 2.8.12.2
> 
> 
> [0m-- Configuring incomplete, errors occurred!
> The command '/bin/sh -c sudo chown user:user /tmp/install /tmp/install/* &&     /tmp/install/nss_wrapper.install &&     sudo rm -rf /tmp/install' returned a non-zero code: 1

**Comment by ibuziuk** [comment]
dedicated issue - https://github.com/redhat-developer/che-dockerfiles/issues/50
PR that should fix the build problem - https://github.com/redhat-developer/che-dockerfiles/pull/52

**Comment by vorburger** [comment]
Yup, confirming that this is exactly what I fixed in https://github.com/redhat-developer/che-dockerfiles/pull/52!

**Comment by ibuziuk** [comment]
PR that should fix node recipies - https://github.com/redhat-developer/che-dockerfiles/pull/56

**Comment by ibuziuk** [comment]
looks like still, some weird things happen due to pre-building of quickstarts projects:

> Downloading maven deps for runtime:  spring-boot  -  health-check
> cloning with git clone -b https://github.com/snowdrop/spring-boot-health-check-booster https://github.com/snowdrop/spring-boot-health-check-booster tmp-folder
> Cloning into 'tmp-folder'...
> [91mfatal: Remote branch https://github.com/snowdrop/spring-boot-health-check-booster not found in upstream origin
> [0m[91mUnexpected end of command stream
> [0mThe command '/bin/sh -c sudo chown user:user /tmp/maven-deps /tmp/maven-deps/* &&     /tmp/maven-deps/maven-deps.install         'spring-boot'         'configmap'         'health-check'         'rest-http' &&     sudo rm -rf /tmp/maven-deps' returned a non-zero code: 128

**Comment by ibuziuk** [comment]
seems to be fixed now https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/605/
