### ISSUE TITLE
Rh-che shouldn't be trying to delete projects when workspaces are removed.

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1349]
**Issue problem:** 
In the discussion around https://github.com/redhat-developer/che-functional-tests/issues/470, @nurali-techie noticed that Che is making delete project calls when a workspace is removed. This seems to be due to [`RemoveProjectOnWorkspaceRemove`](https://github.com/eclipse/che/blob/88923bdb64e535b82b71e61fc946b0ec7a516943/infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/RemoveProjectOnWorkspaceRemove.java#L74).

Since we are not creating projects in rh-che and instead using pre-provisioned projects and oso-proxy, this functionality should be removed in our downstream.

**Red Hat Che version:** 
 - [x] I can reproduce it on latest official image

**Comment by ibuziuk** [comment]
Closing as outdated
