### ISSUE TITLE
Implement compatibility with the new automatic multicast discovery in plugin broker

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1354]
Placeholder for https://github.com/eclipse/che/issues/13272

**Comment by ibuziuk** [comment]
Related to the **Future Improvement** comment in the merge meta.yaml / plugin.yaml change -https://github.com/eclipse/che/issues/12908#issuecomment-474312103

**Comment by tsmaeder** [comment]
It is important that we do not break self hosting as described in https://docs.google.com/document/d/1V292nYN655ekPPZvzdg7zbLpwVXW5uFjmffgoN2CmpM/edit#bookmark=id.kw179rb9gjl6 
If we _do_ break that approach, we need to come up with an alternative.

**Comment by davidfestal** [comment]
@benoitf any idea about whether it might break self-hosting ?

**Comment by benoitf** [comment]
@davidfestal why it should break self-hosting ?

**Comment by davidfestal** [comment]
@benoitf no idea, but my purpose was to let you confirm to @tsmaeder that it doesn't break it :-)

**Comment by tsmaeder** [comment]
@benoitf https://docs.google.com/document/d/1V292nYN655ekPPZvzdg7zbLpwVXW5uFjmffgoN2CmpM/edit#heading=h.mu558mvq9pl4 suggests running the ide and plugin containers in a workspace: if we can't tell the ide container where the plugin host is, how do we separate the outer editor (the one we're using to develop) from the inner (the one being developed)?

**Comment by benoitf** [comment]
@davidfestal @tsmaeder 
it should not break self-hosting

in fact multiple containers is still compliant with discovery (as we share the network). Moreover, there are custom ENV variables allowing to specify the discovery host/port if you need to opt-out
Also, we can still use previous ENV variables to declare remote endpoint for any plugin.

**Comment by tsmaeder** [comment]
@benoitf can we please try this work flow and document it in the referenced document _before_ we turn on discovery as the default mechanism? IMO, we need to continuously improve developer experience and we should make sure at the very least that we don't break documented work flows.

**Comment by ibuziuk** [comment]
@davidfestal, as I understand once the docs are updated we can close this issue, right?

**Comment by ibuziuk** [comment]
Moving to Done. since it is merged to plugin-broker-master. Should be closed once plugin broker `v0.17.2` and rh-che is updated to Che 7 CR1 version
