### ISSUE TITLE
Cannot create workspace with my account apupier@redhat.com

### ISSUE THREAD

**Issue by apupier** [redhat-developer/rh-che#1359]
**Issue problem:** 

when using my apupier@redhat.com account, I can access dashboard but when I try to create a workspace. it stays blocked on the "loading" page:
![image](https://user-images.githubusercontent.com/1105127/56032091-83ea8700-5d21-11e9-8763-b69c10f17d07.png)

I tried in incognito browser mode

in console log, there are errors:

/api/permissions/system:1 Failed to load resource: the server responded with a status of 404 ()

/api/organization/find?name=apupier@redhat.com:1 Failed to load resource: the server responded with a status of 404 ()
/api/oauth/:1 Failed to load resource: the server responded with a status of 403 () 

api.github.com/user:1 Failed to load resource: the server responded with a status of 401 (Unauthorized) 

**Red Hat Che version:** 

accessing che.openshift.io

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by apupier** [comment]
I tried using my aurelien.pupier@gmail credentials and I have the same result

**Comment by ibuziuk** [comment]
@apupier are you still facing the same issue on `7.1.0` ? which browser are you using?

**Comment by apupier** [comment]
it is working fine with current instance of che.openshift.io
thanks
