### ISSUE TITLE
Cannot access che.openshift.io - There was an error processing request for access

### ISSUE THREAD

**Issue by apupier** [redhat-developer/rh-che#1360]
**Issue problem:** 

> There was an error processing request for access. Please try again by visiting: <a href='https://manage.openshift.com/openshiftio'>https://manage.openshift.com/openshiftio</a>. Contact us if you continue to see the issue.

if I try to use my account "apupier", i cannot access che.openshift.io
firtst I'm redirected to login page.
then I have some captcha:
![image](https://user-images.githubusercontent.com/1105127/56032378-57833a80-5d22-11e9-94c2-b9980d37339a.png)
then I have to an "activate account" button:
![image](https://user-images.githubusercontent.com/1105127/56032395-6669ed00-5d22-11e9-93c7-b0ba1edf8510.png)
I'm redirected to login page again.
Then I arrive on this page:
![image](https://user-images.githubusercontent.com/1105127/56032459-8c8f8d00-5d22-11e9-9e0d-38bba5d72a51.png)

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
@davidfestal maybe you have some ideas?

**Comment by ibuziuk** [comment]
@alexeykazakov any ideas about https://user-images.githubusercontent.com/1105127/56032459-8c8f8d00-5d22-11e9-9e0d-38bba5d72a51.png ?

**Comment by alexeykazakov** [comment]
I see two users with the same email. It can cause issues. Please login using your username, not email. Otherwise developers.redhat.com/openshift.io got confused what user to use.

**Comment by apupier** [comment]
I logged using my username for this issue.

I have this other issue when I login with email https://github.com/redhat-developer/rh-che/issues/1359

**Comment by alexeykazakov** [comment]
Do you see any error if you go to https://manage.openshift.com and login?

**Comment by apupier** [comment]
with "apupier" account, I arrive on this page without error:
![image](https://user-images.githubusercontent.com/1105127/56110567-4b32f380-5f55-11e9-8639-6b0d2a0c0978.png)
if I click on "Open web console"
I arrive on this page:
![image](https://user-images.githubusercontent.com/1105127/56110593-5d149680-5f55-11e9-8d31-4aea5fa04deb.png)
if i click on signup, I arrive to the same error page:
![image](https://user-images.githubusercontent.com/1105127/56110622-76b5de00-5f55-11e9-8956-e9f5023aa907.png)

**Comment by apupier** [comment]
as you mentioned that 2 users with same email address can cause trouble. I modified one of the account to use another mail address. i still have the exact same behavior.

**Comment by alexeykazakov** [comment]
You are trying to sing up but you have already signed up. Does it work if you just go to che.openshift.io and login?

**Comment by apupier** [comment]
if i click on login, I get back to login page, then when I enter credentials again, I'm redirected to the exact same Code ready Toolchain page

**Comment by ibuziuk** [comment]
@alexeykazakov redirect is also broken for me on prod-preview 

![image](https://user-images.githubusercontent.com/1461122/56572500-79e94380-65bf-11e9-88e7-19bcfeee9cd9.png)

This is what I get after pressing sign-up button^ 
NOTE: I can access https://che.prod-preview.openshift.io and web-console of oso cluster without any issues by accessing the direct link. This looks like redirect issue for me not related to Che

**Comment by alexeykazakov** [comment]
Sign-up flow in prod-preview is not that straight forward as it in prod. This is why you got confused:

1. manage.openshift.com shows that error only if you are trying to sign up instead of login for the existing account. The message here is misleading.
2. "Open Web Console" opens openshift.io (PROD!), not prod-preview.openshift.io. This is why you are not logged-in there.

So, do not use sign-up button in prod-preview at all (it's not supposed to work in prod-preview).

**Comment by ibuziuk** [comment]
hmm.. ok so you redirect from `prod-preview.openshift.io` to `che.prod-preview.openshift.io` is not supposed to work and this is known issue that will not be fixed, right?

**Comment by alexeykazakov** [comment]
Redirects from prod-preview.openshift.io to che.prod-preview.openshift.io should work. But I don't see here any redirection issues.
@ibuziuk can you please describe your steps?

**Comment by ibuziuk** [comment]
@alexeykazakov The problems I see on prod-preview:
- when one press "SIGN UP" button on prod-preview.openshift.io  regular RH login page is shown
![image](https://user-images.githubusercontent.com/1461122/56662943-513b7980-66a5-11e9-9cbd-0765e70719f1.png)
- once a user is registered the following page is shown
![image](https://user-images.githubusercontent.com/1461122/56663198-ceff8500-66a5-11e9-8fb8-aae1dcb661a0.png)
- pressing `Open Web Console" redirects on https://openshift.io/ (NOT on prod-preview.openshift.io) 
- opening `https://prod-preview.openshift.io/` manually does not redirect to prod-preview.openshift.io (even after manual SiGN UP)

But as I understand this is expected from auth team since you commented above:

> do not use sign-up button in prod-preview at all (it's not supposed to work in prod-preview).

**Comment by alexeykazakov** [comment]
Yes, this is what I'm talking about. Prod-preview uses different sign-up flow (see dev guide) for security reasons.
Use login instead of sign-up.

**Comment by ibuziuk** [comment]
ok, but anyway @apupier has a similar issue on prod

**Comment by alexeykazakov** [comment]
The only problem I see in prod is that misleading error message in manage.openshift.com when you are trying to sign up but using credentials for the existing account (you should have logged in instead).
Do you see anything else?

**Comment by ibuziuk** [comment]
ok, so how should we escalate / tackle this issue - this sign up flow is super misleading [1] and redirect does not seem to happen.
@apupier are we correct that this is  the only issue you are facing?

[1] https://github.com/redhat-developer/rh-che/issues/1360#issuecomment-483119417

**Comment by alexeykazakov** [comment]
What redirect does not happen? I'm still confused. You are trying to sign up for the existing OSIO account. The only problem I see is the confusing error message saying "There was an error processing your request" vs. something like "Such account already registered/exists please use login instead" or something like this.

manage.openshift.com is external service managed by OpenShift Online (team) and integrate it better is pretty tricky. The UX is bad but it's what we have for the last 2+ years and we are not planning to improve it in the current OSIO (something to take care of for SaaS.next).

**Comment by ibuziuk** [comment]
@apupier what about this one? still fails to login ?

**Comment by apupier** [comment]
working too now
