### ISSUE TITLE
Connection reset during plugin brokering process for che 7 workspace startup

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1378]
> Starting Init Plugin Broker
> Cleaning /plugins dir
> Unified Che Plugin Broker
> List of plugins and editors to install
> - che-machine-exec-plugin:0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
> - redhat.vscode-yaml:0.3.0 - Provides comprehensive YAML Language support to Visual Studio Code, via the yaml-language-server, with built-in Kubernetes and Kedge syntax support.
> - redhat.vscode-xml:0.3.0 - This VS Code extension provides support for creating and editing XML documents, based on the LSP4XML language server, running with Java.
> - org.eclipse.che.vscode-sonarlint:0.0.1 - VS Code extension that provides sonarlint features
> - ms-vscode.typescript:1.30.2 - Typescript language features
> - ms-python.python:2019.2.5433 - Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
> - redhat.vscode-openshift-connector:0.0.17 - Interacting with Red Hat OpenShift clusters and providing a streamlined developer experience using Eclipse Che
> - ms-kubernetes-tools.vscode-kubernetes-tools:0.1.17 - Develop, deploy and debug Kubernetes applications
> - org.eclipse.che.editor.theia:1.0.0 - Eclipse Theia
> Starting Che common plugins processing
> Starting Theia plugins processing
> Starting VS Code plugins processing
> Downloading VS Code extension for plugin 'redhat.vscode-yaml:0.3.0'
> Downloading VS Code extension for plugin 'redhat.vscode-xml:0.3.0'
> Downloading VS Code extension for plugin 'org.eclipse.che.vscode-sonarlint:0.0.1'
> Downloading VS Code extension for plugin 'ms-vscode.typescript:1.30.2'
> Downloading VS Code extension for plugin 'ms-python.python:2019.2.5433'
> Downloading VS Code extension for plugin 'redhat.vscode-openshift-connector:0.0.17'
> Get https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/vscode-openshift-connector/0.0.17/vspackage: read tcp 10.131.44.210:56980->13.107.6.175:443: read: connection reset by peer
> Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceelguwylwvi82sddc failed with error: Get https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/vscode-openshift-connector/0.0.17/vspackage: read tcp 10.131.44.210:56980->13.107.6.175:443: read: connection reset by peer

Plugins:

> "attributes": {
>     "editor": "org.eclipse.che.editor.theia:1.0.0",
>     "plugins": "che-machine-exec-plugin:0.0.1,redhat.vscode-yaml:0.3.0,redhat.vscode-xml:0.3.0,org.eclipse.che.vscode-sonarlint:0.0.1,ms-vscode.typescript:1.30.2,ms-python.python:2019.2.5433,redhat.vscode-openshift-connector:0.0.17,ms-kubernetes-tools.vscode-kubernetes-tools:0.1.17"
>   }

![image](https://user-images.githubusercontent.com/1461122/56371543-98d18980-61fd-11e9-8365-5aa5ca2b0107.png)

**Comment by ibuziuk** [comment]
Haven't seen this for a while against 7.3.1.Closing

**Comment by Katka92** [comment]
Seen again during periodic tests on 1a: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1562/console
![image](https://user-images.githubusercontent.com/29278800/69035670-7d716b80-09e4-11ea-8448-6c97c4f57fa0.png)

**Comment by ScrewTSW** [comment]
Seen again on production-2 cluster at 3AM on Nov. 25th
![image](https://user-images.githubusercontent.com/16451875/69537364-3ead5980-0f80-11ea-8163-dd6b792a32b3.png)

**Comment by ibuziuk** [comment]
@amisevsk closing this one due to plugin broker refactoring + the fact that it hasn't been reproducible since the late November
