### ISSUE TITLE
Theia IDE **Next** editor fails to start with Che 7 workspace (works on minishift)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1379]
### Description

Theia IDE**Next** / **Master** editor fails to start with Che 7 workspace
Seems to work just fine on minishift against upstream (7.0.0-beta-4.0-SNAPSHOT)
Default and `master` Theia editor work fine

### Reproduction Steps
Create and start che 7 workspace with Theia IDE next editor 
![image](https://user-images.githubusercontent.com/1461122/56429338-d6e4b100-62c2-11e9-9a57-72799e2addf1.png)

ERROR workspace fails to start (loader image is shown forever, refresh does not help)
![image](https://user-images.githubusercontent.com/1461122/56429675-1069ec00-62c4-11e9-8eb2-4c4195da0f45.png)

**OS and version:**    
che.openshift.io
che 7 beta 3 (theia next seems to work just fine against minishift `7.0.0-beta-4.0-SNAPSHOT`)
Also Theia IDE **Master* works fine

**Diagnostics:**

**Comment by ibuziuk** [comment]
also one funny thing noted. Theia `Master` is also broken the same way on che.openshift.io, but it looks like it uses the very same image as `next` editor - `Image: eclipse/che-theia:next`

![image](https://user-images.githubusercontent.com/1461122/56430524-dea65480-62c6-11e9-909e-288148e41502.png)

![image](https://user-images.githubusercontent.com/1461122/56430608-18775b00-62c7-11e9-9138-69a55d06e01c.png)

**Comment by mmorhun** [comment]
@ibuziuk `master` is deprecated, `next` should be used instead. The fact that both use the same image is expected.

**Comment by mmorhun** [comment]
Just checked, it works from Firefox.

**Comment by garagatyi** [comment]
@mmorhun also checked upstream Che on minikube - works correctly on Chrome

**Comment by garagatyi** [comment]
Tried to play with it in PR https://github.com/redhat-developer/rh-che/pull/1380 but got next error error
```
Message: "Failure executing: POST at: https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/ogaragat-preview-che/configmaps. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps is forbidden: User "ogaragat-preview" cannot create configmaps in the namespace "ogaragat-preview-che": no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."
```
At the same time I'm able to login using the same account to prod-preview and start a workspace. But Theia with image `next` doesn't start neither there.

**Comment by ibuziuk** [comment]
@mmorhun if `master` deprecated maybe it makes sense to hide this editor picking from UD completely ?
@garagatyi yeah, as I wrote in the description theia next seems to work just fine in the upstream

**Comment by garagatyi** [comment]
@ibuziuk I wasn't sure if you were talking about upstream or RhChe

**Comment by ibuziuk** [comment]
yeah. sorry for the confusion - just updated the description

**Comment by AndrienkoAleksandr** [comment]
I see DOM Exception in the browser console, maybe it's a reason of the issue:

<details><summary>Stack trace</summary>
<p>

```javascript
theia.b98e6bbaa771fa5efc00.js:1 Uncaught (in promise) DOMException
s @ theia.b98e6bbaa771fa5efc00.js:1
Promise.then (async)
c @ theia.b98e6bbaa771fa5efc00.js:1
(anonymous) @ theia.b98e6bbaa771fa5efc00.js:1
a @ theia.b98e6bbaa771fa5efc00.js:1
e.start @ theia.b98e6bbaa771fa5efc00.js:1
(anonymous) @ che.4e315c956aed0da82cb7.js:1
Promise.then (async)
nJ+H @ che.4e315c956aed0da82cb7.js:1
f @ runtime.e89741c86dc89dd2ddfd.js:1
t @ runtime.e89741c86dc89dd2ddfd.js:1
r @ runtime.e89741c86dc89dd2ddfd.js:1
(anonymous) @ theia.b98e6bbaa771fa5efc00.js:1
theia.b98e6bbaa771fa5efc00.js:1 root INFO Config file tasks.json does not exist under file:///projects
```
</p>
</details>

I am trying to build image to get normal stack trace.

**Comment by AndrienkoAleksandr** [comment]
@ibuziuk We got **breaking changes from theia**:  https://github.com/theia-ide/theia/pull/4724
Something wrong with theia start synchronization. On the local servers like minikube and minishift it's not reproducible...

Original error: `InvalidStateError: getLayoutMap() must be called from a top-level browsing context.`. We lost original exception, because theia code has some code section without try-catch error handling. 

I begin analyze how to fix it.

**Comment by AndrienkoAleksandr** [comment]
Upstream issue: https://github.com/theia-ide/theia/issues/5046
Variant of the fix to track: https://github.com/theia-ide/theia/pull/5047

**Comment by ibuziuk** [comment]
Mover to `Other Che Teams` pipeline since OSIO team is not working on this issue

**Comment by ibuziuk** [comment]
verified on che.openshift.io:

![image](https://user-images.githubusercontent.com/1461122/57628831-f5c12500-759a-11e9-9da1-0d8e4aca94e5.png)

Closing. Thanks @AndrienkoAleksandr !
