### ISSUE TITLE
Unable edit container definition in the che 7 workspace

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [redhat-developer/rh-che#1381]
Placeholder for openshiftio/openshift.io#

![unableEditMachineInTheDashboard (2)](https://user-images.githubusercontent.com/6873095/56503250-96cd3a80-651d-11e9-800e-075a671b6a74.gif)

**Comment by AndrienkoAleksandr** [comment]
@amisevsk could you take a look?

**Comment by amisevsk** [comment]
Is this a regression? I don't recall making any changes around this recently.

**Comment by AndrienkoAleksandr** [comment]
Yes, it's regression.

**Comment by amisevsk** [comment]
This issue reproduces in upstream 7.0.0-beta-3.0 as well.

**Comment by amisevsk** [comment]
Created issue https://github.com/eclipse/che/issues/13218 to track

**Comment by amisevsk** [comment]
I took a brief look at fixing this issue but couldn't figure it out so I'm leaving it for normal prioritization (unless it's a blocker @AndrienkoAleksandr )

Editing the workspace config works without any problems, but making any modifications to the machine recipe results in the recipe being thrown away with some errors logged (see upstream issue).

**Comment by AndrienkoAleksandr** [comment]
I't's not a blocker issue.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/13218
