### ISSUE TITLE
Fix workspace keycloak authentication

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#139]
see - https://issues.jboss.org/browse/CHE-291

**Comment by davidfestal** [comment]
Fixed in PR https://github.com/redhat-developer/rh-che/issues/173

**Comment by amisevsk** [comment]
Closing issue as fixed, since https://github.com/redhat-developer/rh-che/pull/117 was merged into master. Feel free to reopen, but I think the remaining issues are better served by separate issues.

**Comment by amisevsk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix workspace keycloak authentication](https://trello.com/c/PjqGPNSr/4-fix-workspace-keycloak-authentication)
