### ISSUE TITLE
Remove pod getting stuck in status Terminating

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1392]
**Issue problem:** 
After many (thousands) workspace creations, starts and deletions an account tends to get a remove pod that's stuck in state Terminating with no container running in the pod

namespace: `<username>-che`
usernames:
* `osiotest-workspace-2` (production account)
* `osiotest-workspace-2a` (production account)

![Screenshot_20190429_121658](https://user-images.githubusercontent.com/16451875/56894210-6d645f80-6a85-11e9-99e5-99baebb9a597.png)
![Screenshot_20190429_121424](https://user-images.githubusercontent.com/16451875/56894222-75240400-6a85-11e9-858c-72be336fd54b.png)
![Screenshot_20190429_121434](https://user-images.githubusercontent.com/16451875/56894224-76edc780-6a85-11e9-8f73-32be75b3012f.png)

The workspace gets correctly deleted and the container that does the job is terminated, the quotas are released, but the pod itself remains stuck in `Terminating` status.
The pod does not seem to consume any quotas, I did not have issues starting both che6 and che7 workspaces, both with volume claims and ephemeral workspaces.

**Red Hat Che version:** 

Version: 1.0.0-SNAPSHOT
Build Time: 2019-04-18 09:53:18
Revision: e0b8bed1f3c420ba

**Reproduction Steps:**

Intermittent issue with random behavior

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
some investigation details - the rm pod is a single container one and the container has `Terminated` status with exit code 0:

 

>    Container ID:  
>     Image:         centos:centos7
>     Image ID:      
>     Port:          <none>
>     Host Port:     <none>
>     Command:
>       rm
>       -rf
>       /tmp/job_mount/
>     State:          Terminated
>       Exit Code:    0
>       Started:      Mon, 01 Jan 0001 00:00:00 +0000
>       Finished:     Mon, 01 Jan 0001 00:00:00 +0000
>     Ready:          False
>     Restart Count:  0
>     Limits:
>       cpu:     488m
>       memory:  250Mi
>     Requests:
>       cpu:        29m
>       memory:     125Mi
>     Environment:  <none>
>     Mounts:
>       /tmp/job_mount from claim-che-workspace (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-gxmvl (ro)

The first thing that is really suspicious is the:

> Started:      Mon, 01 Jan 0001 00:00:00 +0000
>       Finished:     Mon, 01 Jan 0001 00:00:00 +0000

It is not at all clear why the Pod as marked as `Terminating` even though the Container itself `Terminated` with 0 exit code. @pbergene @jfchevrette ideas?

**Comment by ScrewTSW** [comment]
HK issue: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2609

**Comment by Katka92** [comment]
Our testing account ``` osio-ci-e2e-004 ``` has two pods stuck in the same state. They were created today at ~0:45 am. 

![Screenshot from 2019-05-02 07-47-03](https://user-images.githubusercontent.com/29278800/57059097-f52fb100-6cb3-11e9-93d9-3eab99b4b8e9.png)

**Comment by ScrewTSW** [comment]
And the list extends. Another account of ours has stuck workspace pods that are not visible as a workspace in the che dashboard.
![image](https://user-images.githubusercontent.com/16451875/58003331-d49f8d80-7ae0-11e9-84b5-ed310157653f.png)

**Comment by ibuziuk** [comment]
Closing as outdated
