### ISSUE TITLE
Add Quarkus Stack

### ISSUE THREAD

**Issue by vorburger** [redhat-developer/rh-che#1393]
So https://github.com/redhat-developer/che-dockerfiles/pull/54, based on https://github.com/eclipse/che-dockerfiles/pull/240 (and https://github.com/CentOS/container-index/pull/395), was a first step to add a Quarkus Stack to https://che.openshift.io.

What's missing is to add it to https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json.

To be able to do that, we'd need a (regular) build to deploy a container image for https://github.com/redhat-developer/che-dockerfiles/pull/54/files to https://quay.io/repository/openshiftio/che-centos_quarkus.io_jdk8.

Who needs to do what for this? I'm happy to try to help, if you like to add me (vorburger) as admin to https://quay.io/repository/openshiftio.

**Comment by ibuziuk** [comment]
@vorburger looks like the build is fix now \o/ https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/
and Quarkus image is built periodically and pushed to the quay registry - https://quay.io/repository/openshiftio/che-centos_quarkus.io_jdk8

@vorburger I believe now you can provide the brand-new stack to the stacks.json

**Comment by ibuziuk** [comment]
Closing, feel free to contribute Quarkus devfile ;-) cc: @sunix 
https://github.com/eclipse/che-devfile-registry

**Comment by sunix** [comment]
@ibuziuk is it a requirement that devfile in the registry works on che.openshift.io?  (Because 3Go is definitely not enough)
