### ISSUE TITLE
Need to create the `latest` folder for each plugin in the plugin registry that would allow to specify plugins with the `latest` version

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1395]
Need to create the `latest` folder for each plugin in the plugin registry that would allow to specify plugins via the following format:

- `che-machine-exec-plugin:latest`

**Comment by ibuziuk** [comment]
we should work on this only once https://github.com/eclipse/che-plugin-registry/pull/135 is merged. This means `latest` folder would become obligatory only for `v3` version of plugins

**Comment by amisevsk** [comment]
@ibuziuk Would this be a manually managed thing or automated in some way? Do committers manually have to set the meta in the latest folder?

**Comment by ibuziuk** [comment]
@amisevsk yeah, the current plan is to manually manage the folder. My understanding that for Che 7 GA it is ok, but we might reconsider the whole plugin registry approach beyond GA since it looks like it does not scale well (each vsix should be manually added to the registry and supported there )

**Comment by ibuziuk** [comment]
Closing as done
