### ISSUE TITLE
If the plugin version is not specified - fall back on `latest` 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1396]
This issue is to allow a definition of a workspace plugin without a specific version:

- `id: che-machine-exec-plugin` - in this case, the `latest` version of the plugin should be used.

the case should be tackled on wsmaster / plugin broker side (when version is missing always fall back on the latest).

Another thing we need to take care of are the versions of the `exec` and `theia` that are automatically added by wsmaster (when a user do not specify them in a Devfile).

**Comment by ibuziuk** [comment]
On ws-master side:
 - changes required in Devfile config to not specify the version of plugin at all - https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json#L175
 - modify parsing of the plugin version in FQNParser - https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/PluginFQNParser.java#L68 

- Default editor provisonser / Default Plugin Provisioner

And there should be a change on the plugin-broker side -

**Comment by nickboldt** [comment]
another use case is if the plugin version IS specified but doesn't exist. see https://github.com/eclipse/che-plugin-registry/pull/319 for a workaround (hardcoding all the old versions of 7.y.z plugins in the master branch).

So if you were running 7.3.3 and updated to 7.6/master you'd break because the new plugin reg would be missing 7.3.3 theia and machine-exec plugins.

**Comment by ibuziuk** [comment]
Closed in favour of https://github.com/eclipse/che/issues/15447

> another use case is if the plugin version IS specified but doesn't exist. see eclipse/che-plugin-registry#319 for a workaround (hardcoding all the old versions of 7.y.z plugins in the master branch).
> 
> So if you were running 7.3.3 and updated to 7.6/master you'd break because the new plugin reg would be missing 7.3.3 theia and machine-exec plugins.

@nickboldt please, create a separate upstream issue for that
