### ISSUE TITLE
Adapt upstream dashboard changes

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1408]
## Description

PR https://github.com/eclipse/che/pull/13198 upstream adds devfile support to the user dashboard. Once merged we'll need to check if downstream updates are needed and, if so, make them.

**Comment by ibuziuk** [comment]
Closing as outdated, currently, we have https://github.com/redhat-developer/rh-che/blob/master/dev-scripts/check-upstream-dashboard.sh for checking UD compatibility
