### ISSUE TITLE
Fix Che Server to WIT Relationship

### ISSUE THREAD

**Issue by sbryzak** [redhat-developer/rh-che#1409]
Creating this issue in order to track the Che-related work required to address upstream issue (requires access): https://jira.coreos.com/browse/ODC-228.

Related auth service PR: https://github.com/fabric8-services/fabric8-auth/pull/838

### Description
WIT Service is currently used by Che Server (/api/user/services). See https://github.com/redhat-developer/rh-che#interaction-of-red-hat-che-with-other-openshiftio-services. WIT will be removed in ODC-123, so we need to remove the dependency from Che.

### Acceptance Criteria
The endpoint and functionality of /api/user/services is moved from WIT to Auth Service (can’t use Tenant Service because it’s not exposed).
Remove all calls from Auth to WIT.
Ensure that Che is not calling WIT directly anymore.
**Note**: This needs also work from the Che team. Part of this story is make sure this is happening.

**Comment by ibuziuk** [comment]
@l0rd looks we would need to take in the next sprint. Adding the item to prio - should be ~ 3 sp

**Comment by sbryzak** [comment]
@ibuziuk prod-preview has now been updated with the new auth endpoints.  The Che team may now commence the migration of the WIT endpoints to auth, and test against [https://auth.prod-preview.openshift.io](https://auth.prod-preview.openshift.io)

**Comment by ibuziuk** [comment]
@sbryzak we need to first update to the latest upstream versions, once done I will start looking into this.

**Comment by ibuziuk** [comment]
@sbryzak could you clarify which endpoints should we use now instead of https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.config.yaml#L22 ?

**Comment by alexeykazakov** [comment]
@ibuziuk it's `https://auth.prod-preview.openshift.io/api/user/services` for prod-preview and `https://auth.openshift.io/api/user/services` for prod. So, it's the same endpoint/path but different domain/service. auth instead of api (wit)

**Comment by ibuziuk** [comment]
@alexeykazakov @sbryzak looks like new endpoint does not work as expected

**Comment by sbryzak** [comment]
@ibuziuk I've deployed an updated release of auth to prod-preview which should hopefully fix the error now.  Could you please retry the endpoint again and let me know how it goes?

**Comment by ibuziuk** [comment]
PR updated and ready for review - https://github.com/redhat-developer/rh-che/pull/1443

**Comment by sbryzak** [comment]
@ibuziuk I noticed the PR has been merged, is it ok if I close this issue now?

**Comment by ibuziuk** [comment]
no, we have not yet promoted it t prod - should be done this week

**Comment by ibuziuk** [comment]
The fix is promoted to prod. Closing.
@alexeykazakov @sbryzak we can now terminate the wit on prod-preview and observe the `che.prod-preview.openshift.io` behavior.
