### ISSUE TITLE
Inject user KC token in bayesian LS

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/rh-che#141]
details: https://issues.jboss.org/browse/CHE-281

> Currently an hardcoded KC token is set as a env variable (RECOMMENDER_TOKEN) inside workspaces containers. This KC token is [consumed by the bayesian LS|https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/blob/master/src/server.ts#L177) for authentication with the remote recommandation service.
> The current user KC token should be used instead. There are 2 different approach here:
> 1) Add KC token as a LS configuration and use LSP DidChangeConfiguration notification to push token updates (when it's renewed) to bayesian LS
> 2) Before every remote call Bayesian should get the KC token using wsagent REST API

**Comment by kbsingh** [comment]
Hi Guys,

this is a production blocker for the analytics team - if we can do something to prioritise and expediate this, would be appreciated.

**Comment by kbsingh** [comment]
cc @krishnapaparaju

**Comment by sunix** [comment]
will probably implement that client side: getting the token like:
https://github.com/redhat-developer/rh-che/blob/2a2ff37132295f1219c0b38c41b844f480b85e49/builds/fabric8-che/plugins/keycloak-plugin-ide/src/main/java/com/redhat/che/keycloak/ide/KeycloakAsyncRequestFactory.java#L71
and use LSP DidChangeConfiguration to send the token to the language server

**Comment by sunix** [comment]
Requires https://github.com/fabric8-analytics/fabric8-analytics-server/pull/99 to have user keycloak token "generated" by Che authorized in the  bayesian recommandation api.
