### ISSUE TITLE
Slow workspace start

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1413]
**Issue problem:** 
Workspace startup time last too long. Periodic tests are failing on timeout for workspace startupt, which is currently set to 10 minutes. 
Logs from Kibana for workspace ``` workspaceo7jttxuwdggqa2ei ```:
```
00:10:28.594 Workspace created by user 'osiotest1a'
00:10:29.065 Starting workspace by user 'osiotest1a'
(workspace is not started in 10 minutes, try to stop and remove it)
00:20:34.699 Workspace is stopping by user 'osiotest1a'
00:22:11.050 Workspace started by user 'osiotest1a'
00:22:11.079 No workspace start time recorded for workspace workspaceo7jttxuwdggqa2ei
00:27:16.806 Workspace is stopped by user 'osiotest1a'
(then four of this:)
00:27:17.007 Could not get runtimeIdentity for workspace 'workspaceo7jttxuwdggqa2ei', and so cannot verify if current subject '593d4c52-dfe0-47cd-9238-6a44b06e4d34' owns workspace
00:27:17.529 Workspace 'workspaceo7jttxuwdggqa2ei' removed by user 'osiotest1a'
(then two of this:)
00:27:21.565 Could not get runtimeIdentity for workspace 'workspaceo7jttxuwdggqa2ei', and so cannot verify if current subject '593d4c52-dfe0-47cd-9238-6a44b06e4d34' owns workspace
```
From the log, we can see that after 10 minutes the request for stopping worspace is sent (caused by timeout in periodic tests). Time taken to start the pod was ~12 minutes. The longest time I found was ~ 14 minutes for workspace ``` workspaceq4jnery4fyew6b5q  ```. 
From what I can see in periodic tests, some are started in 28 seconds.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by Katka92** [comment]
Seen again on cluster 2 (started in ~13 minutes), 2a (~4,2 minutes), 1a (~7,3 minutes), 1b (~14 minutes).
Prod-preview cluster 2a is not affected, all workspaces are started in 40 seconds.

**Comment by Katka92** [comment]
Seen again
cluster 2:
```
workspacekmylefcz76ucr4no   25 minutes
workspacer8iyx5c49mdggqf9   15 minutes
workspacedn7on9573lg8wj77   19 minutes (Che 7)
workspacejvanphjot7clj6rr   20 minutes
```
cluser 2a:
```
workspacet3jxfae5z19dvrbg   32 minutes
workspaceoy15wcrl4hbrsi63   9.5 minutes
workspace4xu8p0lnxzxcbu3c   12 minutes
```
cluster 1a:
```
workspaceypn3cmom6ha1noz1   6 minutes (Che 7)
workspacehnya4u5syumfc29k   20 minutes
```
cluster 1b:
```
workspace8jejjzt21hwvyklv   32 minutes
workspaceu5e90tksxvw5qk23   8  minutes (Che 7)
workspacellknpgh54332szn1   14 minutes (Che 7)
workspacehkkarwnbi9gkt3h9   12 minutes
```

**Comment by Katka92** [comment]
Cluster 2
``` 
workspace8ig6evw4kb26eqgl   34 minutes
workspacejrdy7yvnz4jaszbo   25 minutes
workspaceg18wjnecsepaqp0t    16 minutes
```
Cluster 2a
```
workspacedi1bp5cnoqqkd8f6   26 minutes
workspaced4vjdnkf2bt0gfb4   19 minutes
workspacevf24bdxdh5a0e29n   30 minutes
```
Cluster 1a
```
workspace8dm7hy97cohp9itj  24 minutes
workspaceewmw0c82fn9zy0bz   22 minutes
workspace8d3dlr18z7qgjsl1   30 minutes
```
Cluster 1b
```
workspacespr52qwl26by5em8   33 minutes
workspaceaeen4vt5hfifggmc   12 minutes
workspacejg2zkg4htps1kx04  29 minutes
```

:exclamation: Workspace failed to start on prod-preview today, but Kibana is not working and rh-che is receiving a lot of logs so I can not provide you any useful information. 
Affected jobs from prod-preview:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/689/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/688/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/687/console

**Comment by Katka92** [comment]
Cluster 2 
```
workspace45hfsgrqo99bboot   21 minutes
workspacevxxkyhro5y0rk2za   25 minutes
```
Cluster 2a
```
workspacepzoxz8ym0s4q89uu   16 minutes
workspaceajtjr9099nx7rrpy   23 minutes
```
Cluster 1b
```
workspacefe63d2nzkhxvnjod   12 minutes 
workspace5bvya31udyn4wate   22 minutes
```

**Comment by ibuziuk** [comment]
all pods have been restarted on prod and the error rate dropped sufficiently. So far I can not reproduce the issue.

**Comment by Katka92** [comment]
Seen again.
Cluster 2 ``` workspacew2kx1ock6r6qc2va   22 minutes ```
Cluster 2a ``` workspaceek6ap8q6nbqj1p2g   25 minutes ```
Cluster 1a ``` workspaceoxdjswnf2uivp0hb   23 minutes ```
Cluster 1b ``` workspacel0uujupegwyla39c 15 minutes ```

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW I believe this issue is not reproducible anymore according to the metrics and test results

**Comment by Katka92** [comment]
Agreed. Closing.
