### ISSUE TITLE
Allow cookies from static.developers.redhat.com

### ISSUE THREAD

**Issue by themr0c** [redhat-developer/rh-che#1429]
Allow cookies from static.developers.redhat.com

To authenticate in https://che.openshift.io, you need to allow cookies from `static.developers.redhat.com`.

In case these cookies are blocked (by a browser extension like Privacy Badger), you will get following error:

```
Authorization token is missed
Click here to reload page.
```

**Comment by ibuziuk** [comment]
> Authorization token is missed
> Click here to reload page.

We probably need to add info about extentions like Privacy Badger [1] to the Troubleshooting section https://github.com/redhat-developer/rh-che/blob/master/FAQ.adoc#troubleshooting

[1] https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp
