### ISSUE TITLE
Simplify rhche developer onboarding and daily workflow (after openshift-connector is merged to master)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#143]
see https://issues.jboss.org/browse/CHE-288

> One thing we should do is not build upstream Che anymore but retrieving the artifact from nexus.
> Another thing is we need to review the build requirements [(cf. this PR)](https://github.com/redhat-developer/rh-che/pull/87#discussion_r120307203) and think if we really need them all or if we can give up some to make the build simpler simpler
> Before starting this task the asigned developer should setup a blue jeans call to discuss how this should be simplified.

released versions of che should be used instead of snapshot versions

- [ ] Remove upstream build and align to Che upstream release #249

**Comment by benoitf** [comment]
I would comment on this issue as I'm also use of the scripts/build process.

on the scripts:
- First, as a newcomer, I think it's very hard to have scripts at the root directory which are not the one I've to used in the README
So I would prefer to have the "script to run" in the root directory and the "functions/tools/macros" used by the scripts to be inside an internal folder
- Next, there are tons of scripts with name that are closed but then it's very hard to know the differences between all the scripts.
I would have only one script (or two) with flags to do what I need.
like : 
```
$ che-minishift.sh build
$ che-minishift.sh deploy
$ che-minishift.sh clean
$ che-minishift.sh update
```
Here I'm quite lost to know which scripts I could test


next, on maven process.
There are some enforcing rules that is preventing me to be efficient.

For example, it's not possible to build a dedicated maven module.
I had to fix https://github.com/redhat-developer/rh-che/tree/openshift-connector-rebased/builds/fabric8-che/assembly/assembly-wsmaster-war pom.xml

but launching `$ mvn clean install`was not possible (told to launch at root folder)
I ended up by using `mvn  -DbaseCheRepository=/Users/benoitf/Documents/git/codenvy/che -Denforcer.skip clean install` but I would expect to be able to do simple maven commands everywhere

Also, setting env variables (like the _PATH is not usual when you're using pure maven)
Could we grab all content through maven dependencies ? If some of them are missing, we could do some enhancements in eclipse che upstream repository (or fabric8) (for example by default you wouldn't need any PATH to set to start)

I've other issues but these items are my main concerns on working daily with Che/Minishift

**Comment by davidfestal** [comment]
> So I would prefer to have the "script to run" in the root directory and the "functions/tools/macros" used by the scripts to be inside an internal folder

If it's OK for everyone, I've no problem with moving the CI-dedicated scripts to a `ci-build-scripts` sub-folder, and bring the `dev-scripts` at the root.

> I would have only one script (or two) with flags to do what I need

That's an interesting idea, but some scripts already take arguments (mainly the arguments that can be passed to the underlying maven build). However, we could manage this a bit like many other tools (git, ...): `main_script <sub-command> <parameters>`.

> For example, it's not possible to build a dedicated maven module

Even if running from the root maven is required, it's possible to build a given maven module by using the `-Dpl='assembly/assembly-wsmaster-war' -Damd` arguments. As described [here](https://github.com/redhat-developer/rh-che#build-scripts-parameters) and more precisely (here)[https://github.com/redhat-developer/rh-che#build-only-some-modules-of-the-redhat-che-distribution]

> Also, setting env variables (like the _PATH is not usual when you're using pure maven)
> Could we grab all content through maven dependencies ? If some of them are missing, we could do some enhancements in eclipse che upstream repository (or fabric8) (for example by default you wouldn't need any PATH to set to start)
 
Not sure I see what you're speaking of ...

> IMHO the use of the maven invoker is producing also some overhead so I think it would lot simpler without using that invoker.

We plan to review / discuss the initial constraints that led to using the invoker as soon as the `openshift-connector-branch` is merged to master.

**Comment by benoitf** [comment]
>> I would have only one script (or two) with flags to do what I need

> That's an interesting idea, but some scripts already take arguments (mainly the arguments that can be passed to the underlying maven build). However, we could manage this a bit like many other tools (git, ...): main_script <sub-command> <parameters>.

yes that was the idea. One tool, several commands and you can get help for each command to know the required/optional parameters

>> For example, it's not possible to build a dedicated maven module
> Even if running from the root maven is required, it's possible to build a given maven module by using the -Dpl='assembly/assembly-wsmaster-war' -Damd arguments. As described here and more precisely here

My goal is that it's overcomplicated. In any standard maven project, when you want to build a module, you can go to the module folder directly and just run the command from there. No need to give extra arguments or forced to launch from a specific top level folder
AFAIK I call using the exclusion of module and using it from the root folder a workaround.

>> Also, setting env variables (like the _PATH is not usual when you're using pure maven)
Could we grab all content through maven dependencies ? If some of them are missing, we could do some enhancements in eclipse che upstream repository (or fabric8) (for example by default you wouldn't need any PATH to set to start)

> Not sure I see what you're speaking of ...

I'm speaking of setting 
```
export UPSTREAM_CHE_PATH="/Users/mariolet/Github/che"
export FABRIC8_ONLINE_PATH="<path where you cloned it>/fabric8-online/"
```
on a maven project. I expect that I have no env variables to set. All should be retrieved from maven repositories.


>> IMHO the use of the maven invoker is producing also some overhead so I think it would lot simpler without using that invoker.

> We plan to review / discuss the initial constraints that led to using the invoker as soon as the openshift-connector-branch is merged to master.

Great !
After using it since one month, I got failures sometimes and launching it again I got success.
I got sometimes "BUILD success" on the screen but "BUILD failed" in maven top level project as well

**Comment by l0rd** [comment]
Thanks @benoitf for these details. Whoever is going to work on the improvement of these scripts should considers all your comments. And I agree with @davidfestal that we will be able to simplify it a lot as soon as `openshift-connector` branch has been merged.

**Comment by sunix** [comment]
> Even if running from the root maven is required, it's possible to build a given maven module by using the -Dpl='assembly/assembly-wsmaster-war' -Damd arguments. As described here and more precisely here

agree with @benoitf , having so many layers (sh script + maven + maven) is adding more complexity, more bugs and more constraints. For example, how can I build 2 modules that I've modified and also build the dependent modules ?
``` -Damd  -Dpl="plugins/che-plugin-bayesian-lang-serverm,assembly/assembly-wsmaster-war" ``` doesn't work as for some reason it concider `plugins/che-plugin-bayesian-lang-serverm assembly/assembly-wsmaster-war` as one module name. And this is just one example

**Comment by ibuziuk** [comment]
still need to figure out how simplification is going to be implemented

**Comment by ibuziuk** [comment]
blocked by existence of `openshift-connector-wip`

**Comment by sunix** [comment]
first step: https://github.com/redhat-developer/rh-che/issues/249
