### ISSUE TITLE
Need to make sure that all devfiles from registry work on che.prod-preview.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1434]
Cc: https://github.com/redhat-developer/che-functional-tests/issues/543 (migrating this issue to rh-che)

Dev-file registry - https://che-devfile-registry.openshift.io/devfiles/

### Stack images Acceptance Criteria

These are the things that we should verify to validate a particular stack

 - workspace containers can be started
 - terminal shell for the runtime container(s) is bash (git PS1 is nice to have)
 - HOME is set
 - No "User has no name" problem
 - devfile commands can be executed successfully

### Stack Language Servers Acceptance Criteria

- code completion works successfully
- code navigation works successfully
- debugging works successfully

### Known issues

 https://gist.github.com/amisevsk/86ec3540da1b9b5ccd98aa23d4e9fafb

**Comment by ibuziuk** [comment]
Also, I noticed that devfiles from prod-preview registry are not compatible with CR1, which is currently deployed on production:

> Error occurred during creation a workspace from devfile located at `https://che-devfile-registry.prod-preview.openshift.io/devfiles/dotnet/devfile.yaml`. Cause: Devfile schema validation failed. Error: (/apiVersion):The object must not have a property whose name is "apiVersion".(/metadata):The object must not have a property whose name is "metadata".The object must have a property whose name is "specVersion".The object must have a property whose name is "name".

**Comment by amisevsk** [comment]
I've done a runthrough [1] of current devfiles on our dev-cluster (so not a full check on che.openshift.io) but a number of issues have been resolved in a general sense. The arbitrary-users patch PR has been merged and nightly images are available (in all cases except for the angular stack, which is based off alpine). This *should* resolve most known issues with the stacks, but should be verified.

[1] https://gist.github.com/amisevsk/86ec3540da1b9b5ccd98aa23d4e9fafb

**Comment by ibuziuk** [comment]
thanks, @amisevsk for the detailed `Testing devfiles` document with issue description
Basically, as I understand from standup there are a few obstacles for testing devfiles on prod-preview:
- UI on prod-preview is not up-to-date (should be updated as part of Che 7 rc 4 release)
- I do not think we have enough time to automate tests for all the devfiles in the next 3 weeks
- currently che 7 tests, in general, are not stable enough

@Katka92 could you please provide an update based on the `QA involvement` section of our `Che OSIO ENDGAME` plan  https://gist.github.com/ibuziuk/cd9eac654daac34ac9d139af988bec01#qa-involvement

**Comment by Katka92** [comment]
@ibuziuk Me and @ScrewTSW went through the devfiles on prod-preview. The sum up can be found here https://github.com/redhat-developer/che-functional-tests/issues/543. 
About current state of tests:
- Once UI is updated, it would require only small changes in tests
- We are focused on automation test for Java Maven now
- The new tests are quite stable, the only issue they are falling on is project import - and I would say it is a problem with Che 7 (today I was able to reproduce that manually, but it happens really rarely). 
- Current flow of tests is:
   - Select Java Maven stack
   - Add `console-java-simple` project
   - Create&Open workspace
   - Wait project is imported
   - Open file
   - Check "Java Language Server" initialisation by suggestion invoking' - PR [here](https://github.com/redhat-developer/rh-che/pull/1492)

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW thanks for the update - great summary. Hope you will be able to do the second round of testing once we update to `rc-4.0`

**Comment by Katka92** [comment]
@ibuziuk We are counting with second round, we believe that the results with rc-4.0 would be much better. :+1:

**Comment by ibuziuk** [comment]
@Katka92 @tdancs it looks like quite a few devfiles from the registry are failing with quota issues e.g. `apache-camel` / `spring-boot`. Could you please provide a list of incompatible devfiles in https://github.com/eclipse/che/issues/13969

**Comment by amisevsk** [comment]
Current testing document: https://gist.github.com/amisevsk/fb60ca6bbbcc03f2916a2074fa2ce526

There are a few common issues I've noticed and am working on PRs to address them.

**Comment by ScrewTSW** [comment]
```
[WIP]
01.08.2019
Che version: 7.0.0-rc-4.0
che.prod-preview.OSIO

NodeJS Angular Web Application - OK
===
* devfile project is automatically selected
* Workspace starts up
* Commands:
  * start - OK
  * build - OK
  * lint - OK
  * yarn install - OK

Apache Camel based on Spring Boot - WARN
===
* devfile project is automatically selected
* Workspace starts up
* Commands:
  * build the project - OK
  * **run the services - WARN - swagger is not working when you try the endpoint request**

.NET Core - OK
===
* devfile project is automatically selected
* workspace started
* Commands:
  * update dependencies - OK
  * run - OK

Go - OK
===
* devfile project is automatically selected
* workspace started
* Commands:
  * New terminal - opens a new go-cli terminal
  * test outyet - OK
  * run outyet - OK

Java Gradle - WARN
===
* devfile project is automatically selected
* workspace started
* Commands:
  * gradle build - OK
  * gradle run - OK
  * **8080/tcp** - successfully opens up a new tab - THIS IS USELESS, there's no application deployment happening, it's just a single-run simple java hello world.

Java Maven - WARN
===
* devfile project is automatically selected
* workspace started
* Commands:
  * maven build - OK
  * maven build and run - OK
  * **8080/tcp** - successfully opens up a new tab - THIS IS USELESS, there's no application deployment happening, it's just a single-run simple java hello world.
```

**Comment by amisevsk** [comment]
The current state of our devfiles on prod-preview is shown in this [gist](https://gist.github.com/amisevsk/fb60ca6bbbcc03f2916a2074fa2ce526)

There are a few outstanding issues that are upstream issues and prioritized for post-7.0.0:
- The Python extension does not work; this breaks language features and debugging (I think) on python-based devfiles https://github.com/eclipse/che/issues/14074
- Debugging on most nodejs images doesn't work https://github.com/eclipse/che/issues/14190
- Running the node mongo sample application is confusing (it's a backend REST API so the preview URL is useless): https://github.com/eclipse/che/issues/14009
    - I think it's just a bad sample application

**Comment by ibuziuk** [comment]
@amisevsk great job! since all the known issues are listed and most of them prioritized for `7.1.0` I would propose to close this issue. 
@Katka92 will do verification on QA side as part of the https://github.com/redhat-developer/rh-che/issues/1490
