### ISSUE TITLE
Workspace idling is not working

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#144]
see - https://issues.jboss.org/browse/CHE-289

**Comment by l0rd** [comment]
This has been fixed in https://github.com/eclipse/che/pull/5512. We will be able to close it once we will be using eclipse/che `master` branch (curently we are using `openshift-connector-wip`).

**Comment by sunix** [comment]
I can rebase 'openshift-connector-wip'

**Comment by l0rd** [comment]
This is going to be fixed by #154
