### ISSUE TITLE
Explore CRW integration with devconsole

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1447]
Explore CRW integration with devconsole: (The user's openshift token wouldn't be accepted by Che auth since they use different keycloaks / keys) Related to ODC-26

**Comment by ibuziuk** [comment]
Initial investigation with token ex-change have been done  - https://docs.google.com/document/d/1UU8ql9bgwvhK1F3AWsWeVepVeUHGFf1-2mkLcl0CXvU/edit#heading=h.idj2dinxe2y9
