### ISSUE TITLE
Workspace pod log

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#145]
see https://issues.jboss.org/browse/CHE-243

**Comment by benoitf** [comment]
@ibuziuk I see a PR for it there https://github.com/redhat-developer/che-dockerfiles/pull/14/files

**Comment by ibuziuk** [comment]
@benoitf the PR is not ideal. Please take a look at @l0rd comment [1]

> The PR sent by Snjezana Peco is brilliant but has 2 drawbacks:
> 1. The code is error prone and it's run in container pid 1: if, for whatever reason, logging to stdout fails the workspace will crash
> 2. Besides wsagent there are still other agents logging (i.e. bayesian)

[1] https://issues.jboss.org/browse/CHE-243?focusedCommentId=13415139&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13415139

**Comment by ibuziuk** [comment]
Also https://issues.jboss.org/browse/CHE-243?focusedCommentId=13417714&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13417714

> The goal of this issue is to have the logs of the workspaces in openshift.io sent to zabbix for further inverstigation.

**Comment by benoitf** [comment]
@ibuziuk yes I saw that comment, but I'm using minishift and AFAIK there is no zabbix there.
Workspace logs are written in the home user directory on the che master, so I don't see what I can bring more from Che project part or from rh-che scripts.
It looks like I'm not the right guy on this task

**Comment by ibuziuk** [comment]
@benoitf but a part from zabbix, will it be possible to make log process less error prone and have some mechanism for adding logs from other agents ?

**Comment by benoitf** [comment]
@ibuziuk What is error prone in the log process ?
Also we already logs from other agents as agents are executed inside the machine

here are the logs of the ssh agent for example (and terminal agent)
```
tail -f .che/cli/instance/logs/machines/machineb52i0e695cdq3kw4/machineId.logs 
[STDOUT] OK: 8429 distinct packages available
[STDOUT] (1/5) Installing openssh-keygen (7.5_p1-r1)
[STDOUT] (2/5) Installing openssh-client (7.5_p1-r1)
[STDOUT] (3/5) Installing openssh-sftp-server (7.5_p1-r1)
[STDOUT] (4/5) Installing openssh-server (7.5_p1-r1)
[STDOUT] (5/5) Installing openssh (7.5_p1-r1)
[STDOUT] Executing busybox-1.26.2-r5.trigger
[STDOUT] OK: 103 MiB in 56 packages
[STDOUT] ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 
[STDOUT] 2017/06/29 09:24:23 Start new terminal.

```

**Comment by ibuziuk** [comment]
> @ibuziuk What is error prone in the log process ?
if logging fails for some reason workspace will crash. Anyway, probably it's better to wait for @l0rd who can provide more details what is expected right now. In the meanwhile, please feel free to pick any other issue from the current sprint which is not assigned

**Comment by l0rd** [comment]
@benoitf as far as I understand the original request was to make it easier to access the logs of the agents. We usually want to access the logs from the openshift console or, for OSIO, fetch the logs and integrate them to view it in a kibana-like web console.

I'm scared to merge @snjeza PR because it's complex (difficult to debug/maintain) and risky (it's a shell script with hardcoded strings manipulations that run as PID 1 in the container). That would be ok if we had alternatives but I think we would address the original request if we:

1. Print to stdout some instructions about how to access agents logs: this would be visible from the openshift console (or with the `docker log` command)
2. Write the logs in a volume (using a property to define where the logs should be): this would make them easily accessible for an external tool

**Comment by benoitf** [comment]
@l0rd 

> Print to stdout some instructions about how to access agents logs: this would be visible from the openshift console (or with the docker logs command)

These instructions would be in the log of the che server docker container ?

> Write the logs in a volume (using a property to define where the logs should be): this would make them easily accessible for an external tool

These logs are Machine logs, correct ?

**Comment by l0rd** [comment]
> These instructions would be in the log of the che server docker container ?

No the che workspace docker container that currently doesn't log anything to stdout. Adding something like this in the `entrypoint.sh` [before `tail -f /dev/null`](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L57):

```bash
echo "
Workspaces don't log to stdout. Instead agents log files can be fond inside the container:
- wsagent logs open are in folder /home/user/che/ws-agent/logs
- ls-bayesian logs can be found in /home/user/che/bayesian.log
"
```

**Comment by l0rd** [comment]
> These logs are Machine logs, correct ?

Yep

**Comment by jfchevrette** [comment]
Would it be possible to write the log files to the PV (currently mounted at /projects)? That would allow them to persist between pod restarts. Right now STDOUT is nice to debug in real time through the OpenShift console but they are not archived anywhere so again if the pod restarts we loose the ability to see what was shown at the console right before it restarted.

**Comment by l0rd** [comment]
I'm opening a new issue for the [che-server](https://github.com/redhat-developer/rh-che/issues/212) logs and closing this one.
