### ISSUE TITLE
After update of che.openshift.io to Che 7 GA all Che 6 sample from SaaS Cloud will stop working (need to replace with devfile equivalent)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1451]
https://www.eclipse.org/che/getting-started/cloud/

![image](https://user-images.githubusercontent.com/1461122/59335759-848da280-8cfd-11e9-92e4-3325e25770be.png)

- [x] Spring Rest Guide https://github.com/redhat-developer/devfile/pull/47
- [x] Vert.x verticle https://github.com/redhat-developer/devfile/pull/50
- [x] Angular https://github.com/redhat-developer/devfile/pull/40
- [x] C++ (**No equivalent - replaced with Go**) - https://github.com/redhat-developer/devfile/pull/44
   - https://github.com/eclipse/che/issues/13698#issuecomment-508423288
- [x] Java + Gradle https://github.com/redhat-developer/devfile/pull/36
- [x] Java + Maven https://github.com/redhat-developer/devfile/pull/38
- [x] Node.js https://github.com/redhat-developer/devfile/pull/42
- [x] PHP https://github.com/redhat-developer/devfile/pull/39
- [x] Spring (spring boot pet-clinic) https://github.com/redhat-developer/devfile/pull/43
- [x] Spring Boot https://github.com/redhat-developer/devfile/pull/51
- [x] Vaadin https://github.com/redhat-developer/devfile/pull/34
- [x] Wildfly **(Rebrending to `thorntail` is required)** - https://github.com/redhat-developer/devfile/pull/41

**Comment by ibuziuk** [comment]
@l0rd @slemeur  are we going to promote devfiles from the https://che-devfile-registry.openshift.io/devfiles/ on SaaS next page ?

**Comment by l0rd** [comment]
Yes I think we should have a devfile / stack for each one of those

**Comment by ibuziuk** [comment]
AFAIK, stack story is finished and we need to fall back on deviles only. Also, it looks like we will not be able to update prod to CR2 until we would fix the getting started page

**Comment by l0rd** [comment]
@ibuziuk the stack story is not finished: the devfile is the new (yaml) format to define a workspace or a stack. Like a Dockerfile defines a container or an image. But yes we are deprecating the old workspace config (json) format for stacks and workspaces (replaced by the devfile) as well as the `stacks.json` (replaced by the devfile registry).

Actually the getting started factories should be replaced by devfiles but we don't need to put those devfiles in the defvile registry. The main issue currently is C++ because there is no Che 7 language server yet.

**Comment by ibuziuk** [comment]
thanks for the clarification - I meant `stacks.json` / `json` workspace config format deprecation

**Comment by ibuziuk** [comment]
Closing this issue since all devfile have been created. There are separate issues for:
- verification cc @Katka92 https://github.com/redhat-developer/rh-che/issues/1547
- website update https://github.com/redhat-developer/rh-che/issues/1490
