### ISSUE TITLE
Need to create CI for community operator

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1453]
**Description:**

- Job to build and push operator image to quai.io 
- Use operator in the happy-path e2e scenario 

- Add QA to the operator release process
- Automatic PR to che-operator once new version of che server is released

**Comment by ibuziuk** [comment]
@davidfestal is this issue still valid for upstream ?

**Comment by ibuziuk** [comment]
@davidfestal I will probably close this issue. Feel free to open a dedicated issue for operators in the upsream
