### ISSUE TITLE
Investigate approach with the entrypoint script injection to Che 7 images in the runtime to make the /etc/passwd writable for the arbitrary user

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1455]
Investigate approach with the entrypoint script injection to make the /etc/passwd writable for the arbitrary user:

````
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi
```


related to https://github.com/eclipse/che/issues/13454

**Comment by ibuziuk** [comment]
Draft PR with patching community images to make them openshift compatible - https://github.com/eclipse/che-dockerfiles/pull/248

**Comment by ibuziuk** [comment]
Initial PR with patched Dockerfile has been merged to devfile registry eclipse/che-devfile-registry#24

**Comment by ibuziuk** [comment]
PR for CI/CD setup - https://github.com/openshiftio/openshiftio-cico-jobs/pull/1034

**Comment by ibuziuk** [comment]
@amisevsk hope you will be able to add all the missing images to https://github.com/eclipse/che-devfile-registry/tree/master/arbitrary-users-patch

and take care of nighly CI - https://github.com/eclipse/che/issues/13837

**Comment by amisevsk** [comment]
Closing as done
