### ISSUE TITLE
Inconsistencies between stacks

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#147]
see - https://issues.jboss.org/browse/CHE-266

There is Inconsistencies between stacks:

- [ ] centos jdk does not use scl but download tars instead
- [ ] other images (vertx, wildfly, spring boot, node.js) should be based on centos jdk

**Comment by dharmit** [comment]
SCL issues covered in this issue are fixed by https://github.com/eclipse/che-dockerfiles/issues/108

**Comment by ibuziuk** [comment]
There is Inconsistencies between stacks:

- [ ]  centos jdk does not use scl but download tars instead
- [ ]  other images (vertx, wildfly, spring boot, node.js) should be based on centos jdk

**Comment by l0rd** [comment]
When this issue is solved we should solve also https://github.com/openshiftio/openshift.io/issues/432

**Comment by benoitf** [comment]
is this issue is finished ?

**Comment by l0rd** [comment]
Still something to merge https://github.com/CentOS/container-index/pull/198...
