### ISSUE TITLE
Need to find a better home for Hosted Che FAQ

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1479]
Currently, FAQ point to the adoc file in the rh-che repo:

![che openshift io FAQ](https://user-images.githubusercontent.com/1461122/54819527-7438cf00-4c9c-11e9-8411-181fabbe3612.gif)

Based on the discussion in https://github.com/eclipse/che-docs/pull/729 it was considered to find a better place for FAQ after Che 7 GA release - https://github.com/eclipse/che-docs/pull/729#issuecomment-509527338

**Comment by ibuziuk** [comment]
@themr0c @rkratky I think it should be part of https://www.eclipse.org/che/docs/che-7/hosted-che/#about-hosted-che_hosted-che wdyt?

**Comment by themr0c** [comment]
@ibuziuk You are right.

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che-docs/pull/1295

**Comment by ibuziuk** [comment]
Merged https://github.com/redhat-developer/rh-che/pull/1908
Closing
