### ISSUE TITLE
Stack template suggestion

### ISSUE THREAD

**Issue by Nickk4** [redhat-developer/rh-che#1483]
Feature request
The stack I would like to use is not available as template. And I don't have the know-how to build a custom stack myself. More importantly, I think it's a pretty common stack. Is it possible to add this stack as a template:
- Unix/Ubuntu
- Node
- MySql 5.7
- npm
- git

**Comment by ibuziuk** [comment]
@Nickk4 hello, in the short run (~1 month) we are going to get rid of Che 6 templates and use devfiles from upstream https://github.com/eclipse/che-devfile-registry. Devfile registry is already deployed as part of our CI / CD pipeline and available in https://che-devfile-registry.openshift.io/devfiles/ 

Feel free to contribute devfiles you are interested in to https://github.com/eclipse/che-devfile-registry and very soon those will become available on che.openshift.io. 

Some docs about devfiles - https://redhat-developer.github.io/devfile/

**Comment by ibuziuk** [comment]
@Nickk4 going to close this issue and looking forward to your contributions to the new devfile registry ;-)
