### ISSUE TITLE
Apache Camel devfile does not start on prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1486]
**Issue problem:** 
When starting Che 7 workspace based on ` Apache Camel based on Spring Boot `, the workspace is not started saying ` Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacevd196kj996eb1v7b.maven-85dcd48884-55sdr" is forbidden: [maximum cpu usage per Pod is 6, but limit is 6424m., maximum memory usage per Pod is 3Gi, but limit is 3450109952.]', 'workspacevd196kj996eb1v7b.maven-85dcd48884'" `.

Screenshot:
![Screenshot from 2019-07-12 13-00-31](https://user-images.githubusercontent.com/29278800/61124031-27287500-a4a6-11e9-8b51-fdfb3dd7078e.png)

**Red Hat Che version:** 
version: 7.0.0-rc-3.0 on prod-preview

**Reproduction Steps:**
Log in to https://che.prod-preview.openshift.io. Click Add Workspace, click ` Apache Camel based on Spring Boot ` and hit the button `CREATE & OPEN`.

**Comment by Katka92** [comment]
Created issue in upstream: https://github.com/eclipse/che/issues/13832

**Comment by amisevsk** [comment]
Closing as devfile has been updated.
