### ISSUE TITLE
Tests for verifying stacks

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#149]
see - https://issues.jboss.org/browse/CHE-257

**Comment by l0rd** [comment]
# How to properly test a Che stack

## Set some variables to configure the stack we want to test

The following values are for testing stack `centos-dotnet20`. Values should be changed when testing other stacks.

```bash
STACK_NAME=centos-dotnet20
IMAGE_NAME=registry.centos.org/che-stacks/centos-dotnet20:latest
MAIN_COMMAND="dotnet --version"
current_project_path="/projects/${STACK_NAME}"
SAMPLE="https://github.com/che-samples/dotnet-web-simple.git"
CMD1="dotnet run"
```

## 01. Build

```bash
docker build -t ${IMAGE_NAME} .
```

## 02. Check exec of main binary as default user

```bash
docker run -d --name "${STACK_NAME}" \
                 "${IMAGE_NAME}" \
                 tail -f /dev/null
docker exec -ti "${STACK_NAME}" ${MAIN_COMMAND}
```

## 03. Check exec of main binary as arbitrary user

```bash
docker run -d --name "${STACK_NAME}" \
              --user 15151515 \
                 "${IMAGE_NAME}" \
                 tail -f /dev/null
docker exec -ti "${STACK_NAME}" ${MAIN_COMMAND}
```

## 04. Check run main binary from bash as default user

```bash
docker run -ti --rm --name "${STACK_NAME}" \
                 "${IMAGE_NAME}" \
                 bash
$ ${MAIN_COMMAND}
```

## 05. Check run main binary from bash as arbitrary user

```bash
docker run -ti --rm --name "${STACK_NAME}" \
                 --user 15151515 \
                 "${IMAGE_NAME}" \
                 bash
$ ${MAIN_COMMAND}
```

## 07. Check run commands as default user

```bash
git clone ${SAMPLE} /tmp/${STACK_NAME}
docker run -ti --rm --name "${STACK_NAME}" \
                -v  /tmp/${STACK_NAME}:/projects/${STACK_NAME}/ \
                -w /projects/${STACK_NAME}/ \
                 "${IMAGE_NAME}" \
                 sh -c "${CMD1}"
```

## 08. Check run commands as arbitrary user

```bash
git clone ${SAMPLE} /tmp/${STACK_NAME}
docker run -ti --rm --name "${STACK_NAME}" \
                --user 15151515 \
                -v  /tmp/${STACK_NAME}:/projects/${STACK_NAME}/ \
                -w /projects/${STACK_NAME}/ \
                 "${IMAGE_NAME}" \
                 sh -c "${CMD1}"
```

## 09. Check starting a Che workspace using the stack using the Docker Connector

## 10. Check starting a Che workspace using the stack using the OpenShift Connector

**Comment by l0rd** [comment]
@JPinkney is working on implementing the tests using [godog](https://github.com/DATA-DOG/godog) and including the test in the suite of tests used to verify minishift.

**Comment by l0rd** [comment]
Original PR was created on minishift repository https://github.com/minishift/minishift/pull/1967

Minishift team asked to move this PR to minishift-addon repo. Before we could do that the test framework needed to be ported to that repo too https://github.com/minishift/minishift-addons/issues/67.

Yesterday the framework has been ported so we can proceed with the new PR.

**Comment by ibuziuk** [comment]
@rhopp if you or @ScrewTSW would like to work on this also it would be great - feel free to add it to your sprint backlog ;-)

**Comment by rhopp** [comment]
Assigned to @Katka92 and changed milestone to sprint 147.

**Comment by ibuziuk** [comment]
Closing as outdated.
Some of the tests for Che 6 were implemented and contributed to minishift addon
