### ISSUE TITLE
[regression] Create workspaces in ephemeral mode does not work

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1503]
**Issue problem:** 
Switching to devfiles for creating workspaces in the UD broke ephemeral mode as a default at some point (reproducible on prod-preview now).

The toggle in workspace config still works, issue is only present at creation stage.

**Red Hat Che version:** 

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Create workspace, with ephemeral toggle set to "on"; check devfile for `persistVolumes` attribute.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
PR was merged - https://github.com/redhat-developer/rh-che/pull/1505
moving to the done column

**Comment by ibuziuk** [comment]
Should be fixed on prod-preview and still working on prod. Closing
