### ISSUE TITLE
How should we handle ephemeral mode and devfile workspace creation?

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1504]
**Issue problem:** 
Our current approach is to use ephemeral volumes by default on che.openshift.io due to performance issues (gluster is slow).

When a user creates a workspace from a devfile by passing it directly to Che (i.e. as in `che.openshift.io/f?url=<url of devfile>`), it currently is not created as ephemeral. 

Should we extend the ephemeral-by-default option to workspaces created in this way?

Pros: 
- Consistency between UD workspaces and devfile workspaces (same workspace can be created by using a devfile in the registry or by passing a link to that same devfile)
- Avoid performance issues (still present -- e.g. `yarn install` can fail due to fs sync issues)

Cons:
- We would be rewriting the devfile passed in (adding the `persistVolumes` attribute)
- Could probably be more easily solved by making sure default devfiles have the property already

**Comment by sunix** [comment]
I think we should keep like it is ... and see how it goes.

**Comment by ibuziuk** [comment]
> Should we extend the ephemeral-by-default option to workspaces created in this way?

I believe for now we would fix in on devfile level for getting-started devfiles only https://www.eclipse.org/che/getting-started/ as part of https://github.com/redhat-developer/rh-che/issues/1451

**Comment by ibuziuk** [comment]
@amisevsk I believe this is the answer - https://github.com/eclipse/che/issues/15500 
We need to implement a way in the upstream to add / override devfile attributes via URL parameters 
Closing
