### ISSUE TITLE
Update .NET 2.0 stack image to version 2.1

### ISSUE THREAD

**Issue by kevchu3** [redhat-developer/rh-che#1508]
**Issue problem:** 
The referenced `quay.io/openshiftio/che-centos_dotnet20` stack in `assembly/fabric8-stacks/src/main/resources/stacks.json` is out of date as .NET 2.0 was deprecated in October 2018 [1].  I'm opening this issue to have both the quay.io image and this stack's reference to the image updated to .NET 2.1 (or 2.2).  I'd expect to keep the naming convention, so perhaps `quay.io/openshiftio/che-centos_dotnet21` (or dotnet22) would suffice.

**Red Hat Che version:** 

che.openshift.io version: 7.0.0-RC-1.1
quay.io/openshiftio/che-centos_dotnet20 image version: 2.0.3

 - [X] I can reproduce it on latest official image

**Reproduction Steps:**

Running `dotnet --version` from within the stack's terminal shows it's running version 2.0.3.

**Runtime:**

runtime used:
   - [X] OpenShift.io

**Comment by amisevsk** [comment]
The `stacks.json` file will be deprecated completely once https://github.com/redhat-developer/rh-che/pull/1481 is merged; currently it should not be used and instead the [devfile](https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/dotnet/devfile.yaml) is used instead (which does reference .NET 2.2)

**Comment by ibuziuk** [comment]
We are going to close this issue once che.openshift.io is updated to Che 7 GA
