### ISSUE TITLE
[Test Issue] Che7 Java Selenium times out during IDE loading

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1510]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/476

![image](https://user-images.githubusercontent.com/16451875/62044391-219b9080-b203-11e9-8359-f22cdce161bd.png)

Issue did not appear recently, but still needs to remain open, until old java selenium suite is deprecated and replaced by typescript e2e

**Comment by ScrewTSW** [comment]
Seen today again on `starter-us-east-2` production

![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/a8821b75-5fda-4ff4-9203-c9bd4b79a267)

**Comment by Katka92** [comment]
Java tests are not used anymore. Closing as deprecated.
