### ISSUE TITLE
[Test Issue] Che7 Java Selenium tests selected incorrect menu in editor

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1512]
Related: https://github.com/redhat-developer/che-functional-tests/issues/476

![image](https://user-images.githubusercontent.com/16451875/62045245-29f4cb00-b205-11e9-8846-a6b5aa2444c3.png)

This issue doesn't seem to appear often. Will be closed once java selenium test suite is deprecated in favor of typescript e2e

**Comment by Katka92** [comment]
Not seen for a long time, closing.
