### ISSUE TITLE
[Infra Issue] Che7 master deployment route flapping

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1513]
Related: https://github.com/redhat-developer/che-functional-tests/issues/476

![image](https://user-images.githubusercontent.com/16451875/62045435-95d73380-b205-11e9-93f7-8f79df357440.png)

This issue doesn't seem to happen recently. Created for completion, can be closed once decided that the infrastructure is stable.

Last occurence: April 16 2019

**Comment by Katka92** [comment]
For last month of monitoring, infra seems quite stable. Can be closed.
