### ISSUE TITLE
[Test Issue] Che7 Java Selenium based test times out during workspace startup

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1515]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/541

![image](https://user-images.githubusercontent.com/16451875/62055106-3c79ff00-b21b-11e9-94c0-c37558883d2b.png)
![image](https://user-images.githubusercontent.com/16451875/62129784-d901d700-b2d7-11e9-99e2-04f171ab5f06.png)

For some reason our tests time out waiting for the editor window during the worksapce startup
Related to: https://github.com/redhat-developer/rh-che/issues/1525

Last appeared:
* 29.07.2019 **x7** @ `starter-us-east-1a`
* 29.07.2019 **x7** @ `starter-us-east-1b`

**Comment by Katka92** [comment]
Seen again on 2a production 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/897/console
1a 3x 
1b 2x

**Comment by ScrewTSW** [comment]
seen today on 1a x1 and 1b x3

**Comment by Katka92** [comment]
Seen on cluster 2 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1145/console
cluster 1a 6x 
cluster 1b 7x

**Comment by Katka92** [comment]
Seen on cluster 2 1x, 1a 1x, 1b 1x

**Comment by Katka92** [comment]
Seen on 1a 1x

**Comment by Katka92** [comment]
Seen on 2 2x, 1a 2x, 1b 2x

**Comment by Katka92** [comment]
Seen on 2 2x.

**Comment by Katka92** [comment]
Seen on cluster 2 15x, 1a 2x, 1b 2x.

**Comment by Katka92** [comment]
Seen on cluster 2 5x.

**Comment by Katka92** [comment]
Seen on cluster 2 2x

**Comment by Katka92** [comment]
Seen on cluster 2 1x, 1a 1x, 1b 1x.

**Comment by ScrewTSW** [comment]
appeared once today at `us-east-2`

**Comment by ScrewTSW** [comment]
Seen today again:
`starter-us-east-2` x2
`starter-us-east-2a` production x2
`starter-us-east-1b` x1

**Comment by Katka92** [comment]
Java tests are not used anymore. Closing this issue as deprecated.
