### ISSUE TITLE
[Infra issue] Failed to log in - internal server error

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1517]
The login fails with internal server error.
![image](https://user-images.githubusercontent.com/29278800/62110621-1c941b00-b2af-11e9-80a8-eaa6fad57c34.png)

Seen on 1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/897/console

**Comment by ScrewTSW** [comment]
Happened again on `starter-us-east-2` today

**Comment by Katka92** [comment]
Not seen for a long time. Closing.

**Comment by Katka92** [comment]
This issue was seen again during a reload of a page. Happened on prod-preview 2a cluster 1x. 
Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2104/console

**Comment by Katka92** [comment]
Seen again on prod-preview 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2199/console

**Comment by ibuziuk** [comment]
@alexeykazakov can we raise this issue with the SSO team?

**Comment by alexeykazakov** [comment]
We can't file a ticket with so little information.
What you did to get that error? What steps? Any logs in the browser?

**Comment by Katka92** [comment]
Sorry for the delay, I was waiting for the next occurrence of the failure but for now, it was not reproduced. So from the last I've reported here - we don't have any browser logs [1]. We are gathering them, but the file is empty. 
The test flow is simply opening a browser and trying to reach the `https://che.prod-preview.openshift.com`. Test logs in using username and password. Then this page with error message appears. 

I'm afraid that's all I can offer to you now. I'll keep monitoring this issue and raise it again once it will appear.

[1] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/2199/e2e_report/report/Java_Vert.x_test_Create_Java_Vert.x_workspace_wksp-test-AzNqt_Create_and_open_workspace/

**Comment by Katka92** [comment]
Not seen for more than a month. Closing.
