### ISSUE TITLE
[Che Issue] (Che7) Project not imported

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1519]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/552

![image](https://user-images.githubusercontent.com/16451875/62112659-6bdc4a80-b2b3-11e9-90c0-5090af50ffbf.png)

Last seen on: July 29 2019

**Comment by Katka92** [comment]
Not tested on production, not happening on prod-preview. Closing.
