### ISSUE TITLE
[Rebase oscon] Move bayesian recommendation token support to rh-che

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#152]
Rebase openshift-connector to master - https://github.com/redhat-developer/rh-che/issues/146 

Move bayesian recommendation token support to rh-che [CHE-271](https://issues.jboss.org/browse/CHE-271)  -

**Comment by sunix** [comment]
maybe requires https://github.com/redhat-developer/rh-che/issues/150

**Comment by sunix** [comment]
Requires https://github.com/redhat-developer/rh-che/issues/166 to be fixed

**Comment by ibuziuk** [comment]
Closing in favour of - https://github.com/redhat-developer/rh-che/issues/141
