### ISSUE TITLE
[Infra Issue] Build timeout

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1521]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/525

**Description:**
Build timeout started to occur more often now. Investigate why and adjust the timeout if needed.
It started to happen when there was a problem with workspace startup. Startup takes too much time and it was considered that that's the cause why tests are failing on BUILD TIMEOUT.
Now, worksapce startup takes only ~35 seconds, so it is obvious that the worksapce startup time is not a cause of this problem.
Add logs saying how much time each phase consume (e.g. building Rh-Che, deploying Postgre + Rh-Che on dev cluster...) and depending on that optimise the process or increase a timeout. 

Last seen on: July 10 2019 at `1a` `2` and `2a` clusters

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
