### ISSUE TITLE
[Che Issue] (Che6) Project not imported

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1522]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/519

![image](https://user-images.githubusercontent.com/16451875/62121110-3b9ca800-b2c3-11e9-9039-486f5f61bdbb.png)

Last seen on: July 29 2019 at `starter-us-east-2` cluster

**Comment by ibuziuk** [comment]
should be closed after Che 7 GA promotion to prod - https://github.com/redhat-developer/rh-che/issues/1490
We are not planning to invest into investigation

**Comment by Katka92** [comment]
We are not testing this on a prod now. Not happening on prod-preview. Closing.
