### ISSUE TITLE
Need to verify that ssh plugin works correctly in Hosted Che

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1524]
Need to verify that ssh plugin works correctly in Hosted Che and once configured users can push to the remote. 

Help links:
- https://www.eclipse.org/che/docs/che-7/hosted-che.html#prerequisites-5
-  https://github.com/eclipse/che-theia/tree/master/plugins/ssh-plugin
- https://youtu.be/72MDoJT05cY

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 hope you will be able to help to verify the flow against prod-preview

**Comment by ibuziuk** [comment]
cc: @vparfonov

**Comment by ScrewTSW** [comment]
Pubkey doesn't work right after generating
Pubkey works after workspace restart (can authorize git)

**Comment by ibuziuk** [comment]
Upstream issue has been created - https://github.com/eclipse/che/issues/14073

**Comment by ScrewTSW** [comment]
Issue is still being discussed in upstream. Moved to On-Hold

**Comment by ibuziuk** [comment]
@ScrewTSW could you confirm that message is shown once ssh key is generated? and that ssh access work in general on prod-preview?

**Comment by ScrewTSW** [comment]
> @ScrewTSW could you confirm that message is shown once ssh key is generated? and that ssh access work in general on prod-preview?

![image](https://user-images.githubusercontent.com/16451875/64004278-39ba4480-cb0e-11e9-8144-082818609f48.png)

It seems to be working just as expected, so it's :+1: from me.

**Comment by ibuziuk** [comment]
@ScrewTSW great, so git push / pull works just fine?

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/64017364-bad30500-cb29-11e9-8332-05133c05e5ff.png)

Everything works as intended. Closing
