### ISSUE TITLE
[Test Issue] Failed to get access token

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1526]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/494

Sometimes it happens that our tests fail to get access tokens for users.

Last seen on: July 29 2019 at `starter-us-east-2a`

**Comment by ScrewTSW** [comment]
seen today again on 1b once

**Comment by Katka92** [comment]
Seen on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/929/console

**Comment by Katka92** [comment]
Not seen for a month, closing.
