### ISSUE TITLE
[Che Issue] Bayesian for package.json does not trigger after reopening file

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1527]
Parent: https://github.com/redhat-developer/che-functional-tests/issues/464

![image](https://user-images.githubusercontent.com/16451875/62130393-3ba7a280-b2d9-11e9-88d9-aec4a9b3dbcb.png)

Last seen on: July 29 2019 at `starter-us-east-2`

**Comment by ibuziuk** [comment]
bayesian was removed in the latest commit (update to rc4). Issue should be closed once we update to Che 7 GA on prod

**Comment by ibuziuk** [comment]
we should get rid of bayesian test for now

**Comment by Katka92** [comment]
We are not testing Bayesian. This issue is obsolete, closing.
