### ISSUE TITLE
[Rebase oscon] Verify that on master branch Unit Tests are started in their own process now (c.f. CHE-214) 

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#153]
Rebase openshift-connector to master - https://github.com/redhat-developer/rh-che/issues/146

Verify that on master branch Unit Tests are started in their own process now (c.f. CHE-214) [CHE-273](https://issues.jboss.org/browse/CHE-273)

**Comment by sunix** [comment]
@davidfestal 

> This will be the case when this branch is finished and merged : https://github.com/eclipse/che/tree/new-java-test

**Comment by davidfestal** [comment]
For the case of TestNG, I added this comment to the PR : https://github.com/eclipse/che/pull/5472#pullrequestreview-47609385.

It seems that the JUnit support is not included in this refactoring for the moment. So we'll have to further monitor this work until JUnit testing is also using the new out-process architecture, and check that JUnit test process is also started in the project root directory.

**Comment by ibuziuk** [comment]
@davidfestal modified JUnit the same way -  https://github.com/eclipse/che/pull/5710#pullrequestreview-50543437

**Comment by davidfestal** [comment]
I've tested with project `wildfly-swarm-openshiftio-boosters/wfswarm-rest-http` from the intial issue (JIRA-214), and the error doesn't occur anymore. It seems we can close this one.

**Comment by davidfestal** [comment]
waiting for the build + publish in prod before closing

**Comment by davidfestal** [comment]
Validated in OSIO, tenant 1.0.244
