### ISSUE TITLE
[Test issue] Resources from upstream removed

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1531]
Resources from upstream were removed. Java Che 6 tests were removed. Not sure how many resources that are needed for us were removed too. Need further investigation.

**Comment by ibuziuk** [comment]
@Katka92 what does it mean `Resources from upstream removed ` ?could we have more clear issue titles with details in the description ?

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW please remove obsolete Che 6 tests as part of this issue. Let's focus on testing Che 7 only (both prod and prod-preview)

**Comment by Katka92** [comment]
Obsolete tests remove. Closing.
