### ISSUE TITLE
rh-che dsaas deployment migration to OpenShift 4

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1534]
dsaas / dsaas-stg migration to OpenShift v4 is planned to be done in the near future. Need to help SD team with the migration process of rh-che and other dependent Che services

**Comment by ibuziuk** [comment]
cc: @pbergene @kbsingh do you have any particular migration plan ?

**Comment by pbergene** [comment]
We are currently starting verifying our tooling and pipelines vs 4.x.  Once we're at a satisfactory state there it would be a matter of pointing the stage pipelines and app-interface to a 4.x cluster, do deployments, apply runtime configuration from app-interface.  Some verification would be done by devs at this point (baseline, stuff comes up, not throwing exceptions), then move to switch DNS at which point we could run full e2e flow on the stage env.

Then repeat for prod. 

Last we heard you could be ready to go mid-september, has this changed?

**Comment by ibuziuk** [comment]
@pbergene thanks for an update, mid-september sounds like a good timing for moving prod-preview to 4.x cc: @slemeur @l0rd

**Comment by gazarenkov** [comment]
Related brief: https://docs.google.com/document/d/1npu0EognOCI4TDX-cUgugkHIL8mELKfPlHNuEwkCH5s/edit#

**Comment by ibuziuk** [comment]
> Some verification would be done by devs at this point (baseline, stuff comes up, not throwing exceptions), then move to switch DNS at which point we could run full e2e flow on the stage env.

@pbergene will you need any help with that in the next sprint from the Hosted Che team?

**Comment by pdaverh** [comment]
What work remains? Thanks!

**Comment by pbergene** [comment]
Cluster is up and operational, launcher is in flight currently as the first component.  @mmclanerh @skryzhny executing this. 

cc @jmelis @aditya-konarde

**Comment by ibuziuk** [comment]
Che server has been migrated from dsaas / dsaas-stg to new OSD v4
The incident that had happened during migration is resolved - https://che.statuspage.io/history
Closing
