### ISSUE TITLE
.NET Core devfile does not work with ephemeral mode

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1535]
**Description:**
Issue https://github.com/eclipse/che/issues/13739 means that running the .NET devfile in ephemeral mode results in error markers everywhere.

The workaround is currently to `dotnet restore` and restart the workspace; this does nothing since any changes are not persisted in ephemeral mode.

When running in non-ephemeral mode (and after running the update dependencies task and restarting the workspace), the language server works as expected.

**Comment by ibuziuk** [comment]
any chance that plugin broker refactoring will address this case?

**Comment by amisevsk** [comment]
Plugin broker refactoring likely won't have an impact on this, though I can no longer reproduce this on 7.3.2 (likely due to https://github.com/eclipse/che-plugin-registry/pull/199).

Currently, the project initially has error markers, and the `update dependencies` command must be run, but after that I see on issues. I think this one can be closed.

**Comment by ibuziuk** [comment]
Should be fixed since eclipse/che#13739  is closed
