### ISSUE TITLE
[Test issue] Epel installation failed 

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1538]
When running tests, some dependencies need to be installed. This time Epel fails with the message:
```
One of the configured repositories failed (Extra Packages for Enterprise Linux 7 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail.
```
This appeared on all cluster at the same time - between 22:00 2nd August and 3:00 3rd August. It was probably some outage of a service.
 
One of affected jobs: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1134/console

**Comment by Katka92** [comment]
This failure affected our route tests too so we don't have date around that time.

**Comment by Katka92** [comment]
This issue is seen again. Periodic tests are failing from 2:35 AM, route tests are not gathering info from 2:15.

**Comment by Katka92** [comment]
Failing on all clusters & route tests. There were two successful runs of route tests on cluster 2 at 15:00 and 23:00. Trying to investigate what is happening.

**Comment by Katka92** [comment]
According to centos wiki documentation [1] I tried to add yum clean.
There are three possible causes listed on a wiki page:
**1. You are not connected to the internet.**
That is probably not our problem, it seems that epel was downloaded correctly, but it seems that there is a problem with updating it. 

**2. This issue can also occur if the system is able to communicate with given server but could not find or access the requested package or path on the server.**
Need more investigation.

**3. You have a misconfigured proxy server.**
I don't assume that anything regarding proxy server changed on Jenkins. 

[1] https://wiki.centos.org/yum-errors

**Comment by Katka92** [comment]
None of my tries to stabilise the run works, but I found an issue about that on centos bug tracker. https://bugs.centos.org/view.php?id=16337

**Comment by Katka92** [comment]
Was fixed by workaround yesterday. Jobs are working from ~19:00.

**Comment by ScrewTSW** [comment]
Appeared once at `us-east-1b`

**Comment by Katka92** [comment]
Not seen for a month. Closing.

**Comment by Katka92** [comment]
Problems with epel installation are back on cluster 2 2x, 2a (production) 2x, 1a 2x, 1b 3x, 2a (prod-preview) 3x.
`Error downloading packages:   epel-release-7-11.noarch: [Errno 256] No more mirrors to try.`

https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1703/console

**Comment by Katka92** [comment]
The problem was fixed. Closing the issue again.

**Comment by Katka92** [comment]
Appeared once on 1b, seems like an intermittent issue, not reopening yet.
