### ISSUE TITLE
Idling of wsmaster is not working on OSIO

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#154]
Rebase openshift-connector to master - https://github.com/redhat-developer/rh-che/issues/146

Improve idling implementation [CHE-274](https://issues.jboss.org/browse/CHE-274) - **estimation**: 5

**Comment by sunix** [comment]
PR: https://github.com/eclipse/che/pull/5425 on master

**Comment by ibuziuk** [comment]
need to rebase `openshift-connector-wip` to the che master

**Comment by l0rd** [comment]
UPDATE: `openshift-connector-wip` has been rebased on top of che master and as a result idling of Che server is not working anymore. Let's keep this issue opened to track this issue.

/cc @aslakknutsen
