### ISSUE TITLE
[Test issue] False positive fail on workspace stop

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1543]
Test fails on a step when it tries to stop a workspace. According screenshot it seems that worksapce was already stopped. 

Seen only once so far. Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1152/console

![image](https://user-images.githubusercontent.com/29278800/62519378-bcabf000-b82b-11e9-94e3-b6f8a7d2d6e0.png)

**Comment by ibuziuk** [comment]
@Katka92 closing as not reproducible. Feel free to reopen if needed
