### ISSUE TITLE
Support caching more images in image puller

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1550]
**Description:**
Currently, the kubernetes image puller caches all images in a single daemonset. As OpenShift quotas are calculated based off number of pods started in the namespace (which is one pod per node in the cluster for a daemonset) it's easy to bump into limits.

We should investigate splitting daemonsets into multiple runs to allow caching more images (e.g. cache images in batches of five). This can be worked around by increasing the quota allotted, but it would still be a nice feature to have.

**Comment by ibuziuk** [comment]
Closing for now. might need to create a separate issue in the upstream
