### ISSUE TITLE
[Test issue] Test fails on name input when creating workspace

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1552]
Test fails when creating workspace. It expects the name field to be empty, but it already contains workspace name. Seems like some intermittent issue of our Java tests.
For now happened only once on 2a cluster and once on 1a.
On 1b it expected 'wksp-m1569' but was 'wksp-qrlfwksp-m1569' https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/973/console
Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/972/console 
Screenshot:
![image](https://user-images.githubusercontent.com/29278800/62847273-ad1e2280-bcd5-11e9-908d-e31453ca6150.png)

**Comment by ibuziuk** [comment]
@Katka92 closing as not reproducible. Feel free to reopen if needed
