### ISSUE TITLE
Need to tag all the `arbitrary-users-patch` images during the che-devfile-registry release CI

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1557]
Placeholder for eclipse/che#14165

**Comment by ibuziuk** [comment]
Auxilary PR that should help - https://github.com/eclipse/che-devfile-registry/pull/80

**Comment by amisevsk** [comment]
The open PR: https://github.com/eclipse/che-devfile-registry/pull/90

**Comment by ibuziuk** [comment]
Upstream issue is closed. Closing
