### ISSUE TITLE
Need to verify how Che 6 -> Che 7 workspace migration works on prod-preview (7.0.0 GA) before updating prod

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1568]
Need to verify how Che 6 -> Che 7 workspace migration works on prod-preview (7.0.0 GA) before updating prod.

![image](https://user-images.githubusercontent.com/1461122/63365697-66d15f00-c378-11e9-876a-95101ce77606.png)

![image](https://user-images.githubusercontent.com/1461122/63365724-7650a800-c378-11e9-91f1-09822ecae72b.png)

**Comment by ibuziuk** [comment]
@rkratky docs links still point to https://www.eclipse.org/che/docs/che-6/what-are-workspaces.html 
do you happen to know when are we going to have the migration guide available under this page ?

**Comment by skabashnyuk** [comment]
@ibuziuk FYI https://github.com/eclipse/che/issues/14200

**Comment by rkratky** [comment]
@ibuziuk I'm afraid we haven't worked on a migration guide. Do you have the steps available, so that we could turn it into published docs?

**Comment by rkratky** [comment]
@ibuziuk, unless you mean https://www.eclipse.org/che/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/ (Converting a Che 6 workspace to a Che 7 devfile).

**Comment by amisevsk** [comment]
@rkratky that looks about as good as we can expect (there's no automatic way to do it). We should update the docs link.

**Comment by ibuziuk** [comment]
Upstream issue - https://github.com/eclipse/che/issues/14308
A workaround on doc side - https://github.com/eclipse/che-docs/pull/794

**Comment by Katka92** [comment]
I've gone through the procedure of a migration which is described in a documentation and I found some issues. I've created an issue with sum up here https://github.com/eclipse/che/issues/14315

**Comment by ibuziuk** [comment]
@rkratky docs PR is pending review - https://github.com/eclipse/che-docs/pull/796

**Comment by ibuziuk** [comment]
@Katka92 doc migration is merged. Could you please confirm that the migration process defined in the docs works on prod-preview. After that, I believe we can close this issue

**Comment by Katka92** [comment]
I've checked the new migration docs, seems to be up-to-date. Closing this issue.
