### ISSUE TITLE
User accounts on che.openshift.io are being provisioned without SA token

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1569]
**Description:**
We're getting more common reports of "Unauthorized! Configured service account doesn't have access" issues when running on che.openshift.io. From the cases I have checked, it's because these users' `*-che` namespace does not contain the che token secret used by oso-proxy to create workspace resources. 

We need to figure out why this is occurring, and also improve the [reset environment flow](https://github.com/redhat-developer/rh-che/blob/master/dev-guide.adoc#update-tenant) since it is quite complicated.

Reference issues: 
https://github.com/redhat-developer/rh-che/issues/1566
https://github.com/eclipse/che/issues/12366

**Comment by ibuziuk** [comment]
cc: @alexeykazakov @nurali-techie

**Comment by amisevsk** [comment]
Note the best example I have currently is namespace `rhs-gps-brson-che`, although it has since been reset.

**Comment by amisevsk** [comment]
Note the best example I have currently is namespace `rhs-gps-brson-che`, although it has since been reset.

**Comment by amisevsk** [comment]
Accidentally clicked the "Close and comment button" :)

**Comment by ibuziuk** [comment]
Created https://jira.coreos.com/browse/CRT-355

**Comment by ibuziuk** [comment]
https://issues.redhat.com/browse/CRT-355 is closed. Need to verify and close the rh-che specific issue

**Comment by ibuziuk** [comment]
verified. Closing
