### ISSUE TITLE
[Test issue] Expand project and open file in editor fails

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1571]
Project tree is expanded up to the last folder which hasn't been expanded yet and tests fail as they cannot find the file they are looking for

![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/d270a947-325f-4e58-bdee-eef3c97d7f13)

**Comment by Katka92** [comment]
There was an upstream issue: https://github.com/eclipse/che/issues/14197
It was fixed: https://github.com/eclipse/che/pull/14199
The PR with a fix was merged on 12th August, the release was done on 14th August, so the fix should be contained in tests that runs against actual version of prod-preview. Reopening upstream issue.

**Comment by ScrewTSW** [comment]
Seen today, on Saturday and Sunday:

https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1269/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1262/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1258/console

**Comment by ScrewTSW** [comment]
Happened again today: 
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/ac911e86-7e56-4eba-9359-a3f6e2c3bd50)
The tests completely failed to expand the `src` folder

https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1289/console

**Comment by ScrewTSW** [comment]
Happened today again, stuck on expanding `examples`

**Comment by ScrewTSW** [comment]
Happened today and yesterday on prod-preview. stuck on `src` folder.

**Comment by Katka92** [comment]
Not seen for a 21 days. Closing. Feel free to reopen when occurs again.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2177/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2426/console

**Comment by Katka92** [comment]
The file was opened, but its status is not `saved` so the test fails. 
Seen on production 2a cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2248/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2490/console
on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2278/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2279/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2276/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2277/console

**Comment by Katka92** [comment]
Can not expand the project tree and open file. Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2600/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2601/console

**Comment by Katka92** [comment]
Seen again on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2407/console
