### ISSUE TITLE
[Che issue] Login fails with Authorization token is missing

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1572]
Very rarely it happens that the login fails with error during authentication.

![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/2cbc28c1-d03d-429b-86c2-9ddc674e4890)

**Comment by ScrewTSW** [comment]
The issue was last seen on Friday August 23rd on prod-preview `starter-us-east-2a` cluster:

https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1256/console

**Comment by ScrewTSW** [comment]
@amisevsk I cannot see anything that would catch my eye in the logs, maybe you can see what I can't

[kibana_logs](https://logs.dsaas-stg.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-23T06:30:00.000Z',mode:absolute,to:'2019-08-23T07:00:00.000Z'))&_a=(columns:!(message,kubernetes.container_name),index:'project.dsaas-preview.6e520a9f-d097-11e8-9fb7-121499db9246.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:%22e87f54b8-7905-46f9-8055-f987c5b58320%22)),sort:!('@timestamp',desc)))

**Comment by ScrewTSW** [comment]
Happened today again on `starter-us-east-1b` cluster x1

**Comment by Katka92** [comment]
Not seen for a month. Closing.
