### ISSUE TITLE
Fix daily telemetry woopra report

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1578]
Daily Woopra report is broken and needs to be fixed

**Comment by ibuziuk** [comment]
will start with sending the message to the woopra support team - the report used to work just fine before

**Comment by ibuziuk** [comment]
@davidfestal can I help with this issue ? maybe I can take over it?

**Comment by tomgeorge** [comment]
Once I get prod Woopra access, I will start working on this.

**Comment by ibuziuk** [comment]
Closing as out-of-date
