### ISSUE TITLE
Kubernetes image puller wants to schedule pods on non-compute nodes

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1580]
**Description:**
The Kubernetes image puller appears to be trying to schedule nodes on non-compute (i.e. infra and master) nodes. This causes it to report that 75/81 pods are ready, even though it can't, and shouldn't schedule on infra pods.

We need to examine the daemonset being created and configure it to only create pods on the desired nodes.

**Comment by ibuziuk** [comment]
the funny thingy is that infra & master nodes also have the "compute" role, woth checking with SD if theoretically workspace creation could happen on those

**Comment by amisevsk** [comment]
Open PR: https://github.com/redhat-developer/kubernetes-image-puller/pull/14

**Comment by amisevsk** [comment]
Fixed in redhat-developer/kubernetes-image-puller#14
