### ISSUE TITLE
Standardize registry containers based on UBI8 minimal + httpd + yq (+ jq + python)

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1581]
Placeholder for eclipse/che#14113

**Comment by amisevsk** [comment]
Progress is blocked because it's not clear that we want to build + maintain a `ubi8-httpd` container ourselves. E.g. the currently used `registry.centos.org/centos/httpd-24-centos71` [is quite complicated](https://github.com/sclorg/httpd-container/tree/master/2.4).

Additionally, such a container would likely need its own CI and repository, as it would be reused in both brokers.

**Comment by ibuziuk** [comment]
@nickboldt any comments on that ^ ? Moving to "On Hold" pipeline

**Comment by amisevsk** [comment]
@ibuziuk I think it's more a question for @l0rd -- Nick has ubi8-httpd images built already, it's just a fairly [complicated](https://github.com/nickboldt/containers/blob/da29b14dfa57eedabda6029258948e6a181b25dc/ubi8-httpd-yq/Dockerfile#L44-L83) dockerfile compared to what we do now (pull a working image). 

We can pull these changes into one of our repos, but it's a question of if we want to be the ones to maintain a new `ubi8-httpd` image. 

Also, the `registry.access.redhat.com/ubi8/python-36` image appears to have httpd installed, but it's also `750MB` in size and includes Python, which we don't need.

**Comment by l0rd** [comment]
To move forward on this I would temporarily build and publish the `ubi8-httpd` image as an alternative to the alpine image. Alpine should be the default upstream but we need to build both the ubi and the alpine versions nightly to make sure we never break the ubi build. 

Once we move to a standalone web service for registries (https://github.com/eclipse/che/issues/14268) I would use a `FROM scratch` image (no ubi, no alpine). That's the smallest possible size and compatible with brew (is it right @nickboldt)?

**Comment by ibuziuk** [comment]
Let's move the discussion back to upstream - https://github.com/eclipse/che/issues/14113
Closing this issue
