### ISSUE TITLE
Fix project expanding issue

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1583]
Issue: https://github.com/redhat-developer/rh-che/issues/1571
Igor's comment with sum up of his investigation of possible root cause: https://github.com/eclipse/che/issues/14197#issuecomment-526620050

According to Igor's comment it seems that this is Rh-Che specific test issue and should be fixed on Rh-Che side. 
It seems that there have to be some difference in a logic, because files displayed in project tree in pure Che (running via chectl) and Rh-Che differs. See the pictures below for comparison of project tree using the default Java Maven stack.

Upstream Che 7.1.0-SNAPSHOT
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/dc6b35b7-ae62-4bb9-9963-586845c68e8e)

Rh-Che 7.0.0 on prod-preview (same for 7.1.0 deployed on devcluster)
![Screenshot from 2019-09-02 11-33-12.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/a2947887-3bf2-4a94-9d50-dc80fa709e73)

**Comment by Katka92** [comment]
Further investigation: 
Both are `Java Maven` default stacks with the default setting (on Rh-Che using ephemeral mode). 
From a devfile both seems to be using master branch of a project:

pure Che 
![Screenshot from 2019-09-02 12-27-52](https://user-images.githubusercontent.com/29278800/64108517-45f80900-cd7d-11e9-910e-07a491f94052.png)

Rh-Che on prod-preview
![Screenshot from 2019-09-02 12-27-29](https://user-images.githubusercontent.com/29278800/64108529-4db7ad80-cd7d-11e9-8d81-af11bfc61381.png)

**Comment by Katka92** [comment]
From and advice of @sunix it seems like a problem with vscode extension that has the ability to hide/show these files. 
When a workspace is started, it asks if those files should be hidden, but even if I select hiding them in a workspace, I can still see the files. It may be bug in a vscode extension.

**Comment by sunix** [comment]
vscode extension -> java vscode extension.

**Comment by sunix** [comment]
maybe related to https://github.com/theia-ide/theia/issues/6046 ?

**Comment by Katka92** [comment]
It seems that the project tree looks the same in Che and Rh-Che finaly, but in Che it takes much longer time to view `.gradle` and other items. That answers the question why upstream tests are not failing. According to that, I can verify that it isn't bug of Java vscode extension but timing issue of tests. We can write a fix in tests - e.g. wait until all items are shown in project explorer and only then start opening a file.

**Comment by Katka92** [comment]
For now seems like this issue is not present in 7.1.0. Will observe for a while and close if issue will not be reproducible.

**Comment by ibuziuk** [comment]
@Katka92 can we close this one ? seems to be fixed in `7.1.0`

**Comment by Katka92** [comment]
Yes, the issue was not seen from the day we updated to 7.1.0. I left this opened to track it, I think that 15 days is enough. Closing.
