### ISSUE TITLE
Explore the impacts of adding the `all namespaces` install mode in the Che operator

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1587]
Currently, the Che operator doesn't support the `all namespaces` installation mode, which prevents it to be added as a dependency of another operator that supports this installation mode.

We should take some time to play with it and explore the impacts of adding this, especially the impacts on required permissions and eligibility for OSD 4 OperatorHub.

**Comment by l0rd** [comment]
As far as I understand supporting `all namespaces` allow a Kubernetes admin to deploy a `che-server` in every single namespace. That's something that doesn't make sense for Che and that we do not support.

Recently [we have decided](https://github.com/eclipse/che/issues/14203#issuecomment-521287804) that we will only support one `che-server` per Kubernetes cluster. Deploying more than one che-server will break Che and DevConsole integration on OpenShift 4.2 or above. And I am afraid that supporting `all namespaces` goes in the opposite direction.

**Comment by alexeykazakov** [comment]
@l0rd I understand your reasoning. It makes sense. But it becomes a blocker for Toolchain operator then. Not sure how we could solve that and be able to install both Tekton and Che operators via Toolchain operator...

**Comment by pdaverh** [comment]
So from what I understand, if we enable "All namespaces" installation mode for Che, then there is a risk that some admin or developer would start an instance of the Che operator in more than one namespace. Is that correct? If so, should we consider Che to check if an instance of the operator is already running on the cluster and prevent one from starting?

**Comment by ibuziuk** [comment]
@davidfestal @l0rd I think we should close this one and create a dedicated issue in the upstream if needed. AFAIK, it is not planned to have the `all namespaces` support atm

**Comment by ibuziuk** [comment]
Closing as outdated
