### ISSUE TITLE
Replace workspace config with devfile in workspace-startup tests

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1589]

**Comment by ibuziuk** [comment]
@ScrewTSW ca we close this one?

**Comment by ibuziuk** [comment]
ok, I see we need to merge - https://github.com/redhat-developer/rh-che/pull/1679

**Comment by ScrewTSW** [comment]
> ok, I see we need to merge - #1679

yes.

**Comment by ibuziuk** [comment]
https://github.com/redhat-developer/rh-che/pull/1679 merged. Closing
