### ISSUE TITLE
[Spike] Investigate a possibility to move plugin broker to a separate service shared among all the workspaces

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1592]

**Comment by amisevsk** [comment]
Opened issue https://github.com/eclipse/che/issues/14494 with proposed refactoring as a first step in running broker as a service.

**Comment by amisevsk** [comment]
@ibuziuk I believe this one can be closed; issue https://github.com/eclipse/che/issues/14494 is the next step and would spawn the required subtasks.
