### ISSUE TITLE
Enable worksapce-startup-test email failure reporting

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1597]
Implement mail-to functionality in workspace-startup-tests pipeline.

This section should alert us when the workspace-startup-tests start failing.

**Comment by ibuziuk** [comment]
@ScrewTSW is it still actual? please provide a meaningful description or close as not relevant

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW is it still relevant?

**Comment by ScrewTSW** [comment]
@ibuziuk yes, we wanted to add a `mail-to` section into the jenkins pipeline which would be sending alert mails to us when the tests are failing. It isn't a high priority though, it's more of a nice-to-have feature.

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW let's consider closing the issue

**Comment by ibuziuk** [comment]
Closing as obsolete
