### ISSUE TITLE
[E2E] Remove workspace on --bail not working for 7.1.0

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1599]
The `--bail` option should stop running the tests but still should stop and remove a workspace. That is not working as expected in 7.1.0. Fix that or remove `--bail` option before releasing.
Related to fixing tests for 7.1.0 https://github.com/redhat-developer/rh-che/issues/1575

**Comment by Katka92** [comment]
According to the failed tests on prod-preview [1] it may be useful to DON'T run tests in --bail mode. The IDE in this particular tests was not started in 2 minutes, but started when test was waiting for a project. So we can see that all other tested components behaves correctly. If the --bail was set, we would have no idea if other components work correctly or not.
The "problem" is that if all other tests would fail (e.g. IDE is not loaded at all) we will have a huge report - screenshots of each failed tests etc. But IMHO it is still better to run tests without --bail. 

[1] 
![Screenshot from 2019-09-11 12-44-14](https://user-images.githubusercontent.com/29278800/64695615-e0063280-d49c-11e9-9432-2351c7fff451.png)

**Comment by ibuziuk** [comment]
@Katka92 is it still actual?

**Comment by Katka92** [comment]
Yes, we still have some issues with `--bail` mode so we are not using it.

**Comment by Katka92** [comment]
We are running without --bail till today and I think this is very valuable. We will not switch to --bail option so there is no need to investigate and fix this issue. Closing.
