### ISSUE TITLE
Cannot import private repository as a project from github

### ISSUE THREAD

**Issue by akochnev** [redhat-developer/rh-che#1602]
**Issue problem:** 

che.openshift.io does not allow me to use a private repository on GitHub. When I log in with my github account, it only shows the public repositories in the account. I am unable to import a new private repo neither when creating a new workspace, nor after the workspace is created. 

In contrast, when I create a workspace in codenvy, the private repositories are available to import. 

**Red Hat Che version:** 

Version:     1.0.0-SNAPSHOT       
Build Time:  2019-06-21 11:39:19  
Revision:    074a40ebc814337f   

 - [ x ] I can reproduce it on latest official image

**Reproduction Steps:**

1. Workspaces -> Add Workspaces
2. Select the default python stack
3. Click on "Add or Import Project", choose the GitHub tab
4. Authenticate with github using my credentials. 
5. Scroll down and observe that the private repo is not listed. 

**Runtime:**

runtime used: che.openshift.io as of Sept 6, 2019

**Comment by ibuziuk** [comment]
workaround: generating SSH key from the workspace and uploading to Github would allow to pull / push to the private repositorie
