### ISSUE TITLE
[Test issue] Typescript tests - Test fails to create workspace

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1603]
Test selects correct stack, default project is selected, it clicks `Create & Open` button, but nothing happens. Test then fails waiting for IDE element ` By(xpath, //ide-iframe[@id='ide-iframe-window' and @aria-hidden='false']) `. 

Seen two times: 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1341/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1342/console

**Comment by ibuziuk** [comment]
@Katka92 is it still reproducible ?

**Comment by Katka92** [comment]
@ibuziuk This issue was not seen for 16 days.

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
