### ISSUE TITLE
[Che issue] Timeout when waiting for IDE

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1604]
Workspace is created correctly, but it last too long for IDE to show up. Current timeout is set to 2 minutes from clicking button ` Create & Open`. 

![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/52a9dd99-20dd-4805-8702-b113bde8a8ae)

Last seen: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1356/console

**Comment by Katka92** [comment]
Seen again on prod-preview 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1366/console 
Screenshot:
![image](https://user-images.githubusercontent.com/29278800/64673703-28a6f700-d46f-11e9-9e7b-e8be987b3686.png)

**Comment by Katka92** [comment]
Seen again on 1a and 1b.

**Comment by ScrewTSW** [comment]
seen today at 1b cluster x1

**Comment by ScrewTSW** [comment]
Seen today again on prod `1a` two times. and once on `1b`

**Comment by ScrewTSW** [comment]
Appeared today only once at `1b` cluster.

**Comment by ScrewTSW** [comment]
Seen today once on cluster `1b`

**Comment by Katka92** [comment]
Happened again 4x on `1a` and 2x on `1b`.

**Comment by Katka92** [comment]
Happened again on `1a` 1x.

**Comment by Katka92** [comment]
Happened again on `1a` 1x.

**Comment by Katka92** [comment]
Seen on `1a` 2x.

**Comment by ScrewTSW** [comment]
Seen on `1a` twice and once on `prod-preview 2a` stuck at IDE load screen
![image](https://user-images.githubusercontent.com/16451875/65878474-71770f00-e38e-11e9-8f53-ee29b18aba6f.png)

**Comment by ScrewTSW** [comment]
happened once on `1a`

**Comment by ScrewTSW** [comment]
happened once on `1a` and twice on `2a`

**Comment by Katka92** [comment]
Happened again on 1a once.

**Comment by Katka92** [comment]
Seen 2x on 2, once on 2a, once 1a, once on 1b.

**Comment by Katka92** [comment]
Happened 1x on 1a and 1x on 1b.

**Comment by ScrewTSW** [comment]
Happened 1x on `1a`

**Comment by Katka92** [comment]
Happened 1x on 2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1614/console

**Comment by Katka92** [comment]
Seen again on 2a 1x

**Comment by ScrewTSW** [comment]
Happened yesterday 1x on prod-preview 2a cluster

**Comment by ScrewTSW** [comment]
Happened today again at `production-1b`
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1540/console

**Comment by skabashnyuk** [comment]
Can you extract che-server logs relate to this workspace?

**Comment by ScrewTSW** [comment]
Seen again on `prod-2`
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1758/console
There is nothing special in the logs themselves.

**Comment by ScrewTSW** [comment]
Appeared on `production 1a` x1

**Comment by ScrewTSW** [comment]
seen on `production 1a` x1

**Comment by Katka92** [comment]
Seen again on 1a 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1653/console

**Comment by Katka92** [comment]
IDE was stuck on this screen for the whole test. Happened 1x on production cluster 2a. 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1658/console

![image](https://user-images.githubusercontent.com/29278800/70121106-36cf7280-166e-11ea-93d0-b16df9bd47e2.png)

**Comment by Katka92** [comment]
Seen again on cluster 2 2x, 2x on 2a production, 2x on 1a, 1x on 1b, 1x on prod-preview 2a.

**Comment by Katka92** [comment]
Seen again on production cluster 2a 1x.

**Comment by ScrewTSW** [comment]
Seen today on production 1a x1.
![image](https://user-images.githubusercontent.com/16451875/71821792-5275d080-3093-11ea-9794-efaf7e01ce6b.png)

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2086/console

**Comment by dmytro-ndp** [comment]
Happened again while testing Eclipse Che 7.7.0.RC being installed on minikube 1.1.1 https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/Single-Che-pre-release-check-test-all-devfiles-against-K8S/21/console

**Comment by Katka92** [comment]
This issue was not observed for 2 weeks. Closing.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2030/console

**Comment by Katka92** [comment]
Workspace start took too long. Seen 1x on prod 2a (3 minutes and 17 secs).
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2039/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2211/console

**Comment by Katka92** [comment]
Test for workspace readiness failed 1x on cluster 1b.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2246/console

**Comment by Katka92** [comment]
The project view was not expanded, test timeouts waiting for workspace readiness. 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2254/console

**Comment by ScrewTSW** [comment]
Seen again on production 1b x2:
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2272/e2e_report/report/

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2280/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2281/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2287/console

![image](https://user-images.githubusercontent.com/16451875/76961690-14f8b380-691e-11ea-8458-1d7b4467d093.png)

**Comment by Katka92** [comment]
Not seen for 12 days. Closing.

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2573/console
caused timeout of Python Django test

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2439/console

^ the above failure is suspected, but cannot be confirmed with 100% certainty since we are currently missing screencaster.

**Comment by Katka92** [comment]
Workspace startup timeouted 1x on cluster 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2487/console

**Comment by Katka92** [comment]
Seen again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2474/console
Seen again on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2475/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2474/console

**Comment by Katka92** [comment]
See again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2722/console
Seen again on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2510/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2519/console
![image](https://user-images.githubusercontent.com/16451875/80375269-4e66fc00-8898-11ea-917a-8bb828df3b24.png)

**Comment by Katka92** [comment]
Not seen for three weeks. Closing.
