### ISSUE TITLE
verifying that chectl can deploy multiuser Che without cluster admin privileges 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1609]
@l0rd I remember we discussed this issue during prioritization, but as I understand currently cluster-admin is a requirement according to the error message:

> [ibuziuk@fedora ~]$ chectl server:start --platform=minishift --multiuser
>   ✔ ✈️  Minishift preflight checklist
>     ✔ Verify if oc is installed...done.
>     ✔ Verify if minishift is installed...done.
>     ✔ Verify if minishift is running...done.
>   ❯ 🏃‍  Running the Che Operator
>     ✔ Copying operator resources...done.
>     ✔ Create Namespace (che)...done.
>     ✔ Create ServiceAccount che-operator in namespace che...done.
>     ✖ Create Role che-operator in namespace che
>       → ERROR: It looks like you don't have enough privileges. You need to grant
> …
>       Create ClusterRole che-operator
>       Create RoleBinding che-operator in namespace che
>       Create ClusterRoleBinding che-operator
>       Create CRD checlusters.org.eclipse.che
>       Waiting 5 seconds for the new Kubernetes resources to get flushed
>       Create deployment che-operator in namespace che
>       Create Che Cluster eclipse-che in namespace che
>  ›   Error: ERROR: It looks like you don't have enough privileges. You need to 
>  ›   grant more privileges to current user or use a different user. If you are 
>  ›   using minishift you can "oc login -u system:admin"

**Comment by ibuziuk** [comment]
@l0rd could you please clarify the scope of this issue?

**Comment by l0rd** [comment]
@ibuziuk what I mean is that admin rights should not be required (except if the user wants to configure Keycloak to use OpenShift OAuth). Today for some reason we create a che-operator `ClusterRole`. Why do we need that? Can we avoid it?

**Comment by ibuziuk** [comment]
Closing in favour of upstream - https://github.com/eclipse/che/issues/14662

**Comment by hari1992-web** [comment]
Readiness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container

**Comment by hari1992-web** [comment]
Does any way fix it ?? 
thanks in advance
