### ISSUE TITLE
[E2E] Move Java Maven test to upstream

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1620]
Move the test of Java Maven default stack to the upstream. Check the code and update some parts if needed, get inspired by HappyPath test which is already using maven plugins.

**Comment by ibuziuk** [comment]
@Katka92 is this issue still actual?

**Comment by Katka92** [comment]
I'm not sure about that. But this test should be updated and moved to upstream. I'll change the title and description a bit.

**Comment by ibuziuk** [comment]
Hmm.. I thought that we have already contributed maven & vertx tests to upstream, no?

**Comment by Katka92** [comment]
No, there is only Vert.x stack in upstream, we still need to move the Maven one.

**Comment by Katka92** [comment]
PR in upstream: https://github.com/eclipse/che/pull/15545
We will be able to remove the test from rh-che repo next release.

**Comment by Katka92** [comment]
PR merged and included to nightly test suite.
