### ISSUE TITLE
[Infra issue] Maven application build takes too long to start

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1622]
Hello.

I've noticed an issue with our Maven test failing because of a timeout.
When I've taken a closer look it appears to have been caused by the infrastructure.

Once the maven build has started it has taken the terminal 13 seconds just to connect to the maven pod.
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/b1d05a2a-6bf7-4af0-8ca3-e73da1be7e78)

After that the build was hanging at starting Java for another five seconds.
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/35ed240c-b1f0-4f83-b045-11ada6263374)

And finally the tests have timed out.
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/d39f45a6-d458-40a9-a0ea-2e6c2fa3dd48)

I don't believe this to be a test related issue and it's probably not a Che related issue. This to me seems like a hiccup of K8s.

I would really appreciate your opinion @ibuziuk @amisevsk @davidfestal

**Comment by Katka92** [comment]
Seen again on prod-preview [1]. This time nor build neither run were executed in given time frame. Screenshots below are taken when tests timeouted. 

![image](https://user-images.githubusercontent.com/29278800/65407247-30a55600-dde2-11e9-8b3b-70c22694bb89.png)

![image](https://user-images.githubusercontent.com/29278800/65407260-3c911800-dde2-11e9-909e-59fa33cc4d2c.png)

Job link: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1438/console

**Comment by Katka92** [comment]
Today tests failed on build and run commands again, seems like it lasted too long to show the pop-up saying `Task che: maven build has exited with code 0.`
![image](https://user-images.githubusercontent.com/29278800/65667995-2df46c00-e041-11e9-89a6-cacb49693e4a.png)

**Comment by Katka92** [comment]
Seen again on cluster 2.

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
