### ISSUE TITLE
[Test issue] Site can't be reached

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1625]
Periodic test on production failed because it can not reach a page che.openshift.io [1]. Tests for route flapping are not catching any major issues with route exposure so it may not be related. 

Seen once on production 1b cluster on 22 September 14:44: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1225/consoleFull
and once on prod-preview (during stopping worksapce) on 22 September 14:35: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1438/console

Jobs were running at almost same time so it might be some outage.

[1]
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/3a88e9e7-79f2-4cef-bc5e-4b632123de08)

**Comment by ScrewTSW** [comment]
Happened today once on `1b` cluster

**Comment by Katka92** [comment]
Not seen for 20 days now. Closing.
