### ISSUE TITLE
Load tests on prod-preview

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1631]
**Description:**
Target: run as many as possible concurrent workspaces using test accounts (currently should be possible to have at least 15 concurrent)

The load script should be reused from https://github.com/eclipse/che/issues/14629 

This issue is required for further investigation of https://github.com/eclipse/che/issues/14530
since the  `CHE_WORKSPACE_POOL_TYPE` was changed to `cached` on prod-preview. Now we need to gather some data of how this would behave under load

**Comment by Katka92** [comment]
@ibuziuk Which devfile should be used to test prod-preview? In upstream they are using quarkus [1]. Is that devfile suitable or should we use some other? 

[1] https://raw.githubusercontent.com/redhat-developer-demos/guru-night/master/quarkus-tutorial/devfile.yaml

**Comment by Katka92** [comment]
We will not implement that test.
