### ISSUE TITLE
Workspace sharing on hosted Che does not work

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1634]
**Description:**
As of Che 7, the "share workspace" tab is entirely non-functional, giving only the error
> Workspace created with Devfile can not be exported as Factory.

PR https://github.com/redhat-developer/rh-che/pull/1626 removes the share workspace tab, but we should re-examine workspace sharing in Che 7 and update hosted Che appropriately.

**Comment by ibuziuk** [comment]
workspace sharing has been disabled on Hosted Che - https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-ide-dashboard-war/src/assets/branding/product.json#L34
Closing
