### ISSUE TITLE
[Che Issue] Editor is not initialized

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1635]
Workspace after starting is non functional.

* Welcome page doesn't load
* Project is not imported
* Workspace commands are missing

![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/71e929f1-10ab-4946-a47c-46aed8258f55)

**Comment by ScrewTSW** [comment]
happening at prod-preview since Sptember 30, 10:44 PM UTC

**Comment by ScrewTSW** [comment]
still keeps on consistently failing on prod-preview (6x)

**Comment by rhopp** [comment]
@ScrewTSW Is this also manually reproducible?
Can you dig out browser console logs?

**Comment by amisevsk** [comment]
I'm able to reproduce manually. The console log:
![Screenshot from 2019-10-02 09-28-13](https://user-images.githubusercontent.com/16168279/66048171-16146080-e4f7-11e9-9600-6fd4fd7a7974.png)

(zoomed out to get the whole thing)

**Comment by ScrewTSW** [comment]
> @ScrewTSW Is this also manually reproducible?
> Can you dig out browser console logs?

Didn't try to do it manualy, but seems that Angel was successful.
Anyways, it's still failing all the time on prod-preview

**Comment by amisevsk** [comment]
I suspect the issue may be related to prod-preview using the 7.2.0 release of plugin registry. I see the images 
```
"quay.io/eclipse/che-java11-maven:nightly"
"docker.io/eclipse/che-machine-exec:7.1.0"
"docker.io/eclipse/che-theia:7.1.0"
"docker.io/eclipse/che-remote-plugin-runner-java8:7.2.0"
```
for a java-maven workspace. I would hold off work on this issue until 7.2.0 is rolled to prod-preview.

**Comment by ScrewTSW** [comment]
still have to report it though :D it's still failing.

**Comment by Katka92** [comment]
Seen yesterday and today on prod-preview. Seems like it should be fixed from now.

**Comment by Katka92** [comment]
Not seen for a log time. Closing.
