### ISSUE TITLE
Compatability check CI should also deploy updated plugin registries

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1636]
## Description:
During the process for updating the upstream Che dependency version, we're stuck in a state where the PR-check CI job for the "update to version x" PR continues to use the previous versions registries (since it reuses the staging registries). I don't know of any *specific* issues related to different versions of Che vs. the registries, but this could potentially cause issues in the future.

Instead, the PR-check job should also deploy the relevant plugin and devfile registries, to make the check more accurate.

### Background
Previously, the prod-preview registry was updated continuously, so when we created the "update to version 7.x" PR, the PR-check would use the current registry. Now that registries are pinned to the `release-preview` branch, they are left behind.

### Related
https://github.com/redhat-developer/rh-che/issues/936

**Comment by ScrewTSW** [comment]
Prod-preview seems to be still reliably failing in every test run :D 
We are tracking this for the reporting purposes in this rh-che issue: https://github.com/redhat-developer/rh-che/issues/1635

**Comment by Katka92** [comment]
The logic was added to our PR check. @ScrewTSW please verify it is working correctly and if so, please close this issue. :)

**Comment by ibuziuk** [comment]
@ScrewTSW can we close the issue?

**Comment by ibuziuk** [comment]
@ScrewTSW closing. feel free to reopen if needed
