### ISSUE TITLE
Improve logging of keycloak-plugin-server

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#164]
Only errors should be logged and we should avoid using `System.out` in [KeycloakAuthenticationFilter.java](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/plugins/keycloak-plugin-server/src/main/java/com/redhat/che/keycloak/server/KeycloakAuthenticationFilter.java)

c.f. https://github.com/redhat-developer/rh-che/pull/159/files#r124846818

**Comment by amisevsk** [comment]
Looks like this will be addressed by PR https://github.com/redhat-developer/rh-che/pull/170/

**Comment by ibuziuk** [comment]
https://github.com/redhat-developer/rh-che/pull/170 pushed to master
