### ISSUE TITLE
Update dependencies in rh-che build scripts

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1655]
E.g.: We are using outdated version of docker in the cico_build.sh script
https://github.com/redhat-developer/rh-che/blob/master/.ci/cico_build.sh#L33

It should be replaced by https://download.docker.com/linux/centos/docker-ce.repo as it's causing unnecessary delays and conflicts with the rest of the CI scripts.

We should also investigate and refactor the rest of the bash logic and update dependencies.

**Comment by ibuziuk** [comment]
Should be fixed in https://github.com/redhat-developer/rh-che/pull/1898
