### ISSUE TITLE
Multiple exceptions on che.openshift.io  - Unable to perform '[rm, -rf, /tmp/job_mount/xxx]' command

### ISSUE THREAD

**Issue by skabashnyuk** [redhat-developer/rh-che#1656]
**Issue problem:** 
Error in logs
```
Unable to perform '[rm, -rf, /tmp/job_mount/XX]' command for the workspace 'XXX' cause: 'Exception during the user tenant data retrieval or parsing'
```
From org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.PVCSubPathHelper
Can be related to  https://github.com/redhat-developer/rh-che/blob/fe214adca6902bf830260433201ca6b0ad876207/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/tenantdata/TenantDataProvider.java#L75

At the same time, I can see a noticeable increase in workspace stop failures.
Kibina logs: https://logs.dsaas.openshift.com/goto/a55ac0a51b448a7793e9f756379b5f15

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [X] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
Closing as outdated
