### ISSUE TITLE
Verify workspace-start-tests are working correctly

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1660]
**Description:**
It seems that data gathered from `workspace-start-tests` are not consistent. The consistency problem seems to be not only between Zabbix and Grafana, but even between different Zabbix charts.

1. It seems that data in Zabbix differs a lot from data in Grafana
Zabbix (e.g. cluster 3):
![Screenshot from 2019-10-16 15-17-40](https://user-images.githubusercontent.com/29278800/66922838-257fc780-f028-11e9-807e-9ac80b35f228.png)

Grafana:
![Screenshot from 2019-10-16 15-18-24](https://user-images.githubusercontent.com/29278800/66922897-39c3c480-f028-11e9-8550-2e0a74469c9a.png)

2. The soft-fail seems to be set to 5 sec but the data in the chart are not corresponding.
![Screenshot from 2019-10-16 15-16-05](https://user-images.githubusercontent.com/29278800/66922746-f406fc00-f027-11e9-9b78-680eb7c29604.png)

**Comment by ibuziuk** [comment]
@Katka92 should we close it as outdated? I believe we need to re-evaluate the tests if / when we would have a monitoring stack on osd

**Comment by Katka92** [comment]
Closing as outdated.
