### ISSUE TITLE
[Infra issue] Waiting for pod interrupted

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1666]
A workspace failed to start. Following message was shown in a UI:

`Error: Failed to run the workspace: "Waiting for pod 
'workspacefba43izc7hf5uvka.maven-75869c6948-d8vhz' was interrupted" `

Seen on cluster 2 when starting Java Vert.x stack: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1619/console

**Comment by ibuziuk** [comment]
is it still actual?

**Comment by Katka92** [comment]
It wasn't seen for 21 days now. Closing.
