### ISSUE TITLE
[Test issue] README pops up and steals focus

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1667]
From time to time we can see in tests that README is opened and it steals focus, so the action that is taking place fails. That can result in other different failures.
E.g.: When README pops up when LS is tested, all LS related tests fail. 

Seen on cluster 2a: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1408/console

Hint: The pop-up of README is usually caused when the workspace is refreshed. A possible solution for that can be removing all refreshing methods, as it is not the expected user behavior.

**Comment by Katka92** [comment]
Seen 2x on 1a.

**Comment by ibuziuk** [comment]
do we have an upstream issue for that. This is not Hosted Che specific I suppose

**Comment by Katka92** [comment]
I am not sure it is an upstream issue, because they don't have problems with that while running tests. But it was not seen for ~2 weeks, which is a time we updated to 7.3.1. I think we can close it as it is not reproducible now.

**Comment by Katka92** [comment]
Seen again on cluster 2 when testing Suggestion invoking. There is already a workaround implemented that waits for README when IDE is loading. There is no check of README when testing LS because it is a quite long time from IDE loaded and README should not pop-up.
![image](https://user-images.githubusercontent.com/29278800/69036110-79921900-09e5-11ea-9297-90c12e66cce7.png)

**Comment by Katka92** [comment]
Not reproduced for 23 days. Closing.
