### ISSUE TITLE
Reduce time of PR check

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1669]
When PR check fails to deploy Postgres or Rh-Che, it is still waiting until timeout. Would it be possible to end it directly when a `Progressing` is `False`?

Example from console logs:
```
...
[0;38;5;60mPostgres status: Available:[0;1m"False" [0;38;5;60mProgressing:[0;1m"Unknown" [0;38;5;60mTimeout:[0;1m146[0m
[0;38;5;60mPostgres status: Available:[0;1m"False" [0;38;5;60mProgressing:[0;1m"False" [0;38;5;60mTimeout:[0;1m145[0m
...
```

**Comment by ibuziuk** [comment]
@Katka92 is it still relevant?

**Comment by Katka92** [comment]
I guess yes.

**Comment by ibuziuk** [comment]
@Katka92 what is the plan with this issue? If it is P2 I guess it will never get attention and we can simply close it wdyt?

**Comment by Katka92** [comment]
I placed it as a P2 as it is not blocking us now, because the development in this repo is low. But I would not close that, the priority of this issue may change after some time.

**Comment by Katka92** [comment]
Closing this issue in favour of https://github.com/eclipse/che/issues/16679
