### ISSUE TITLE
Test 7.3.1 on prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1676]
**Description:**
Go manually through all stacks on prod-preview version 7.3.1 to verify that all are working correctly. Once it is done, give approve for pushing 7.3.1 to production.

**Comment by Katka92** [comment]
**ASP. NET Core Web Application**
The project is not able to build. The `install Cake` command finishes successfully, but build command fails with this error:
```
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(169,5): error MSB3027: Could not copy "/home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.2.7/runtimes/linux-x64/lib/netcoreapp2.2/System.Data.Common.dll" to "/projects/aspnetcore-example/publish/System.Data.Common.dll". Exceeded retry count of 10. Failed.  [/projects/aspnetcore-example/src/Conduit/Conduit.csproj] 
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(169,5): error MSB3021: Unable to copy file "/home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.2.7/runtimes/linux-x64/lib/netcoreapp2.2/System.Data.Common.dll" to "/projects/aspnetcore-example/publish/System.Data.Common.dll". Disk quota exceeded [/projects/aspnetcore-example/src/Conduit/Conduit.csproj]
```

**Comment by ScrewTSW** [comment]
# NodeJS MongoDB
This workspace experiences a small issue where the YAML files syntax highlighting doesn't work.
Probably missing/misconfigured XML language server?

**Comment by ScrewTSW** [comment]
# Python Django
The build steps work correctly, however the open URL commands point to a non existing location.
The index from the base folder is probably missing `/`

```
Performing system checks...

System check identified no issues (0 silenced).
October 31, 2019 - 08:15:20
Django version 1.10.5, using settings 'conduit.settings'
Starting development server at http://0.0.0.0:7000/
Quit the server with CONTROL-C.
Not Found: /
[31/Oct/2019 08:15:23] "GET / HTTP/1.1" 404 2290
Not Found: /
[31/Oct/2019 08:15:30] "GET / HTTP/1.1" 404 2290
```

**Comment by Katka92** [comment]
@ibuziuk I can create issues upstream, but I'm not sure about `disk quota exceeded` one - it seems more like Hosted Che issue. I tried to run locally (currently I have 7.4.0-SNAPSHOT but I don't think it is such a difference) and build succeeded.
