### ISSUE TITLE
"oandriie" account on the che.openshift.io was recreated.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [redhat-developer/rh-che#1677]
Placeholder for openshiftio/openshift.io#
My account 'oandriie' on the che.openshift.io was recreated. And currently I have 1 Gb(earlier was 3Gb) and I don't have access to the che.openshift web console.

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr https://api.openshift.io/api/users/0086d9d1-7541-42bd-ba49-f9caa243df9f

Could you login and provide screenshots from https://api.starter-us-east-2.openshift.com/ ?
do you have a `*-che` namepsace?

**Comment by AndrienkoAleksandr** [comment]
> do you have a *-che namepsace?

Yes, I do:

![screenshot-console](https://user-images.githubusercontent.com/6873095/68746800-044bd000-0602-11ea-92c3-b0b8fdb7263f.png)

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr ok so you have all setup correctly, Could you login with the `oandriie@redhat.com` email to che.openshift.io ?

**Comment by AndrienkoAleksandr** [comment]
@AndrienkoAleksandr ok so you have all setup correctly, Could you login with the oandriie@redhat.com email to che.openshift.io ?

Yes, I do.

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr ok, can we close the issue in this case ? :-)

**Comment by AndrienkoAleksandr** [comment]
Yes, sorry.
