### ISSUE TITLE
[Che Issue] Authorization token missing during test run

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1678]
Authorization token became missing during test run.

![image](https://user-images.githubusercontent.com/16451875/68023673-2b241100-fca8-11e9-83cc-567d5cafcfa6.png)

When tests opened workspaces dashboard to delete a workspace the missing auth token error appeared

Possibly related to #1572

**Comment by ScrewTSW** [comment]
Issue happened on production `1a` cluster
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/1464/consoleFull

**Comment by ScrewTSW** [comment]
Happened today again on `1a`

**Comment by ScrewTSW** [comment]
Happened once at `2a-prod-preview`

**Comment by Katka92** [comment]
Seen again on prod-preview 2a cluster. Maybe it can be related to the rollout update that happened this day. https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1788/console

**Comment by ScrewTSW** [comment]
Happened on Prod 1a during workspace stopping
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/1599/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x after login: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1850/consoleFull
Seen on cluster 2a 1x when returning from IDE to Dashboard: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1641/consoleFull
Seen on 1a 1x.

**Comment by Katka92** [comment]
Seen again on cluster 2 1x when returning from IDE to Dashboard https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1876/console
Seen on prod-preview 2a - after login there was `Application is not available`, after refresh the `Authorization token is misssed`.

**Comment by Katka92** [comment]
Seen on cluster 2 1x.

**Comment by Katka92** [comment]
Seen right after login:
1x on cluster 2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1682/console
1x on cluster 1a
1x on cluster 1b
2x on cluster 2a prod-preview

Seen when switching to Dashboard to stop the workspace:
2x on cluster 2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1685/console
1x on cluster 1a
1x on cluster 1b

**Comment by Katka92** [comment]
Seen again on cluster 2a productoin 2x, cluster 1b 1x, prod-preview cluster 2a 2x.

**Comment by Katka92** [comment]
Seen again on cluster 2 2x, 2x on cluster 1a, 1x on cluster 1b, 1x prod-preview cluster 2a.

**Comment by ScrewTSW** [comment]
Seen once at prod cluster 1b
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1857/console

**Comment by Katka92** [comment]
Seen again on cluster 2 1x, cluster 1a 2x, cluster 1b 2x.
Seen again on prod-preview 1x with different style (see image, link to job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2113/console). 
![image](https://user-images.githubusercontent.com/29278800/72245552-23121700-35f1-11ea-879b-05743a8925ed.png)

**Comment by ScrewTSW** [comment]
Seen again on production 2: x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2140/consoleFull
on production 1b: x2
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1928/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1935/console - appeared after login, messed up the tests at the beginning, second test went fine.
on prod-preview 2a: x2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2148/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2154/console

**Comment by ScrewTSW** [comment]
Seen again on production2: x2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2175/console x2
cluster production1a: x2
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/1964/console - failed twice while trying to stop the workspace (opening Dashboard)

**Comment by Katka92** [comment]
Seen again on production cluster 2 after login 2x and when refreshing dashboard during workspace deletion 1x. 
Seen again on cluster 2a production when going to the dashboard to stop the workspace 1x.
Seen again on cluster 1a after login 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1986/console

**Comment by Katka92** [comment]
Seen again right after a login on cluster 2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2217/console

**Comment by ScrewTSW** [comment]
user became unauthorized during workspace deletion
seen on production cluster 2 x3
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2237/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2231/console
production cluster 2a x2
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2028/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2027/console
production cluster 1a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2028/console
production cluster 1b x3
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2025/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2024/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2009/console
prod-preview cluster 2a x2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2232/console

**Comment by Katka92** [comment]
Seen again on cluster 2, 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2257/console

**Comment by Katka92** [comment]
Seen again on 1b cluster 1x.

**Comment by Katka92** [comment]
Seen again on cluster 2 2x, production cluster 2a 3x, cluster 1a 5x, cluster 1b 2x, prod-preview cluster 2a 4x.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2299/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2323/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2342/console
on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2341/console

**Comment by Katka92** [comment]
Seen on production cluster 2 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2354/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2364/console

Seen on production cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2143/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2144/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2153/console

Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1A/2153/console

Seen on cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2143/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2151/console

**Comment by Katka92** [comment]
Seen on 1b 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2170/console

**Comment by Katka92** [comment]
Seen on cluster 2a production 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2173/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2396/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2185/consoleFull
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2196/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2192/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2193/console

**Comment by ScrewTSW** [comment]
We are seeing this issue with a new face:
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2425/e2e_report/report/Java_Vert.x_test_Stopping_and_deleting_the_workspace_Stop_workspace/screenshot-Stop_workspace.png

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2425/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2214/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2447/consoleFull
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2448/console
Seen on production cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2227/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2237/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2227/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2448/console

**Comment by Katka92** [comment]
Seen on production cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2467/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2279/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2279/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2476/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2510/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2299/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2513/console

**Comment by Katka92** [comment]
Seen again on cluster 2 4x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2522/consoleFull
Seen again on prod-preview cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2532/consoleFull

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2574/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2362/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2362/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2360/consoleFull
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2574/consoleFull

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2382/consoleFull
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2382/consoleFull

**Comment by Katka92** [comment]
Seen again on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2404/console
Seen again on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2404/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2405/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2403/console
Seen on prod-preview cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2616/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2624/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2424/console

**Comment by ScrewTSW** [comment]
The issue has new face once again:
![image](https://user-images.githubusercontent.com/16451875/79325497-8e7dc480-7f11-11ea-8feb-5c530a6bbffc.png)

Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2649/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2657/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2446/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2436/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2453/console

**Comment by Katka92** [comment]
Seen again on production cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2700/console
Seen again - user even can not login correctly to cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2489/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2742/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2743/console

**Comment by Katka92** [comment]
Seen on prod cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2572/console
Seen on prod cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2563/console
Seen on prod 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2555/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2570/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2768/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2826/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2605/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2612/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2634/console
on production cluster 1b x1:
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2632/e2e_report/report/

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2858/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2647/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2654/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2868/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2909/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2699/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2696/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2910/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2718/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2740/console

**Comment by Katka92** [comment]
Seen on cluster 1b 1x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2758/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2984/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2771/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2985/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2793/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3022/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3035/console
Seen on production cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2815/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2824/console
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2815/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2824/console
Seen on cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2807/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2822/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3028/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2844/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2857/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3078/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3120/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3120/console
