### ISSUE TITLE
Improve workspace start/stop reports

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1680]
**Description:**
The **Che QE bot** is nicely reporting the workspace start/stop times [1] every day. Due to logic for labeling tests are green/red we have the whole report marked as red almost every day even if there is no problem wit workspace start/stop times.

**Current state: **
The threshold for the test to be green/red is set by percentage (currently set to 5%). This is quite misleading nowadays because times are quite stable so even the small change is counted as a high percentage. That's why we are having all reports red even there is no problem with workspace start/stops. 

**Possible solutions:**
1) Remove color labels so everyone can watch exact times and make own picture about how good/bad the start/stop times are.
2) Adjusting the algorithm for labeling gathered times as red/green. Maybe that would be suitable for us to set seconds as a threshold, not a percentage. 

[1] 
![Screenshot from 2019-11-05 13-46-37](https://user-images.githubusercontent.com/29278800/68208991-b9630480-ffd2-11e9-9c85-f49ec4153966.png)

**Comment by amisevsk** [comment]
One approach that may make more sense now that the timing has settled down is to just specify explicit cutoffs. E.g. for start, avg <35 seconds is green, 35-45 seconds is yellow, >45 seconds is red. These could be adjusted as we bring start times down (to reflect what we expect our performance to be).

**Comment by amisevsk** [comment]
One approach that may make more sense now that the timing has settled down is to just specify explicit cutoffs. E.g. for start, avg <35 seconds is green, 35-45 seconds is yellow, >45 seconds is red. These could be adjusted as we bring start times down (to reflect what we expect our performance to be).

**Comment by amisevsk** [comment]
One approach that may make more sense now that the timing has settled down is to just specify explicit cutoffs. E.g. for start, avg <35 seconds is green, 35-45 seconds is yellow, >45 seconds is red. These could be adjusted as we bring start times down (to reflect what we expect our performance to be).

**Comment by ScrewTSW** [comment]
![Screenshot_20200109_094004](https://user-images.githubusercontent.com/16451875/72054114-aa494d00-32c8-11ea-931a-7362ede533e5.png)

Current updated layout.
Working on cleaning up the code and then I'll submit a PR
