### ISSUE TITLE
Implement "getting started" devfiles test suite

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1684]
We need to be testing the getting started devfiles regularly as well, not only the registries.

We should implement a separate suite and a job to accomplish this.

This was also referenced in https://github.com/redhat-developer/rh-che/pull/1679#pullrequestreview-310900556

**Comment by ibuziuk** [comment]
Closed in favor of https://github.com/eclipse/che/issues/15244
