### ISSUE TITLE
[Test issue] Maven build timeout

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1697]
**Description:**
Maven build in a test for Java Maven stack reached timeout. 
![image](https://user-images.githubusercontent.com/29278800/69035344-ba892e00-09e3-11ea-85b0-1281df27f559.png)

For now, seen once on 1b: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1561/console

**Comment by Katka92** [comment]
Seen again 1x on 1b.

**Comment by Katka92** [comment]
Seen again 3x on 1b. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1632/console

**Comment by Katka92** [comment]
Seen again on 1b 2x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1651/console

**Comment by Katka92** [comment]
Seen again 2x on 2a production

**Comment by Katka92** [comment]
Seen again 2x on cluster 1b.

**Comment by Katka92** [comment]
Seen again on cluster 2a 1x, cluster 1b 1x.

**Comment by Katka92** [comment]
Seen again on 1b 1x.

**Comment by Katka92** [comment]
Seen again on cluster 1b 3x.

**Comment by Katka92** [comment]
Seen again on 1b 4x.

**Comment by Katka92** [comment]
Seen again 1x on production 2a cluster, 1x on cluster 1b.

**Comment by Katka92** [comment]
Seen again on production 2a cluster 1x.

**Comment by ScrewTSW** [comment]
Seen again on production 1b cluster 1x.
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1847/console

**Comment by ScrewTSW** [comment]
Seen on prod cluster 2a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/1869/console

**Comment by ScrewTSW** [comment]
seen again on production 1b x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1880/console

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 what is the timeout for mvn build atm? Can we consider increasing it? build time depends on the central state which we can not affect

**Comment by Katka92** [comment]
@ibuziuk It is set to 120000 seconds. Do you think it is not enough? We can increase that, but I would do the change in upstream, so we don't need to override code on our side. That would mean that we will get that fix next release.

**Comment by Katka92** [comment]
Seen again on production 2a cluster 3x, cluster 1b 3x.

**Comment by Katka92** [comment]
Seen again on 1b 1x

**Comment by ScrewTSW** [comment]
Seen on 1b x1 https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1941/console

**Comment by Katka92** [comment]
Maven build test timeouts, but the console seems like it didn't even start.
![image](https://user-images.githubusercontent.com/29278800/76504679-73b6bc80-6448-11ea-893f-763fc5c6f917.png)

Seen on 1a 1x.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2254/console

**Comment by Katka92** [comment]
Not seen for a long time. Closing.

**Comment by Katka92** [comment]
Maven build failed on cluster 1a, but currently, we don't have screencast, so we're not able to tell if it didn't start or if the terminal was reset. 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2474/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2475/console

**Comment by Katka92** [comment]
Maven build timeouted or was not started on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2510/console

**Comment by Katka92** [comment]
Not seen for three weeks. Closing.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3404/console
