### ISSUE TITLE
Workspace stopped unexpectadly

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1703]
**Description:**
Running task failed with `Error resolving task 'maven build': Error: Workspace is not running.`. Seems like the workspace was quit unexpectedly and pods remain running so user is not able to run any workspace now.

Screenshot:
![image](https://user-images.githubusercontent.com/29278800/69218920-08cc3780-0b72-11ea-91b4-5f2fc8a7ee10.png)

Kibana logs:
![Screenshot from 2019-11-20 08-47-10](https://user-images.githubusercontent.com/29278800/69219105-695b7480-0b72-11ea-8c35-381f42be4c88.png)

job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1573/console

**Comment by ibuziuk** [comment]
can we get openshift event when this happens again ?

**Comment by Katka92** [comment]
We have events archived, fortunately. Here they are: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/1573/events_report.txt
I think that this issue is related to the update to 7.3.2 so that workspace was killed by that. Is this possible?

**Comment by Katka92** [comment]
Not reproduced for 20 days. Closing.
