### ISSUE TITLE
Update project build test logic according to upstream changes

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1710]
Sometimes it happens, that the project build test times out even though the build has been a success. We need to update our logic on how we detect project build status.

**Comment by ScrewTSW** [comment]
in another case, the build was too slow and the part of the tests failedhttps://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1597/console

**Comment by ScrewTSW** [comment]
And another case where the successful build was detected incorrectly
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1604/console

**Comment by ScrewTSW** [comment]
Project build too slow seen again on `production 1b`
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1612/console

**Comment by ScrewTSW** [comment]
seen again on `production 2` x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1835/console
`production 2a` x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/1625/console
`production 1b` x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1623/console

**Comment by Katka92** [comment]
We have another issue for tracing maven build timeouts [1]. 
The test was moved to upstream [2] and will be removed from downstream in the next release. If the issue will still be present, we can create a new issue for changing the approach to check the successful maven build. 

[1]  https://github.com/redhat-developer/rh-che/issues/1697
[2]  https://github.com/eclipse/che/pull/15545
