### ISSUE TITLE
Finalize and complete CI for the new `che-incubator/che-workspace-telemetry-client` GH repo

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1712]
**Description:**

In this new repository [1], there is the definition of:
- A Java abstract implementation of the telemetry backed, as a Quarkus-based, OpenAPI-enabled, REST application library
- The corresponding Javascript client library, defined as a typescript-based library available as a JS NPM package. The model part of the client library is generated from the OpenApi schema provided by the Java implementation module.

There is a number of things to do here:
- Make the javascript library a part of the @che-incubator NPM org, instead of the personnal `@dfatwork-pkgs` organization, and complete the CI already started as GitHub actions, so that it would push a new NPM package on each commit to master
- Add basic tests to the Java implementation
- Allow pushing to Maven (either Main maven repo, or the GitHub Maven repository since this artifact would only be used in limited, identified contexts for now) 
 
 [1] https://github.com/che-incubator/che-workspace-telemetry-client

**Comment by tomgeorge** [comment]
che-workspace-telemetry client is FINALLY publishing NPM and Maven packages :tada:

**Comment by ibuziuk** [comment]
@tomgeorge @davidfestal once https://github.com/che-incubator/che-workspace-telemetry-client/pull/6 is merged can we close this issue ?

**Comment by tomgeorge** [comment]
Yes, I think so
