### ISSUE TITLE
Plug basic events (commit, save file, etc ...) to submit to the new telemetry API

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1713]
**Description:**

The telemetry plugin should track the events:
- push,
- edit file,
- commit file
 that were already tracked in Che 6 inside Theia, and submit corresponding events to the telemetry API.

Also it should also probably plug into the activity tracker che-theia extension in order to regularly sent `activity` notifications

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/15469
