### ISSUE TITLE
[Infra issue] Issues related to ci.centos.org

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1715]
**Description:**
Docker installation fails - see the logs below. Other dependencies are already installed there so for me it seems that the environment given is not cleaned before given to the new job.

<details><summary>First failure</summary>
<p>

***** Installing dependencies for functional tests Mon Dec  2 06:57:27 GMT 2019 ******
Installing dependencies...
* epel: mirror.ci.centos.org
epel/x86_64                            Extra Packages for Enterprise Linu 13,483
Epel already installed, skipping instalation.
Package jq-1.5-1.el7.x86_64 already installed and latest version
Package yum-utils-1.1.31-52.el7.noarch already installed and latest version
Package device-mapper-persistent-data-0.8.5-1.el7.x86_64 already installed and latest version
Package 7:lvm2-2.02.185-2.el7_7.2.x86_64 already installed and latest version
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
Error: docker-ce-cli conflicts with 2:docker-1.13.1-103.git7f2769b.el7.centos.x86_64
Error: docker-ce conflicts with 2:docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Connection to 172.19.3.76 closed. 

</p>
</details>

<details><summary>Second failure</summary>
<p>
***** Installing dependencies for functional tests Sat Nov 30 12:01:00 GMT 2019 ******
Installing dependencies...

* epel: mirror.ci.centos.org
epel                               Extra Packages for Enterprise Linux 6  12,578
Epel already installed, skipping instalation.
Package jq-1.3-2.el6.x86_64 already installed and latest version
Package yum-utils-1.1.30-42.el6_10.noarch already installed and latest version
Package device-mapper-persistent-data-0.6.2-0.2.rc7.el6.x86_64 already installed and latest version
Package lvm2-2.02.143-12.el6_9.1.x86_64 already installed and latest version
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo

docker-ce.repo                                           | 2.4 kB     00:00     
repo saved to /etc/yum.repos.d/docker-ce.repo
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: libseccomp >= 2.3
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: systemd
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: libsystemd.so.0()(64bit)
Error: Package: containerd.io-1.2.10-3.2.el7.x86_64 (docker-ce-stable)
           Requires: systemd
Error: Package: containerd.io-1.2.10-3.2.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: 3:docker-ce-19.03.5-3.el7.x86_64 (docker-ce-stable)
           Requires: libseccomp.so.2()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Connection to 172.19.3.126 closed.
</p>
</details>

<details><summary>Third failure</summary>
<p>
***** Installing dependencies for functional tests Mon Dec  2 02:11:18 GMT 2019 ******
Installing dependencies...

 * epel: mirror.ci.centos.org
epel/x86_64                              Extra Packages for Enterprise Li 13,483
Epel already installed, skipping instalation.
Package jq-1.5-1.el7.x86_64 already installed and latest version
Package yum-utils-1.1.31-52.el7.noarch already installed and latest version
Package device-mapper-persistent-data-0.8.5-1.el7.x86_64 already installed and latest version
Package 7:lvm2-2.02.185-2.el7_7.2.x86_64 already installed and latest version
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
Package 3:docker-ce-19.03.5-3.el7.x86_64 already installed and latest version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
oc
mkdir: cannot create directory ‘logs’: File exists
Connection to 172.19.3.94 closed.
</p>
</details>

Job with the first failure: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1861/console
Job with the second failure: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1638/console

**Comment by Katka92** [comment]
Unexpected error when installing Docker. May be caused by a weak internet connection. Seen on prod-preview 2a cluster.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1868/console

**Comment by Katka92** [comment]
On cluster 1a test failed during installing dependencies on `gzip: stdin: unexpected end of file`. It seems like a networking issue.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1674/console

**Comment by Katka92** [comment]
On cluster 2a production, 1x failed on 
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
```
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1704/console

**Comment by Katka92** [comment]
`No space left on device` when cloning the project.
Cluster 2 3x
Cluster 1a 3x
Cluster 1b 2x
Cluster 2a prod-preview 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1921/console

Cluster 2a 1x:
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
```
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1710/console

Error while cloning repo cluster prod-preview 2a 1x
`
Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from slave04.ci.centos.org/172.19.4.20:47554
`
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1921/console

**Comment by Katka92** [comment]
Error during installing and starting docker `Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`.
Seen once on production 2a cluster.

**Comment by Katka92** [comment]
Can not get node - happened for all tests between 22 and 23 PM UTC.

**Comment by Katka92** [comment]
Error during installing dependencies `gzip: stdin: unexpected end of file`. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1925/console

**Comment by Katka92** [comment]
Error during docker pull: `docker: received unexpected HTTP status: 500 Internal Server Error.`. https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1985/console

Error during getting version from pom `scl: command not found`. It seems like a dirty node. 2x on 2a production and 1x on 1a. 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1986/console

Failed to install docker `gzip: stdin: unexpected end of file`. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1980/console

Dirty node for 2a production tests - files already exists 2x and 1b 1x, prod-preview 2a 1x.

**Comment by Katka92** [comment]
Error during getting the version from pom `scl: command not found`. 1x on prod-preview 2a cluster.

**Comment by Katka92** [comment]
Error during getting the version from pom `scl: command not found`. 1x on cluster 2, 1x on production cluster 2a, 1x on prod-preview cluster 2a.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2216/console

**Comment by ScrewTSW** [comment]
Tests sometimes fail with `docker: invalid reference format.`

Seen on cluster prod 2 x3
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2230/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2224/console
cluster prod 2a x2
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2019/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2013/console
cluster prod 1a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2014/console
cluster prod 1b x4
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2018/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2012/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2011/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2010/console
cluster prod-preview 2a x3
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2226/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2223/console

**Comment by Katka92** [comment]
Error during installing epel. Seen 1x on production 2.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2250/console
Seen 1x on prod 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2038/console
Seen 1x on prod 1b
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2036/console

**Comment by Katka92** [comment]
Error during getting version from pom.xml: `scl: command not found`. Seen on cluster 2 2x, production cluster 2a 1x, cluster 1a 1x, cluster 1b 3x, prod-preview cluster 2a 1x. 

Error during installing epel cluster 1b 1x.

**Comment by ScrewTSW** [comment]
Seen again on prod-preview 2a cluster x1 - docker: invalid reference format
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2300/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2314/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2321/console
on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2103/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2111/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2315/console

**Comment by ibuziuk** [comment]
@ScrewTSW was the issue reported to centos CI ?

**Comment by ScrewTSW** [comment]
@ibuziuk it was reported a longer time ago to the `ci-users` mailing list with name `Dirty Nodes`

**Comment by ibuziuk** [comment]
@ScrewTSW ok, if it is not fixed let's report it one more time

**Comment by Katka92** [comment]
Error during installing dependencies: `gzip: stdin: unexpected end of file` 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2148/console

Error during getting version from pom: `scl: command not found` 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2143/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2142/console

**Comment by Katka92** [comment]
Error during getting version from pom: `scl: command not found` 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2384/console

**Comment by Katka92** [comment]
Error during getting the version from pom: `scl: command not found` 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2384/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2407/console

**Comment by ScrewTSW** [comment]
![Screenshot_20200305_102056](https://user-images.githubusercontent.com/16451875/75966809-3a6fd100-5ecb-11ea-8e3b-55d3a9c4dd36.png)

Seen networking issue with installation of dependencies

**Comment by ScrewTSW** [comment]
Seen scl and docker problem again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2212/console

**Comment by ScrewTSW** [comment]
Scl and Docker issue seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2215/console

**Comment by Katka92** [comment]
`scl: command not found` on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2438/console
`scl: command not found` on prod cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2228/console
`scl: command not found` on prod cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2226/console

**Comment by Katka92** [comment]
`scl: command not found` seen on production 1b 1x, prod-preview 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2244/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2458/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2490/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2293/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2507/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2301/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2301/console

**Comment by Katka92** [comment]
@ScrewTSW It would be nice if you could copy the reason of error to the comment so it is more clear.

**Comment by Katka92** [comment]
`scl: command not found` seen again on cluster 2a production 1x, cluster 1a 2x

**Comment by Katka92** [comment]
Can not get node: `'cico node get' failed, trying again in 60s`, `giving up on 'cico node get'`
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2541/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2328/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2542/console

`scl: command not found` seen on 1b cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2332/console

**Comment by Katka92** [comment]
`scl: command not found` on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2340/console
on 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2338/console
on prod-preview 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2552/console

**Comment by ibuziuk** [comment]
@Katka92 could you please raise it on the mailing list. Looks like this issue happens quite often

**Comment by Katka92** [comment]
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Seen once on the production cluster 2a

`scl: command not found` seen on 1a and 1b again (it is probably not ci.centos.org issue, we should fix it on our side).

**Comment by Katka92** [comment]
`scl: command not found` on 1a and 1b cluster 1x, on prod-preview 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2413/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2412/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2625/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2626/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2446/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2649/console

**Comment by Katka92** [comment]
```
FATAL: could not log in into vault
java.io.EOFException: SSL peer shut down incorrectly
```
Seen once on cluster 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2495/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2728/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2517/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2531/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2530/console
on production cluster 1b x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2519/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2528/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2529/console
on production cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2733/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2742/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2535/console

**Comment by Katka92** [comment]
`scl: command not found` seen again on cluster 2 1x, 2a 1x, 1a 1x, 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2767/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2556/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2556/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2554/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2561/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2603/console
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2817/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2827/console

installation of docker-ce failed on production cluster 1b x1:
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2614/console

**Comment by Katka92** [comment]
`scl: command not found`
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2868/console
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2657/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2656/console
Seen on cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2645/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2655/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2869/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2689/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2699/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2687/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2697/console
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2901/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2911/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2917/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2913/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2929/console

**Comment by ScrewTSW** [comment]
`scl: command not found` seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2930/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2931/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2720/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2720/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2718/console
on prod-preview 2a x2:
|https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2931/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2932/console

**Comment by ScrewTSW** [comment]
```
GPG key retrieval failed: [Errno 12] Timeout on https://download.docker.com/linux/centos/gpg: (28, 'Operation timed out after 30001 milliseconds with 0 out of 0 bytes received')
```
seen on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2720/console

**Comment by Katka92** [comment]
Failed to pull test image
on production 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2937/console

Can not get version `slc: command not found` 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2731/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2740/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2731/console

**Comment by Katka92** [comment]
`scl: command not found`
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2756/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2756/console

**Comment by Katka92** [comment]
`scl:commad not found`
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2763/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2760/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2975/console

**Comment by ScrewTSW** [comment]
`scl: command not found` Seen agian on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2993/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2780/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2994/console

**Comment by ScrewTSW** [comment]
`scl: command not found` Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2786/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2786/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3002/console

**Comment by ScrewTSW** [comment]
Hello. `scl: command not found` has been fixed as part of https://github.com/eclipse/che/issues/17052
I am closing this issue and opening relevant sub-issues for the problems that still appear on `ci.centos.org` infra
