### ISSUE TITLE
[Test Issue] Can not get version from parent pom.xml

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1716]
**Description:**
Sometimes test fails because they can not get VERSION from parent pom.xml.

Log example:
```
****** Starting functional tests Sun Dec  1 02:45:34 GMT 2019 ******
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * ****
    ****-che

Using project "****".
Welcome! See 'oc help' to get started.
API_SERVER_URL=https://api.prod-preview.openshift.io
OPENSHIFT_URL=https://api.starter-us-east-2a.openshift.com/
User name printed in format: 3 first letters, space, the rest of letters.    osi o-ci-preview-testper
parse error: Invalid numeric literal at line 1, column 10
Running test with user **** against prod-preview environment with version .
docker: invalid reference format.
See 'docker run --help'.
Running functional tests lasted 13 seconds.
```

One of the jobs: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1855/console

**EDIT**

After some debugging and fixing, currently the output is:
```
User name printed in format: 3 first letters, space, the rest of letters.    osi otest2aprod2
Unable to open /etc/scl/conf/rh-maven33!

parse error: Invalid numeric literal at line 1, column 10
Running test with user **** against prod environment with version .
```
So it seems that currently the culprit is wrongly installed rh-maven33.

**Comment by Katka92** [comment]
Seen again on cluster 2a production and on 2a prod-preview.

**Comment by Katka92** [comment]
Seen again on cluster 2 3x, cluster 2a 4x, cluster 1a 2x, cluster 1b 3x, cluster 2a prod-preview 2x

**Comment by Katka92** [comment]
Seen again on cluster 2 3x, cluster 2a production 2x, cluster 1a 2x, cluster 1b 1x

**Comment by Katka92** [comment]
Seen again on prod-preview 2a cluster 1x. https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2048/console

**Comment by ibuziuk** [comment]
@Katka92 could you clarify how the version of the parent pom is obtained?

**Comment by Katka92** [comment]
@ibuziuk Here is a function: https://github.com/redhat-developer/rh-che/blob/master/.ci/functional_tests_utils.sh#L121
It uses maven to extract this item. Currently, I'm not sure what can be the root cause. I plan to add more debug output here.

**Comment by ibuziuk** [comment]
@Katka92 sent a PR for adding the logs with mvn version - https://github.com/redhat-developer/rh-che/pull/1746

**Comment by ScrewTSW** [comment]
Happened twice on production 2 cluster
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/2057/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/2069/console
and once on production 1b cluster
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1843/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/1878/console

**Comment by Katka92** [comment]
Seen again on cluster 2 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2112/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2: x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/2174/console
production cluster 1b: x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/1962/console

**Comment by Katka92** [comment]
Reports of this issue went to https://github.com/redhat-developer/rh-che/issues/1715 Closing.

**Comment by Katka92** [comment]
Seen on production 2a cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2825/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2825/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3036/console

**Comment by Katka92** [comment]
Seen on cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2837/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2834/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2832/console

**Comment by Katka92** [comment]
Seen on cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2840/console

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please prioritize the issue for the next sprint?

**Comment by Katka92** [comment]
Seen on cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2844/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2846/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2849/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2849/console

**Comment by ScrewTSW** [comment]
I believe these two issues are related https://github.com/redhat-developer/rh-che/issues/1914 maybe we could merge them

**Comment by ScrewTSW** [comment]
```
Unable to open /etc/scl/conf/rh-maven33!

error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
parse error: Invalid numeric literal at line 1, column 10
```
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3063/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3077/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2852/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2857/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2850/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3064/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3097/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2908/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2907/console
Installation error on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3121/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3122/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2911/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2911/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3122/console

**Comment by ibuziuk** [comment]
@ScrewTSW should we close the issue, or do you plan to keep monitoring?

**Comment by Katka92** [comment]
@ibuziuk We usually close the issues when they are not reproduced for ~2 weeks. I'll close this one next week if it will not be reproduced if you're OK with that.

**Comment by ibuziuk** [comment]
@Katka92 time to close?

**Comment by Katka92** [comment]
Sure, closing :)
