### ISSUE TITLE
Strategy for automatically bumping the version of the backend-base telemetry client

### ISSUE THREAD

**Issue by tomgeorge** [redhat-developer/rh-che#1734]
**Description:**

This is a continuation of https://github.com/redhat-developer/rh-che/issues/1712.  Currently we do not have a way to automatically bump the version of the maven dependency, and deploy it to the GitHub package registry.  

My original thought was to use the [maven release plugin](https://maven.apache.org/maven-release/maven-release-plugin/examples/update-versions.html).  But that, unfortunately, only works to update SNAPSHOTS, and creates a release later.  GitHub packages do not support SNAPSHOT releases, so I am going to use the [maven versions plugin](https://www.mojohaus.org/versions-maven-plugin/) to update the backend-base release version, and add a commit/push to the GH action. 

Regardless, this updating of the dependency will require us to push back to the GH repo.  After talking to @davidfestal it may be a good idea to invest in pushing these artifacts to maven central, to leverage the release plugin, and to allow for SNAPSHOT releases.

**Comment by tomgeorge** [comment]
cc @ibuziuk

**Comment by tomgeorge** [comment]
Update: the maven versions plugin will not allow you to set an arbitrary property value.  So if I ask the plugin to replace the value of `backend-base-version` to `0.0.7`, it will fail, because a release of `0.0.7` does not exist yet.  So it seems like our best bet is to run a shell command to auto-increment the version :(

**Comment by davidfestal** [comment]
@benoitf is there another alternative to store the maven artifacts apart from maven central ?

**Comment by tomgeorge** [comment]
This work also needs to include pushing back for the NPM library
