### ISSUE TITLE
[Test Issue] Test can not click on STOP icon

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1744]
**Issue problem:** 
The test can not stop a running workspace from the Dashboard view. It fails on timeout.
![image](https://user-images.githubusercontent.com/29278800/71659967-c8073700-2d49-11ea-9769-143429f624c8.png)

Seen 2x on cluster 2, 1x on production cluster 2a and 3x on cluster 1b in the last three days.

**Comment by ibuziuk** [comment]
@Katka92 this looks like test issue, right? does it also reproducible against upstream?

**Comment by Katka92** [comment]
@ibuziuk For me, it seems more like a test issue, but I think I experienced that manually some time ago when I needed to click on that icon twice. I'll investigate further and do some manual testing. 
I think this is not experienced in nightly tests running with the same test suite against Che. @dmytro-ndp can you please verify?

**Comment by Katka92** [comment]
@ibuziuk According to upstream nightly tests, this issue is not reproduced with Che.

**Comment by Katka92** [comment]
Seen again on cluster 1a 1x, on cluster 1b 2x.

**Comment by ibuziuk** [comment]
@Katka92 can you repro this manually? looks like in our CI test it happens pretty often

**Comment by Katka92** [comment]
@ibuziuk I've just tried few times on cluster 2 manually and was not able to reproduce that. Maybe I'm too slow in comparison with an automated test. If this issue will persist during a weekend, maybe we can add a workaround on our side - to click on this icon again.

**Comment by ScrewTSW** [comment]
Seen today on production 2 x3
production 1a x2
production 1b x4

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 is it still the case after 7.7.1 update?

**Comment by Katka92** [comment]
The issue was not seen. Closing. cc @ScrewTSW

**Comment by ScrewTSW** [comment]
And the issue has come back on production 1b cluster once:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2126/console
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2126/e2e_report/report/Java_Vert.x_test_Stopping_and_deleting_the_workspace_Stop_workspace/screenshot-Stop_workspace.png

**Comment by Katka92** [comment]
Seen agaon in 1b cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2148/console

**Comment by Katka92** [comment]
Seen again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2367/console

Seen again on cluster 1b 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2155/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2157/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2153/console

**Comment by Katka92** [comment]
Seen on cluster 2 4x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2372/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2374/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2377/console

Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2164/console

**Comment by ibuziuk** [comment]
funny that this issue does not happen in the upstream :/

**Comment by Katka92** [comment]
Actually, the last few days, nightly tests on upstream are broken, so we don't have a data. But yes, before that, there were no such failures.

**Comment by Katka92** [comment]
One more thing just came on my mind - on upstream they are always creating new user, but our users have several workspaces (leftovers from runs where delete of a workspace failed). Maybe there can be some delay because of that, so the test for stopping the workspace fails. I removed those workspaces, we'll see if it will help. It seems that the number of workspaces and the number of failures can correlate.

Workspaces removed:
cluster 1a: 4 workspace
cluster 2a production: 7 workspaces
cluster 2: 16 workspaces
cluster 1b: 14 workspaces
cluster 2a prod-preview: 5 workspaces

**Comment by Katka92** [comment]
Seen again on cluster 2 2x, cluster 1a 1x, cluster 1b 2x

The removal of workspaces didn't help:
![image](https://user-images.githubusercontent.com/29278800/75420155-a5ebf880-5937-11ea-9df5-a4c2c09bc39a.png)

**Comment by ScrewTSW** [comment]
seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2203/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2269/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2273/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2292/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2714/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2503/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2504/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2510/console
Seen on production cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2510/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2732/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2738/console
on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2523/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2527/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2531/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2535/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2536/console

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 is the issue still relevant?

**Comment by Katka92** [comment]
The issue was not seen for 2 weeks. Closing.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3634/console
maybe just a glitch?

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3807/console
![image](https://user-images.githubusercontent.com/16451875/101493728-bcaf8900-3966-11eb-88cf-06e86ce1bdb5.png)

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 this seems to be a pretty rear / hard-to-repro issue - do we have anything similar in the upstream periodic tests when the stop button can not be pressed

**Comment by ScrewTSW** [comment]
@ibuziuk I don't believe I've seen it in upstream before and I haven't seen this issue for a while

**Comment by Katka92** [comment]
Well, the report that you linked here is not related to this issue. The issue is about the test that did not click on the stop icon button. In the report, you can see that test clicked on it correctly, but it took too long for the workspace to stop - the workspace was not stopped within 5 seconds (the timeout of the test). So it is even not a test issue.
@ScrewTSW please close this issue and report to the correct one.

**Comment by ScrewTSW** [comment]
> Well, the report that you linked here is not related to this issue. The issue is about the test that did not click on the stop icon button. In the report, you can see that test clicked on it correctly, but it took too long for the workspace to stop - the workspace was not stopped within 5 seconds (the timeout of the test). So it is even not a test issue.
> @ScrewTSW please close this issue and report to the correct one.

oh, do you think it's a timing issue then?

**Comment by Katka92** [comment]
Also in kibana, it's clear that stopping the workspace lasted longer than 5 sec. We have an agreement that stopping should not last longer than 5 sec, so it is more like a "product" issue I guess. If devs think that it's not a product issue and we should increase the timeout for the test, we can handle that, but from what I see in kibana, the average workspaces stop time is around 1 sec, the maximums are around 2 secs.

**Comment by ScrewTSW** [comment]
sorry, forgot to close for false report.
