### ISSUE TITLE
Figure out the location for "meta.yaml" for a new telemetry plugin (local plugin in che-theia)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1749]
**Description:**

Potentially the `meta.yaml` could be hosted together with the CDN files - static.developers.redhat.com
 
Related epic - https://github.com/redhat-developer/rh-che/issues/1714

**Comment by ibuziuk** [comment]
@tomgeorge can we close the issue? l suppose meta.yaml is already hosted on static.developers.redhat.com

**Comment by tomgeorge** [comment]
Yes, this can be closed
