### ISSUE TITLE
Compatibility check not creating PR

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1760]
If compatibility check fails on conflict (e.g. when trying to rebase) it should still create PR and send a comment here. Example of a failed job that didn't create/update PR: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/326/console

**Comment by ibuziuk** [comment]
@Katka92 this is fixed AFAIK. Can we close it?

**Comment by Katka92** [comment]
The fix was provided, I think we can close. Thank you
