### ISSUE TITLE
Ephemeral toggle sets to true when changing stack

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1777]
**Issue problem:** 
When user switched off Ephemeral toggle and then changes a stack, the toggle switch to true again.

**Red Hat Che version:** 
7.7.1b

**Reproduction Steps:**

1. Log in to che.openshift.io
2. Go to Workspaces -> Add Workspace
3. Turn off the Ephemeral mode
4. Choose different stack

![toggle](https://user-images.githubusercontent.com/29278800/73332881-6a8ed900-4268-11ea-9f46-57b7c4768074.gif)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
@Katka92 should be fixed on prod

**Comment by Katka92** [comment]
@ibuziuk Thank you, verified for prod and prod-preview. :) Closing.
