### ISSUE TITLE
setup CI for building che-workspace-telemetry-woopra-backend  image on quay.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1779]
**Description:**
Need to setup CI for building `che-workspace-telemetry-woopra-backend`  image on quay.io [1]:

Build instructions `docker build --build-arg GITHUB_USERNAME=username --build-arg GITHUB_PASSWORD=token -f src/main/docker/Dockerfile.multi`

GITHUB_USERNAME / GITHUB_PASSWORD should be stored on vault and available via Centos CI.

[1] https://quay.io/repository/openshiftio/che-workspace-telemetry-woopra-backend

**Comment by tomgeorge** [comment]
Should this CI process also include deploying the `meta.yaml` to static.developers.redhat.com?

**Comment by ibuziuk** [comment]
@tomgeorge no let's keep static.developers.redhat.com manual for now

**Comment by ibuziuk** [comment]
CI - https://ci.centos.org/view/Devtools/job/devtools-che-workspace-telemetry-woopra-backend-build-master/
image - https://quay.io/repository/openshiftio/che-workspace-telemetry-woopra-backend?tab=tags

**Comment by ibuziuk** [comment]
Once https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend/pull/12 is merged we can close the issue

**Comment by tomgeorge** [comment]
Merged redhat-developer/che-workspace-telemetry-woopra-backend#12
