### ISSUE TITLE
Add Javadoc in class `TokenController`

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#178]
The class `/che-keycloak-plugin-token-provider/src/main/java/com/redhat/che/keycloak/token/provider/contoller/TokenController.java` misses javadoc comments on the endpoint methods.

Just a reminder of PR comment https://github.com/redhat-developer/rh-che/pull/173#discussion_r126131357 that will finally be fixed in a new PR.

**Comment by sunix** [comment]
it can also be api docs available through swager

**Comment by amisevsk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Javadoc in class `TokenController`](https://trello.com/c/BX42JrwL/3-add-javadoc-in-class-tokencontroller)
