### ISSUE TITLE
[Infra issue] Pod sandbox changed on prod cluster 1b

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1782]
**Issue problem:** 
The workspace was not started during e2e periodic tests. This happened when starting Maven and Vert.x workspaces on cluster 1b.
There was an error in events saying `network: failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: connection refused]`. 

Events: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2004/events_report.txt

Job artifacts: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2004/console

Screen:
![image](https://user-images.githubusercontent.com/29278800/73518810-94c6cf00-43ff-11ea-95ee-870c964f656e.png)

**Red Hat Che version:** 
7.7.1b

**Comment by ScrewTSW** [comment]
Seen the same issue resulting to `Plugins installation process timed out`
![image](https://user-images.githubusercontent.com/16451875/73727212-4ed87680-4731-11ea-934c-2d6df39e17e9.png)

Seen today on production cluster 1b x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2030/consoleFull

**Comment by Katka92** [comment]
Seen again on cluster 1b 1x
![image](https://user-images.githubusercontent.com/29278800/73918674-55e2be80-48c2-11ea-82e5-9c24f4421b29.png)
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2040/consoleFull

**Comment by Katka92** [comment]
Seen again on cluster 1b 7x. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2052/console

**Comment by Katka92** [comment]
Seen again on cluster 1b 1x.

**Comment by ScrewTSW** [comment]
seen again on production cluster 1b x5:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2077/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2076/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2075/consoleFull
![image](https://user-images.githubusercontent.com/16451875/74332028-356ca580-4d95-11ea-93d1-441d278519ef.png)

**Comment by ScrewTSW** [comment]
Seen again on production 1b x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2082/consoleFull

**Comment by ibuziuk** [comment]
infra ticket has been created

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x5:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2091/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2090/consoleFull
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2089/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2087/console

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW can we close this issue?

**Comment by Katka92** [comment]
The issue was not observed for two weeks. Closing.
