### ISSUE TITLE
[Che issue] Plugin installation process timed out

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1783]
**Issue problem:** 

Java Maven workspace failed to start during e2e periodic tests because of `Plugin installation process timed out`.
There is an error in an events saying that `network: failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: connection refused]`.

Events: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2008/events_report.txt

Job artifacts: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2008/

Screen:
![image](https://user-images.githubusercontent.com/29278800/73519154-84632400-4400-11ea-8eea-a84abf7951e4.png)

According to error, maybe it is related to issue #1782 
It was seen once on cluster 1b.

**Red Hat Che version:** 
7.7.1b

**Comment by ibuziuk** [comment]
@Katka92 can we close this one?
