### ISSUE TITLE
[Test issue] Test for LS initialization fails

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1790]
**Issue problem:** 
Test for LS initialization fails for Java Maven stack. Te file is opened, but the test for an opening file is still waiting for something (probably for `saved` status of a file). When the test for opening file succeeds, LS is already initialized, but the test expects LS just to start initializing, so LS initialization test fails even if LS is initialized correctly.

**Edit**: Sometimes, also test for opening file fails - it is waiting too long for a saved status of a file.

Screenshots: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2252/e2e_report/report/executionScreencast/ (Java Maven stack is running as a second workspace)

**Comment by Katka92** [comment]
Seen again 1x on 1a cluster and yesterday once at saas PR check.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2048/console

**Comment by Katka92** [comment]
Seen again on cluster 2 1x, on production cluster 2a 2x, cluster 1a 1x, cluster 1b 4x, prod-preview cluster 2a 3x.

**Comment by Katka92** [comment]
Seen again on production cluster 2a 1x, cluster 1b 1x and prod-preview cluster 2a 1x.

**Comment by ibuziuk** [comment]
@Katka92 this looks like an upstream issue
@rhopp @dmytro-ndp folks, do we have smth similar in the upstream tests?

**Comment by Katka92** [comment]
@ibuziuk I'm monitoring nightly tests of upstream (they use the same tests and our periodic ones) and it seems that this issue is not present there. It can be Hosted Che specific, which I don't think is a case. Or it can be related just to 7.8.0 which is deployed on Hosted Che, but nighly tests are testing 7.9.0-SNAPSHOT. We can try to fix this upstream and have it downstream next release, but I'm not sure if it is the right way to go.

**Comment by ibuziuk** [comment]
well, if nothing is reproducible in the upstream, than let's update to 7.9.0 once release and monitor the situation

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2291/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2088/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2094/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2106/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2096/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2322/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2115/console

**Comment by ScrewTSW** [comment]
Seen again on production 2a cluster x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2120/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2120/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2339/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2127/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2125/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2126/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2130/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2127/console

**Comment by ibuziuk** [comment]
@Katka92 upstream issue is https://github.com/eclipse/che/issues/16051 ?

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2136/console
production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2132/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2136/console
production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2132/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2134/console
prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2345/console

**Comment by Katka92** [comment]
@ibuziuk No, this one is test issue - LS is initialized correctly, but the test doesn't catch that. The one you shared is broken LS. 

Seen again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2365/console

Seen again on production cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2144/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2152/console

Seen again on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1A/2154/console

Seen again on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2143/console

Seen again on prod-preview cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2355/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2359/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2361/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2155/console

Seen on production cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2155/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2158/console

Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2369/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2377/console

Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2166/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2380/console
Seen on cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2168/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2174/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2393/console
on production cluster 2a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2184/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2187/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2193/console
on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2184/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2189/console
on production cluster 1b x5:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2181/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2183/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2186/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2192/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2193/console
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2398/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2406/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2198/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2197/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2199/console
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2409/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2413/console

**Comment by ScrewTSW** [comment]
seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2205/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2429/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2218/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2283/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2285/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2288/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2294/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2299/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2303/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2298/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2299/console

**Comment by Katka92** [comment]
The issue related to the unsaved status of a file was moved into a separate issue: https://github.com/redhat-developer/rh-che/issues/1842

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2348/console
With a strange comeback where tests have been stuck on open notifications manager
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/2348/e2e_report/report/Java_Vert.x_test_Language_server_validation_LS_initialization/screenshot-LS_initialization.png
