### ISSUE TITLE
[Infra Issue] Production cluster 2 - Slow workspace startups - pod sandbox context deadline exceeded

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1801]
We are currently experiencing very slow workspace startups on production cluster 2 with `Failed to create pod sandbox` errors.

This is not the same error as we were experiencing on prod-1b before https://github.com/redhat-developer/rh-che/issues/1782

Workspace startup hangs on the `context deadline exceeded` until it finally fails with `Plugins installation process timed out`.

We see this issue happen either at the start of the workspace or during theia pod creation.

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/74815678-f93bc680-52f9-11ea-8998-a12f8922e08f.png)

![image](https://user-images.githubusercontent.com/16451875/74815744-153f6800-52fa-11ea-9b71-10d203bda4c5.png)

**Comment by ScrewTSW** [comment]
Seen yesterday on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2329/console
Seen today on production cluster 2 x4:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2331/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2332/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2333/consoleFull

**Comment by ScrewTSW** [comment]
seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2337/console

**Comment by ibuziuk** [comment]
@ScrewTSW could you please also provide links to events

**Comment by ScrewTSW** [comment]
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2337/events_report.txt :) will remember to link it the next time

**Comment by ibuziuk** [comment]
@ScrewTSW this issue is no longer reproducible, right?

**Comment by Katka92** [comment]
The issue did not reproduce for two weeks. Closing.

**Comment by ScrewTSW** [comment]
Seen again, probably just a fluke (slow startup and context deadline exceeded)
production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3649/console
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/3649/e2e_report/report/Java_Maven_test_Language_server_validation_Error_highlighting/screenshot-Error_highlighting.png

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3710/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3747/console

**Comment by Katka92** [comment]
Not seen for 11 days. Closing.
