### ISSUE TITLE
[Test issue] Error highlighting false negative

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1811]
**Description:**
The erroneous text is highlighted but a test from time to time results as a failure.
![image](https://user-images.githubusercontent.com/29278800/75429154-a097a980-5949-11ea-880f-3f0c361285f9.png)

Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2383/console

**Comment by Katka92** [comment]
@ibuziuk The issue is reproduced by upstream tests https://github.com/eclipse/che/issues/16166

**Comment by ibuziuk** [comment]
@Katka92 should we disable it on our end until fixed?

**Comment by Katka92** [comment]
I'll discuss that tomorrow on standup and if somebody will fix that, we can apply the same fix as a patch downstream. If no, I'm OK to disable that until it will be fixed.

**Comment by Katka92** [comment]
Seen on prod-preview cluster 2a 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2390/console

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster 2a x4:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2391/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2395/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2400/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2406/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2421/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2209/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2425/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2429/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2430/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2217/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2213/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2214/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2437/console
Seen on production cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2224/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2223/console
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2222/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2235/console
Seen on cluster 1b 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2222/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2224/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2236/console
Seen on prod-preview cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2437/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2438/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2450/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1X
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2239/console
Seen on production cluster 1a 1x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2241/console
Seen on production cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2241/console
Seen on prod-preview cluster 2a 1x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2453/console

**Comment by Katka92** [comment]
Seen on production 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2456/console
Seen on production 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2250/console
Seen on production 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2248/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2250/console
Seen on prod-preview 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2460/console

**Comment by Katka92** [comment]
Seen on production cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2464/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2466/console
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2252/console
Seen on production cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2253/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2254/console
Seen on production cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2250/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2252/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2466/console

**Comment by Katka92** [comment]
Seen on production cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2468/console
Seen on production cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2260/console
Seen on prod-preview cluster 2a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2471/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2473/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x3:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2479/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2481/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2482/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2277/console
on production cluster 1a x4:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2264/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2265/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2272/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2280/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2278/console
on prod-preview cluster 2a x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2480/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2483/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2496/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2280/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2281/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2502/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2289/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2293/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2285/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2507/console
on production cluster 2a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2293/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2294/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2296/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2296/console
on prod-preview cluster 2a x3:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2506/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2508/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2510/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2515/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2304/console

**Comment by Katka92** [comment]
Seen on cluster 2 4x
Seen on production cluster 2a 3x
Seen on cluster 1a 4x
Seen on cluster 1b 3x
Seen on prod-preview 2a 2x

**Comment by Katka92** [comment]
Seen on cluster 2a prod 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2327/console
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2325/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2326/console
Seen on cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2322/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2325/console
