### ISSUE TITLE
[Che issue] Workspace is started but not redirected to the IDE

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1812]
**Description:**
A workspace stuck on a loading page [1] instead of being redirected to the IDE. No weird logs in kibana, but `Failed to create pod sandbox` in events.

Job log: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2169/console
Events: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1a/2169/events_report.txt

[1] 
![image](https://user-images.githubusercontent.com/29278800/75420589-9ae59800-5938-11ea-8b8b-9d42eb8def98.png)

[2] 
![Screenshot from 2020-02-27 08-12-56](https://user-images.githubusercontent.com/29278800/75420762-029be300-5939-11ea-8d0c-95b7344591ce.png)

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2269/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2271/consoleFull

**Comment by ScrewTSW** [comment]
reopening, seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2585/consoleFull
![image](https://user-images.githubusercontent.com/16451875/78110141-c9083d00-73fa-11ea-9995-424d5dee1b8c.png)

**Comment by ScrewTSW** [comment]
reopening, seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2585/consoleFull

**Comment by ScrewTSW** [comment]
reopening, seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2858/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2858/console

**Comment by Katka92** [comment]
I can see `CNI request failed with status 400: 'pods \"workspacetqkyv12f9sr4uyih.che-plugin-broker\" not found\n'",` in the events of 
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2858/console. Maybe it can be related to the problem.

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2950/console
![image](https://user-images.githubusercontent.com/16451875/86784309-a45adb80-c061-11ea-8f61-893eb5325b9b.png)

**Comment by ScrewTSW** [comment]
Seen again, stuck on the preloader forever:
seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3490/console
![image](https://user-images.githubusercontent.com/16451875/98945339-b0184c00-24f2-11eb-9bb4-a34d6ce92832.png)

**Comment by Katka92** [comment]
Seen again on prod-preview 2a cluster
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3765/console

**Comment by ScrewTSW** [comment]
> ![image](https://user-images.githubusercontent.com/16451875/86784309-a45adb80-c061-11ea-8f61-893eb5325b9b.png)
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3997/console

**Comment by ibuziuk** [comment]
Closing as outdated
