### ISSUE TITLE
LS not working for Java workspaces

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1813]
**Description:**
LS not started for Java Maven and Java Vertx tests. The message is not shown in a status bar and features like error highlighting, code navigation, code suggestion and autocomplete are not working.
Maybe caused by `Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container \"af92db2e5160de09a443e12830e2b6218a32d3985629db52253c0fa9d07da515\" network for pod \"workspaceg6dsfrwmt1w1807v.che-plugin-broker\": NetworkPlugin cni failed to set up pod \"workspaceg6dsfrwmt1w1807v.che-plugin-broker_osio-ci-preview-testper-che\" network: CNI request failed with status 400: 'pods \"workspaceg6dsfrwmt1w1807v.che-plugin-broker\" not found\n'` 

Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2380/console
Events: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/2380/events_report.txt

Seen on prod-preview 2x for Java Maven and 2x for Java Vertx

**Comment by ibuziuk** [comment]
Looks like an infra issue that has been resolved
@Katka92 are you ok to close?
