### ISSUE TITLE
Create test for worksapce idling

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1824]
**Description:**
Create a test for workspace idling and add it to the nightly test suite.
This test should create a workspace, wait for an expected amount of time and check that the workspace is switched to offline state.

**Comment by ibuziuk** [comment]
@Katka92 can we move it to upstream? or close it not relevant

**Comment by Katka92** [comment]
Upstream issue is already created https://github.com/eclipse/che/issues/16511. Closing.
