### ISSUE TITLE
[Test issue] Java Maven code suggestion jumps around

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1829]
Sometimes suggestion invoking part of Mavan LS test fails because the cursor jumps lines.

![image](https://user-images.githubusercontent.com/16451875/76750709-032cda00-677f-11ea-92c8-ed166f156957.png)
![image](https://user-images.githubusercontent.com/16451875/76750724-06c06100-677f-11ea-82aa-ccbc84a59003.png)
![image](https://user-images.githubusercontent.com/16451875/76750737-09bb5180-677f-11ea-8bc8-2abf9f4a513e.png)
![image](https://user-images.githubusercontent.com/16451875/76750748-0d4ed880-677f-11ea-8eed-cc1becab21f4.png)

Seen on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2478/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2483/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2288/console

**Comment by Katka92** [comment]
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2308/console
