### ISSUE TITLE
KC authentication fails when username contains a dot

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#183]
In `KeycloakUserValidator` we match the KC user with the OpenShift Che project name. 

Due to some limitations on OpenShift  project names we need to modify the KC user name before checking if that matches with the project name. For example if the KC user contains a `@` the [part of the name after `@` is discarted](KeycloakUserValidator ).  We now need also to replaces any `.` with `-` for cases like:

```
name: mario.loriedo@gmail.com
project name: mario-loriedo-che
```

**Comment by l0rd** [comment]
cc @ibuziuk @davidfestal @amisevsk

**Comment by amisevsk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KC authentication fails when username contains a dot](https://trello.com/c/zwEfnaan/2-kc-authentication-fails-when-username-contains-a-dot)
