### ISSUE TITLE
Check rollout test, switch to TLS

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1838]
**Description:**
Check that rollout tests works as expected on a new dev cluster. 
Its flow should now be changed to test the deployment with TLS enabled.

**Comment by ibuziuk** [comment]
@Katka92 any updates on this one?

**Comment by Katka92** [comment]
I didn't check that. We still don't have a Prometheus instance to send data to, so maybe it would be fine to do that when we'll update scripts to migrate to Prometheus. But if you consider that having a higher priority, we can try to add it.

**Comment by ibuziuk** [comment]
@Katka92 I believe we need to fix the rollout test. Could you please prioritize this for the next sprint? Not sure how come prometheus is related to this

**Comment by Katka92** [comment]
Ah, sorry, I misread the issue, I thought it's about route tests. We will take that one in the next sprint.

**Comment by Katka92** [comment]
PR merged. Waiting for tomorrow. If the job will pass, I'll close this issue.

**Comment by Katka92** [comment]
Job failed on deploying Postgre. Waiting for tomorrow.

**Comment by Katka92** [comment]
Rollout test is passing https://ci.centos.org/job/devtools-rh-che-rollout-test-devtools-dev.ext.devshift.net/625/console
