### ISSUE TITLE
KC authentication fails silently when OSO token has expired 

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#184]
When a user has a valid KC token but an invalid OSO token Che fails to authenticate. 

That's usually because the OSO token has expired. We should at least make it clear in the logs and add a link to the procedure to re-enable the OSO token.

**Comment by l0rd** [comment]
cc @ibuziuk @amisevsk @davidfestal

**Comment by ibuziuk** [comment]
@l0rd this situation with expired tokens should not even happen now since oso tokens must be valid for a year. 
@alexeykazakov does there any related issue on keycloak side ?

**Comment by ibuziuk** [comment]
Workaround for invalid / expired oso tokens is relinking oso account via

`https://sso.openshift.io/auth/realms/fabric8/account/identity`

**Comment by l0rd** [comment]
@ibuziuk even if that happens only after 365 days we probably still need to address that right? I mean that's not urgent but we probably need to think about how to notify a user when, after 365 days, his OSO token has expired.

**Comment by ibuziuk** [comment]
@l0rd agree, but this should not be done on che side IMO (maybe some email notification ?). Here we just fall back on keycloak API and use the token that is received.

**Comment by alexeykazakov** [comment]
There is an issue to address OSO token refresh - https://github.com/fabric8-services/fabric8-wit/issues/1351
But to be clear. Invalid OSO token is not part of Keycloak authentication. Keycloak will login users regardless of any problem with the OSO token.

**Comment by ibuziuk** [comment]
yeah, this one is really outdated since OSO tokens is not used anymore. Closing
