### ISSUE TITLE
[Test issue] Test for opening a file fails because file isn't saved

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1842]
**Description:**
Test for opening a project tree and opening a file fails because the status of a file is not saved.

![image](https://user-images.githubusercontent.com/29278800/77303584-7d1b1100-6cf3-11ea-8b2d-49a9e86da150.png)

Jobs failed: 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2303/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2311/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2312/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2305/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2323/console

**Comment by Katka92** [comment]
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2327/console

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2548/console
Seen on cluster 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2335/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2336/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2345/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2562/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2573/console
on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2353/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2354/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2356/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2357/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2378/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2381/console

**Comment by Katka92** [comment]
Seen again on cluster 1a 5x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2391/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2392/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2398/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2399/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2404/console

**Comment by Katka92** [comment]
Seen again on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2408/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2410/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2636/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2660/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2663/console
on production cluster 2a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2433/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2445/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2454/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2431/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2431/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2450/console
on prod-preview cluster 2a 1x:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2648/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2457/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2455/console

**Comment by Katka92** [comment]
Seen on production cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2689/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2692/console

**Comment by Katka92** [comment]
Seen on production cluster 2 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2703/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2706/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2707/console

**Comment by Katka92** [comment]
Seen on production cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2713/console

**Comment by Katka92** [comment]
Seen on production 1b 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2502/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2505/console

**Comment by Katka92** [comment]
Seen on production 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2513/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2730/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2739/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2513/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2754/console

**Comment by Katka92** [comment]
Seen on prod cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2558/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2776/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2622/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2689/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2729/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2766/console
