### ISSUE TITLE
[Infra issue] Workspaces briefly switching to offline during test run

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1848]
Sometimes it happens that workspaces switch temporarily to offline state during workspace readiness stage of tests.
There are no evicted events present
![image](https://user-images.githubusercontent.com/16451875/77901279-a0a80380-727f-11ea-9490-b759e0e0f39e.png)
![image](https://user-images.githubusercontent.com/16451875/77901288-a3a2f400-727f-11ea-8d14-19c4bc2ebda8.png)

**Comment by ScrewTSW** [comment]
Last seen on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2352/console

**Comment by Katka92** [comment]
It also seems there is nothing suspicious in kibana logs. 
Search command used: `workspace8m9jip0n7hhb1jx3 AND kubernetes.conatiner_name=rhche`

![Screenshot from 2020-03-30 12-32-00](https://user-images.githubusercontent.com/29278800/77903071-8d4a6780-7282-11ea-96ec-20da048da662.png)

**Comment by Katka92** [comment]
Seen again on cluster 2 1x - workspace didn't start
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2605/consoleFull

![image](https://user-images.githubusercontent.com/29278800/78534666-144f9080-77eb-11ea-9fb3-5dd1c3fdc748.png)

**Comment by Katka92** [comment]
Reopening this issue as a root of of failures for those issues:
Workspace reloaded twice during startup https://github.com/redhat-developer/rh-che/issues/1837
Maven terminal reset during build https://github.com/redhat-developer/rh-che/issues/1633

**Comment by Katka92** [comment]
Workspace switched to offline on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2852/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2853/console

**Comment by Katka92** [comment]
Workspace switched to offline on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2872/console

**Comment by Katka92** [comment]
Seen 7 days ago: 
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2912/console

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/85404108-c5e69e00-b55e-11ea-8d6b-73a94181abce.png)
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3081/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2874/console
(workspace switched to offline briefly after starting up)

**Comment by Katka92** [comment]
Seen again on cluster 2 - workspace switched to offline, that broke running command and LS stopped working.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3212/console

**Comment by Katka92** [comment]
Workspace switched to offline. After "restarting" to online again, LS was not working and command was not able to run.
![image](https://user-images.githubusercontent.com/29278800/88642018-3a61af00-d0c0-11ea-83d0-c7a3c353f9a1.png)

https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3065/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3080/console

#3080 failing with a new message
![image](https://user-images.githubusercontent.com/16451875/89181995-0c371000-d595-11ea-9e1d-8b1dac4cb579.png)

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3109/console

**Comment by Katka92** [comment]
Seen on production cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3136/console

**Comment by Katka92** [comment]
Seen on production cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3370/console

**Comment by Katka92** [comment]
Seen on productin cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3168/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3413/console
resulting in maven build fail - connection is closed
![mpc-hc64_bqjdRWUcJQ](https://user-images.githubusercontent.com/16451875/91724924-46003400-eb9e-11ea-8163-120edc9687ff.png)

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3208/console
causing project to not be imported and test refresh

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3450/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3451/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3476/console

**Comment by Katka92** [comment]
Seen on prod-preveiew 1x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3615/console

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3636/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3472/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3473/console

**Comment by Katka92** [comment]
Seen again on cluster 2a, LS was not working at all because of that.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3559/console

**Comment by Katka92** [comment]
Probably seen again on cluster 2. https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/4036/console

**Comment by ibuziuk** [comment]
Closing as outdated
