### ISSUE TITLE
[Che issue] Maven build failed with no error

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1856]
We have seen a maven build process fail with no output or error message

![image](https://user-images.githubusercontent.com/16451875/78249509-c0912e80-74ee-11ea-8be8-67eef5c45f80.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2591/console

**Comment by Katka92** [comment]
It failed because of some networking issue: "Terminal failed to connect".

![image](https://user-images.githubusercontent.com/29278800/78530500-0a765f00-77e4-11ea-8016-769e7e0b07fa.png)
