### ISSUE TITLE
[Infra issue] Unexpected end of file during dependency installation

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1863]
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

We have seen this problem during installation of `docker-ce` package

**Comment by ScrewTSW** [comment]
Seen on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2434/console

**Comment by Katka92** [comment]
This issue is reported as a part of ci.centos.org issues here https://github.com/redhat-developer/rh-che/issues/1715. Closing.
