### ISSUE TITLE
Failed to start worksapce - secrets/configmap already exists

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1870]
**Description:**
Workspace is not able to start. Message:

`
Error: Failed to run the workspace: "Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/osiotest2aprod2-che/secrets. Message: object is being deleted: secrets "workspacejdarhzcxg98eigc4-sshprivatekeys" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=secrets, name=workspacejdarhzcxg98eigc4-sshprivatekeys, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=object is being deleted: secrets "workspacejdarhzcxg98eigc4-sshprivatekeys" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
`

![image](https://user-images.githubusercontent.com/29278800/80078232-e5f1e500-854e-11ea-8e50-fa15183417cb.png)

Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2505/console

**Comment by ibuziuk** [comment]
This one should be fixed in 7.12.0 - https://github.com/eclipse/che/issues/16512

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2741/console
- seen at Apr 26, 2020 6:44:01 PM

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW  eclipse/che#16512 is closed. Could you confirm that there is no such issue anymore?

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2691/console
this time with configmaps instead of secrets
![image](https://user-images.githubusercontent.com/16451875/82814797-21f2cf80-9e98-11ea-90d8-fd5a2743314a.png)

**Comment by ScrewTSW** [comment]
Configmaps seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2704/console

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 should have been fixed. Can we close it - clipse/che#16512
