### ISSUE TITLE
Randomly [object Object] page shows up ....

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#1873]
**Issue problem:** 
I randomly having since this morning random page showing up on che.openshift.io:
![image](https://user-images.githubusercontent.com/650571/80277424-22f4dd80-86ef-11ea-9f8a-da52aa17aaa4.png)

**Comment by ibuziuk** [comment]
Looks like related to https://github.com/eclipse/che/issues/16719
@sunix could you post the browser console logs?

**Comment by sunix** [comment]
![image](https://user-images.githubusercontent.com/650571/80859858-18dd5c80-8c64-11ea-90b4-ad72c4e11844.png)

@ibuziuk just got that this morning again

**Comment by ibuziuk** [comment]
@sunix closing in favor of eclipse/che#16719
