### ISSUE TITLE
[Che issue] Plugin installation process timed out

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1874]
Workspace startup failed with an error message:
`Error: Failed to run the workspace: "Plugin installation process timed out"`

![image](https://user-images.githubusercontent.com/16451875/80375573-d2b97f00-8898-11ea-9fc5-4fbb213c8123.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2525/console

**Comment by Katka92** [comment]
Seen on production cluster 1a 1x
Workspce stuck on `Loading...` page for 3 minutes. Then it fails with `Error: Failed to run the workspace: "Plugins installation process timed out"`.
![image](https://user-images.githubusercontent.com/29278800/80949254-f0846800-8df3-11ea-9265-4f308b443ed0.png)
![image](https://user-images.githubusercontent.com/29278800/80949405-448f4c80-8df4-11ea-8440-a51e5bab9d92.png)

https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2561/console

**Comment by Katka92** [comment]
Not seen for two weeks. Closing.

**Comment by Katka92** [comment]
Seen on cluster 2 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3108/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3112/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3117/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2912/console
![image](https://user-images.githubusercontent.com/29278800/86091247-d2fa1480-baab-11ea-8881-061ee2eee5cd.png)

This issue is probably related to older one: https://github.com/redhat-developer/rh-che/issues/1782
