### ISSUE TITLE
[Infra issue] login stuck on verifying account username

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1891]
Sometimes it happens that login hangs on verifying username.

It can either be a short delay, or it's stuck like that for an entire test run.

![Screenshot_20200514_152231](https://user-images.githubusercontent.com/16451875/81939632-dc601800-95f6-11ea-988e-58679afc0326.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2845/console

**Comment by Katka92** [comment]
Seen on production cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2647/console

**Comment by Katka92** [comment]
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2823/console
