### ISSUE TITLE
[Che issue] Keycloak initialization fails during workspace startup

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1892]
**Issue problem:** 
Keycloak fails to initialize during workspace startup. Then the run command fails to execute.
![image](https://user-images.githubusercontent.com/29278800/82207564-513e9500-990a-11ea-84e6-14bfa54faae5.png)

Seen once on production cluster 2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2656/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2942/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2951/console
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2952/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2773/console

**Comment by Katka92** [comment]
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2807/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2918/console

**Comment by ibuziuk** [comment]
@Katka92 I saw the same issue against upstream - could you please open the relevant ticket?

**Comment by Katka92** [comment]
The issue was not seen on a Hosted Che for ~2 weeks. Closing.

**Comment by Katka92** [comment]
Seen again during workspace startup - before loading IDE. Seen once on cluster 2.

https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3658/console
![image](https://user-images.githubusercontent.com/29278800/97842896-b20b2f80-1ce8-11eb-870f-d9c4b346f412.png)

**Comment by Katka92** [comment]
Not seen for 2 weeks, closing.
