### ISSUE TITLE
gcc/gdb -> Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64

### ISSUE THREAD

**Issue by pflegende** [redhat-developer/rh-che#1897]
**Issue problem:** 
 

**Red Hat Che version:** 

version: (help/about menu)
Che-Theia@3549376 using Theia@9bc52ad1
List of extensions
    @eclipse-che/che-theia-hosted-plugin-manager-extension 0.0.1
    @eclipse-che/theia-about 0.0.1
    @eclipse-che/theia-activity-tracker 1.0.0
    @eclipse-che/theia-dashboard-extension 0.0.1
    @eclipse-che/theia-git-provisioner 0.0.1
    @eclipse-che/theia-logging 1.0.0
    @eclipse-che/theia-plugin-ext 0.0.1
    @eclipse-che/theia-preferences-provider-extension 0.0.1
    @eclipse-che/theia-remote 0.0.1
    @eclipse-che/theia-terminal 0.0.1
    @eclipse-che/theia-user-preferences-synchronizer 0.0.1
    @theia/callhierarchy 1.0.0
    @theia/console 1.0.0
    @theia/core 1.0.0
    @theia/debug 1.0.0
    @theia/editor 1.0.0
    @theia/file-search 1.0.0
    @theia/filesystem 1.0.0
    @theia/json 1.0.0
    @theia/keymaps 1.0.0
    @theia/languages 1.0.0
    @theia/markers 1.0.0
    @theia/messages 1.0.0
    @theia/metrics 1.0.0
    @theia/mini-browser 1.0.0
    @theia/navigator 1.0.0
    @theia/outline-view 1.0.0
    @theia/output 1.0.0
    @theia/plugin-dev 1.0.0
    @theia/plugin-ext 1.0.0
    @theia/plugin-ext-vscode 1.0.0
    @theia/preferences 1.0.0
    @theia/preview 1.0.0
    @theia/process 1.0.0
    @theia/scm 1.0.0
    @theia/search-in-workspace 1.0.0
    @theia/task 1.0.0
    @theia/terminal 1.0.0
    @theia/userstorage 1.0.0
    @theia/variable-resolver 1.0.0
    @theia/workspace 1.0.0

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem:

delet workspace
fresh from dashbord: "c++/c Clang workspace" run fresh workspace
produces identicaly missing message.

  ¯\_(ツ)_/¯

**Comment by ibuziuk** [comment]
@pflegende could you please open the issue in the https://github.com/eclipse/che/issues with clear steps to reproduce. C++ getting started stack seems to work just fine against the latest 7.13.1 Hosted Che version:

![image](https://user-images.githubusercontent.com/1461122/82895958-67c19d80-9f55-11ea-9302-0606e2cbcedd.png)
