### ISSUE TITLE
Improve Bayesian agent logging from `launch.sh`

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#190]
Bayesian agent generating a `launch.sh` script that is used to start the bayesian language server when the IDE needs it.
Bayesian language server is logging to the file `bayesian.log`
However, if an error occurs in the launch.sh script, there is not way to find out the problem as output is not persisted/displayed anywhere.

**Comment by l0rd** [comment]
@sunix do you think that having `launch.sh` logging somewhere (e.g. `/home/user/che/launchers/bayesian_launcher.log`) would solve that?

**Comment by ibuziuk** [comment]
@sunix could you please create an issue upstream ?

**Comment by ibuziuk** [comment]
Closing as outdated
