### ISSUE TITLE
[Unknown] Failed to pull image during workspace startup

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1904]
**Description:**
Workspace startup fails on pulling an image.
![image](https://user-images.githubusercontent.com/29278800/83403152-6afed280-a408-11ea-9e88-5676e41751cd.png)
![image](https://user-images.githubusercontent.com/29278800/83403178-781bc180-a408-11ea-8da7-19551e4136a1.png)

Seen on cluster 2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2944/console 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2947/console
Seen on production cluster 2a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2726/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2738/console
Seen on cluster 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2734/console
Seen on cluster 1b
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2727/console

**Comment by ibuziuk** [comment]
Closing since it was related to https://status.quay.io/history
