### ISSUE TITLE
[Infra issue] "gzip: stdin: unexpected end of file" while installing docker package

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1916]
Docker-ce installation fails with `gzip: stdin: unexpected end of file`

```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Connection to 172.19.2.94 closed.
```

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3009/console
Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2798/console
Seen on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2798/console
Seen on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2796/console
Seen on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3010/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2808/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2838/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3030/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3533/console

**Comment by Katka92** [comment]
Not seen for 11 days. Closing.
