### ISSUE TITLE
[Infra issue] repomd.xml does not match metalink for epel

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1917]
During installation of dependencies epel repo went out of sync

```
...
http://mirror.nodesdirect.com/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
http://fedora.westmancom.com/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
https://iad.mirror.rackspace.com/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
https://dfw.mirror.rackspace.com/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
http://mirror.compevo.com/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.compevo.com/epel/7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
```

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3011/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2803/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2805/console

**Comment by Katka92** [comment]
Seen on cluster 2 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3024/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3025/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3026/console
Seen on production cluster 2a 4x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2809/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2813/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2814/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2816/console
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2813/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2814/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2813/console
Seen on prod-preview cluster 2a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3023/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3026/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3027/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3153/console
on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2946/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2954/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2944/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2949/console

**Comment by ScrewTSW** [comment]
Another temporary failure I would group up with this issue:
`Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again`

Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3131/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3129/console

**Comment by ibuziuk** [comment]
Closing as obsolete. if happens again please raise on the epel end
