### ISSUE TITLE
No license for rh-che project

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#192]
There is no LICENSE file nor license header in source code files (java, xml ...)
Which license are we suppose to use ?

**Comment by l0rd** [comment]
As for the license type I would say [EPL](http://www.eclipse.org/legal/epl-v10.html). @gorkem ? 

For the copyright headers I think most of the java source files already have one and we should verify it and enforce a check at build time (for .xml, .sh etc...too of course).

**Comment by gorkem** [comment]
Yes, EPL is the natural choice.

**Comment by JPinkney** [comment]
Fixed as part of #332
