### ISSUE TITLE
[Che Issue] Workspace starting too long

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1923]
**Description:**
Workspace start lasted 2 minutes and IDE load up lasted extra 30 seconds. That caused the test to fail.
Kibana:
![Screenshot from 2020-06-16 10-40-36](https://user-images.githubusercontent.com/29278800/84752274-d5de0b00-afbd-11ea-848f-d86907ff277a.png)

Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2830/console

**Comment by Katka92** [comment]
Seen on cluster 1a, workspace started in 2 minutes 33 seconds, IDE ready in additional ~30 seconds. (ws id: workspaceoamq93te99u2wcy7)
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2837/console

Seen on prod-preview cluster 2a, workspace started in 2 minutes 3 seconds, IDE ready in additional ~30 seconds. (ws id: workspacee1899vjmqhwm8r3x)
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3049/console

**Comment by Katka92** [comment]
Seen on cluster 1a - workspace was started under 2 minutes, but with IDE loading it reached timeout in tests. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2841/console

Seen on cluster 1a - workspace startup took 9 minutes
![Screenshot from 2020-06-18 09-46-33](https://user-images.githubusercontent.com/29278800/84992878-cb03b180-b148-11ea-9c5c-339aeddfc73f.png)
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2842/console

**Comment by Katka92** [comment]
Seen on cluster 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2848/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2874/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2883/console

**Comment by Katka92** [comment]
Seen again on cluster 1a - workspaces starting for more than 3 minutes.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2897/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2900/console
workspaces starting more than 2 minutes:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2902/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2906/console
workspace starting almost 2 minutes - caused the test to timeout when waiting for IDE:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2901/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2910/console

**Comment by Katka92** [comment]
Seen on cluster 1a 2x - workspace starting for more than 2 minutes
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2912/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2913/console

**Comment by ibuziuk** [comment]
should be fixed I believe. @Katka92 are you ok to close?

**Comment by ScrewTSW** [comment]
@ibuziuk The issue was seen again on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2945/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2955/console

**Comment by Katka92** [comment]
@ScrewTSW The firs link you've shared is with passed tests. 
@ibuziuk  The second link shows the workspace starting for more than 3 minutes. So I would wait with the closing of this issue for a few more days - just to be on a safe side.

![Screenshot from 2020-07-09 14-24-54](https://user-images.githubusercontent.com/29278800/87039815-02b5c480-c1f0-11ea-8527-92512a86fd08.png)

**Comment by Katka92** [comment]
@ibuziuk The issue was reproduced again on cluster 1a. The workspace started after ~3 minutes 20 seconds.
![Screenshot from 2020-07-13 12-14-38](https://user-images.githubusercontent.com/29278800/87293468-a2ca6100-c502-11ea-8888-c787ef6e3a7d.png)


https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2994/console

**Comment by Katka92** [comment]
Workspace starting for more then 3 minutes on cluster 1a.
![Screenshot from 2020-07-16 08-52-03](https://user-images.githubusercontent.com/29278800/87636883-b1eb2200-c741-11ea-942a-834018fd546f.png)

https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3008/console

**Comment by Katka92** [comment]
Workspace was starting for more then 3 minutes on clusetr 1a.
![Screenshot from 2020-07-27 07-50-03](https://user-images.githubusercontent.com/29278800/88507926-cea71580-cfdd-11ea-94b6-a601b62e6d3a.png)

https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3058/console

**Comment by Katka92** [comment]
Workspace starting for more than 2 minutes on cluster 1a
![Screenshot from 2020-07-28 10-40-10](https://user-images.githubusercontent.com/29278800/88640936-d25e9900-d0be-11ea-9129-01b91b4a321f.png)
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3068/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3105/console
