### ISSUE TITLE
[Che issue] Workspace switched offline temporarily during test run

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1932]
Workspace switched to offline for about 20 seconds during a maven build task, no events, no obvious errors

![mpc-hc64_2020-06-23_13-58-39](https://user-images.githubusercontent.com/16451875/85401041-ac8f2300-b559-11ea-9873-63bf0a1b9f1e.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3081/console

**Comment by Katka92** [comment]
Seems that it's related to https://github.com/redhat-developer/rh-che/issues/1848

**Comment by ScrewTSW** [comment]
merging issues and closing
