### ISSUE TITLE
[Test issue] Code navigation not working for Java Maven

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1936]
**Issue problem:** 
Test for code navigation fails. I've tested that manually and it seems to work well. It was probably some glitch. 

EDIT: The action that fails is Ctrl:F11. It is very much possible, that the reason, why it fails, is that the LS was not fully initialized at the time when the tests attempted that action, and they didn't retry the attempt

Seen once on prod-preview
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3136/console

**Comment by Katka92** [comment]
Seen on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3142/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2966/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3186/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2976/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2970/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3189/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3193/console
Seen on cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/2991/console
Seen on cluster 1a 5x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2980/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2988/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2990/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2991/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2976/console
Seen on cluster 1b 2x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2976/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2981/console

**Comment by Katka92** [comment]
Seen on cluster 1a 3x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2997/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2998/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2999/console

**Comment by Katka92** [comment]
PR with the fix to upstream was created today https://github.com/eclipse/che/pull/17397

**Comment by Katka92** [comment]
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3214/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3001/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3003/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3005/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3220/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3222/console
Seen on cluster 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3007/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3005/console

**Comment by Katka92** [comment]
Seen on cluster 2 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3223/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3227/console
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3016/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3017/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3245/console
on production cluster 1a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3019/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3027/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3032/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3038/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3502/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3505/console

**Comment by Katka92** [comment]
Not seen for 18 days. Closing.
