### ISSUE TITLE
[Che issue] Maven build fails with some of the artifacts inaccessible

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1943]
![image](https://user-images.githubusercontent.com/16451875/86891748-a1aec380-c0ff-11ea-9d59-bc228669de29.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3175/console

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/87126161-05fe8e00-c28c-11ea-8f6b-32c5289c4947.png)

Seen again on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2969/console

**Comment by ibuziuk** [comment]
Can you close it and report it upstream? I'm not sure if anything can be done since this looks like the central issue

**Comment by ScrewTSW** [comment]
I will open an upstream issue, but I won't close the one we use for reporting to keep track of whether the problem is still present

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3247/console
on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3024/console
