### ISSUE TITLE
[Che issue] Workspace failed to start due to che-plugin-metadata-broker pull failure

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1944]
![image](https://user-images.githubusercontent.com/16451875/86891990-efc3c700-c0ff-11ea-9541-e4302be99716.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2962/console

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW is it still relevant?

**Comment by ibuziuk** [comment]
obviously some quay glitch
