### ISSUE TITLE
[Infra issue] Failed to run workspace : plugin installation process failed on prod-preview cluster

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1952]
This issue should be resolved, it was caused by missing images during the weekend.

![image](https://user-images.githubusercontent.com/16451875/87937390-edb11f00-ca94-11ea-898e-dd772d12ef76.png)

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster 2a x17:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3232/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3233/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3234/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3235/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3236/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3237/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3238/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3239/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3240/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3241/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3242/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3243/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3244/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3245/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3246/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3247/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3248/console

**Comment by ibuziuk** [comment]
This was expected as I mentioned on Friday due to broken plugin registry build - https://github.com/eclipse/che/issues/17428#issuecomment-660154725
