### ISSUE TITLE
Invalid resources displayed for che.openshift.io

### ISSUE THREAD

**Issue by benoitf** [redhat-developer/rh-che#1954]
**Issue problem:** 
As a new user, after creating an account on che.openshift.io at some point I'm redirected to https://manage.openshift.com/account/index

But it displays like 1GiB of memory on icons while it's more now.

![image](https://user-images.githubusercontent.com/436777/88401798-7d730800-cdca-11ea-8177-16a16770dbbc.png)

**Red Hat Che version:** 

https://manage.openshift.com/account/index
https://che.openshift.io

**Reproduction Steps:**

Just browse to https://manage.openshift.com/account/index

**Comment by ibuziuk** [comment]
@alexeykazakov any ideas how can we update https://manage.openshift.com/account/index ?

**Comment by alexeykazakov** [comment]
It's complicated... We don't control this page. It's OSO.

**Comment by ibuziuk** [comment]
Closing as outdated
