### ISSUE TITLE
Workspace not starting on prod-preview: Waiting for Kubernetes environment 'default' reached timeout

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1964]
**Description:**
Can not start workspace on prod-preview.
`Error: Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the 'workspace-workspaces48linf7jdhrn8bu' reached timeout"`
![image](https://user-images.githubusercontent.com/29278800/90727661-eb282c00-e2c3-11ea-85f2-103e1e6180ba.png)

Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3372/console
Artefacts: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/3372/

**Comment by bharathkuppala** [comment]
Problem solved or still exist???

**Comment by Katka92** [comment]
@bharathkuppala It was not discovered again by our periodic tests.
