### ISSUE TITLE
saas-openshiftion pre-release test suite does not post success mesgae once CI is green 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1966]
there is such a comment for pre-release test suite in rh-che repo - https://github.com/redhat-developer/rh-che/pull/1935#issuecomment-660092366 (edited), but not in https://github.com/openshiftio/saas-openshiftio/pull/1454

**Comment by Katka92** [comment]
MR in app-interface created and merged. Closing.
