### ISSUE TITLE
[Infra Issue] mvn: command not found

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1971]
This seems to be a strange one-off issue caused by dependency not being installed correctly

```
User name printed in format: 3 first letters, space, the rest of letters.    osi otest2aprod2
.ci/cico_utils.sh: line 153: mvn: command not found

parse error: Invalid numeric literal at line 1, column 10
Running test with user **** against prod environment with version .
docker: invalid reference format.
```

**Comment by ScrewTSW** [comment]
Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3201/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3484/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3532/console

**Comment by ibuziuk** [comment]
Closing as out-dated

**Comment by Katka92** [comment]
Seen on prod-preview 2a cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3665/console

**Comment by Katka92** [comment]
Not seen for 2 weeks, closing.
