### ISSUE TITLE
[Test Issue] Project tree - expand file path logic broken, README.md stealing focus

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1972]
Quite often it happens that the project tree is being opened and expanded incorrectly, sometimes README.md spontaneously opens which steals focus from the webdriver resulting in multiple workspace refreshes and the test failing

![mpc-hc64_EOADln8WbZ](https://user-images.githubusercontent.com/16451875/91725657-58c73880-eb9f-11ea-897a-00be804f8754.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/3410/console
on production cluster 1a x5:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3204/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3199/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3197/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3195/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3194/console
on production cluster 1b x5:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3200/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3198/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3195/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3194/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3192/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 1a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3209/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3208/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3207/console
on production cluster 1b x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3205/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3204/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3212/console
Seen again on production cluster 1a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3213/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3210/console
Seen again on production cluster 1b x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3210/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3208/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3207/console
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/3422/console

**Comment by Katka92** [comment]
Seen on cluster 2 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3436/console
Seen on cluster 2a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3221/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3229/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3232/console
Seen on cluster 1a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3223/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3224/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3226/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3227/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3229/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3230/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3231/console
Seen on cluster 1b
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3220/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3221/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3223/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3224/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3225/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3228/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3229/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3230/console
Seen on prod-preview cluster 2a
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3435/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3436/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3440/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3442/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3444/console
