### ISSUE TITLE
[Unsorted Issue] Java Maven LS initialization fails on multiple issues

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1975]
Language server failed installation because the workspace reported gradle not being installed
I did not see workspace switching to offline or any other indication of networking problems

![firefox_DGBuhc6vTX](https://user-images.githubusercontent.com/16451875/91829013-2a019e80-ec41-11ea-921a-82cd468f1d1a.png)

This seems to be a one-off glitch so far.

**Comment by ScrewTSW** [comment]
Seen on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3206/console

**Comment by ScrewTSW** [comment]
![mpc-hc64_x3rGXJdRjg](https://user-images.githubusercontent.com/16451875/91983516-1717c880-ed2c-11ea-9db5-eb181eacd31d.png)

Seen on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/3212/console

**Comment by Katka92** [comment]
Seen on 2a cluster 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3223/console
Seen on cluster 1b 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/3225/console
