### ISSUE TITLE
[Unsorted Issue] Java Maven build fails on Connection reset

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1976]
This is something that happens sometimes during workspace project builds. The workspace itself is not being switched offline during this step.
![mpc-hc64_xkfx61ZIgf](https://user-images.githubusercontent.com/16451875/91990461-09654180-ed32-11ea-9a42-d542b4715e92.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/3207/console

**Comment by Katka92** [comment]
Seen on cluster 1a 1x
fhttps://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3225/console

**Comment by Katka92** [comment]
Seems like the same issue with a different error:
![Screenshot from 2020-09-09 08-29-05](https://user-images.githubusercontent.com/29278800/92562638-964e5480-f276-11ea-9e8a-4b9c365e609b.png)
Seen on cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3240/console
