### ISSUE TITLE
[Unsorted issue] SSO Error during accessing Dashboard

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1983]
**Description:**
Periodic tests encountered the problem of accessing Dashboard. The page with the message was shown:
```
SSO Error

We are experiencing some technical difficulties from our SSO: 
undefined: undefined
Please try `Shift` + `Refresh`
```

![](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/3438/e2e_report/report/Java_Maven_test_Stopping_and_deleting_the_workspace_Remove_workspace/screenshot-Remove_workspace.png)

Related browser logs:
```
"SEVERE" "" "https://auth.prod-preview.openshift.io/api/token - Failed to load resource: the server responded with a status of 401 (Unauthorized)"
"SEVERE" "" "https://che.prod-preview.openshift.io/dashboard/scripts/app-4cceec60f0.js 1423:1503 "Keycloak initialization failed. undefined: undefined""
"SEVERE" "" "https://che.prod-preview.openshift.io/dashboard/ 0:0 "
"SEVERE" "" "https://che.prod-preview.openshift.io/dashboard/ 0:0 "
```
[Full browser logs](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/3438/e2e_report/report/Java_Maven_test_Stopping_and_deleting_the_workspace_Remove_workspace/browserlogs-Remove_workspace.txt)

Seen once on prod-preview 2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3438/console

**Comment by ibuziuk** [comment]
I believe it was related to the SSO incident - https://status.redhat.com/incidents/npd2wxdvq8h4
Is it still reproducible?

**Comment by Katka92** [comment]
It was not reproduced for 25 days, closing.

**Comment by ScrewTSW** [comment]
Seen again on prod-preview 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3991/console
![image](https://user-images.githubusercontent.com/16451875/105844857-2ac51380-5fda-11eb-9dcf-4c4956bb3f36.png)

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
