### ISSUE TITLE
Account is in broken state

### ISSUE THREAD

**Issue by mmorhun** [redhat-developer/rh-che#1995]
**Issue problem:** 

After a delay in a few weeks I tried to log in into my account on che.openshift.io. However, the account is sort of hunged.
Sometimes after login page I see (my internet connection has no proxies and works ok):
![Screenshot from 2020-09-25 10-06-04](https://user-images.githubusercontent.com/15607393/95295252-64351000-087f-11eb-8178-307e0481fc38.png)
When I click on activate account, I see provisioning in progess but then nothing happens and I see active button on the next login again. Sometimes I see the error page:
![Screenshot from 2020-09-25 10-26-14](https://user-images.githubusercontent.com/15607393/95295520-eae9ed00-087f-11eb-8282-1e9b172a4b80.png)

**Red Hat Che version:** 
che.openshift.io

**Reproduction Steps:**
Try to log in in my account. Contact me in PM for more details if needed.

**Comment by ibuziuk** [comment]
@mmorhun could you please clarify if the styles on provision.html are still broken for you? That should have been fixed as part of https://github.com/eclipse/che/issues/17965

@alexeykazakov could you please take a look and check the state of the `mmorhun` user?

**Comment by mmorhun** [comment]
Styles are ok now.

**Comment by alexeykazakov** [comment]
Can you try to login using your username: `mmorhun`. Not your email.

**Comment by mmorhun** [comment]
@alexeykazakov it works as expected with username instead of email.

**Comment by ibuziuk** [comment]
@alexeykazakov looks like the known issue https://github.com/eclipse/che/issues/15885 ?
Any chance we can have this documented?

**Comment by ibuziuk** [comment]
Closing in favour of eclipse/che#15885
