### ISSUE TITLE
Java with Spring Boot and MongoDB fails to build project - disk quota exceeded

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2000]
**Issue problem:** 
Java with Spring Boot and MongoDB fails to build project with disk quota exceeded for both build steps (backend and frontend)

**Red Hat Che version:** 

version: 7.20.0 prod-preview

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**
* Start Java with Spring Boot and MongoDB devfile
* Start either of the build steps
* Build will fail with disk quota exceeded

**Comment by ibuziuk** [comment]
does it happen only in ephemeral mode?

**Comment by ibuziuk** [comment]
Closing as outdated
