### ISSUE TITLE
Compatibility bot should not only update the parent version but also bump the 'che.version' property

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#2003]
e.g. <che.version>7.21.0-SNAPSHOT</che.version> update should not be done manually - https://github.com/redhat-developer/rh-che/pull/1999/commits/3432f53a97a05c59544850fb452f8d3d818647e0
The bot should take care of this update in the compatibility PR

**Comment by Katka92** [comment]
The change of parent is done [here](https://github.com/redhat-developer/rh-che/blob/master/.ci/cico_rhche_compatibility_test.sh#L139). I'm not much familiar with `mvn` so not sure if can do that as a part of this command or we need to use for example separate sed to change the `che.version` item.

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please take it to the next sprint

**Comment by ScrewTSW** [comment]
done.
