### ISSUE TITLE
[Unsorted issue] LS test is failing because of mismatched devfile registry version

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2005]
LS does not function properly because of version of che deployed and version of devfile-registry deployed do not match.
This happend because of automated deployment on prod-preview cluster

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster x4:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3649/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3650/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3651/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3652/console

**Comment by ibuziuk** [comment]
Should be fixed. Closing
