### ISSUE TITLE
[Test issue] Go projectTree didn't open the correct file

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#2007]
**Red Hat Che version:** 
During the Go test, project folder was not opened correctly. Not sure why, maybe README/welcome page stole the focus or the IDE page was loaded so slowly.
You can watch the video of the test [here](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-pre-release-test/85/e2e_report/report/ffmpeg_report/output.mp4) - starting at 7:10.
Screen & error:
![image](https://user-images.githubusercontent.com/29278800/97880531-93755a80-1d21-11eb-8f81-daac6bdaf7b5.png)
```
Go test
       Test opening file
         Expand project and open file in editor:
     TimeoutError: Exceeded maximum gettin of the 'data-node-id' attribute attempts, from the 'By(css selector, div[data-node-id])' element
      at DriverHelper.waitAndGetElementAttribute (node_modules/e2e/dist/utils/DriverHelper.js:265:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Katka92** [comment]
There are also other tests failed, but I assume it is because of this one.

**Comment by ibuziuk** [comment]
@Katka92 is it QR team that is expected to work on this issue?

**Comment by Katka92** [comment]
Yes, it seems like a test flakiness.

**Comment by Katka92** [comment]
Closing in favour of https://github.com/redhat-developer/rh-che/issues/2010 - it is not Go specific.
