### ISSUE TITLE
[Test issue] Build commands timeout in tests

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#2008]
**Issue problem:** 
Test for running `maven build` in Java SpringBoot is failing because of timeout.
During the investigation, I found out that even if the build timeout is set to [6 minutes](https://github.com/eclipse/che/blob/master/tests/e2e/tests/devfiles/JavaSpringBoot.spec.ts#L39), the test timeouts after 2 minutes (see error log below). 
```
  19) Java Spring Boot test
       Validation of workspace build
         Run command 'maven build':
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/rh-che/local_tests/node_modules/e2e/dist/tests/devfiles/JavaSpringBoot.spec.js)
```
![image](https://user-images.githubusercontent.com/29278800/97881041-2d3d0780-1d22-11eb-9778-5388659d51d4.png)

**Comment by ibuziuk** [comment]
@Katka92 is QA team expected to work on this issue? I suppose it is related to the test config

**Comment by Katka92** [comment]
Yes, it is test flakiness.

**Comment by ScrewTSW** [comment]
Fixed in https://github.com/redhat-developer/rh-che/pull/2022 . Build should now pass correctly

**Comment by ScrewTSW** [comment]
Upstream fix for java maven run app was also merged.
