### ISSUE TITLE
[Unsorted issue] Tests failed to expand project tree

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2010]
Project Tree was not expanded.
Only seen this happen once.
![image](https://user-images.githubusercontent.com/16451875/98945819-52383400-24f3-11eb-8412-10b84dfc5fd6.png)

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster 2a x1:
****

**Comment by ibuziuk** [comment]
duplicate of https://github.com/redhat-developer/rh-che/issues/2007 ?

**Comment by Katka92** [comment]
Not reproduced for 18 days. Closing.
