### ISSUE TITLE
[Unsorted issue] Workspace stuck in starting state

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2011]
Workspace just never started, no error shown in the logs
![image](https://user-images.githubusercontent.com/16451875/98946744-91b35000-24f4-11eb-9fab-4f3941411b55.png)
Kibana shows plugin installation timeout
```
{"@timestamp":"2020-11-11T17:52:48.698+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspacemlgh7oalilgpfyb4.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-25","level":"WARN","level_value":30000,"stack_trace":"org.eclipse.che.api.workspace.server.spi.InfrastructureException: Plugins installation process timed out\n\tat org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.WaitBrokerResult.execute(WaitBrokerResult.java:75)\n\t
```

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3702/console

**Comment by Katka92** [comment]
Not reproduced for 18 days. Closing.

**Comment by Katka92** [comment]
Seen again on cluster 2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/4043/console

**Comment by ScrewTSW** [comment]
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/4043/console
![image](https://user-images.githubusercontent.com/16451875/107333702-20b11380-6ab6-11eb-869a-fcaea0b8c79d.png)

**Comment by ibuziuk** [comment]
Closing as outdated
