### ISSUE TITLE
[Infra issue] Maven build failed with 503 between bytes timeout

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2018]
Maven build for Java Maven devfile failed with a strange error during build

![image](https://user-images.githubusercontent.com/16451875/99963055-7ae0e900-2d91-11eb-8d58-8327d3044eb5.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3527/console

**Comment by ibuziuk** [comment]
This is a central outage issue which we ca not infuence. Closing since the issue was not part of the daily reports this week
