### ISSUE TITLE
[Infra issue] Machine exec plugin meta.yaml missing

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2020]
During our periodic tests on production the machine exec plugin was missing. The problem seems to be not present anymore, so creating this as a fringe issue

![image](https://user-images.githubusercontent.com/16451875/100100141-a1218a00-2e60-11eb-8389-8bb6595d3d85.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x2:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3751/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3752/console
on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3539/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3540/console

**Comment by ibuziuk** [comment]
Closing this is not an infra issue
The problem was related to the fact that cm 7.22.0 update from app-sre was applied unexpectedly due to OOM
