### ISSUE TITLE
[Test issue] Sometimes workspace stopping takes more than 5 seconds, causing tests to fail

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2025]
![image](https://user-images.githubusercontent.com/16451875/101751091-26977200-3ad0-11eb-8be3-d44c3b0b94be.png)

Logs form Kibana show that the stopping of workspace took longer than 5 seconds

**Comment by ScrewTSW** [comment]
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3807/console

**Comment by ibuziuk** [comment]
@ScrewTSW I suppose we need to increase the timeout to 30 seconds on the test end.

**Comment by ibuziuk** [comment]
@ScrewTSW can we close the issue?

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
