### ISSUE TITLE
[Uncategorized issue] Workspace start failed because of networking/CNI problems

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2028]
![image](https://user-images.githubusercontent.com/16451875/102628263-b03ae580-4149-11eb-887f-0b7f4802ce48.png)

This was so far it seems just a small fluke that happened twice today. Let's hope it doesn't persist.

**Comment by ScrewTSW** [comment]
Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3633/console
on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3847/console

**Comment by Katka92** [comment]
Seen again on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3923/console
Seen again on prod cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/3711/console

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
