### ISSUE TITLE
[Unsorted issue] Workspace failed to start - plugin installation timed out

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2035]
Workspace failed to start, was stuck on loading bar before the error message was shown
che version: che 7.23.1
![image](https://user-images.githubusercontent.com/16451875/104347968-7dde9700-5501-11eb-8da9-4e55619334c9.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3948/console

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
