### ISSUE TITLE
[Infra issue] prod-preview 2a workspaces failed to start because of misconfigured instance

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2036]
RhChe was trying to download machine exec clugin with version 7.23.1 when the deployment was on 7.24.0 and got 404
![image](https://user-images.githubusercontent.com/16451875/104348651-43292e80-5502-11eb-927b-e02fc68d250c.png)

**Comment by ScrewTSW** [comment]
seen on prod-preview cluster 2a x3:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3946/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3947/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/3948/console

**Comment by ibuziuk** [comment]
Closing as fixed on staging
