### ISSUE TITLE
Create automated tests for stacks

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/rh-che#204]
At the moment stacks and changes to Dockerfiles to stack images are not tested before merged. We should have a process, CI for this. 

My suggestion:
- PR to a stack Dockerfile is created
- automated CI job is triggered
     - it builds staging image and push it to dockerhub
     - then it uses a running Che server and via REST API it creates a new workspace
     - it checks that a workspace has been created and is running
     - then it runs UI smoke tests on a workspace - whether it is running as it is supposed to
- if job passes, it could be merged (manually/automatically depends on white list...)
- production image is built or retagged from the staging and pushed to docker registry
- update of existing stack is done - image is replaced by the latest production

**Comment by mlabuda** [comment]
cc @Katka92

**Comment by l0rd** [comment]
Duplicates #149
