### ISSUE TITLE
[Unsorted issue] Internal server error during workspace deletion

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2041]
![image](https://user-images.githubusercontent.com/16451875/105845186-a8891f00-5fda-11eb-955a-16872b6aeeb5.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/3779/console

**Comment by ibuziuk** [comment]
This looks like SSO outage

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
