### ISSUE TITLE
[Unsorted issue] Failed to load devfile registry metadata

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2044]
![image](https://user-images.githubusercontent.com/16451875/105965135-5819cc00-6083-11eb-9c31-8c6317ff936f.png)

Seems like this was just a one-time fluke

**Comment by ScrewTSW** [comment]
Seen on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/4006/console

**Comment by ibuziuk** [comment]
This one happened due to updated template for deployment in upstream, closing
