### ISSUE TITLE
Connection got disposed during IDE startup

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#2045]
**Issue problem:** 
When IDE is starting, it throws a `Connection is disposed` error. Then it takes quite a long time for IDE to load so the tests refresh the page. As a result of the refresh, the PROJECT section in a menu is not opened.

Screenshot of a `Connection is disposed`
![Screenshot from 2021-02-02 09-50-19](https://user-images.githubusercontent.com/29278800/106575799-c4417780-653c-11eb-9b63-8ca6a54f2477.png)

Screenshot of a project not opened
![image](https://user-images.githubusercontent.com/29278800/106575895-d9b6a180-653c-11eb-8be7-eb415a1a5979.png)

Bowser [logs](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/4023/e2e_report/report/Java_Maven_test_Create_Java_Maven_workspace_Wait_for_workspace_readiness/browserlogs-Wait_for_workspace_readiness.txt)

**Comment by ibuziuk** [comment]
Closing as outdated
