### ISSUE TITLE
Dashboard stuck in loading state after direct access via URL

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#2046]
**Issue problem:** 
After accessing Dashboard via URL, the Dashboard was stuck in a loading state. It caused tests to fail.
Browser [logs](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/4030/e2e_report/report/Java_Maven_test_Stopping_and_deleting_the_workspace_Remove_workspace/browserlogs-Remove_workspace.txt)
[Video](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/4030/e2e_report/report/ffmpeg_report/output.mp4)

Screenshot
![image](https://user-images.githubusercontent.com/29278800/106576796-d5d74f00-653d-11eb-991a-e5b2fed9f399.png)

**Comment by ibuziuk** [comment]
Closing as outdated
