### ISSUE TITLE
[Unsorted issue] Workspace stuck on loading circle

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2049]
Sometimes the workspace startup gets stuck on the loading circle even though the workspace started.
Only thing that helps is to refresh the tab.
![image](https://user-images.githubusercontent.com/16451875/107333445-c87a1180-6ab5-11eb-83d3-95dbde4bd7fa.png)

**Comment by ScrewTSW** [comment]
Seen on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/4046/console

**Comment by ibuziuk** [comment]
Closing as outdated
