### ISSUE TITLE
Cleanup / archive Hosted Che related repos, jobs, resources on dsaas

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#2059]
List of repositories for archiving:
- [x] https://github.com/redhat-developer/rh-che
- [x] https://github.com/redhat-developer/che-monitoring
    - [x] https://github.com/openshiftio/saas-openshiftio/pull/1508
- [x] https://github.com/redhat-developer/kubernetes-image-puller
- [x] https://github.com/fabric8-services/che-tenant-maintainer
    - [x] https://github.com/openshiftio/saas-openshiftio/pull/1510
- [x] https://github.com/redhat-developer/che-starter
- [x] https://github.com/fabric8-services/fabric8-che
- [x] https://github.com/redhat-developer/che-vertx-server
- [x] https://github.com/redhat-developer/che-starter-performance

List of jobs:
- [x] rh-che pre-release https://ci.centos.org/job/devtools-rh-che-pre-release-test
- [x] saas openshiftio pre-release https://ci.centos.org/job/devtools-saas-openshiftio-pre-release-test/
- [x] rollout https://ci.centos.org/job/devtools-rh-che-rollout-test-apps.che-dev.x6e0.p1.openshiftapps.com/
- [x] compatibility https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io
- [x] test dependencies https://ci.centos.org/job/devtools-rh-che-build-func-dep
- [x] build che credentials master https://ci.centos.org/job/devtools-rh-che-build-che-credentials-master
- [x] PR check cleanup https://ci.centos.org/job/devtools-rh-che-prcheck-cleanup
- [x] PR check https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io
- [x] route test 2 https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-route-2
- [x] route test 2a https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-route-2a/
- [x] periodic prod-preview https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/
- [x] periodic 2a https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/
- [x] periodic 2 https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/

List of resources on dsaas / dsaas-stg:
- [x] https://github.com/openshiftio/saas-openshiftio/tree/master/dsaas-services (No Che specifc services left)

Others
- [x] Vault secrets cleanup

**Comment by Katka92** [comment]
I've updated issue - added (I hope all) links to QE jobs + `build che credentials mater` job.

**Comment by ibuziuk** [comment]
@Katka92 we should probably also consider vault cleanup as part of CI jobs removal

**Comment by ericwill** [comment]
Hey just FYI I have already removed the `release-preview` centos-ci jobs for both the devfile and plugin registries: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15557

**Comment by ibuziuk** [comment]
Regarding the registries, the rest of the cleanup is done in 
- https://github.com/openshiftio/saas-openshiftio/pull/1511
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16118

**Comment by Katka92** [comment]
@ibuziuk I've removed the part trigger build-che-credentials for rh-che, now I'm trying to understand if I can remove whole job definition - as I don't see it being used anywhere else. Could you please double check?
Removed definition [here](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16143/diffs#de1efadf29a9fdc7016aa58e1dbe576423c5c4e3_452_369)
Job definition [here](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml#L1809)

**Comment by ibuziuk** [comment]
@Katka92 the only concern regarding the job definition cleanup is the upstream components like image puller that have not been migrated yet - https://github.com/eclipse/che/issues/19294

**Comment by ibuziuk** [comment]
The cleanup is done dsaas only contains the redirector workloads:
- che.openshift.io -> workspaces.openshift.com
- openshift.io -> https://developers.redhat.com/developer-sandbox
