### ISSUE TITLE
Default Run command is broken

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer/rh-che#215]
For Vert.x projects, it should be
cd /projects/newspace && scl enable rh-maven33 'mvn compile vertx:run'

but it is currently
scl enable rh-maven33 'java -jar target/-fat.jar'

**Comment by l0rd** [comment]
I've provided a couple of PRs (upstream and downstream) to address that. Tomorrow the fix should be available on OSIO.

**Comment by l0rd** [comment]
@burrsutter @gastaldi This has been fixed as of version 1.0.234 of Che. I am closing the issue but feel free to re-open it if needed.
