### ISSUE TITLE
Rename property `che.keycloak.disabled`

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#224]
So to enable keycloak it's "not not enable" or "not disable" (`che.keycloak.disabled` = false ).
Would be easier if the property were: `che.keycloak.enabled`

**Comment by l0rd** [comment]
Agree that `che.keycloak.enabled` would be better naming

**Comment by l0rd** [comment]
Since it's going to disappear in the upstream multi user support we close the issue
