### ISSUE TITLE
"Git" menu items are disabled after workspace creation and only after a while become available"

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#230]
Non working account:
Safari: burr@redhat.com, bursutter on github, burrsutter, tatooine
Committer info and token are set correctly according to che-starter logs:

```
2017-07-26 19:14:12.888  INFO 1 --- [p1906808037-305] i.f.c.s.client.github.GitHubClient       : GitHub OAuth token has been successfully set via 'https://che-burrsutter-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/token/github'
--
  | {"time":"2017-07-26T19:14:12.888+00:00","msg":"GitHub OAuth token has been successfully set via 'https://che-burrsutter-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/token/github'","logger":"io.fabric8.che.starter.client.github.GitHubClient","thread":"qtp1906808037-305","level":"INFO","HOSTNAME":"che-starter-23-7f7dp","req_id":"52099e95-c80d-4196-be96-08365952c764","identity_id":"42c40980-bd10-4ba0-812e-b140c87b7e25"}
  | 2017-07-26 19:14:12.994  INFO 1 --- [p1906808037-305] i.f.c.s.c.WorkspacePreferencesClient     : Committer name: Burr Sutter
  | {"time":"2017-07-26T19:14:12.994+00:00","msg":"Committer name: Burr Sutter","logger":"io.fabric8.che.starter.client.WorkspacePreferencesClient","thread":"qtp1906808037-305","level":"INFO","HOSTNAME":"che-starter-23-7f7dp","req_id":"52099e95-c80d-4196-be96-08365952c764","identity_id":"42c40980-bd10-4ba0-812e-b140c87b7e25"}
```

**Comment by burrsutter** [comment]
https://screencast.com/t/IGLhwJwnTfO

**Comment by burrsutter** [comment]
Might be Safari specific as it works in FF (but with a different user account)

**Comment by ibuziuk** [comment]
from @burrsutter comment:
	

> 3:37 AM
> @ibuziuk Chrome + burrzinga does not have enabled Git menu items
> 3:37 AM
> and that was a perfectly clean account

**Comment by ibuziuk** [comment]
@sunix @benoitf do you guys know when "Git" menu is supposed to be disabled ? (no preferences / token set ?)

**Comment by benoitf** [comment]
@ibuziuk 
https://github.com/eclipse/che/blob/8e5967613daddac84d9e3ea0ef47d53d08dbd11e/plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/GitAction.java#L52

and 

https://github.com/eclipse/che/blob/d5de61bfb9e64691c68f6ea607fc443c3a71f2f9/plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitUtil.java#L32-L43

**Comment by ibuziuk** [comment]
@burrsutter When menu items are disabled, do you have committer info set in "Git" preferences ?

**Comment by ibuziuk** [comment]
@eivantsov any ideas about this issue ?

**Comment by eivantsov** [comment]
From what I see in the screencast I can say the following:

1. Current project isn't configured as a valid project. Can you see red cross on the project icon?
2. Project explorer shows hidden files and folders, but I do not see `./git` there.

If you initialize the repository Git menu items will be active but I am afraid you won't see the initial remote this repo has been cloned from.

Unfortunately, the screencast does not give enough context to even assume how a project ended up as a misconfigured project in a workspace.

**Comment by burrzinga** [comment]
one thing we have noticed today...if you wait a while...the menus become available
if you refresh the browser, the menus become available
it is apparently an async process that happens after the workspace comes up

**Comment by ibuziuk** [comment]
Created an issue upstream - https://github.com/eclipse/che/issues/5831

**Comment by l0rd** [comment]
An update on this from @eivantsov :

> https://github.com/eclipse/che/issues/5852 i believe when we fix this one it will fix this issue too
> 
> I suspect there are some race conditions sometimes:
> - ws agent starts
> - ide initializes, it does not find project sources but sees project in ws config.. marks it as broken...
> - then che-starter imports a project or is importing in parallel.. 
> - so by the  time the ide is up.. project sources is there, but the IDE still thinks it is a broken project.

**Comment by bmicklea** [comment]
FYI - prioritized as P1 in the IO Workshop kill list.

**Comment by l0rd** [comment]
@bmicklea updated severity here too to match IO Workshop kill list

**Comment by ibuziuk** [comment]
The same comment as for - https://github.com/redhat-developer/rh-che/issues/228
@ldimaggi @rhopp @Katka92 could you please verify this issue on prod ?
@bmicklea @burrsutter the project import logic has been significantly changed, so please let me know if all works for you

**Comment by ibuziuk** [comment]
Verified against che 1.0.294 
Closing
