### ISSUE TITLE
Population of workspace github preferences using Keycloak & GitHub API

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#231]
Need to implement the population of workspace github preferences using Keycloak & GitHub API.
Currently, che-starter uses wsmaster API for setting preferences, so first need to have mechanism in place for setting preferences per user or per workspace

**Comment by gorkem** [comment]
@benoitf can you confirm that wsmaster API is in fact multi-tenant ready?

**Comment by benoitf** [comment]
yes preferences API is multi tenant ready but there is no implementation of users/filters that manage different users in Che
Codenvy is using the same wsmaster API preferences implementation but has filters that assign current user

For example the token validator implementation in che  is always providing "che"
https://github.com/eclipse/che/blob/8e5967613daddac84d9e3ea0ef47d53d08dbd11e/wsmaster/wsmaster-local/src/main/java/org/eclipse/che/api/local/DummyTokenValidator.java

while in codenvy there is
https://github.com/codenvy/codenvy/blob/ca5ba8d98e66351bf8b89df28e7d73ac7c06bbaa/wsmaster/codenvy-hosted-sso-server-organization/src/main/java/com/codenvy/auth/sso/server/BearerTokenValidator.java

**Comment by ibuziuk** [comment]
> yes preferences API is multi tenant ready but there is no implementation of users/filters that manage different users in Che

@benoitf @gorkem my understanding is that I can move the logic of population preferences from che-starter to rh-che right now by using the same `/wsmaster/api/preferences` endpoint and it will become multitenant automatically once keycloak support [1]  will be in place with token validator in place. Does this sound right ?

[1] https://github.com/eclipse/che/issues/5362

**Comment by skabashnyuk** [comment]
@ibuziuk  what kind of  "workspace github preferences" you would like to see?

**Comment by ibuziuk** [comment]
@skabashnyuk committer name & email smth. that is set via `POST /wsmaster/api/preferences`

**Comment by skabashnyuk** [comment]
What is the user story? At what stage you want to set it? What is the flow?

**Comment by ibuziuk** [comment]
@skabashnyuk preferences are already set on osio via che-starter. This task is about moving this functionality from che-starter to rh-che plugin. Preferences are set just after workspace creation the user story would be "As a osio user I want to create workspace and have git preferences configured automatically"
![image](https://user-images.githubusercontent.com/1461122/29024560-ebc59564-7b72-11e7-8169-8e78009ce16a.png)

**Comment by skabashnyuk** [comment]
So in Multi-user, Multi-tenant Che it has to be done once, before first workspace usage? Am I correct?

**Comment by ibuziuk** [comment]
@skabashnyuk yes, since committer preferences are per user and not per workspace

**Comment by ibuziuk** [comment]
BTW, since multi-tenant Che will never be idled setting committer info could be even done on first login to osio

**Comment by gorkem** [comment]
I think it is a good idea to refresh the setting per workspace create/launch in case it is updated. Users will have no idea that they need to change Che's preferences on OSIO.

**Comment by skabashnyuk** [comment]
Where do you want to store them? Why is Eclipse Che preferences not the main storage?

**Comment by l0rd** [comment]
That will be needed when che-started will be deprecated. Deferring implementation.

**Comment by l0rd** [comment]
We need to verify that https://github.com/eclipse/che/issues/5943 will fix that

**Comment by ibuziuk** [comment]
was implemented for Che 6. Closing
