### ISSUE TITLE
KeycloakUserValidator could use local network subadress for decision

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/rh-che#232]
At the moment, solution to validate is relying on eclipse-che project, well, for eclipse-* project (parsing on dash, taking first). The more robust solution, working with any local OpenShift instance (or at least those allowing it from resources etc. POV) would be to get URL of the OpenShift instance via k8 client and check whether it fits to local area network sub-address or not.

**Comment by l0rd** [comment]
Not valid anymore
