### ISSUE TITLE
Verify if debugger still fails if not on incognito mode

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/rh-che#233]
Debugger fails with `Can not connect to localhost:5005` if the browser is not in incognito. Incognito seems to fix the problem

See also https://screencast.com/t/IB4yUf3w

**Comment by ibuziuk** [comment]
@gorkem @eivantsov  do we have upstream issue for this task?

**Comment by eivantsov** [comment]
I habe hard time reproducing this one. Will look at it closer tomorrow.

**Comment by ibuziuk** [comment]
@eivantsov great thank you!

**Comment by eivantsov** [comment]
Is this still an issue?

**Comment by l0rd** [comment]
@gorkem please let us know if you still have this issue

**Comment by l0rd** [comment]
I've tested it on OSIO (Che v2.0.23) and I could debug vertx booster without using incognito. I'm closing this issue.
