### ISSUE TITLE
Add debug commands for Vert.x and Spring Boot projects generated from OpenShift.io

### ISSUE THREAD

**Issue by bmicklea** [redhat-developer/rh-che#238]
We have two project types that users can start with in IO: Vert.x and spring boot. We need to add debug commands that appear by default when a Che workspace is started from IO.

Tasks:

- [] Add new "Debug" command to Vert.x projects
- [] Add new "Debug" command to Spring Boot projects

**Comment by ibuziuk** [comment]
@bmicklea @burrsutter new debug commands are added in Che version - 1.0.270
Hot deployment does not seem to work, so I have created a separate issue - https://github.com/redhat-developer/rh-che/issues/254
![image](https://user-images.githubusercontent.com/1461122/29086572-5ca4c236-7c73-11e7-95f2-35f8f25bd15b.png)

**Comment by ibuziuk** [comment]
Closing. feel free to reopen

**Comment by burrsutter** [comment]
We updated the Workshop doc today to reflect new Debug command for Vert.x (workshop does not current have debugging for Spring)
