### ISSUE TITLE
Figure out Keycloak auth for wsagent -- wsmaster communication when agent is in different namespace

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#246]
Our current implementation of Keycloak authentication depends workspaces being started in the same namespace as che-host. Once multitenancy is included, requests between workspace and che server will be blocked.

This may be easier to implement once Che supports multiple users, as it may be possible to know which namespace we expect requests to come from.

Currently, I don't see a good way of implementing auth between workspace and server that doesn't also allow a malicious user to use their OpenShift token to access other users' workspaces.

**Comment by l0rd** [comment]
already managed in eclipse/che now.
