### ISSUE TITLE
Run che-multiuser branch on OpenShift

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#247]
Che multi-user implementation is currently wip in upstream branch [che-multiuser](https://github.com/eclipse/che/tree/che-multiuser). It has been tested on Docker infrastructure but need to be run/tested on OpenShift. 

Note that:
- Tests should be done using current `eclipse/che` master branch OpenShiftConnector and not the OpenShift infrastructure implemented in the SPI branch
- For now we don't need to test multi cluster, multi namespace configurations: using one unique namespace for wsmaster and wsagents pods should be enough to validate multi-user implementation for openshift. Minishift can be used for that.

**Comment by l0rd** [comment]
cc @mshaposhnik @skabashnyuk

**Comment by davidfestal** [comment]
Submitted PR on upstream

**Comment by davidfestal** [comment]
https://github.com/eclipse/che/pull/6096

**Comment by davidfestal** [comment]
merged
