### ISSUE TITLE
Add KC token as a LS configuration and use LSP DidChangeConfiguration notification to push token updates (when it's renewed) to bayesian LS

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#248]
With https://github.com/redhat-developer/rh-che/issues/141 the last used user token is injected when the LS is starting. The goal of this task is to:
1. detect KC token changes more dynamically (client side?)
2. propagate the new token with DidChangeConfiguration to the Bayesian LS

**Comment by ibuziuk** [comment]
closing since Che 6  bayesian LS is deprecated. Bayesian plugin for Che 7 is implemented as part of the https://github.com/redhat-developer/rh-che/issues/1045
