### ISSUE TITLE
Run Test -> Run Test menu items are sometimes disabled in Project Explorer context menu

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#252]
Steps to reproduce:
- creare new space on osio with vert.x quickstart project
- once codebase is created start a workspace
- build vert.x project via "build" command
- right click on "OpenShiftIT" class in  Project Explorer
- ERROR: "Run Test" menu item is disabled:

![image](https://user-images.githubusercontent.com/1461122/28998113-b4940864-7a23-11e7-8468-d64b25085ff4.png)

**Comment by ibuziuk** [comment]
cc: @davidfestal ^
for now @burrsutter  recommend to use "mvn test" command during workshops

**Comment by ibuziuk** [comment]
looks like the Java class must be opened in editor to make the test items active

**Comment by eivantsov** [comment]
@ibuziuk this PR addresses it - https://github.com/eclipse/che/pull/5804

I have updated Che in my OSIO account (version dated Aug 4), and **can** see test menu items without opening files.

**Comment by ibuziuk** [comment]
@eivantsov could you please tell your che version ?

**Comment by eivantsov** [comment]
@ibuziuk  1.0.269

**Comment by ibuziuk** [comment]
@burrsutter @bmicklea verified on osio - closing
