### ISSUE TITLE
Error openshift_deploy.sh on Minishift

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer/rh-che#266]
the `devscripts/openshift.deploy.sh` fails with sed substitution for both OSO and minishift, especially when the sed substitution has urls in it. the sed script failed for `KEYCLOAK_OSO_ENDPOINT` and `KEYCLOAK_GITHUB_ENDPOINT` as they have patterns like `http://<some-url>`.

**Comment by eivantsov** [comment]
@kameshsampath it worked for me by the way. I am on Ubuntu 14.04. I think it is OS specific.

**Comment by amisevsk** [comment]
Also see #263

**Comment by l0rd** [comment]
#263 should have fixed that. @kameshsampath please re-open this issue if this is not the case.
