### ISSUE TITLE
Project import sometimes fails

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#285]
This is probably a followup of #228 
I've created workspace for vertx-wiki2 project from OSIO. The workspace gets created, but the project obviously not (it has rex X marker). Trying to expand the project, many dialogs pop up saying "Project vertx-wiki2 exists in workspace but does not exist in file system. Do you want to import project?".
![image](https://user-images.githubusercontent.com/1215011/29554286-d571e21a-871e-11e7-802d-3e3fb7560b0b.png)
I cannot get rid of those dialogs now: https://youtu.be/NZsbzwls6L0

**Comment by rhopp** [comment]
Edit: After a while, the project gets imported and those dialogs stopped to appear, so when i confirmed all those dialogs, everything seems ok.  But having so many dialogs is definitely bad thing.

**Comment by l0rd** [comment]
@rhopp how do you create the workspace? Did you use a quickstart or have you imported an existing project? If this was an existing project what is the github repo URL?

**Comment by rhopp** [comment]
@l0rd I've created workspace from OSIO codebases view. It was existing project: https://github.com/rhopp/vertx-wiki2

**Comment by ibuziuk** [comment]
@eivantsov do you happen to know if there is an upstream issue for this import dialog thingy? This issue is definitely coupled with changing the way of project import on che-starter side

**Comment by eivantsov** [comment]
@rhopp @ibuziuk it looks like an old version of Che is used. This dialogue should not popup and project import should happen automatically.

**Comment by rhopp** [comment]
I'm using OSIO che version 1.0.291.
Directly in Che UI, the version is empty 
![image](https://user-images.githubusercontent.com/1215011/29562779-05362d5a-873b-11e7-8fb0-75081983a7cf.png)

**Comment by eivantsov** [comment]
Got it now. Investigating.. slow network may do bad things here

**Comment by eivantsov** [comment]
Upstream issue: https://github.com/eclipse/che/issues/6075

This issue is related to slow network.

**Comment by ibuziuk** [comment]
Upstream issue is fixed and would be available on osio after migration to 5.19.0 release
