### ISSUE TITLE
Vertx stack debug command should include the compile goal

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#291]
Feedback from osio workshop:
vertx stack debug command should include the compile goal
See screenshot:
![selection_056](https://user-images.githubusercontent.com/650571/29672802-8d29e3c4-88ed-11e7-839e-508dc3af7440.png)

otherwise it won't take the latest changes in account when running debug command

**Comment by burrsutter** [comment]
We fixed this once before, did it go away?

**Comment by kameshsampath** [comment]
compile and package goals are must from the mvn command perspective as part of vertx-maven-plugin we don't tie to any maven lifecycle phase
