### ISSUE TITLE
Errors logged when starting a new workspace 

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#298]
https://github.com/openshiftio/openshift.io/issues/531

```
[STDERR] chown: changing ownership of ‘/projects’: Operation not permitted
.
.
.
[STDERR] chown: changing ownership of ‘/projects’: Operation not permitted
[STDERR] chmod: changing permissions of ‘/projects’: Operation not permitted
```

The strange thing is that it doesn't seem to be reproducible on minishift (just on osio)

**Comment by eivantsov** [comment]
Probably either output is to be sent to /dev/null or a prior check where a user has rights to do so is required: https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L58

**Comment by l0rd** [comment]
Need to verify if that has been fixed

**Comment by l0rd** [comment]
fixed
