### ISSUE TITLE
Activity service is not authorized (403) and introduce performance issue in Openshift.io

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#300]
![selection_058](https://user-images.githubusercontent.com/650571/29724919-b0bba786-89ca-11e7-90ed-8635e574c848.png)

**Comment by sunix** [comment]
Can reproduce locally with minishift with keycloak enabled

**Comment by l0rd** [comment]
Need to verify if this issue exist. May have been fixed upstream.

**Comment by l0rd** [comment]
Need to check if this has been fixed in multi tenant-che

**Comment by sunix** [comment]
I don't think we can reproduce with the new keycloak integration upstream, closing it. Will reopen if we see this issue again.
