### ISSUE TITLE
do the java based stacks have 'maven' enabled properly to get nicer folder navigation?

### ISSUE THREAD

**Issue by jstrachan** [redhat-developer/rh-che#31]
it sounds like the `maven project type` will enable nicer folder navigation to avoid this issue:
https://github.com/eclipse/che/issues/4749

I wonder if vertx / spring boot / WF Swarm stacks are properly including the maven project type to get nicer folder navigation?

**Comment by sunix** [comment]
Any project can have the `maven` project type. it is not defined in the stack but in the project definition. When creating/importing a project, che-starter adds the right project type.

**Comment by ibuziuk** [comment]
@jstrachan  stack -> projectType mapping is located in che-starter [1], so I believe this issue can be closed now 

[1] https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/model/stack/StackProjectMapping.java#L29
