### ISSUE TITLE
Use Logback JsonLayout for Che server logs on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#311]
Using @aslakknutsen words:

> We're currently looking at getting the CheHost logs etc pushed to the OSD Elastic as well. It would have been nice to get CheHost to log json so we don't have to deal with multi line exceptions etc

**Comment by sunix** [comment]
https://github.com/redhat-developer/rh-che/pull/341

**Comment by sunix** [comment]
upstream issue:
https://github.com/eclipse/che/issues/6537

**Comment by ibuziuk** [comment]
need to test with rh-che multi-user branch
