### ISSUE TITLE
Include OSIO identity_id and request_id in Che server logs 

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#312]
Using @aslakknutsen words:

> Since CheStarter forwards the Token and is within a X-Request-ID call from Core [we could] forward those values and CheHost log whatever it does including the identity_id and request_id. Then we could track a request all the way from UI via OSD to OSO

**Comment by skabashnyuk** [comment]
@l0rd I think @riuvshin and @skryzhny can help in this. We use to have additional logback appender on our prod. It can be a simular issue.

**Comment by l0rd** [comment]
Cool, thank @skabashnyuk for letting us know.

**Comment by ibuziuk** [comment]
changed priority to P1 - this issue is becoming utterly important for multi-tenant che-server IMO

**Comment by ibuziuk** [comment]
Closing. There is separate issue for improving che server json logs facilities - https://github.com/redhat-developer/rh-che/issues/495
