### ISSUE TITLE
Fix rh-che-ci-master on Codenvy CI

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#335]
Job https://ci.codenvycorp.com/job/rh-che-ci-master/ is failing. 

Fix for that should be done in a separate branch (e.g. `fixes-for-next-che-release`).

@riuvshin Once that is done `rh-che-ci-master` job should be modified so that it builds the `fixes-for-che-release`. Something like:
```bash
git clone https://github.com/redhat-developer/rh-che
cd rh-che
git checkout fixes-for-next-che-release
git rebase master || echo "ERROR: Rebasing branch 'fixes-for-next-che-release' on top of 'master' failed"; exit 1
# do the build as usual
```

**Comment by riuvshin** [comment]
haha! auto rebase as we discussed! :)  I can;t assign issue in that repo =/  but this is no an issue.

**Comment by benoitf** [comment]
I've pushed changes on `upstream` branch https://github.com/redhat-developer/rh-che/tree/upstream

**Comment by l0rd** [comment]
@riuvshin I will wait that you update the job definition to close this issue

**Comment by riuvshin** [comment]
so branch name will be `upstream` not `fixes-for-next-che-release` ?

**Comment by benoitf** [comment]
I've pushed with `upstream` branch but if you prefer I may rename it.

**Comment by riuvshin** [comment]
ok let's use `upstream` name

**Comment by riuvshin** [comment]
job updated, now it is green. Issue can be closed.

**Comment by l0rd** [comment]
Thanks @benoitf and @riuvshin
