### ISSUE TITLE
CentOS base stack: sshd fails to start

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#337]
![image](https://user-images.githubusercontent.com/606959/30505513-6c575912-9a75-11e7-9d2f-b6bf2e1e3762.png)

To reproduce it just run:

```bash
docker run --rm -ti registry.centos.org/che-stacks/centos-stack-base
```
you should see the following output:

```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
[user@ea91ad6b3be0 projects]$
```

**Comment by l0rd** [comment]
cc @dharmit

**Comment by eivantsov** [comment]
Add `sudo /usr/bin/ssh-keygen -A` to the entrypoint just before starting sshd

**Comment by JPinkney** [comment]
Can confirm that solution works ^, I tried it earlier but wanted to make sure I wasn't missing something
