### ISSUE TITLE
Move `builds/fabric8-che` maven project to root folder of rh-che

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#343]
Now that the invoker is not used anymore, it makes sense to move builds/fabric8-che to the root folder
This will envolves:
- updating all the scripts
- update CI (and test results location?)
- notify everybody working on other "big" task: can cause merge conflicts

**Comment by benoitf** [comment]
it would fix https://github.com/redhat-developer/rh-che/issues/328 as well

**Comment by benoitf** [comment]
fixed
