### ISSUE TITLE
Che workspaces should boot even if sshd fail to start

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#346]

**Comment by eivantsov** [comment]
@l0rd do you think disabling ssh agent for all stacks will do? And if a user wants to add it, Dashboard UI is always there?

Or changing logic of a a launcher checker maybe?

**Comment by l0rd** [comment]
I would like to change the logic of the launcher. If SSH launcher fails to start don't interrupt the workspace bootstrap. So I would add a field to launchers to specify if it's mandatory or not for. And the ssh launcher implementation should be not mandatory.
