### ISSUE TITLE
Package Che as a minishift addon

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#353]
Refer to https://github.com/minishift/minishift/issues/1264#issuecomment-329120040

**Comment by gorkem** [comment]
wonder if this can be easier once openshift can be provisioned through CLI?

**Comment by gbraad** [comment]
@gorkem can you provide some information about the provisioning through CLI? At the moment it is possible to use `oc clucter up` to get a local instance setup, and Minishift wraps this inside a virtual machine like a docker machine. The add-on approach would simplify the process to add Che to a current instance of Minishift.

**Comment by l0rd** [comment]
@gbraad it's about [Che CLI](https://www.eclipse.org/che/docs/setup/cli/index.html), the official way to run Che on Docker. Instead of running a bash script we use the CLI. That is basically a container that figures out the right command to start Che based on the platform (e.g. mac, windows, linux, is there a firewall). We call it the CLI because it can execute different commands (`start`, `info`, `upgrade`, `version`, `backup` etc...). 

@gorkem I don't think it would be easier but if we go with minishift addon first we will probably need to rework it when we move to the CLI. So I agree that CLI should be done first. I've sort them in that order in [the epic](https://github.com/eclipse/che/issues/6097#issue-253080141).

**Comment by gbraad** [comment]
I was confused by the wording. I have seen and proposed some fixes earlier for this part.

I'll leave things up to you... But I guess the rework is incorporating deploy to openshift (general case)?

**Comment by l0rd** [comment]
@gbraad if we go with the minishift addon first and we later update the script to install Che (from a single script to the CLI) we will want to update the minishift addon to use the CLI. That's because we want to have/maintain only one way to install Che.

**Comment by gbraad** [comment]
@l0rd I understand this point... no questions there. Just curious about the needed steps and see what can be be done to help.

**Comment by l0rd** [comment]
@budhrg @gbraad fyi @sunix has started working on that a couple of days ago

**Comment by budhrg** [comment]
> @sunix has started working on that a couple of days ago

Glad to know @l0rd thanks.

**Comment by kameshsampath** [comment]
it will be great if the addon can include the option to add `CHE_GITHUB_OAUTH` variables as that helps the user with one quick setup

**Comment by sunix** [comment]
minishift PR: https://github.com/minishift/minishift-addons/pull/43 merged

**Comment by gbraad** [comment]
Thanks again...
