### ISSUE TITLE
Don't fail starting a workspace if we cannot get a Persistent Volume for it

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#364]
**Issue problem:** 

When trying to start a Java-MySQL-CentOS workspace on openshift.io (via the dashboard) the following error appears in the OpenShift events:

```
"Created pod: che-ws-db-1668658746-xq73r"
"Successfully assigned che-ws-db-1668658746-xq73r to ip-172-31-79-58.us-east-2.compute.internal"
"pulling image \"172.30.98.11:5000/mloriedo-che/centos_mysql-57-centos7:che-ws-4gshokzfebs3ts0zf7hbptjs3lx599f\""
"Successfully pulled image \"172.30.98.11:5000/mloriedo-che/centos_mysql-57-centos7:che-ws-4gshokzfebs3ts0zf7hbptjs3lx599f\""
"Error syncing pod"
"Error: Error response from daemon: {\"message\":\"create 91d4a809a3147709f689adea5022c9191603df8240b95b3ca6fd8d990f353139: mkdir /var/lib/docker/volumes/91d4a809a3147709f689adea5022c9191603df8240b95b3ca6fd8d990f353139: permission denied\"}"
```

That is probably related to the fact that Che claims 3 Persistent Volumes (one for itself and 2 for the machines) but che namespace PV limit is set to 2. A fix would be to continue the machines bootstrap even if there are not enough PV available (providing a warning to the user because data are going to be lost as soon as the workpace is stopped). 

**Red Hat Che version:** 

version: 2.0.31

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Login to the Che dashboard on openshift.io, start a Java-MySQL-CentOS and look at the OpenShift events (`oc get events -w`)

**Runtime:**

runtime used:
   - [x] OpenShift.io

**Comment by ibuziuk** [comment]
I believe we can close this issue:
- it was created when che-server was single-tenant and in order to run mysql stack 3 PVC were required. Currently `Java-MySQL-CentOS` stack works just fine on che.openshift.io
- currently there is a support of ephemeral workspace that use `emptyDir` volumes instead of PVC.
