### ISSUE TITLE
Make the Bayesian plugin compatible with multi-tenancy token management

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#369]
Currently, the Keycloak token injected into the Bayesian plugin is retrieved in a way that cannot work with the upstream multi-user implementation (which is becoming the basis of the `rh-che` assembly)

**Comment by l0rd** [comment]
cf #248

**Comment by ibuziuk** [comment]
Duplicate of https://github.com/redhat-developer/rh-che/issues/376
