### ISSUE TITLE
Correctly manage the running workspaces when restarting multi-tenant che-server

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#370]
Currently, in the ongoing implementation of multi-tenancy based on the upstream multi-user assembly, the che server, if restarted, has no way to identify to workspaces that were previously left running, in order to do some cleanup at restart. This leads to errors when trying to access to these workspaces again.

This will be a problem when upgrading the che-server.

**Comment by l0rd** [comment]
The clean solution (don't need to stop/start workspace when the server is restarted) would be implemented in the SPI branch (to be confirmed). Until then we probably can implement a cache with user tokens mapped to each workspace. These tokens don't need to be persisted, they are just needed to stop workspace when master is shut down.
