### ISSUE TITLE
Installing multi-tenant Redhat Che distribution on a dedicated cluster for load testing / final testing before production

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#372]
Currently, during the implementation phase, multi-tenancy is tested on a small VPS server (for the che-server) and uses OSIO 'xxx-che' namespaces on the production OSIO cluster for workspaces.
It also uses a dedicated Postgres database deployed along with the che-server to the VPS server.
Last but not least, it is also limited to unsecure traffix (`http`) due to self-signed certificates used in the VPS.

We should setup a testing environment that points to an external Postgres database (as similar as possible to what would be used for production). We should probably also have the ability to create many workspaces for many different users simultaneously to get a first insight of how it manages the load related to concurrent users.

**Comment by l0rd** [comment]
@davidfestal can we close this one?

**Comment by davidfestal** [comment]
I assume since now we are at the next step (testing on pre-prod)
