### ISSUE TITLE
OS.io migration from single to multi-user Che: export and restore workspace metadata

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#377]
This is about creating a new script to export the metadata of a user's workspaces (in single user Che) and somehow re-import these data (in multi-user Che).

This script should be run once during single user to multi user migration and would help not losing users workspaces.

Workspaces data (source code) should be persisted in PV (that are never deleted) and the script should not handle it.

This is not a blocker but nice to have.

**Comment by l0rd** [comment]
After discussion today with @aslakknutsen and @ibuziuk the workflow of the migration is the one described below:

Migration happens when a user updates his tenant. If the user is in `deploy.che-multi-tenant` list:

- `init-tenant` deploys `fabric8-tenant-che-mt` in the user namespace
- `fabric8-tenant-che-mt`start a small application (`fabric8-tenant-che-migration`):
- When started `fabric8-tenant-che-migration`:
  - Checks if migration has already been done. If it's the case exit.
  - Retrieve workspaces metadata [1]
  - Export the data to the mt-che-server
  - Delete the single user che server resources (routes, services, dc, pods): don't delete PVs
  - Exit

When all users have been migrated to mt-che we can simply modify `fabric8-tenant-che-mt` to not deploy `fabric8-tenant-che-migration` anymore

Open questions:
- [ ] How will `fabric8-tenant-che-migration` retrieve mt-che URL? Should it be a new config map?
- [ ] How the user KC token will be provided? That will be needed for `fabric8-tenant-che-migration` to connect to Che

---
[1] To retrieve the metadata there can be two options:

1. Retrieve the data using the wsmaster API:
    - If the wsmaster is stopped start it
    - Call the API to export the metadata

2. Retrieve the data opening the files from the filesystem: 
    - If the wsmaster is running stop it
    - Create a PVC to mount the workspace-data PV
    - Retrieve the workspaces metadata data from the PV `/data/` folder

**Comment by aslakknutsen** [comment]
> How will fabric8-tenant-che-migration retrieve mt-che URL? Should it be a new config map?

I would simply put it as a 'static' ENV variable on the pod spec. Less to clean up after. :)

> How the user KC token will be provided? That will be needed for fabric8-tenant-che-migration to connect to Che

yea... good catch. @alexeykazakov ?

Maybe expose a special endpoint on the Che MT side that does the import which doesn't require a full token, but just a known secret or something. Then `fabric8-tenant-che-migration` adds 'who this is for' as part of the import request. What's the worst that can happen? Someone adds a non working workspace definition to my account (to get a working one it would be required to be on my PV?)? Change the Project to point to some owned repo that contains malicious code, but only if they know an existing workspace id that I have on my PV?

**Comment by l0rd** [comment]
To summarize the discussion we had this morning:

- `fabric8-tenant-che-migration` needs 2 environment variable:
   - `OSIO_TOKEN` with the kc token for the user => **provided by `init-tenant` as a secret**
   - `CHE_MT_SERVER`  => **provided as a config map**   
- `che-starter` should:
   - Verify if the migration for mt user has been completed or not (e.g. looking if the `che-host` pod exist in user namespace)
   - If the migration hasn't been completed it should automatically initiate a tenant update sending a `PATCH` request to the [tenant service endpoint](https://api.openshift.io/api/user/services).
