### ISSUE TITLE
Need to migrate to a new github token url

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/rh-che#379]
related to https://github.com/fabric8-services/fabric8-auth/issues/149

Related PRs:

- https://github.com/fabric8-services/fabric8-tenant-che/pull/46
- https://github.com/redhat-developer/rh-che/pull/381
- https://github.com/eclipse/che/pull/6809

Related init tenant issue - https://github.com/fabric8-services/fabric8-tenant/issues/414

**Comment by ibuziuk** [comment]
Migration is done - closing
