### ISSUE TITLE
multi-tenant che-server CI / CD onboarding for prod-preview / prod

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#395]
It was decide to have similar setup for promoting new versions of multi-tenant che-server to prod-preview / prod to the approach that is used in che-starter right now [1] - single template with config map (promotion to prod-preview happens automatically / promotion to prod requires manual step - PR to `saas-openshiftio`)

Onboarding guide  - https://docs.google.com/document/d/14rKA_Uxve5f_mFNK4vhKhXrMcquiy25AQ5tpHJQwtbc/edit#heading=h.2r3a4udhggjl
GitLab issue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/689

[1] https://github.com/redhat-developer/che-starter/tree/master/openshift-template
[2] https://github.com/openshiftio/saas-openshiftio/tree/master/dsaas-services

**Comment by ibuziuk** [comment]
@l0rd @davidfestal setting correct `che-workspace-che-server-endpoint` eliminates the need of RoleBinding - verified on https://glusterpoc37aws.devshift.net

**Comment by davidfestal** [comment]
great !

**Comment by ibuziuk** [comment]
This one is fixed. Closing
