### ISSUE TITLE
Ability to configure the Keycloak `minValidity` on the client side (GWT + Dashboard)

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#396]
This is required to ensure that a request would not be submitted to the wsmaster with a Keycloak token that would expire before the corresponding workspace becomes idled.   

This might be critical for having multi-tenant in production

**Comment by l0rd** [comment]
This doesn't look to be a problem in OSIO because the validity of a token = 1 day. It would be interesting for other OCP installations only.

**Comment by ibuziuk** [comment]
@davidfestal is this issue still relevant for Che 7 ?
