### ISSUE TITLE
Port multi-tenant changes to the Che6 branch 

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#397]
The multi-tenant changes were mostly implemented in the `OpenshiftConnector`, and some of the related changes that were implemented in other parts of upstream Che were not reintegrated into the Che6 development branch by the upstream team.

This task consists in implementing the equivalent changes in the che6 branch and testing them with `rh-che`, since the changes cannot be ported *as is*.

**Comment by l0rd** [comment]
This issue is being worked by the platform team
