### ISSUE TITLE
Help -> Community menu in Development Workspace is redirecting to openshift.io home page

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#398]
This issue is to schedule work for openshift.io issue https://github.com/openshiftio/openshift.io/issues/1159

**Comment by ibuziuk** [comment]
I believe we should redirect to https://mattermost.eclipse.org/eclipse/channels/eclipse-che, but we are not planning to work on this issue in the meantime. The issue should be closed once che 7 is going to be the only option for che.openshift.io (Theia does not have Help -> Community / only Help -> About)

**Comment by ibuziuk** [comment]
Should be closed once we update che.openshift.io to Che 7 GA
