### ISSUE TITLE
Update `init-tenant` script for multi-tenant 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#404]
- [x] Update `init-tenant` script (**with platform team**):
  - [x] Create a new script to deploy Che on dsaas
  - [x] Support list of namespaces / users which are multi-tenant ready and don't deploy che server in their tenant spaces anymore.
  - [x] `init-tenant` should create PVC `claim-che-workspace` in `che-*` namespaces.
  - [x] Create a script to cleanup `*-che` namespaces (do not delete `claim-che-workspace`)

**Comment by ibuziuk** [comment]
@l0rd I think we can close this one. WDYT ?

**Comment by l0rd** [comment]
yes. Thanks @ibuziuk great great job!
