### ISSUE TITLE
.NET workspace will not start

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#412]
**Issue problem:** 
.NET workspace will not start.
Log:
```
017-11-07 09:07:05,608[aceSharedPool-3]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 158]  - An error occurs while starting 'Exec' agent in 'workspacetfui8kwly8tut818' workspace in 'machinercectb0htzx0255m' machine on 'localhost' node. Detailed log:
--
  | [STDOUT] Exec Agent binary is downloaded remotely
  | [STDERR] chown: changing ownership of ‘/projects’: Operation not permitted
  | [STDERR]
  | [STDERR] gzip: stdin: unexpected end of file
  | [STDERR] tar: Child returned status 1
  | [STDERR] tar: Error is not recoverable: exiting now
  | [STDERR] /bin/sh: line 226: /home/user/che/exec-agent/che-exec-agent: No such file or directory
```

**Red Hat Che version:** 
Che : 2.0.46
version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Start .NET stack workspace from Che dashboard.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by eivantsov** [comment]
@rhopp are you talking about eclipse/dotnet_core image?

**Comment by rhopp** [comment]
@eivantsov It's about this one: https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L265

**Comment by eivantsov** [comment]
Is this still an issue?

**Comment by rhopp** [comment]
Yep. Tried it today on prod OSIO and the workspace failed to start with exactly the same error.

**Comment by eivantsov** [comment]
You need to make sure that this image does something like this: https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/ubuntu_jdk8/Dockerfile#L38

**Comment by l0rd** [comment]
@eivantsov does https://github.com/eclipse/che-dockerfiles/pull/159 fix this?

**Comment by eivantsov** [comment]
Not really, but since the base image has been rebuilt some time ago, a new build of dotnet image should be ok. At least I can confirm now that an arbitrary user can create dirs in home directory and `/projects`

**Comment by rhopp** [comment]
Closing as duplicate of https://github.com/redhat-developer/rh-che/issues/513
