### ISSUE TITLE
multi-tenant images do not override upstream stacks to rh-che ones

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#429]
**Issue problem:** 
rh-che multi-tenant images [1] for some reason do not override stacks.   

https://hub.docker.com/r/rhche/che-server-multiuser/tags/

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**
deploy multi-tenant che-server to prod-preview or glusterpoc37aws.devshift.net 
ERROR: After navigating to the dashboard stacks would be upstream no rh-che

**Comment by ibuziuk** [comment]
This problem is not reproducible against `b5919a9-fabric8-8808a8d` (7 days old)
Trying to figure out what is causing it

**Comment by ibuziuk** [comment]
Also works with `df1a722-fabric8-bed56da` (6 days old)

**Comment by ibuziuk** [comment]
Works fine with `a17f120-fabric8-808bc0e` (5 days old)

**Comment by ibuziuk** [comment]
Works fine with `703f8ed-fabric8-d344377` (4 days old)

**Comment by ibuziuk** [comment]
Was able to reproduce against `f8256a2-fabric8-dcbb673` (1 day old)

**Comment by ibuziuk** [comment]
from rh-che side the difference between working & non working images is the following commit [1] "Bayesian compatibility and workspace cleaning with multi-tenancy" which does not seem to be related to the issue. Looking into upsream...

[1] https://github.com/redhat-developer/rh-che/commit/dcbb67342de0b2ff895776cfdaed4b6ff4973edb

**Comment by riuvshin** [comment]
as I understand that issue is about `replace_stacks.sh`
AFAIK that script never supported multitenant usecase, a while ago I was wokring on my own to adopt it but then I switched to `che6` where we don't need that script anymore, but issue was only with auth. As in multitenant che you can't do api calls without auth. let me know if your issue is the same I will take a look maybe I still have that branch

**Comment by ibuziuk** [comment]
Nope, it is not about `replace_stacks.sh` https://github.com/redhat-developer/rh-che/pull/432/files
it was about loading 2 versions of stack.json (upstream / rhche) and depending on classloading sequence upstream / rhche stacks were used. David provided a fix so we can now close this one
