### ISSUE TITLE
Create a new Che status icon that shows multi-tenant Che status

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#450]
That should be deployed only after every osio user has been migrated to mt che

**Comment by ibuziuk** [comment]
PRs for docs and ui are merged:
- https://github.com/fabric8-ui/fabric8-ui/pull/2299
- https://github.com/openshiftio/openshift.io/pull/1558

Will close the issue once the new fake staus icon will be avilable on prod

**Comment by ibuziuk** [comment]
new icon is available on prod - closing
