### ISSUE TITLE
Use one OkHttpClient for Che server

### ISSUE THREAD

**Issue by akorneta** [redhat-developer/rh-che#472]
Since we reworked the way of interacting with `OpenShiftClient` in Che _che6_ branch(now we use only one instance for all the requests). But it doesn't work in this way for multi-tenant che as one `OpenShiftClient` uses only one master url and user's credentials while multi-tenant che interact with OpenShift clusters with current user's token.
So, it is proposed to use one `OpenShiftClient` for one OpenShift cluster. And for resolving issue with using token of current user it is needed to write custom `OpenShiftClient` implementation with `OAuthInterceptor` which is context dependent.

The proposals of other options are welcome.

**Comment by l0rd** [comment]
https://github.com/eclipse/che/pull/7793

**Comment by l0rd** [comment]
Before closing this issue we need to make sure that the PR are ported to che6 branch

**Comment by l0rd** [comment]
Closing this one. The remaining work will be tracked by https://github.com/redhat-developer/rh-che/issues/516
