### ISSUE TITLE
NPE's when resetting osio env right after deleting che workspaces.

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#473]
**Issue problem:** 
I've used my multitenant account
Steps to reproduce:
1) have some workspaces in che dashboard
2) In che dashboard (che.openshift.io), delete those workspaces.
3) Immediately after that navigate to openshift.io -> Profile -> update profile -> Reset environment

Result: https://pastebin.com/DraEBjbH

What probably happened: Deleting workspaces spawned cleanup pods in user's oso, but before they did their job, they were killed by environment reset, resulting in NPE's.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
I think that this issue is not actual. Feel free to reopen if you think otherwise.
