### ISSUE TITLE
Prepare migration for workspace files

### ISSUE THREAD

**Issue by sleshchenko** [redhat-developer/rh-che#477]
In Che 5 sources of workspace's projects are stored in the following path `{WORKSPACE_NAME}/projects` folder. See the corresponding [OpenShiftConnector code](https://github.com/eclipse/che/blob/master/plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java#L1987
).
But it leads to the following problem https://github.com/eclipse/che/issues/3574.
To avoid such issues Che 6 uses workspace id instead of name in the path to projects sources. See the corresponding [subpath calculation code](
https://github.com/eclipse/che/blob/013d4bb05820283dc3cb4178a0ddaf341bcf6ad3/infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/pvc/CommonPVCStrategy.java#L172).
So, it is needed to prepare migration which will move projects sources according to new subpaths approach while updating Che server to 6 version.

**Comment by l0rd** [comment]
To address that we may reuse the fabric8-tenant-che-migration application we used for multi tenancy migration (cc @davidfestal )

**Comment by davidfestal** [comment]
The migration has been implemented [here](https://github.com/fabric8-services/che-tenant-maintainer) and is available as an internal REST service application in dsaas services.

@l0rd should we wait for the migration to be finished for all users to close this issue ?

**Comment by l0rd** [comment]
@davidfestal we can close it now
