### ISSUE TITLE
Run multi-tenant `rh-che` using the minishift add-on

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#489]
Currently the multi-tenant `rh-che` cannot work out-of-the-box on Minishift, since it tries to create the user workspace pods( and other resources) in the OSIO user namespace. We should provide a way (property ?) that allows overriding the cluster / namespace where the workspace OpenShift resources are created.

**Comment by davidfestal** [comment]
2 PRs have been opened to fix this issue:
- PR https://github.com/redhat-developer/rh-che/pull/498. This one should be mergeable and shouldn't change anything in the multi-tenant case.
- PR https://github.com/eclipse/che/pull/7976 made some required changes to the upstream `deploy_che.sh` script. However in the meantime, che6 has been merged to `master` so that conflicts arose. So it should probably be rebased on the che5 branch that will be created soon.
In the meanime, one could use the `deploy_che.sh` script that can be found there:
https://github.com/davidfestal/che/blob/fix-rh-che-489/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh

### How to deploy to Minishift after this fix:

When those 2 PRs are merged to the appropriate branch, Rh-Che on Minishift will simply be started this way with the `deploy_che.sh` script:

```
export CHE_FABRIC8_MULTITENANT=true
export OPENSHIFT_FLAVOR=minishift
deploy_che.sh 
```

This will use the RedHat production Keycloak server by default.

Or

```
export CHE_DEDICATED_KEYCLOAK=true
export CHE_FABRIC8_MULTITENANT=true
export OPENSHIFT_FLAVOR=minishift
deploy_che.sh 
```
 
if one wants to deploy / use a dedicated Keycloak server inside Minishift as well.

**Comment by l0rd** [comment]
@davidfestal can we close this issue now that both PR have been merged?

**Comment by davidfestal** [comment]
I didn't close it for now since we might have to change some documentation, but first one question arises : do we really want the users to clone branch `5.22.x` to get the right `deploy_che.sh` script ? 

And even when a `5.22.1` version is released, do we want users to clone this tag release to get the right file ?

However, as soon as `5.22.1` is released, we would have the ability to use `docker run che-init -e INIT_VERSION=5.22.1` to retrieve the deployment scripts in some intermediate local directory, and call the `deploy_che.sh` script from there.
And these 2 steps (as well as setting of required env variables) should probably be gathered in a script available in `rh-che` IMO to simplify things for users.

**Comment by l0rd** [comment]
In order to address this issue we should now:
- [ ] Extend the [minishift add-on](https://github.com/minishift/minishift-addons/tree/master/add-ons/che) to be able to run rh-che
- [ ] Improve rh-che README.md to explain how to run rh-che on using the minishift add-on
