### ISSUE TITLE
Pre-pull booster docker images on a daily basis

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#494]
**Issue problem:** 
One of the bottlenecks of a workspace creation is the pull of a new image. We could improve that using a "warm up" pod for pre-pulling the Docker images on a daily basis.

This was an issue that we closed in the past [without fixing it](https://issues.jboss.org/browse/CHE-132) but it makes sense now because images change at least once a day.

**Comment by ibuziuk** [comment]
Closing as duplicate
Should be addressed via `k8s-image-puller` - https://github.com/redhat-developer/rh-che/issues/1226
