### ISSUE TITLE
identy_id and req_id are not available in production logs

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#495]
**Issue problem:** 
It looks like the `identy_id` and `req_id` fields in the wsmaster json logs are not available in production. Here is an example:

```json
{"@timestamp":"2017-12-19T10:47:40.900+00:00","@version":1,"message":"Port: 4401/TCP (wsagent)","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftConnector","thread_name":"WorkspaceSharedPool-6","level":"INFO","level_value":20000}
```

**Comment by l0rd** [comment]
cc @sunix @ibuziuk

**Comment by ibuziuk** [comment]
@sunix it looks like MDC context is lost at some point on che-server side: Here is the example of production logs:

```
{"@timestamp":"2017-12-19T09:25:25.789+00:00","@version":1,"message":"Workspace 'workspace2pkpzdr2uab0q6x0' removed by user 'rhopp-osiotest1'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-7","level":"INFO","level_value":20000,"req_id":"1t67dcqobaw5yot1","identity_id":"25235c85-b434-4572-872d-b7c6a6d7d992"}
--
  | {"@timestamp":"2017-12-19T09:25:25.799+00:00","@version":1,"message":"Synchronously deleting workspace workspace446m4h2g7383git7 on PVC claim-che-workspace","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftConnector","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-37","level":"INFO","level_value":20000}
  | {"@timestamp":"2017-12-19T09:25:25.799+00:00","@version":1,"message":"Deleting 1 workspaces on PVC claim-che-workspace","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftConnector","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-37","level":"INFO","level_value":20000}
```
As you can see only the first entry contains `"req_id":"1t67dcqobaw5yot1","identity_id":"25235c85-b434-4572-872d-b7c6a6d7d992"` and the next two are missing it. You might be interested in the way how che starter handles MDC for async requests [1] (in che-starter logs every single entry contains req_id / identity_id info)


[1] https://github.com/redhat-developer/che-starter/commit/5ba7ca3fc9ea5ef80b50e90ac347849a71a92ccf#diff-2212776c28aa332b97900d4d222b22f3R23

**Comment by sunix** [comment]
I guess things get lost when jobs are scheduled in other thread pool. MDC is per thread. But would need further investigation on specific cases.

**Comment by sunix** [comment]
```
"thread_name":"http-nio-8080-exec-7"
"thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-37"
"thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-37"
```
There is no magic, if we want to keep reqid,  it needs to be done programatically for anything calls that invoke another thread pool.

**Comment by garagatyi** [comment]
Not sure whether it is useful but just FYI https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/concurrent/ThreadLocalPropagateContext.java#L45-L45
https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L234-L234

**Comment by ibuziuk** [comment]
@sunix by programatically you mean pass it as a method parameter ?

**Comment by sunix** [comment]
@garagatyi interesting, the thing is that MDC is not using thread local but a similar mechanism ... will investigate

**Comment by sunix** [comment]
@ibuziuk yes programatically like it is done in your link https://moelholm.com/2017/07/24/spring-4-3-using-a-taskdecorator-to-copy-mdc-data-to-async-threads/
```
copy = MDC.getCopyOfContextMap();
```
and reapplying it in each new threads

**Comment by sunix** [comment]
The first iteration will be focus on che6 and workspace create/start/stop/delete
