### ISSUE TITLE
Need to remove toggle related / workspace migration code from init tenant

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#497]
Migration to multi-tenant che-server has finished, so all toggle / workspace migration related code from che-starter & init-tenant

che-starter issue - https://github.com/redhat-developer/che-starter/issues/255

**Comment by l0rd** [comment]
che-starter has been done

**Comment by ibuziuk** [comment]
Usage of the multi-tenant toggle has been removed from init-tenant as part of the following PR


[1] https://github.com/fabric8-services/fabric8-tenant/pull/690/files

**Comment by ibuziuk** [comment]
I believe we can close this issue now
