### ISSUE TITLE
Add workspaceID-userID link in Che 6 

### ISSUE THREAD

**Issue by sleshchenko** [redhat-developer/rh-che#501]
**Issue problem:** 
Now the current subject is used while OpenShift client creating. But there are cases when there is no subject in EnvironmentContext (stopping workspaces by idle timeout). In this case, it is needed to use the cached subject that started the corresponding workspace.

So it is needed to move [WorkspaceSubjectsRegistry](https://github.com/redhat-developer/rh-che/pull/461/files#diff-d28c1c68acc9e74cd958355a8156159a) into fabric8-multi-tenant-manager or separated maven module. Then use it while OpenShift client creating.

**Comment by sleshchenko** [comment]
blocked by https://github.com/redhat-developer/rh-che/pull/461

**Comment by dmytro-ndp** [comment]
Side affect of the issue: when workspace is stopped by idle timeout linked services, pods, routes are stayed untouched and user can quickly reach limit of service number = 5.

**Comment by sleshchenko** [comment]
@dmytro-ndp Thanks for reporting a bug. It happens because of OpenShift token lack when there is not Subject in Environment while removing OpenShift objects. I believe use cached subject while OpenShift client creating will fix the described bug.

**Comment by dmytro-ndp** [comment]
Another problem: error of start of workspace which was stopped by idle timeout:
```
Could not start workspace workspacewts51s. Reason: Failure executing: POST at: https://api.free-stg.openshift.com/api/v1/namespaces/dnochevn-che/pods. Message: pods "workspacet3o9kushs7xp8hvb.dockerimage" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=pods, name=workspacet3o9kushs7xp8hvb.dockerimage, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "workspacet3o9kushs7xp8hvb.dockerimage" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
```
![screenshot from 2018-01-23 16-25-31](https://user-images.githubusercontent.com/1197777/35281007-7df5f08e-005a-11e8-8907-21646cc860bc.png)

Next start was successful.

**Comment by l0rd** [comment]
Cached subjects are not needed anymore, but a link between workspaces and users should be kept to be able to idle workspaces.

**Comment by sleshchenko** [comment]
@l0rd So, maybe for getting user by workspace id we can use `Workspace#getRuntime#getOwner`. As far as I understand now it should contain user name https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L209-L210.

**Comment by davidfestal** [comment]
@sleshchenko I'm already preparing a PR where I have added the `userId` in the `RuntimeIndentity`. It's tested locally and works fine.

**Comment by sleshchenko** [comment]
@davidfestal Great! :+1:
