### ISSUE TITLE
.NET CentOS workspace is not working on osio

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#505]
**Issue problem:** 
.NET CentOS workspace fails to start with error 
```
Could not start workspace wksp-uqwt. Reason: Start of environment 'default' failed. Error: Fail launching agent Exec. Workspace ID:workspacefxs0syn09dm2rvub
```
```
[STDOUT] Deploying com.redhat.bayesian.lsp server
[STDERR] mkdir: cannot create directory ‘/home/user/che/ls-bayesian’: Permission denied
[STDERR] sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
[STDERR] sudo: no valid sudoers sources found, quitting
[STDERR] sudo: setresuid() [0, 0, 0] -> [1025070000, -1, -1]: Operation not permitted
[STDERR] sudo: unable to initialize policy plugin
[STDERR] /bin/sh: line 149: cd: /home/user/che/ls-bayesian: No such file or directory
[STDERR] tar (grandchild): bzip2: Cannot exec: No such file or directory
[STDERR] tar (grandchild): Error is not recoverable: exiting now
[STDERR] tar: Child died with signal 13
[STDERR] tar: Error is not recoverable: exiting now
[STDERR] curl: (23) Failed writing body (3508 != 16360)
[STDERR] touch: cannot touch ‘/home/user/che/ls-bayesian/launch.sh’: No such file or directory
[STDERR] chmod: cannot access ‘/home/user/che/ls-bayesian/launch.sh’: No such file or directory
[STDERR] /bin/sh: line 158: /home/user/che/ls-bayesian/launch.sh: No such file or directory
[STDOUT] Exec Agent binary is downloaded remotely
[STDERR] 
[STDERR] gzip: stdin: unexpected end of file
[STDERR] tar: Child returned status 1
[STDERR] tar: Error is not recoverable: exiting now
[STDERR] /bin/sh: line 228: /home/user/che/exec-agent/che-exec-agent: No such file or directory
```

**Red Hat Che version:** 

Version :1.0.0-SNAPSHOT
Revision :dd729a5680603cba
Build Time :2017-12-18 13:39:11

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Try to create .NET CentOS workspace

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment]
Duplicate of #412?

**Comment by amisevsk** [comment]
Should be resolved as part of PR https://github.com/redhat-developer/che-dockerfiles/pull/37, which changes dockerfile to install C# lang server.

**Comment by ibuziuk** [comment]
@amisevsk great I can reproduce on the current .net image used on osio `registry.devshift.net/che/centos_dotnet20`

![image](https://user-images.githubusercontent.com/1461122/42895044-edf08e2e-8ab8-11e8-88f6-6c1cfce33c34.png)

**Comment by amisevsk** [comment]
I believe this issue is fixed as of https://github.com/redhat-developer/che-dockerfiles/pull/37. @rhopp Can you confirm?

**Comment by rhopp** [comment]
Yep... Workspace startup is OK now. I've created another issue though with .NET stack: https://github.com/redhat-developer/rh-che/issues/505
