### ISSUE TITLE
Need to gracefully manage the starting of a stopped workspace with already existing resources

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#507]
Related openshift.io issue - https://github.com/openshiftio/openshift.io/issues/1733
The situation when workspace resources still exist when trying to start a stopped workspace can be reproduced the following way:

1. start workspace
2. log out from osio
3. after some time workspace idling is triggered
4. ERROR: when che-server tries to stop workspace the token is already invalid and as a result workspace will not be stopped and resources will not be cleaned correctly 
5. Log in to osio and start a new workspace
6. ERROR: failure while workspace startup due to the fact that openshift resources from the previous workspace were not cleaned correctly

in OpenShift connector we could possibly do the cleanup of the resources when this situation appeare, and send a retry message with explanation. At least this would eliminate the need of manual cleanup of the user namespace and make the problem less critical / improve UX

**Comment by l0rd** [comment]
Not relevant for Che 6 anymore (needs a different implementation)
