### ISSUE TITLE
Port "Use one OkHttpClient for Che server" to Che v6

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#516]
This is about porting this 2 PRs to Che v6 https://github.com/eclipse/che/pull/7935 and https://github.com/eclipse/che/pull/7793 that were related to https://github.com/redhat-developer/rh-che/issues/472

**Comment by davidfestal** [comment]
related rh-che issue: https://github.com/redhat-developer/rh-che/issues/472
