### ISSUE TITLE
pcp/pmcd/prometheus monitoring extensions for workspace pod

### ISSUE THREAD

**Issue by fche** [redhat-developer/rh-che#522]
Similarly to what we had for the OSO che server (before multitenant), we need something analogous for the OSO workspace pod.  We'd be glad to help prototype this part, but need a pointer as to the part of che that constructs / deploys the workspace docker images.  cc: @l0rd

**Comment by l0rd** [comment]
@fche how urgent is this? It's ok if we schedule it for next sprint (in 3 weeks)?

**Comment by fche** [comment]
@l0rd, hard to say.  The sooner the better.  Can we help?

**Comment by l0rd** [comment]
@fche Dockerfiles for Che workspaces pods in OSIO are here https://github.com/redhat-developer/che-dockerfiles/

**Comment by fche** [comment]
@l0rd, thanks, can you point also to the code that merges those images into a DC to launch in the OSO namespace?

**Comment by l0rd** [comment]
@fche there is no such a DC. Che is creating the DC dynamically when you start the workspace.

Anyway to test your image you don't need to build Che. You can just run Che (on openshift, docker or osio) and edit a stack configuration (see the [doc](https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html#configuring-stacks)). You will need to replace the original image with your new image in the recipe location.

**Comment by l0rd** [comment]
@fche is it ok if we close that now after discussions we had during the osio f2f?

**Comment by fche** [comment]
I suspect we'll end up having to reopen this anyway - even if we somehow finagle remote API access to that prometheus server, it is unlikely to include user-level instrumentation metrics.  And exfiltrating that data would require this sort of machinery.
