### ISSUE TITLE
Bayesian not working in rh-che on prod-preview.

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#524]
openshift.io issue - https://github.com/openshiftio/openshift.io/issues/2063

**Issue problem:** 
 

**Red Hat Che version:** 

version:
```
Version :1.0.0-SNAPSHOT
Revision :f13fb48c0c4a31fb
Build Time :2018-01-15 09:43:18
```

 - [✔] I can reproduce it on latest official image

**Reproduction Steps:**

* Create a `vert.x` or `CentOS-JDK` project from template
* Open `pom.xml` or `package.json`
* Type in a dependency with incorrect or dangerous version
  - e.g.:  
    - `"serve-static": "1.7.1"` for `vert.x`
    -  for `CentOS-JDK` :
    ```
        <dependency>                            
            <groupId>ch.qos.logback</groupId>       
            <artifactId>logback-core</artifactId>   
            <version>1.1.10</version>               
        </dependency>
    ```

**Runtime:**

runtime used:
   - [❌] minishift (include output of `minishift version`)
   - [✔] OpenShift.io [prod-preview]
   - [❌] Openshift Container Platform (include output of `oc version`)
   - [❌] k8s (include output of `kubectl version`)

**Comment by ScrewTSW** [comment]
![automated_test_json](https://user-images.githubusercontent.com/16451875/35336977-4a1b56a8-011a-11e8-8833-762ac91e07e8.png)
![manual_test_maven](https://user-images.githubusercontent.com/16451875/35336991-510fc282-011a-11e8-873d-4bfa2a908f03.png)

**Comment by ibuziuk** [comment]
@ScrewTSW @rhopp is it reproducible on prod ?

**Comment by ScrewTSW** [comment]
@ibuziuk It works on prod, prod-preview has the issue and it happens every time

**Comment by ibuziuk** [comment]
@lord @davidfestal probably some regression introduced with `5.22.1` update

**Comment by lord** [comment]
yea I bet that's it

**Comment by l0rd** [comment]
@ScrewTSW would it possible to try to deploy in dev cluster Che 5.20.1 and 5.20.0 and verify if the problme is reporducible on 5.20.1 only? I'm afraid that this could be related to prod-preview environnment.

**Comment by ScrewTSW** [comment]
@l0rd Yes, I will do that first thing tomorrow :)

**Comment by l0rd** [comment]
cool thanks @ScrewTSW

**Comment by rhopp** [comment]
@l0rd I have 5.22.1 deployed on dev.rdu2c here: https://che-rhopp-che-test.dev.rdu2c.fabric8.io/ configured to run agains prod-preview (keaycloak etc.) and this issue is present there.

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW could you verify if the problem is reproducible against `Che 5.22.0` - this version of che is deployed on prod

**Comment by ibuziuk** [comment]
che was updated on prod and the problem is still not reproducible on prod. @ScrewTSW @rhopp Please, open github issue for openshift.io regarding this problem (looks like some misconfiguration)  
[1] https://github.com/openshiftio/saas-openshiftio/pull/560

**Comment by ScrewTSW** [comment]
@ibuziuk https://github.com/openshiftio/openshift.io/issues/2063

**Comment by ibuziuk** [comment]
bayesian ls support was removed as part of the https://github.com/redhat-developer/rh-che/pull/1481/commits. Bayesian will be supported via vscode extention in Che 7 https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics
