### ISSUE TITLE
Support multiple public Keys when validating access token signatures

### ISSUE THREAD

**Issue by alexeykazakov** [redhat-developer/rh-che#525]
Che should load all the keys from Identity provider. Not just the first one. For example OSIO Auth service returns multiple keys - https://auth.openshift.io/api/token/keys
Each key has an ID (kid). And each token has a kid header which refers to the key used to sign the token. So, Che should check kid in the token and use the corresponding public key to validate the token.

It's required to support key rotation when we add a new key then when all tokens are refreshed/re-generated we remove the deprecated key. It allows key rotation without any need to re-login.

**Comment by l0rd** [comment]
Closing because #502 will take care of it
