### ISSUE TITLE
Use an OpenShift Template in eclipse/che and find a better location

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#528]
Currently in eclipse/che [che-openshift.yml](https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/che-openshift.yml) describes a `List` of OpenShift resources to deploy che-server on OpenShift. 

Instead we should use an OpenShift `Template` (as the in minishift-addon and rh-che) and we should find a better location for it (currently it's in the `dockerfiles/init/` folder but it doesn't make really sense to be there).

**Comment by l0rd** [comment]
cc @benoitf

**Comment by l0rd** [comment]
Sync with Eugene and should be part of https://github.com/eclipse/che/issues/8729

**Comment by l0rd** [comment]
The first template should be for multi-user Che with Keycloak and postresql. And the goal is to be able to add Che in the OpenShift applications catalog.

**Comment by garagatyi** [comment]
I suggest changing structure in the following way:
```
che/
|----core/
|----dockerfiles/
|----deploy/
         |----kubernetes/
                  |----helm/
                          |----README.md
                          |----helm.yaml
         |----openshift/
                 |----template/
                          |----README.md
                          |----che-config.yaml
```

**Comment by l0rd** [comment]
From @benoitf 

> I was thinking that there was also an issue on splitting to some repositories
> Also I would say that dockerfiles directory is kind of "catchall" as it contains cli and che server image and docker deployment so maybe there is a need of a moving more stuff from dockerfiles or getting rid of rid

**Comment by l0rd** [comment]
@garagatyi by the way helm convention requires that `chart.yaml` (`helm.yaml`) lives in a folder that has the helm chart name. Something like:

```
         |----kubernetes/
                  |----helm/
                          |----eclipse-che-ide
                                  |----README.md
                                  |----helm.yaml
```

**Comment by garagatyi** [comment]
@l0rd AFAIK Joseph Callen has already done some work on adding Che to the service catalog using ansible playbook. Also, PR from Eugene doesn't contain a single template for Che - some manual steps are still required.
Can you elaborate on what is needed to be done for this issue?
