### ISSUE TITLE
Work with Che Platform team and SD team to make Che upgrade on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#545]
- [ ] Work with Che Platform team to check if the https://github.com/eclipse/che/issues/8547 would be fixed by the end of this sprint
- [ ] Work with Service Delivery team to work on alternative 3 of https://docs.google.com/presentation/d/132NrNTw6mySXNSzVqqep9rgZQLojlxlpLykw0dGAUfs/edit?usp=sharing

**Comment by ibuziuk** [comment]
Closing as outdated
