### ISSUE TITLE
Retrieve the `keycloak.js` file from the official NPM package instead of bundling our own

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#546]
Retrieve the `keycloak.js` from the official Keycloak NPM package to include it into upstream Che, now that PR https://github.com/keycloak/keycloak/pull/4978 has been merged.

Of course, we should wait for a new Keycloak version to be released first.

**Comment by skabashnyuk** [comment]
Is it published on NPM registry already?

**Comment by ibuziuk** [comment]
@davidfestal the PR https://github.com/keycloak/keycloak/pull/4978 has been merged, should we prioritize this issue to make the auth flow more sustainable ?

**Comment by davidfestal** [comment]
Not sure it's really high-priority currently.

**Comment by ibuziuk** [comment]
@davidfestal sure it might be not a priority, just wondering if this issue is still relevant so that we could prioritize it (I'm doing issue triage and want to close irrelevant issues)

**Comment by ibuziuk** [comment]
Closing as won't fix
