### ISSUE TITLE
Che 6: GitHub plugin is included in che 6 build

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#570]
**Issue problem:** 
GitHub plugin is available in che 6, but it should be excluded from `rh-che6` build:
![github_plugin](https://user-images.githubusercontent.com/1461122/37030163-34a775c8-213a-11e8-94fe-8c6da4cbb8ad.png)

**Red Hat Che version:** 

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by skabashnyuk** [comment]
@ibuziuk  your image was related to contribution plugin. Are you sure you need to exclude github support?

**Comment by ibuziuk** [comment]
@skabashnyuk will let @gorkem & @slemeur to comment here. AFAIK, in che 5 it was excluded

**Comment by gorkem** [comment]
The early deliveries to OSIO excluded it but I think we started to include it after we changed the assembly packaging.

**Comment by ibuziuk** [comment]
@gorkem @l0rd going to close this issue, since the contributor plugin has become a `must have` due to codenvy.io -> openshift.io transition - https://github.com/redhat-developer/rh-che/issues/708
