### ISSUE TITLE
Simplify deployment of che-server on osio/minishift

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#572]
**Issue problem:** 
We need a way to make deployment of che-server easier on the user, simplifying/automating the steps.

**Red Hat Che version:** 

version: 5.22.x & 6.1.x

**Runtime:**

runtime used:
   - [X] minishift (include output of `minishift version`)
   - [X] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment]
@ScrewTSW  closing because it looks like a duplicate of #489 #540. Feel free to re-open
