### ISSUE TITLE
Additional steps to migrate workspaces from Che5 to Che6

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#579]
**Issue problem:** 
I Che 6 workspace model has changed a bit and some other stuff from workspace configuration has changed too. We need to change them if we want to migrate existing workspaces properly.
What to change:
- rename field agents to installers
- fix preview URLs
Example: 
From `"previewUrl": "http://${server.port.5000}",` to `"previewUrl": "${server.5000}",`
Here protocol is now part of the template. But to make it work next migration is also needed.
- expose ports with servers
Add port from preview URL to ports. For example, if the port in preview URL is 8080 add port:
```
"8080" : {
   "port" : "8080",
   "protocol" : "http"
 }
```
And preview URL would be `"${server.8080}"`
- add oc login installer `"com.redhat.oc-login"`
**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by davidfestal** [comment]
This was integrated to the https://github.com/fabric8-services/che-tenant-maintainer
