### ISSUE TITLE
che6 workspaces created by che-starter do not work

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#582]
**Issue problem:** 
Workspaces created by che-starter are missing installers - most importantly ws-agent which is crucial for proper workspace startup.

The weird thing is, that when you open the workspace while it's starting, it seems that it is started ok. But opening it after it's already started gives you error.

I've captured this weird behavior in this screencast: https://youtu.be/5H7QncBXL-Q

**Red Hat Che version:** 

version: 6.1.1

**Reproduction Steps:**

Start che6 workspace using che-starter

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@rhopp PR with fix is merged. Could you please verify that now workspace creation via che-starter works correctly against both che 5 & che 6? (all installers are there / possible to run & debug vertx project / preview url is rendered correctly)


[1] https://github.com/redhat-developer/che-starter/pull/277

**Comment by rhopp** [comment]
I've verified this problem is gone now. I've already wrote simple integration test for this particular issue: https://github.com/redhat-developer/che-starter/pull/279

I'll do some more testing with che starter and che6 in next few days. Closing this issue. Will open new one if I find something.
