### ISSUE TITLE
JAVA_HOME is null when running test via UI 

### ISSUE THREAD

**Issue by dipak-pawar** [redhat-developer/rh-che#590]
**Issue problem:** 
Env variable `JAVA_HOME` is null when running tests from UI. Whereas it's working as per expectation when running maven build from terminal.

**Reproduction Steps:**
* open project https://github.com/dipak-pawar/che_java_home_reproducer in che
* Run  Junit Test from UI.

**Stack Tested**
* vert.x
* java-centos

**Runtime:**

runtime used:
   - [x] OpenShift.io

**Comment by garagatyi** [comment]
I think it is an issue for upstream Che project. Please, create an issue there.

**Comment by dipak-pawar** [comment]
@garagatyi Created issue in upstream https://github.com/eclipse/che/issues/9105

**Comment by garagatyi** [comment]
So let's close the issue and track the progress in the upstream repo
