### ISSUE TITLE
Rework injection of OSO login to user namespace to a simpler approach

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#599]
**Issue problem:** 
To implement injection of OSO login to a user namespace in rh-che I added class `RhCheInfraEnvironmentProvisioner` that replaces class from upstream via binding and adds some env vars to the deployment setup. 
Even though this works the approach I've used makes rh-che more dependent on changes in upstream Che code (not APIs) instead of using some more stable pluggability point.
Instead of the current approach, I would like to use a pluggable injection of env var in the runtime https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/EnvVarProvider.java#L23-L23.
But there are 2 points which I would like to see fixed before we do that:
1. Prevent injection of env vars from holding sync request of start workspace API. This is needed because retrieval of values we need for the injection make workspace start call to long which may lead to a clunky API behavior with calls failing from time to time. Here is an issue for that: https://github.com/eclipse/che/issues/8989
1. Allow injection of multiple env variables with a single provider. It is needed because we will have to do the same calls to remote APIs to get data needed to build several env vars needed for `oc login` execution. Here is an issue for that https://github.com/eclipse/che/issues/9145

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
Blocked by https://github.com/eclipse/che/issues/9145, https://github.com/eclipse/che/issues/8989

**Comment by ibuziuk** [comment]
Closing as outdated.
