### ISSUE TITLE
rhche logs are not correctly parsed by kibana

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#603]
**Issue problem:** 
I wanted to do a simple kibana search for all errors rhche reported in logs. And while doing so I stumbled upon weird thing. It seems, that all logs from rhche (and che) pods have level:info in kiabna. 

This is what s in rhche pod log:
```
{"@timestamp":"2018-03-22T09:49:33.273+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspace4cfba14bpz3r057p. Cause: Waiting for Kubernetes environment 'default' of the workspace'workspace4cfba14bpz3r057p' reached timeout","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-6","level":"WARN","level_value":30000,"identity_id":"cd04c727-19a3-4102-8b00-50b444cf0845"}
```
(notice the level:"WARN")

But in kibana, this entry has level:"info"
Here is the same entry in kibana (if you have access):
 https://logs.dsaas.openshift.com/app/kibana#/doc/project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*/project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.2018.03.22/com.redhat.viaq.common?id=AWJNHRc9xiv5CfydVI97&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))

**Red Hat Che version:** 

version: rhche 6.2.0

**Comment by garagatyi** [comment]
Fixed by the update of prod and prod-preview to openshift 3.7
