### ISSUE TITLE
Condenvy.io transition

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#606]
Start working on the condenvy features that we need to port to openshift.io

**Comment by garagatyi** [comment]
Is there any clarity on what has to be done in this epic?

**Comment by l0rd** [comment]
Not yet I beleive

**Comment by garagatyi** [comment]
Looks like this issue has a duplicate https://github.com/redhat-developer/rh-che/issues/701
Should we close this one since the other one has more details?

**Comment by l0rd** [comment]
@garagatyi closed
