### ISSUE TITLE
Notify user as soon as his workspace has been idled

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#607]
**Issue problem:** 

When a running workspace is idled, but the browser tab is not closed, if the user comes back to the workspace tab, he doesn't have any notification that the workspace has been idled, and might start experiencing unexpected behaviors when trying to work with it again. 

**Red Hat Che version:** 

version: Upstream 6.2.0

**Comment by l0rd** [comment]
@davidfestal can you open an upstream issue for that?

**Comment by ibuziuk** [comment]
I believe this one is already fixed. Closing.

![image](https://user-images.githubusercontent.com/1461122/62145659-1d02d500-b2f4-11e9-9628-55eb988230ad.png)
