### ISSUE TITLE
Remove everything related to building assembly without dashboard

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#614]
**Issue problem:** 
We decided to close [issue](https://github.com/redhat-developer/rh-che/issues/563) because we don't need a packaging without the Che UD. We need to cleanup repo from it.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@amisevsk I guess we did it as part of the https://github.com/redhat-developer/rh-che/pull/1481 right?

**Comment by amisevsk** [comment]
@ibuziuk I think it was all removed, but I wasn't especially careful so there may be some traces of it left. I'll double check before closing this issue.

**Comment by amisevsk** [comment]
@ibuziuk I missed a few things, opened https://github.com/redhat-developer/rh-che/pull/1554

**Comment by ibuziuk** [comment]
PR  merged. Closing
