### ISSUE TITLE
Import project from GitHub

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#621]
**Issue problem:** 
API for connecting `GitHub` accounts doesn't work.

**Red Hat Che version:** 

version: 6.3.0

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

When creating a new workspace in RH-Che, click `Add or Import Project`, select `GitHub` tab, click `Connect your GitHub Account`

Results in `404`

Suspicious URL: `https://`github.com/login/oauth/authorize?client_id=`NULL`&response_type=code&scope=user,repo,write:public_key&state=oauth_provider%3Dgithub%26scope%3Duser,repo,write:public_key%26userId%3D`<URL encoded token>`%26redirect_after_login%3Dhttps://rhche.prod-preview.openshift.io:443/dashboard/gitHubCallback.html

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment]
It looks like the git flow work because it correctly use the github token retrieved from the tenant service but the github flow doesn't.

**Comment by l0rd** [comment]
Should be related to https://github.com/redhat-developer/rh-che/issues/642 but according to @garagatyi this may have been already fixed.

**Comment by ibuziuk** [comment]
Github import seems to work fine if url is https based, however it does not work for ssh imports:

**Comment by garagatyi** [comment]
Notice that client_id is NULL in the URL and redirect after login redirects to UD instead of OAuth Service on WS master. These might be the reason. We need to check OAuth configuration of the WS master

**Comment by ibuziuk** [comment]
@l0rd @garagatyi @davidfestal  will this issue be affected by https://github.com/eclipse/che/issues/9488#issuecomment-382468456 ?

**Comment by eivantsov** [comment]
@ibuziuk no. That issue is about removing ssh agent or hiding it. SSH agent provide ways to ssh into a workspace machine which is impossible in case of a k8s pod with OS route.

**Comment by l0rd** [comment]
I confirm @eivantsov comment: that issue is not related to this one

**Comment by l0rd** [comment]
This is related to https://github.com/eclipse/che/issues/9461. Until we don't fix that properly upstream we won't be able have proper GitHub integration.

**Comment by ibuziuk** [comment]
Closing as obsolete. Git push functionality for Che 7 GA should be verified as part of the https://github.com/redhat-developer/rh-che/issues/1524
