### ISSUE TITLE
Send error logs from Tomcat to Sentry 

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#624]
**Issue problem:** 
PR #623 adds sending of error and warning logs to Sentry. But it doesn't include logs from tomcat itself. 
To configure tomcat to send these logs we need to repack tomcat-juli archive to add sentry there and configure tomcat-logger.xml.

**Comment by ibuziuk** [comment]
Closing since sentry has been disabled and it is not clear if we need to enable it again - https://github.com/redhat-developer/rh-che/issues/1854
