### ISSUE TITLE
If volume claim for workspace is missing try to evaluate its parameters before creation of it

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#627]
**Issue problem:** 
Now Che can create PVC for a workspace but it uses hardcoded value. 
This is not the best case when quotas are changing, so the behavior of Che might stop workspace start and when different users have different quotas - onprem, OSO PRO, etc.
Instead, we should add an ability for Che to evaluate possible value of quota for a PVC and create PVC with such value.
It wouldn't cover all the cases but will be better than what we have now.

Followup of #626

**Comment by ibuziuk** [comment]
Closing, as outdated
