### ISSUE TITLE
Add Sentry integration to che-starter

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#631]
**Issue problem:** 
We have PR with such integration in RH-CHE repo but it would be useful to have it in che-starter too.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Closing as outdated
