### ISSUE TITLE
Implement che-tenant-maintainer endpoints to help SD team ns monitoring

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#634]
This is about implement the REST endpoints  in the [che-tenant-maintainer](https://github.com/fabric8-services/che-tenant-maintainer) for [housekeeping issue #1337]( https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1737) (checklist for monitoring `-che` namespaces)

**Comment by ibuziuk** [comment]
che-tenant-maintainer has not been updated for the last 2 years, so I believe we can trea it as deprecated. Closing
