### ISSUE TITLE
Testing configuration of private Docker registry on OpenShift.io

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#637]
That's just about checking if it works. Nothing to implement.

**Comment by l0rd** [comment]
@gorkem private registries on osio don't work. I suspect that private registries don't work on OpenShift at all. @garagatyi @sleshchenko any idea?

Anyway @gorkem I will close this issue and open a new open to fix private registries on osio.

**Comment by garagatyi** [comment]
@l0rd it is not clear to me how did you check. Can you elaborate?

**Comment by l0rd** [comment]
@garagatyi I have added a private docker registry (URL, username and password) using the Administration tab. Then I modified a stack to use a docker image from that private registry. It didn't work (the same worked on codenvy.io). By the way I have double check that we don't support using `imagePullSecrets` when creating pods for kubernetes/openshift infrastructures.

**Comment by l0rd** [comment]
I have created https://github.com/redhat-developer/rh-che/issues/680

**Comment by garagatyi** [comment]
Thanks for the explanation!
