### ISSUE TITLE
Fix wildfly booster - Make tests working

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#649]
This is a placeholder for OSIO issue https://github.com/openshiftio/openshift.io/issues/2152

**Comment by l0rd** [comment]
Test are currently skipped. We should re-enable them.

**Comment by l0rd** [comment]
We have opened an upstream issue for this https://issues.jboss.org/browse/THORN-2049

**Comment by bartoszmajsak** [comment]
There's PR open for that https://github.com/thorntail/thorntail/pull/1061, I will make it pass on TCK tests and we can see if that unblocks us here.
