### ISSUE TITLE
Prod-preview Che server logs are not in Kibana

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#667]
**Issue problem:** 
Che-server logs are not appearing in kibana on prod-preview

**Reproduction Steps:**

Search for `kubernetes.labels.app.raw:"rhche"` in https://logs.rh-idev.openshift.com/app/kibana and you should see che-server logs... Unfotunately, they are not there.
P.S.: This is working on prod.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment]
@jfchevrette do you have an idea about why this is happening on prod-preview?

**Comment by jfchevrette** [comment]
@l0rd thanks for reporting this, i'm looking into it

**Comment by ibuziuk** [comment]
Funny enough that prod-preview kibana is not workig again - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2623
