### ISSUE TITLE
OSO terminates Che workspaces 1h after their creation

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#668]
Placeholder for https://github.com/openshiftio/openshift.io/issues/3496

**Comment by l0rd** [comment]
Use `DeploymentConfig` to start workspaces pods

**Comment by l0rd** [comment]
An important point made by @eivantsov this morning:

```
let's not forget about User Dashboard that validates custom OpenShift recipes, and currently Dashboard widget accepts only kind: pod and kind: service.
```

Dashboard should continue to accept `Pod` and `Service` types objects only. But we should keep in mind to always wrap the pod in a `DeploymentConfig`.

**Comment by amisevsk** [comment]
Closing as PR https://github.com/eclipse/che/pull/10021 is merged and available in prod.

**Comment by amisevsk** [comment]
Nevermind, we haven't pushed to prod because of https://github.com/redhat-developer/rh-che/issues/735
