### ISSUE TITLE
Can't start workspace after DELETE of another workspace

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#673]
**Issue problem:** 
When one workspace is deleted and immediately another workspace is run, the run fails with:

![screenshot from 2018-05-11 09-40-44](https://user-images.githubusercontent.com/29278800/39912597-8d12b080-54ff-11e8-9c40-1b43628d2361.png)

It seems like the pod for deleting workspace is started and consumes some resources and therefore the next pod for another workspace can not be created. 

**Reproduction Steps:**

Create two workspaces. Delete one workspace. Run second workspace.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by davidfestal** [comment]
@Katka92  Could you have the detail / stacktrace of the error in the Che server logs ?

**Comment by Katka92** [comment]
Here is the failure copied from rh-che server log.

{"@timestamp":"2018-05-14T09:36:45.458+00:00","@version":1,"message":"Starting workspace 'kkanova/wksp-akwd' with id 'workspacemfv0ffxmue5593g7' by user 'kkanova'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-4","level":"INFO","level_value":20000,"identity_id":"6e2dd0f9-a5bb-4137-a974-fe99b9d9fa47"}
--
  | {"@timestamp":"2018-05-14T09:36:45.674+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspacemfv0ffxmue5593g7. Cause: Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/kkanova-che/pods . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods \"workspacemfv0ffxmue5593g7.dockerimage\" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=4, used: limits.cpu=488m, limited: limits.cpu=4. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-5","level":"WARN","level_value":30000,"identity_id":"6e2dd0f9-a5bb-4137-a974-fe99b9d9fa47"}


Here are kibana logs of both workspaces:
https://logs.dsaas.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(columns:!(message),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'%22workspacemfv0ffxmue5593g7%22%20%7C%7C%20%22workspacejs9xhx4yfhf2acac%22')),sort:!('@timestamp',desc))

**Comment by rhopp** [comment]
@l0rd I think we should get this issue re-prioritized. I have these reasons for that:
1) We already have some data of how long does it take for the `rm` pod to spawn&finish. In last 3 days, the median value for this was 70 sec on `us-east-2` [1] and 21 sec on `us-east-2a` [2]
2) User can pretty easily reproduce. When one workspace is deleted, it's not so bad, but when user is deleting multiple workspaces, the time for all the `rm` pods to spawn&finish is pretty long.
3) Not only our (rhche) tests are affected by this (we already made changes to not be affected by this), but also upstream tests running against rhche have problems with this: https://github.com/eclipse/che/issues/9753


[1] - https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=36&hostid=11810&graphid=10899
[2] - https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=36&hostid=11811&graphid=10899

**Comment by l0rd** [comment]
This should be fixed by #668 if we set workspace pods as non terminating pods

**Comment by ibuziuk** [comment]
@Katka92 @rhopp could you please verify the problem on prod ? I believe this issue should be closed

**Comment by Katka92** [comment]
@ibuziuk I'll take a look tomorrow and leave comment here.

**Comment by Katka92** [comment]
@ibuziuk Although the time of removing pods has increased [1] I wasn't able to reproduce that issue on production. I think this issue can be closed.

[1] https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=36&hostid=11839&graphid=10899
