### ISSUE TITLE
Fix wildfly booster - set correct maven options

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#674]
This is a placeholder for OSIO issue openshiftio/openshift.io#2152 (maven options part)

**Comment by l0rd** [comment]
Should fix https://github.com/openshiftio/openshift.io/issues/3463 too

**Comment by animuk** [comment]
@ibuziuk When are we planning to resolve this ?

**Comment by ibuziuk** [comment]
@animuk it is the current sprint, but currently no one is working on it since we have issue with the higher priority
