### ISSUE TITLE
Prepare the telemetry Che support for the Theia switch

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#690]
Currently, the Telemetry support main components live in the workspace agent, and receive some information and also retrieve settings from the workspace master.

The switch to Theia will see the workspace agent disappear.

So before this switch we should more the Core Telemetry components (Mainly `AnalyticsManager`) to the workspace master, and provide a REST API that allows submitting telemetry events to it from agents, Theia server-side plugins or WS.Next side card services.

According to the current design, that should be quite easy, and might even simplfiy some parts.

List of sub-taks:

- [x] Investigate complexity of enabling telemetry support in Che 7 and create list of sub-taks #1154
- [x] Migrate the Woopra telemetry main component in a dedicated service for Che 7 #1229

**Comment by skabashnyuk** [comment]
Before you start moving something to ws-master can you describe overall architecture?
I'm not sure that we need to put that on ws-master. Maybe we can setup telemetry as separate microservice.

**Comment by garagatyi** [comment]
Theia is written in TS. Can't we just use javascript integration instead?

**Comment by davidfestal** [comment]
> Theia is written in TS. Can't we just use javascript integration instead?

Well, managing this in a central place server-side has the benefit of being able to gather in the same Che workspace session, and report in a consistent way (regarding woopra durations, etc ...), events that come from various agents / services (Theia IDE, but also other services, such as terminal, command executions, services that might provide a link with desktop tools, etc ...
