### ISSUE TITLE
Need to pass `identity_id` via `Impersonate-User` header instead of query parameter

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#703]
Currently `identity_id` is passed to oso-proxy via query parameter. Unfortunately, k8s client does not proceed query parameters correctly when set in `masterUrl` (details in the upstream issue https://github.com/fabric8io/kubernetes-client/issues/1089 ) and to make it work a workaround [2] was added to `oso-proxy` [2]. Assuming that oso-proxy currently support both approaches of `identity_id` processing this issue should be treated as internal implementation improvement which does not block *-che namespace lockdown.

[1] https://github.com/redhat-developer/rh-che/pull/688
[2] https://github.com/fabric8-services/fabric8-oso-proxy/pull/26

**Comment by l0rd** [comment]
We should fix that as soon as we move to 6.7.0

**Comment by ibuziuk** [comment]
PR is merged - https://github.com/redhat-developer/rh-che/pull/1089
Closing
