### ISSUE TITLE
Disable Organizations on che.openshift.io

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#707]
After discussing "OSIO permission model as a backend for che permission model on che.openshift.io" [1] during f2f it was decided that currently the 'Organizations'  flow is broken for openshift infrastructure in general e.g.:
- resource limits used in Che are not aligned with openshift quotas in namespaces
- shared team workspace would not always be started in the owner namespace, which essentially breaks the idea of teams

Currently, it was decided to disable organizations on che.openshift.io and update the message to in order to clarify that organizations are currently not supported on `che.openshift.io` + add link to the organizations doc[1]:

![image](https://user-images.githubusercontent.com/1461122/43472743-8c35d960-94ee-11e8-9d19-f93bbd41546a.png)

[1] https://docs.google.com/document/d/1y0wjCKcBhzLFgIR-Qgx3YkqWU0kqy638tSOO4oKa_bE/edit#heading=h.6a6mwnzbufob
[2] https://www.eclipse.org/che/docs/organizations.html

**Comment by ibuziuk** [comment]
also need to investigate possibility of integration of che orgs / teams with osio teams as a part of this issue.

**Comment by ibuziuk** [comment]
Sub tasks:
- test the possibility of workspace sharing (workspace details / tab for sharing)
- also need to investigate possibility of integration of che orgs / teams with osio teams as a part of this issue 
- every user should have a possibility to create org from dashboard

**Comment by ibuziuk** [comment]
- [ ] UD is not part of rh-che build, so we probably need to either re-pack the dashboard or add property in upstream to override the message

**Comment by amisevsk** [comment]
PR #830 enables redirection of `learn more` link to upstream organizations doc.

**Comment by garagatyi** [comment]
We also have share workspace view on UD:
![selection_002](https://user-images.githubusercontent.com/1851863/44645437-49c1b480-a9e0-11e8-850f-13f28caa1478.png)
We will have to disable it too. Not sure whether it would work authomatically after disabling organizations.

**Comment by ibuziuk** [comment]
workspace sharing is still planned to be enabled but with some limitations - https://github.com/redhat-developer/rh-che/issues/798

**Comment by l0rd** [comment]
@ibuziuk if I understand correctly we can close this issue right? In any case #798 is already listed in codenvy.io migration epic (#701)

**Comment by ibuziuk** [comment]
@l0rd I was planning to close it once it would be on prod (currently it is only on prod-preview)

**Comment by ibuziuk** [comment]
@amisevsk for some reason organizations where not disabled as expected on the prod-preview and there is still old message shown:

![image](https://user-images.githubusercontent.com/1461122/44977125-78530880-af67-11e8-86cd-309e749d9fc7.png)

Could you please take a look ?

**Comment by ibuziuk** [comment]
it looks like latest rollout on rh-idev failed and the obsolete version is still deployed on prod-preview:


>   | --> Scaling up rhche-112 from 0 to 1, scaling down rhche-110 from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
> -- | --
>   | Scaling rhche-112 up to 1
>   | error: timed out waiting for any update progress to be made

**Comment by amisevsk** [comment]
Changes available on prod as of today.
