### ISSUE TITLE
Opentracing support in Che

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#718]
Initial investigation of opentracing was done as part of the https://github.com/redhat-developer/rh-che/issues/687 

Demo - https://youtu.be/4tWeH8JqQQk

Potential subtasks with estimations:

- creating CQs for opentracing & jaeger and resolving dependency conflicts - `5`
- adding tracer agnostic opentracing support to wsmaster (jaeger would be used as the default tracer) - 
`21`
- adding opentracing support to wsagent (might be relevant for che 6 / RACHEL) - `21`
- adding opentracing to wsnext - `no research / estimation have been done`

**Comment by ibuziuk** [comment]
@slemeur @gorkem we have not added any opentracing related tasks to the current sprint. Could you please comment about the priorities for this epic? If opentracing is smth. which is considered to be in place for the upcoming trains maybe it worth considering to start the CQ process (all libs are under Apache 2.0 but still the approval process from the IP team could potentially take sufficient amount of time)

**Comment by slemeur** [comment]
@ibuziuk : I think you should create this epic upstream as well. We started to discuss with the team at SAP about telemetry during the weekly community call and I think it would be nice that this work and the result of your investigation is visible from upstream. This will get feedbacks from people having a different point of view, which could be really valuable.

Separately, I think this is going to be fairly important for on-prem Che in the future and should be considered. I agree with you we should be starting the CQ process and ideally plan that work in the upcoming sprints. We can add it into account for the goals of the next train, and see if we'll be able to handle it regarding the other priorities we have.

**Comment by ibuziuk** [comment]
@slemeur thanks for clarifications, I will create an epic with details upstream ;-)

**Comment by ibuziuk** [comment]
opentracing epic have been created - https://github.com/eclipse/che/issues/10288

**Comment by ibuziuk** [comment]
Closing this epic since the one with more details has been created upstream - eclipse/che#10288
