### ISSUE TITLE
Che on osio should support wildfly redhat version (currently community version is used)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#723]
Wildfly swarm Repos for the Redhat Version
=====================================

- [ ] build command is failing in wildfly boosters on osio from time to time (100 Mb is not always enough to perform the build)

- [ ] red hat version of cm wildfly bosster is not working in che openshift.io (but works fine in osio build pipeline) details in https://github.com/redhat-developer/rh-che/issues/723#issuecomment-401768645

**Comment by animuk** [comment]
Wildfly swarm Repos for the Redhat Version
=====================================
1. HealthCheck Boosters : https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-health-check-redhat
2. Rest HTTP Boosters : https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-redhat

Issue Description:

- if you import the HealthCheck Booster above within Che workspace,
    1.  **Auto Compile Feature does not work**. ( Please Note : Build and Run is working as expected ).
- If you import Rest HTTP Booster above within the che workspace, Two issues we can see at the moment - 
    1. **Auto Compile Feature does not work** ( Please Note : Build and Run is working as expected ).

please note: here autocompile means hot deployment on any code change

**Comment by ibuziuk** [comment]
@animuk in terms of memory settings, there is a separate issue - https://github.com/redhat-developer/rh-che/issues/674

**Comment by ibuziuk** [comment]
> Two issues we can see at the moment 

Might miss smth. but there is only one issue listed (auto-compile / hot deployment does not work). BTW, does auto compile / hot-deployment works for this wildfly projects OOTB locally against desktop IDE e.g. for spring-boot / vert.x hot deployment works differently [1]

[1] https://github.com/redhat-developer/rh-che/issues/254#issuecomment-335816550

**Comment by animuk** [comment]
@ibuziuk For config map boosters as below repo:
https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-configmap-redhat

In Che workspace - 
1. Imported Successfully
2. dev-machine - build Successfully
3. dev-machine - run Successfully

But Issue is the config map URL - invoke service does not work ( but this is working perfectly in the pipeline). Please check from your side.
![screenshot from 2018-07-02 16-32-59](https://user-images.githubusercontent.com/11207106/42160650-9d2eb3d0-7e15-11e8-8bf7-aeea68d10253.png)

**Comment by animuk** [comment]
To Summerize -
1. Need to set correct maven options - memory options for (wildflyswarm) boosters . Ref Issue : #674
2. for wildfly -config map booster, URL - invoke service does not work in che.

**Comment by ibuziuk** [comment]
@animuk what about the Auto Compile ? Does it work locally for wildfly  ?

**Comment by ibuziuk** [comment]
@animuk unfortunately, we will not be able to address all the issue in the next sprint. But we are planning to  start with https://github.com/redhat-developer/rh-che/issues/674

**Comment by ibuziuk** [comment]
@slemeur @l0rd I just had a blue jins seesion with @animuk and this tasks are requested to be done in the next sprint. Are you ok to take this into the next sprint backlog ? The first part about increasing ram options would not require a lot of time (just a command update) The second one could be trickier and would probably require a few days of investigation

**Comment by amisevsk** [comment]
One note about the configmap issue -- while working on updating the rhdev/che-dockerfiles for https://github.com/redhat-developer/che-dockerfiles/pull/37, I found that there appears to be no officially supported version for the wildfly-swarm configmap booster on OSIO. This can be confirmed by checking the REST endpoint:
```
curl -H "X-App: osio" https://forge.api.openshift.io/api/booster-catalog | jq '.boosters | .[] | select(.mission == "configmap" and .runtime == "wildfly-swarm")'
```
I don't know if this affects the discussion.

**Comment by animuk** [comment]
@amisevsk Yes. Currently, It is not there. But, We want to include that in the OSIO booster catalog so that config map booster will be available.

**Comment by ibuziuk** [comment]
Closing as outdated
