### ISSUE TITLE
Workspaces were stopped during rhche update (upstream 6.7.1) on prod

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#726]
**Issue problem:** 
After merging https://github.com/openshiftio/saas-openshiftio/pull/945 che server used `Recreate`
strategy and workspaces were stopped during the update:

![image](https://user-images.githubusercontent.com/1461122/42041652-9f912bce-7af2-11e8-9b48-a98febfc6475.png)

**Red Hat Che version:** 

https://github.com/openshiftio/saas-openshiftio/pull/945 

 - [x] I can reproduce it on latest official image

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Need to add functional tests for this use-case cc @rhopp @ScrewTSW @Katka92

**Comment by ibuziuk** [comment]
The strategy of deployment of rh-che have been changed from `Recreate` to `Rolling`. This change was meticulously tested on dev cluster by the whole team. Workspaces were created and started and rollout of the deployment was performed many times in the mentime:

![image](https://user-images.githubusercontent.com/1461122/42948259-655ca5f4-8b6f-11e8-844a-af72c13a14fe.png)


Workspaces were still running during multiple updates. No issues were spotted a part from known [1] [2]
Today update of prod was also performed - no workspaces were stopped during the update according to zabbix [3] :
![image](https://user-images.githubusercontent.com/1461122/43012168-efdb85de-8c45-11e8-986c-ece0291076d5.png)


[1] https://github.com/eclipse/che/issues/9740 
[2] https://github.com/eclipse/che-docs/blob/master/src/main/pages/setup-openshift/admin-guide.md#known-issues
[3] https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=35&hostid=11687&graphid=8770

**Comment by ibuziuk** [comment]
@rhopp before closing this issue could we create a separate one for adding functional tests for verifying that workspaces are not stopped during the rolling update of che-server ?

**Comment by rhopp** [comment]
@ibuziuk There is already one present and we already planned that for current sprint: https://github.com/redhat-developer/che-functional-tests/issues/306

**Comment by ibuziuk** [comment]
@rhopp thanks for the info. Closing
