### ISSUE TITLE
Impossible to import from github account from the dashboard

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/rh-che#727]
**Issue problem:** 

**Red Hat Che version:** 
version: 6.7.1

**Reproduction Steps:**
1. Login to che.openshift.io
2. Create a new workspace
3. Select a stack
4. Go into the section to add a new project. Select "Github"
5. Click on the button connect to your github account
![screen shot 2018-06-28 at 20 30 31](https://user-images.githubusercontent.com/1636769/42053671-71169886-7b12-11e8-9d98-0d959db266ed.png)

**Expected Behavior:**
User is already authorized on github (because asked by osio early in the flow) and is able to browse the list of his github projects.

**Current Behavior:**
I have a failure and github showing a 404.
![screen shot 2018-06-28 at 20 32 42](https://user-images.githubusercontent.com/1636769/42053669-6d3d8d50-7b12-11e8-896a-280674351ca8.png)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by slemeur** [comment]
This behaviour is also observed when trying to use the GitHub button in Preferences > SSH

**Comment by slemeur** [comment]
Looking for some news on this issue: will it be addressed during the sprint? I don't see an assignee on it.

**Comment by sbose78** [comment]
You could use 
```
GET https://auth.openshift.io/api/token/link?for=openshift + token
```
to trigger 'connect github'

and 

```
GET https://auth.openshift.io/api/token?for=openshift + token
```
to get the github token, and/or check if user has connected her github.
