### ISSUE TITLE
Fix migrated factories that don't work fully and push the new list to Eclipse

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#729]

**Comment by ibuziuk** [comment]
@davidfestal could you please list osio incompatible docker images that are used in factories

**Comment by davidfestal** [comment]
@ibuziuk @l0rd @slemeur @benoitf  @eivantsov

I ran the migration in the dedicated OSIO user on production, and I'm currently summarizing migration / test results for each factory in the following document which I shared for comments: https://docs.google.com/spreadsheets/d/1JpA3uSjfneeAqeNcchwmI1T0sxpO_o_FTaTAiVl0IIw/edit?usp=sharing

**Comment by davidfestal** [comment]
After discussing with @slemeur and @benoitf and commenting in this document, here is the work to be done:
1. Fix the factories that start but don't work fully:
- Update the Wildfly factory to in fact point to the Wildfly Swarm OSIO booster
- Fix the PHP factory (or the underlying eclipse/php docker image) to allow the apache server to be started as regular user (instead of using sudo)
- Fix the vertx factory to use the last vertX 3 examples repo
- Fix a bug that happens at factory start in the vertX and Jenkins factories related to Git cloning being done asynchronously
- Update the NodeJs example that seems ti use a very old example project with disappeared dependencies (grunt, etc ...)
2. Remove the factories that we don't use anymore
3. Prepare an alternate page on eclipse.org (visible only by us)
4. Push the new json list of factories on this new page.

**Comment by slemeur** [comment]
Sounds good. Thanks @davidfestal

**Comment by davidfestal** [comment]
The migrated / fixed factories are available on the following additional page of the eclipse web-site:
https://www.eclipse.org/che/getting-started/cloud-osio-preview/
to be started in the prod-preview OSIO instance.
Would be great if @ibuziuk @l0rd @slemeur @benoitf could also try them and report anything that doesn't work as it was in `codenvy.io`

Since the telemetry factory support has been merged to master, you can follow the created / used factories here: https://www.woopra.com/live/project/test.openshift.io/reports/analytics/ujyyyn0bw9 

I still have to investigate the bug that happens at factory start in the vertX and Jenkins factories, and seems related to Git cloning being done asynchronously.

**Comment by davidfestal** [comment]
> I still have to investigate the bug that happens at factory start in the vertX and Jenkins factories, and seems related to Git cloning being done asynchronously.

The error encountered in the VertX factory is now fixed by PR https://github.com/redhat-developer/rh-che/pull/768.
However, the Jenkins factory (probably the one with the biggest Git repository) still fails: during the initial project import, the JGit clone action fails *__on the server-side__*.
We agreed to open an new issue for this bug that seems to require a certain amount of additional work before understanding what's going on.

For now the Jenkins factory has been removed from the list of factories available in the Eclipse Web site, and the following issue has been created to track this bug separately: https://github.com/redhat-developer/rh-che/issues/772

So it seems that factories are ready for migration on both:
- prod-preview: https://www.eclipse.org/che/getting-started/cloud-osio-preview/
and 
- production: https://www.eclipse.org/che/getting-started/cloud-osio/

We should be able to do the switch as soon as other concerns (authorization flow for new users, etc ...) are fixed.

**Comment by ibuziuk** [comment]
> We should be able to do the switch as soon as other concerns (authorization flow for new users, etc ...) are fixed.

@davidfestal have you got a chance to chat with @sbose78 about the possibility of the auto-provisioning for users that are redirected to the registration page from the factory link ?

**Comment by l0rd** [comment]
@davidfestal yes I think https://github.com/openshiftio/openshift.io/issues/3814 is the good issue to add the comments

**Comment by davidfestal** [comment]
> @davidfestal yes I think openshiftio/openshift.io#3814 is the good issue to add the comments

done: https://github.com/openshiftio/openshift.io/issues/3814#issuecomment-407722502

**Comment by ibuziuk** [comment]
Closing since there are relevant sub-tasks already opened
