### ISSUE TITLE
Need to enable "che-tenant-maintainer" in order to cleanup old workspace files periodically on production

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#730]
**Issue problem:** 

One of the possibilities of che-tenant-maintainer [1] is cleanup of old workspace files. Currently this happens only during env reset. But if user have not done env reset (which re-creates `claim-che-workspace` pvc), the old workspace files, especially all the Che5 workspaces that have been migrated some months ago, didn't have their PVs cleaned which results in ~700 mb of obsolete files in PVs. PVs should be cleaned, by running the che-tenant-maintainer cleaning enpoint by the SD team. Also it is required to come up with a process for periodic cleanup of workspace PVs 

[1] https://github.com/fabric8-services/che-tenant-maintainer

Related gitlab issue -  https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1977

**Red Hat Che version:** 
6.7.1
runtime used:

   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@riuvshin we are planning to take this issue to the next sprint ? Will you be able to work with us on it ?

**Comment by benoitf** [comment]
if other ppl have issues, here is mario's script I used
```
oc project xxxx-che
oc run cleanup --image=registry.access.redhat.com/rhel7 -- tail -f /dev/null
oc volume dc/cleanup --add -t pvc --name=cleanup --claim-name=claim-che-workspace --mount-path=/workspaces
oc rsh cleanup-X-XXXXX
oc delete all -l app=cleanup
```

**Comment by ibuziuk** [comment]
@l0rd it appeared to be that workspace cleanup if currently broken and we should address this issue first before running che-tenant-maintainer on prod. So, I believe we should add this issue to the current sprint and address it first - https://github.com/redhat-developer/rh-che/issues/1026

**Comment by l0rd** [comment]
@ibuziuk 👍

**Comment by ibuziuk** [comment]
che-tenant-maintainer is considered to be deprecated. Closing
