### ISSUE TITLE
Update rh-dev/che-dockerfiles to include wildfly-swarm configmap booster.

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#734]
**Issue problem:** 
There is currently no supported version of the wildfly-swarm configmap booster on OSIO. This is an issue to track this until we can begin to include a version in https://github.com/redhat-developer/che-dockerfiles.

Currently, the hardcoded version used is not officially supported and should probably be removed. PR [1], in part, does this.

[1]-https://github.com/redhat-developer/che-dockerfiles/pull/37

 - [x] I can reproduce it on latest official image

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Seems that we also will need to re-enable health-check booster once it will be available (it was disabled today) - https://github.com/openshiftio/openshift.io/issues/3124

**Comment by ibuziuk** [comment]
Ignore my previous comment - health-check failures were related to the wildfly runtime renaming to `thorntail`

**Comment by ibuziuk** [comment]
Closing as outdated
