### ISSUE TITLE
Reexamine cico build script in rhdev/che-dockerfiles repo

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#736]
The [`cico_build_publish_images.sh`](https://github.com/redhat-developer/che-dockerfiles/blob/master/cico_build_publish_images.sh) script in `redhat-developer/che-dockerfiles` seems to manage errors using the `exit_with_error` variable. However, since we `set -e` at the top of this script, as soon as a command fails the script will exit so the variable cannot do anything (and it never referenced, for that matter).

We should either remove the unnecessary code or manage errors more gracefully (e.g. remove `set -e` and print a string of which docker images failed to build before exiting in failure).

**Comment by ibuziuk** [comment]
Closing as won't fix,
