### ISSUE TITLE
As a Che developer I want to understand SPI evolution in order to be able to maintain it

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#740]
**Issue problem:** 

Very few people understand SPI currently and can maintain it. We need to have more people able to understand the SPI and maintain it accross Che teams. In order to raise the awareness about SPI we need to:

- [ ] update SPI related documentation due to changes like https://github.com/eclipse/che/pull/10021
- [ ] prepare a few slides (1-3) which explains the current state of SPI
- [ ] prepare a few slides (1-3) which explains plans of SPI evolution in workspace next
- [ ] make a talk about SPI for Che teams (duration 30 - 45 mins)

**Comment by ibuziuk** [comment]
this is a team task and @garagatyi is going to be reviewer

**Comment by slemeur** [comment]
Probably a lot of good material here to author a blog post on the SPI, wdyt?

**Comment by ibuziuk** [comment]
@slemeur sounds good but I believe we could create a separate issue for a blog entry since it was not taken into account during estimation

**Comment by ibuziuk** [comment]
Closing as out-dated
