### ISSUE TITLE
Docs are not accessible from Che Dashboard

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/rh-che#747]
**Issue problem:** 
In the footer of the dashboard and in the IDE menus, we are including links to the documentation. But those are not pointing to the documentation of Eclipse Che or the documentation of OpenShift.io .

At an initial steps, I think we should be pointing to the documentation from upstream. 

Question:
- Could we deploy Che documentation: che.openshift.io/docs ?

**Comment by slemeur** [comment]
cc @rkratky + @petra-sargent

**Comment by ibuziuk** [comment]
@slemeur we can, but why can't we just point the doc to upstream eclipse.org

**Comment by slemeur** [comment]
@ibuziuk : We definitely should start with that. 

I can imagine that, in the future, there will be few things which might be specific to che.osio which we should be able to document (like organization). Upstream docs are really generic while for che.osio we could have a different set of features, tutorials and guides that we would like to highlight. (For example we should have guides for helping user to transition from codenvy.io to che.osio)

**Comment by Katka92** [comment]
I got an error maybe related with docs - when I tried to "Learn more" in Factories section, it gave me an error:
![screenshot from 2018-07-20 08-49-09](https://user-images.githubusercontent.com/29278800/42988548-524913ce-8bfd-11e8-8959-d2c003599774.png)

and the same in organizations:
![screenshot from 2018-07-20 09-15-04](https://user-images.githubusercontent.com/29278800/42988608-87d575dc-8bfd-11e8-8272-46d53b2086d7.png)

and stacks too:
![screenshot from 2018-07-20 09-16-35](https://user-images.githubusercontent.com/29278800/42988638-a8fc27d8-8bfd-11e8-8f4b-7a6ede198751.png)
