### ISSUE TITLE
Upstream `eclipse/che` cannot run on minishift

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#75]
Building **openshift-connector** branch without building rh-che assembly and deploying che-server image to minishift results in the following error during workspace creation:

```
Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'default' failed. Error: Agent com.redhat.bayesian.lsp not found
```

![image](https://cloud.githubusercontent.com/assets/1461122/26201848/518e6c64-3bd5-11e7-89be-c6586e258893.png)

Basically, all stacks on https://hub.docker.com/r/rhche/ contain bayesian agent which is only included in rh-che assembly.
Potential solution is having at least one working stack without bayesian agent

**Comment by sunix** [comment]
you can remove the bayesian agent from stacks.json as a workaround maybe ?

**Comment by ibuziuk** [comment]
@sunix yeah, this is another workaround (probably need to add this info to README.md)

**Comment by l0rd** [comment]
To solve this we need to:
- revert stacks.json to the master branch version as soon as #54 get merged
- merge the mechanism used in redhat-developers/che-dockerfiles to eclipse/che-dockerfiles

Once we have that we can change our CI to build a version of che-server image (let's call it fabric8 IDE) that:
- Is based on latest version of upstream Che
- runs CentOS images only (che server and workspaces)
- comes with stacks that we support only 
- comes with configs to run it on k8s and OpenShift

fabric8-IDE should have the dashboard, should not include recommendation plugin (bayesian) nor keycloak support.

**Comment by l0rd** [comment]
Little update on that. We have merged most of the content of `openshift-connector` branch to master and we have reverted stacks.json. 

So this issue now can be rephrased: "Upstream `eclipse/che` centos Docker image cannot run on minishift". Do address that we still need to port `rhche` dockerfiles trick (support for users with arbitrary ID) to `eclipse` dockerfiles.

**Comment by l0rd** [comment]
We can run upstream Che on openshift right now. The only problem is that we still need to use rh-che docker images. But let's track it in separate issue: #155
