### ISSUE TITLE
Investigate the possibility of use OSIO permission model as a backend for che permission model on che.openshift.io

### ISSUE THREAD

**Issue by skabashnyuk** [redhat-developer/rh-che#751]
**Issue problem:** 
We want to know if it possible and how much afford it will cost to integrate Che and OSIO permission model.

Need for https://github.com/redhat-developer/rh-che/issues/701

TODO 
paste some public links for OSIO's permission documentation.

**Comment by garagatyi** [comment]
@ibuziuk Has we decided to disable organizations and everything like that?

**Comment by ibuziuk** [comment]
yes for J Train we plan just to disable it - https://github.com/redhat-developer/rh-che/issues/707
But we would likely need to get back to it in K Train - https://docs.google.com/document/d/1y0wjCKcBhzLFgIR-Qgx3YkqWU0kqy638tSOO4oKa_bE/edit

**Comment by skabashnyuk** [comment]
won't fix
