### ISSUE TITLE
Can not build rh-che (Red Hat Che distro) failure on 'toRetrieveBranchName' execution

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#76]
Can not build rh-che following the instructions in the Readme.md https://github.com/redhat-developer/rh-che#tldr:

`mvn -DwithoutKeycloak -Pfast -PmultiThread -DlocalCheRepository=${UPSTREAM_CHE_PATH}  clean install`

Basically, required artifacts can not be downloaded for some reason:

`[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (toRetrieveBranchName) on project fabric8-ide-builder: Execution toRetrieveBranchName of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:buildnumber-maven-plugin:jar:1.4 -> com.google.code.maven-scm-provider-svnjava:maven-scm-provider-svnjava:jar:2.1.1: Failed to read artifact descriptor for com.google.code.maven-scm-provider-svnjava:maven-scm-provider-svnjava:jar:2.1.1: Could not transfer artifact com.google.code.maven-scm-provider-svnjava:maven-scm-provider-svnjava:pom:2.1.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org:443 failed to respond -> [Help 1]`

Full build log - https://pastebin.com/zXQMUsMt

Not related but also there is a warning during the build:
`[INFO] [WARNING] The requested profile "multiThread" could not be activated because it does not exist.
`

**Comment by ibuziuk** [comment]
@davidfestal @sunix any ideas about how this can be fixed ?

**Comment by davidfestal** [comment]
@ibuziuk Seems a network problem to me. do you still have it ?

**Comment by davidfestal** [comment]
In your logs I found:
```
The following profiles are active:
 
 - jboss-default (source: external)
```
This might be related.
Could you retry without adding the JBoss maven repositories ?

**Comment by ibuziuk** [comment]
@davidfestal disabling JBoss repos did the trick, however I still need to use `buildnumber-maven-plugin` version 1.3 (with 1.4 there is still a problem with downloading scm artifacts)

**Comment by ibuziuk** [comment]
PR is merged ^ so I guess this one can be closed
