### ISSUE TITLE
Frames are not shown, when debugging on rh-che

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#762]
**Issue problem:** 
When debugging app (I've tried springboot and vert.x) and the app is stopped on breakpoint, there should be stacktrace shown in "Frames" section , but this section is empty:
![image](https://user-images.githubusercontent.com/1215011/42886198-3ed4313a-8aa3-11e8-8932-ccae957e70f3.png)
I've tried that with upstream Che 6.8.0 and everything was as expected.

Screenshoft from upstream Che 6.8.0 for comparison:
![image](https://user-images.githubusercontent.com/1215011/42886422-d0a74840-8aa3-11e8-88fa-6dd114f4f1bc.png)

**Red Hat Che version:** 
6.7.1
version: (help/about menu)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@rhopp looks like here is the upstream issue - https://github.com/eclipse/che/issues/9243#issuecomment-406230149

**Comment by ibuziuk** [comment]
Upstream issue has been closed 
@rhopp could you please verify once the version with the fix would be promoted to prod-preview ?

**Comment by rhopp** [comment]
Verfied on che.prod-preview.openshfit.io (based on che 6.9.0). Closing.

**Comment by rafabene** [comment]
When che.prod-preview.openshfit.io will be published to che.openshfit.io?

**Comment by ibuziuk** [comment]
it is published already
