### ISSUE TITLE
Various issues with stacks on  OSIO

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#763]
there are currently 7 osio specific che recipes and quite a few would be added during the `codenvy.io` -> `che.openshift.io` transition  - https://github.com/redhat-developer/che-dockerfiles/tree/master/recipes
All the stacks should work with the default recommended projects OOTB:

- centos-nodejs
- centos_dotnet20
- centos_jdk8
- spring-boot
- ubuntu_jdk8
- vertx
- wildfly-swarm

Related bugs:

- [ ] Invalid "Preview:" URL in Spring and Nodejs stacks with respective samples #820
- [ ] .NET workspace - quickstart has lot of error markers #805 

Problems description:

**1. `centos-nodejs` / image `registry.devshift.net/che/centos-nodejs`**
 workspace starts correctly so image seems to be fine. When imported with `nodejs-hello-world` and executing `nodejs-hello-world:run` / `run` commands preview url is parsed correctly but not accessible since  preview url points to `${server.8080/tcp}` 

![image](https://user-images.githubusercontent.com/1461122/42894501-465829d4-8ab7-11e8-834b-88c51a9c9198.png)

with `web-nodejs-simple` project:

`build` command works fine. 

`web-nodejs-simple:run`: (preview url is not parsed correctly)

![image](https://user-images.githubusercontent.com/1461122/42893188-f697e298-8ab3-11e8-912a-bfd613a49fa8.png)

`run` (funny thing that `app.js` is not even located in the `app` folder but rather in the `scripts` )

![image](https://user-images.githubusercontent.com/1461122/42893346-64a48a7a-8ab4-11e8-8663-c63e22333ffb.png)

**2. separate issue for  `centos_dotnet20` stack / `registry.devshift.net/che/centos_dotnet20`**  - https://github.com/redhat-developer/rh-che/issues/505

**3. `centos_jdk8` / `registry.devshift.net/che/centos_jdk8`** 
workspace strartup works fine and all commands for `console-java-simple` project. However, for `web-java-spring` preview url `${server.tomcat8}` is not parsed correctly:

![image](https://user-images.githubusercontent.com/1461122/42895564-9868d7ca-8aba-11e8-86a2-e5c600d9215d.png)

**Comment by amisevsk** [comment]
Some preview urls are broken in default build/run commands. E.g. for web-java-spring sample project, I see preview URL as `${server.tomcat8}`, so something is going wrong.

**Comment by rhopp** [comment]
.NET image: Workspace startup is successful with https://github.com/redhat-developer/che-dockerfiles/pull/37, but there are lot of error markers in sourcecode:
![image](https://user-images.githubusercontent.com/1215011/42939914-cf76baaa-8b57-11e8-96dd-69d9aaf0c07d.png)
Building and running works fine, with one minor drawback - The `preview` link is not resolved correctly:
![image](https://user-images.githubusercontent.com/1215011/42939958-f3b44158-8b57-11e8-8715-cec3eaa0a6bf.png)
One has to go to `servers` and take the preview URL from there.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/redhat-developer/rh-che/issues/1434
