### ISSUE TITLE
Wildfly swarm was renamed to thorntail, breaking che-dockerfiles run command

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#764]
**Issue problem:** 

PR https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http/pull/41 in the wildfly-swarm booster repo renames the artifact to thorntail. The built-in run command for this stack is
```bash
cd ${current.project.path} && scl enable rh-maven33 'java -jar target/*-swarm.jar'
```
which fails.

**Reproduction Steps:**

1. Create che workspace using default wildfly-swarm stack
2. Import sample project wfswarm-rest-http
3. Start workspace and attempt to build/run project

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
PR has been sent https://github.com/redhat-developer/rh-che/pull/787
