### ISSUE TITLE
Abandon rhche.openshift.io route

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#771]
**Issue problem:** 
Now it is possible to open Che UD on OSIO by two direct links [https://che.openshift.io/](https://che.openshift.io/) and [https://rhche.openshift.io/](https://rhche.openshift.io/).
But do we need both? What for? 
Let's make [https://che.openshift.io/](https://che.openshift.io/) the mail and change link [https://rhche.openshift.io/](https://rhche.openshift.io/) to redirect users to [https://che.openshift.io/](https://che.openshift.io/)

**Comment by garagatyi** [comment]
@slemeur @l0rd @ibuziuk WDYT?

**Comment by ibuziuk** [comment]
sounds relevant for me. We used to need both for che 5 -> che 6 transitional period when two che-servers where running on osd (**che.openshift.io** was che 5 route & **rhche.openshift.io** was che6 one). Could you please create a HK issue for that? I believe @riuvshin would be able to help
 us with the route removal

**Comment by garagatyi** [comment]
Sure https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2156

**Comment by garagatyi** [comment]
BTW we have config map `che` on prod and it is not needed anymore. Should we remove it too?

**Comment by ibuziuk** [comment]
@garagatyi I actually thought it was already deleted cc: @riuvshin
