### ISSUE TITLE
Che UD shows a black screen when user is logged in prod-preview but accesses prod's Che

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#782]
**Issue problem:** 
Che UD shows a black screen when a user is logged in prod-preview but accesses prod's Che.
We should provide a better UX and handle such a situation with the weird login state.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Closing since now auth error is shown is the keycloak token is not valid
