### ISSUE TITLE
Need to update rhche to use upstream 6.9.0 version 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#785]
6.9.0 is going to be released soon and rhche should be updated in order to use this version. One important thing worth considering is the fact that new EPL 2.0 license headers are applied for Che Parent and it's dependent projects. Before updating to 6.9.0 need to make sure that  correct new license headers are used in rhche via `mvn license:format` -  update of files headers and che version should be done in one PR

**Comment by amisevsk** [comment]
Closing as rhche is currently on 6.10.0
