### ISSUE TITLE
Add telemetry events + telemetry user identification in the automatic registration flow script.

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#791]
related to https://github.com/redhat-developer/rh-che/issues/773 and https://github.com/redhat-developer/rh-che/issues/790

**Comment by slemeur** [comment]
Needed for https://github.com/redhat-developer/rh-che/issues/701 and https://github.com/redhat-developer/rh-che/issues/765

**Comment by davidfestal** [comment]
Deployed to production.
