### ISSUE TITLE
Download of the plugins and editor meta.yaml from the plugin registry. The URL of the plugin registry should be a wsmaster property. Get new properties from workspace attributes.

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#793]
@garagatyi please provide a description

**Comment by garagatyi** [comment]
Work was done in a [branch](https://github.com/eclipse/che/compare/master...garagatyi:integrateBroker). Closing this issue in favor of https://github.com/redhat-developer/rh-che/issues/824
