### ISSUE TITLE
Sometimes opened `manage.openshift.com/openshiftio` page doesn't work as expected

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#796]
In the new end-to-end new user registration flow, implemented in #773, sometimes the opened `manage.openshift.com/openshiftio` page doesn't work as expected and redirects to `manage.openshift.io/index` without doing proper OSIO provisioning.

Should sync with RHD team to understand why and make the whole flow more robust.

Related to #790

**Comment by ibuziuk** [comment]
@davidfestal do you think we can close this issue ?

**Comment by ibuziuk** [comment]
@davidfestal I believe this can be closed wdyt ?

**Comment by ibuziuk** [comment]
@davidfestal @alexeykazakov closing since I believe this does not occur anymore
