### ISSUE TITLE
Warning in logs on both prod&prod-preview - java.io.EOFException

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#801]
**Issue problem:** 
There is this warning in both prod and prod-preview logs:
```
java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
```
{"@timestamp":"2018-08-08T19:00:14.174+00:00","@version":1,"message":"Exec Failure","logger_name":"io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager","thread_name":"OkHttp https://osoproxy.prod-preview.openshift.io/...","level":"WARN","level_value":30000,"stack_trace":"java.io.EOFException:  null\n\tat okio.RealBufferedSource.require(RealBufferedSource.java:60)\n\tat okio.RealBufferedSource.readByte(RealBufferedSource.java:73)\n\tat okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)\n\tat okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)\n\tat okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)\n\tat okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)\n\tat okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)\n\tat okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"}
```

The frequency is as follows:
**prod** - average around 1000 per day
![image](https://user-images.githubusercontent.com/1215011/43907028-e430e18e-9bf4-11e8-9c06-3e67cca302ce.png)

**prod-preview** - average around 2000 per day
![image](https://user-images.githubusercontent.com/1215011/43907043-f5763ebc-9bf4-11e8-8a6a-2790fc0e9a0e.png)

**Comment by ibuziuk** [comment]
I think this one is not relevant anymore. Assigning to me for verification

**Comment by ibuziuk** [comment]
Still happens but quite rarely 5 occurrences for the last 24h:


> java.io.EOFException: null 	at okio.RealBufferedSource.require(RealBufferedSource.java:60) 	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)
> --
> ? thread_name |   |

**Comment by ibuziuk** [comment]
Closing in favor of https://github.com/redhat-developer/rh-che/issues/926

**Comment by ibuziuk** [comment]
Closing in favor of #926
