### ISSUE TITLE
.NET workspace - quickstart has lot of error markers

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#805]
**Issue problem:** 
It seems, that basic .NET libraries are not loaded by language server.

Note, that despite this, build&run works fine.

**Reproduction Steps:**

Create .NET workspace and add `dotnet-web-simple` sample project in there. Opening any `.cs` file shows view like this:
![image](https://user-images.githubusercontent.com/1215011/42939914-cf76baaa-8b57-11e8-96dd-69d9aaf0c07d.png)

This was found as part of verifying https://github.com/redhat-developer/rh-che/issues/763 and https://github.com/redhat-developer/rh-che/issues/505

**Comment by amisevsk** [comment]
@rhopp Could you confirm the original issue is still present on prod? I don't get error markers as in teh screenshot, but I do see two other errors, that are likely upstream issues:

1. lang server launch can timeout on first launch. An error message is displayed and there will be no ls support for that file until it is closed and reopened. Upstream issue: https://github.com/eclipse/che/issues/10151#issuecomment-420989198
2. Duplicate hovers shown (message is always repeated twice). Upstream issue: https://github.com/eclipse/che/issues/10117

**Comment by rhopp** [comment]
@amisevsk Correct. The error markers are not there. I didn't encounter the first issue you are describing (despite starting LS took some time). The second issue is present.
Closing this one.
