### ISSUE TITLE
Integrate che-plugin-registry on OSIO with RhChe to use Walking skeleton flow

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#806]
**Issue problem:** 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Closing. plugin-registry is part of the che.openshift.io flow
