### ISSUE TITLE
Expose che-plugin-registry publicly to allow access from Che UD

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#807]
**Issue problem:** 

Now che-plugin-registry is not accessible for UD on OSIO prod-preview, but we will need that for Eclipse Con epic https://github.com/eclipse/che/issues/10644

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
This one is fixed now - there are routes exposed to che-plugin-registry from both prod / prod-preview
