### ISSUE TITLE
Che `/api/token/github` endpoint is broken

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#814]
Issuing `GET` requests on Che server `/api/token/github` endpoint fails with a HTTP `500` error. Submitting a `POST` request succeeds but subsequent `GET` requests fail anyways.

From debugging a running deployment on dev-cluster, issue appears to be due to [`DefaultHttpJsonRequst`](https://github.com/eclipse/che/blob/f78caa2374064092a585def4147371d52d8d69a3/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequest.java#L293) refusing responses with unsuitable content type (responses from the fabric8 auth server have content type `application/vnd.externaltoken+json`). Additionally, as the auth server's response does not follow [expected semantics](https://github.com/eclipse/che/blob/f78caa2374064092a585def4147371d52d8d69a3/multiuser/keycloak/che-multiuser-keycloak-token-provider/src/main/java/org/eclipse/che/multiuser/keycloak/token/provider/service/KeycloakTokenProvider.java#L54) (response is just json), even without the `DefaultHttpJsonRequest` issue, the token could not be obtained.

A proper fix would probably involve rh-che specific implementation of the token controller, to match what is returned by the fabric8 auth API.

Low priority, as I don't believe this endpoint is used anywhere at the moment.

**Red Hat Che version:** 
Tested on current master (based off upstream 6.7.1)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem:
`curl -H 'Authorization: Bearer [token]' https://che.openshift.io/api/token/github` returns `500` error code with message `OK`.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Closing as outdated
