### ISSUE TITLE
Followup and fixes after the  first test phase of end2end registration flow on production

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#815]
fix the required things that might have been spotted during the first test phase (for example I detected that for some users, the factory workspace stops -erroneously it seems- immediately after creation at first start, and the user needs to refresh his factory URL to have it started finally, or something like that. Would have to investigate this case a bit more, since currently there is a lack of telemetry information for these users):

Sub-tasks:
- [x] The factories workflow after login doesn't work on Firefox #832

**Comment by ibuziuk** [comment]
@davidfestal will you be able to take a look at https://github.com/redhat-developer/rh-che/issues/832 as part of this issue ?

**Comment by davidfestal** [comment]
Hi @ibuziuk Yes, I'll look into it. That's a bit strange since I also tested on Firefox. I'll contact @scela to have more details on the precise use-case.
