### ISSUE TITLE
Create initial diagram for rhche -> osio services flows to better understand OSIO arch

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#827]
**Issue problem:** 
 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Initial diagram of osio services - https://docs.google.com/presentation/d/1VT7iwTFc_y_UzlziiS-opCfcE08TDgddURBmKJs6rQM/edit#slide=id.g412fbb98eb_0_4

**Comment by garagatyi** [comment]
I requested comment access to be able to collaborate in place - this looks more efficient.

**Comment by ibuziuk** [comment]
@garagatyi done

**Comment by garagatyi** [comment]
Looks good! (I saw non-initial diagram too, but now it is gone)

**Comment by ibuziuk** [comment]
@garagatyi @amisevsk @davidfestal could you please take a look if the initial diagram is good enough to be contributed to rh-che docs - https://docs.google.com/presentation/d/1VT7iwTFc_y_UzlziiS-opCfcE08TDgddURBmKJs6rQM/edit#slide=id.g412fbb98eb_0_4

**Comment by garagatyi** [comment]
LGTM

**Comment by davidfestal** [comment]
seems good to me as well

**Comment by amisevsk** [comment]
Looks good. Would it be possible to annotate the numbers with verbs for what that component is requesting of the next, or does that not really make sense in this case? My knowledge ends at the lines leaving che-server at the moment :)

**Comment by ibuziuk** [comment]
PR is sent https://github.com/redhat-developer/rh-che/pull/1064

**Comment by ibuziuk** [comment]
PR is merged. Closing
@amisevsk good point about adding some explanation to the flow, I believe we could gradually add details to this flow and provide more info to the Interaction of Red Hat Che with other openshift.io services
