### ISSUE TITLE
[OSD] Need to support OISO specifc parameters (e.g. space_id) in rh-che during workspace creation flow

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#834]
Current workspace startup flow on openshift.io

![image](https://user-images.githubusercontent.com/1461122/48473793-8213aa80-e7f9-11e8-8bc1-75549c771438.png)

Some clarifications of steps:

**step 1** - request is send from browser / fabric8-ui to initiate workspace creation
**step 4** - che-starter creates workpspace using Che server REST API and returns link back to fabric8-ui through fabric8-wit
**step 9** - by opening the workspace link in browser, workspace is started automatically
 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@alexeykazakov wdyt, can we close this issue ?

**Comment by alexeykazakov** [comment]
Yeah.. we can close it as outdated. Don’t need this anymore.

**Comment by ibuziuk** [comment]
Closing as outdated.
