### ISSUE TITLE
Walking skeleton pulling strategies

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#846]
**Issue problem:** 
Upstream issue https://github.com/eclipse/che/issues/11017

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Upstream issue eclipse/che#11017 is closed
