### ISSUE TITLE
Need to remove java stack which is based on `eclipse/ubuntu_jdk8` from default stacks on prod / prod-preview

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#848]
**Issue problem:** 
We have two java stacks in rh-che. One is based on `eclipse/ubuntu_jdk8` and one on `eclipse/centos_jdk8`.

Do we need both of them? Eugene already said his opinion in mattermost
> indeed.. i do not think we need an ubuntu one from upstream

I'm creating this issue to get more input before sending PR deleting one of those stacks (most probably ubuntu one).

**Comment by ibuziuk** [comment]
good catch. The default stacks on che.openshift.io should be centos based, so indeed the ubuntu one should be deleted.

**Comment by ibuziuk** [comment]
Should be closed once we update to Che 7 GA - https://github.com/redhat-developer/rh-che/pull/1481
(stacks `stacks.json` will not be used and devfiles would be used instead)
