### ISSUE TITLE
PHP stack does not have samples in rh-che

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#850]
**Issue problem:** 
PHP stack in rh-che does not have any examples, but in upstream, this stack has two examples. Was this done on purpose?

The fix would be easy enough... Just add correct tags to php stack.

The problem is, that there are two samples for php. One (`web-php-simple`) is working ok (once #849 is fixed), but the other one is deploying the project to GAE using `dev_appserver.py` and our php docker image is not ready for that.

The main question here is: Should we support the GAE sample (a.k.a. update our docker image), or should we just support the simple php sample (a.k.a. do some tags changes in samples and stacks in our repo & upstream). 
@ibuziuk @eivantsov WDYT?

**Comment by rhopp** [comment]
Or... third option - do nothing and leave php stack without samples.

**Comment by ibuziuk** [comment]
@rhopp I believe we could start with `web-php-simple`. 
@eivantsov does GAE sample works in upstream ? and we are not going to support it on osio could we easily remove it from the dashboard quickstarts ?

**Comment by eivantsov** [comment]
RH Che uses upstream samples

**Comment by ibuziuk** [comment]
@eivantsov yeah, I mean my understanding is that if the sample is presented in the dashboard than it should work OOTB. So, if upstream can handle GAE sample correctly, I believe `che.openshift.io` should do the same. However, if GAE does not work correctly with upstream, probably it makes sense to remove it from the supported samples

**Comment by eivantsov** [comment]
@ibuziuk upstream PHP stack uses an ubuntu based image. And that's why I tagged centos PHP stack as centos-php so that upstream samples never show up - they have associated commands with them. And those commands refer to apache2 while in centos based image it's httpd.. 

It's tricky to have two different sets of stacks and one list of samples.

**Comment by eivantsov** [comment]
Yes, overriding samples.json is a headache. I will add a php-centos sample then.

**Comment by rhopp** [comment]
PR in upstream created for discussion: https://github.com/eclipse/che/pull/11170

**Comment by ibuziuk** [comment]
PR has been merged upstream. Closing
