### ISSUE TITLE
Need to add a warning on Codebases UI page if user would try to create more than 5 workspaces

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#858]
Currently on in rh-che we are using default `CHE_LIMITS_USER_WORKSPACES_COUNT`, which means user can create unlimited number of workspaces. However, if we would switch to the `unique` strategy CHE_LIMITS_USER_WORKSPACES_COUNT would be set to `5` and user will not be able to create more than `5` workspaces. UI validation for it already in place in the dashboard, but we would need to add it also to the codebase UI on in openshift.io flow:

![image](https://user-images.githubusercontent.com/1461122/45169315-a8b3d480-b1fd-11e8-8554-380767104266.png)

https://github.com/eclipse/che/blob/0d27a2c5276f6a0a491ab05f34c28e750b3313bf/dockerfiles/init/manifests/che.env#L626

**Comment by garagatyi** [comment]
@ibuziuk wouldn't error from workspace creation API be populated to the UI automatically?

**Comment by ibuziuk** [comment]
@garagatyi need to check, but likely it would fail without clear reason

**Comment by ibuziuk** [comment]
Closing as outdated
