### ISSUE TITLE
Need to perform workspace data migration during the switch from `common` to `unique` PVC strategy

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#859]
Before taking decision about switching  from  `common` [1] to `unique` PVC strategy the following data should be provided as part of https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2291:

- what is the average number of workspaces per user on prod,
- what is the number of users with more than 5 workspaces

Once we figure it out the main question would be:
- what should we do with users that have more than 5 workspaces?

After that, we would need to migrate data from the common `claim-che-workspace` pvc which looks the following way:

```
pv0001
  workspaceid1
  workspaceid2
  workspaceid3
  workspaceid4
  workspaceid5
      che-logs projects <volume1> <volume2>
```

to the individual PVs
 
[1] https://www.eclipse.org/che/docs/openshift-admin-guide.html#common-pvc-strategy

**Comment by garagatyi** [comment]
@ibuziuk shouldn't we change the workspace limit to 5 on prod right away to decrease the number of users that would require special handling of 5+ workspaces after the applying of the unique strategy?

**Comment by ibuziuk** [comment]
@garagatyi do you happen to know how it would behave if there are already users with more than 5 workspaces (smth. that we need to test on minishift first) ?

**Comment by garagatyi** [comment]
Just checked with 2 workspaces and limit set to 1:
- creation of third WS fails with an appropriate message from the API
- editing, starting of existing WSs works

Looks like what we need in this particular case. The only one thing to check is how OSIO UI would react to such an error. I suppose we can try it out on a prod-preview :)

**Comment by garagatyi** [comment]
Sorry, forgot to add that I checked it on the Upstream Che

**Comment by ibuziuk** [comment]
Closing, since switch to the `unique` PVC strategy is not planned anymore
