### ISSUE TITLE
Need to support ephemeral workspace on che.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#860]
Since currently workspace startup on osio could take sufficient amount of time due to pvc mount [1], it was decided to have support of ephemeral workspace with no pvc attached. There are 2 options for supporting this:

- adding new `none` PVC strategy to the existing `common` & `unique`. When this PVC strategy is set no volume would be mounted for workspace
- having an `ephemeral` option in workspace config, which would allow having it as a per-workspace setting (need to decide how this property would be configured for users in che.openshift.io flow)

[1] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169

**Comment by l0rd** [comment]
Please consider [emptyDirs](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) and [local-ephemeral-storage](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage) when implementing that. These may provide better IOPS than the container COW filesystem.

**Comment by ibuziuk** [comment]
It was decided to have a `mount sources` property in order to disable volume mount for workspaces. Using this property would either not do any volume mount or perform mount via `emptyDirs` approach

**Comment by ibuziuk** [comment]
PR have been sent upstream

**Comment by ibuziuk** [comment]
PR is merged. Issue should be closed one we update rh-che to 6.12.0
