### ISSUE TITLE
Explore Che support of Openshift embedded OIDC server, possibly through Core OS dex

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#862]
This would be the second step of upstream issue https://github.com/eclipse/che/issues/10998:

Explore if / how Upstream Che could support the Openshift embedded OIDC provider, possibly through CoreOS dex ( though a fix for the missing `userInfo` endpoint in dex would be required).

CoreOS dex might be useful for 2 reasons:
- it returns access token as JWT tokens afaik
- it is also strongly integrated with Kubernetes, which would allow having a solution that works with both Openshift or Kubenertes as user manager underlying component.

**Comment by ibuziuk** [comment]
@l0rd is it the priority for J Train ?

**Comment by ibuziuk** [comment]
Closing as outdated
