### ISSUE TITLE
Check for plugin-registry when starting workspace with plugins

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#869]
Upstream https://github.com/eclipse/che/issues/11124

**Comment by amisevsk** [comment]
Upstream PR: https://github.com/eclipse/che/pull/11414

**Comment by ibuziuk** [comment]
@amisevsk could we close this issue ?

**Comment by amisevsk** [comment]
@ibuziuk I don't think so, it won't be pushed to prod until 6.12.
