### ISSUE TITLE
Is it possible for PVC cleanup pods to time out?

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#885]
Given that a volume mount for a PV with many files can take over 5 minutes in some cases, is there a scenario where a `rm` task in Che will time out and fail? If so, this could exacerbate the issue by leaving the PV in a state where it is full of files referred to by no workspace.

**Comment by garagatyi** [comment]
I believe it is possible and probably already happening on OSIO. 
@sleshchenko WDYT?

**Comment by amisevsk** [comment]
The concerning thing is that failed cleanup is not tracked beyond logging, so it's a problem that exacerbates itself -- if a PVC cleanup job fails, it's highly likely that the next one will fail as well. 

If there is a node workspace with a ton of files in `node_modules`, and the delete fails, those files will stick around and likely prevent future deletes, as the chgrp/chmod/chown commands are run on entire PVs when mounting.

**Comment by amisevsk** [comment]
From Kibana, I'm seeing 10-15 errors per day along the lines of
```
Unable to perform '[rm, -rf, /tmp/job_mount/<workspace-id>]' command for the workspace '<workspace-id>' cause: 'Waiting for pod 'rm-<workspace-id>' reached timeout'
```
so this appears to be a quite common issue.
