### ISSUE TITLE
Workspace start can fail prematurely due to volume mount timeout

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#886]
**Issue problem:** 
Since we are handling unrecoverable events again, we have begun to see potential issues in starting workspaces. After ~2 minutes, OpenShift will report that the volume mount has timed out, which will cause Che to fail to start the workspace well before any internally set timeout (5 mins, as far as I remember). This event does not appear to always be truly "unrecoverable", as it could be due to slow PVC mount. 

We should consider enhancing the unrecoverable events functionality / removing "failed mount" as an unrecoverable event.

**Red Hat Che version:** 
 - [x] I can reproduce it on latest official image

**Reproduction Steps:**
1. Start a workspace with a very full PV (the kind that is likely to time out)
2. Time how long it takes for launch to fail
3. Compare to the normal workspace launch timeout

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
I believe the idea is that we should not be in a situation when volume mount takes more that 2 minutes. 
This was discussed as part of https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169 
To avoid this our plan is:
- support ephemeral workspaces - https://github.com/redhat-developer/rh-che/issues/860
- potentially switch from `common` to `unique` PVC strategy - https://github.com/redhat-developer/rh-che/issues/865

**Comment by amisevsk** [comment]
+1 @ibuziuk I fully agree that probably even 1 minute is far too long for most workspaces.

I mostly created this issue to discuss whether we want to do the (relatively) simple step of removing "failed mount" as unrecoverable in the meantime before a proper fix is merged. This could be done by modifying a configmap I think. I feel like we're seeing "workspace failed to start" issues more frequently since the move to 6.10.0 because of fixing unrecoverable events.

**Comment by l0rd** [comment]
@amisevsk @ibuziuk ignoring a failed to mount event is worst than current situation. We can consider the error non blocking and keep waiting for the pod to be up and running but we should at least notify the user about the infrastructure problems.

**Comment by ibuziuk** [comment]
Closing PVC mount ~2 mins means that infra is not usable. The good thing that this does not happen anymore :crossed_fingers:
