### ISSUE TITLE
Open Declaration / Code navigation not working on che.openshift.io

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rh-che#890]
**Issue problem:** 
Went to che.openshift.io, create a blank workspace using the java-default stack, add a project from Git (https://github.com/square/okhttp).
Then I opened a Java file `okhttp/okttp/src/main/java/okhttp3/OkHttpClient.java`.
Then walked to the `newWebSocket` method and tried to open the return type `WebSocket` type but nothing happened

**Red Hat Che version:** 

version: (help/about menu)
Version:     1.0.0-SNAPSHOT       
Build Time:  2018-08-30 10:09:42  
Revision:    414a44ffa3da05d8     

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Should be fixed in Che 7 GA
