### ISSUE TITLE
Wildfly Swarm example project does not build

### ISSUE THREAD

**Issue by scela** [redhat-developer/rh-che#896]
To reproduce:

- Create a workspace from the default 'widfly-swarm' stack
- Create a project from the wfswarm-rest-http template
- Try to do mvn clean install - it fails with "
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 14.963 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
"
- Try to run the 'run' run configuration created automatically - it fails with : "Error: Unable to access jarfile target/*-thorntail.jar"

**Comment by ibuziuk** [comment]
@scela this is appeared to be a known issue on osio - https://github.com/openshiftio/openshift.io/issues/2152#issuecomment-362524343
