### ISSUE TITLE
Enormous number of `Failed to store signature keys for ws` error logs in production:

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#897]
Currently the following query on kibana returns almost 110 000 of hits (the whole number of hits for all logs is 130 000) and it keep increasing:

`kubernetes.pod_name:"rhche-18-8qk5d" AND kubernetes.namespace_name:"dsaas-production" AND message:"Failed to store signature keys for"`

```
Failed to store signature keys for ws workspace1qtjtf67adaallua. Cause: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "che_sign_key_pair" violates foreign key constraint "fk_sign_workspace_id"
  Detail: Key (workspace_id)=(workspace1qtjtf67adaallua) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO che_sign_key_pair (workspace_id, private_key, public_key) VALUES (?, ?, ?)
	bind => [3 parameters bound]
Query: InsertObjectQuery(SignatureKeyPairImpl{workspaceId='workspace1qtjtf67adaallua', publicKey=SignatureKeyImpl{id=2465156, algorithm='RSA', format='X.509', encoded=[48, -126, 1, 34, 
48, 13, 6, 9, 42, -122, 72, -122, -9, 13, 1, 1, 1, 5, 0, 3, -126, 1, 15, 0, 48, -126, 1, 10, 2, -126
```

Sentry - https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/7129/

**Comment by ibuziuk** [comment]
Upstream issue https://github.com/redhat-developer/rh-che/issues/897

**Comment by ibuziuk** [comment]
While testing on dev cluster I was not able to identify the connection of this issue with breaking idling during rollout update - https://github.com/redhat-developer/rh-che/issues/899
deployments / pods are not cleaned and still presented in namepsace but workpsace itself is stopped by che-server and no output `Failed to store signature keys for ws ` is presented in the logs

**Comment by garagatyi** [comment]
Just checked prod and figured out that there are plenty of logs still. Those I checked were from workspaces that were accessed last time 7 to 20 days ago! So those logs are generated by "ghost" workspace deployments.
I did that investigation using Prod logs and Woopra. Kudos to David for explaining how to use it.

**Comment by garagatyi** [comment]
So if we want to stop receiving those events we need to cleanup namespaces somehow.

**Comment by ibuziuk** [comment]
@garagatyi am I correct that woopra provides info about the user / namespace? I believe we need to identify namespaces and provide the list of them to SD as part of https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2337 so that they would be able to clean it by running smth. like `oc delete all -l che.workspace_id` in the namespaces. WDYT ?

**Comment by garagatyi** [comment]
I think we can do that, but not sure how to do that without creating a Woopra report per exception. Maybe @davidfestal could help here?

**Comment by davidfestal** [comment]
@ibuziuk Woopra doesn't provide information about namespace, nor about workspace deletion. It can only give information about the last time a workspace was used by a given user.

But let me think about it, since we might also query Woopra through the API...

**Comment by ibuziuk** [comment]
@davidfestal if we know the user  we already have info about his username / email, right ? So, we should be able to obtain info about the namespace by querying  `api/users?filter[username] / [email]`. If we can not  do it with woopra we should be able to do it manually at very least

**Comment by davidfestal** [comment]
sure

**Comment by ibuziuk** [comment]
HK issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2355

**Comment by ibuziuk** [comment]
Closing as outdated
