### ISSUE TITLE
rh-che on prod has been restarted a few times due to OOMKilled

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#898]
yesterday che has been updated on prod to the latest version 6.11.0. However, during the day rh-che pod was restarted 4 times with `OOMKilled` exception. 
```
Container rhche
State:
Running since Sep 19, 2018 7:37:28 PM
Last State
Terminated at Sep 19, 2018 7:37:27 PM with exit code 137 (OOMKilled)
Ready:
true
Restart Count:
4
```
Note there was a workshop with 30 - 40 participants during this day, and it looks like we never tested rh-che under sufficient load on osio

- [ ] How can we reproduce the OOM? Starting hundreds of simultaneous workspaces is enough?
- [ ] What is the OOM root cause? What classes/methods are using more memory?
- [ ] With 1.5G memory limit what's the maximum number of simultaneous workspaces Che is able to serve?

**Comment by ibuziuk** [comment]
@rhopp @Katka92 @ScrewTSW will it be possible to setup 100 hundred of tests accounts for prod-preview and run stress tests against it ?

**Comment by rhopp** [comment]
@ibuziuk Katka already started working on this. 
@Katka92 Could you create an issue for this (include it in this sprint) and link it here, so we can track the progress?

**Comment by garagatyi** [comment]
@ibuziuk could Che global SA help us with this? We might be able to trick Che and let master create workspaces in different namespaces without having dozens of clients running in parallel. But in any case, we would need these dozens of accounts to have namespaces.

**Comment by ibuziuk** [comment]
@garagatyi well, I actually thought CHE SA would be impl detail and the tests would be run in parallel using OSIO token against rh-che on prod-preview

**Comment by garagatyi** [comment]
Memory consumption by upstream Che with the grow of the load is unclear. I created an issue for that https://github.com/eclipse/che/issues/11326

**Comment by ibuziuk** [comment]
Upstream issue - https://github.com/eclipse/che/issues/5443
Root cause of the problem - https://github.com/eclipse/che/issues/5443#issuecomment-426578251

**Comment by ibuziuk** [comment]
The problem has been workarounded by increasing RAM to 4GB but according to metrics from prod the memory consumption is still tend to keep growing and could result in new OOM restarts:

![image](https://user-images.githubusercontent.com/1461122/47386569-3d6e8500-d70d-11e8-8e2c-fbb53df4b51b.png)

**Comment by ibuziuk** [comment]
@rhopp could you please create an issue for reproducing OOM aginst rh-che on dev cluster?

**Comment by garagatyi** [comment]
Related to https://github.com/eclipse/che/issues/11459

**Comment by ibuziuk** [comment]
Closing. Currently there is no OOM on prod / prod-preview
