### ISSUE TITLE
Correctly track the referrer in the end2end provisioning flow telemetry events 

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#908]
Add the real referrer in the end2end provisioning flow telemetry events.

This should be done in the `RhCheKeycloak.js` file, most probably by storing the initial referrer in the first Dashboard page landing, and reusing it when the page is being refreshed during either login or account linking.

**Comment by ibuziuk** [comment]
@slemeur could you please tell if this is a priority for the next sprint ?

**Comment by slemeur** [comment]
We can hold a bit on this one.

**Comment by ibuziuk** [comment]
Closing as outdated
