### ISSUE TITLE
Bring back end2end provisioning flow resources files (JS, html) to the wsmaster

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#910]
In the first implementation of the end2end provisioning flow, the 3 following files:
- `OIDCKeycloak.js`
- `RhCheKeycloak.js`
- `provision.html`

have been stored [in the GWT assembly](https://github.com/redhat-developer/rh-che/tree/master/assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak) to be accessed without authentication from the client-side.

However now that we have [disabled authentication](https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/DisableAuthenticationInterceptor.java#L44) on the [`fabric8-che-analytics`](https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/AnalyticsService.java#L27) endpoint, we should bring back the 3 resources files mentioned above as resources of the wsmaster assembly, available under the `fabric8-che-analytics` API path.

However this will require updating the corresponding [ che-keycloak-js-adapter-url](https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.config.yaml#L24) property with the new path. In order to do that smoothly, thsi would probably be done in several steps:
- add the files in wsmaster (without removing those in the GWT assembly)
- deploy 
- change the config map property
- once it has been done in prod-preview and prod, clean the files from the GWT assembly.

**Comment by ibuziuk** [comment]
Closing as won't fix
