### ISSUE TITLE
Add and track Che telemetry events for 'push to remote', 'create project', and 'import project' 

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#911]
Related to EPIC https://github.com/redhat-developer/rh-che/issues/765

**Comment by ibuziuk** [comment]
@slemeur could you please clarify if it is a priority for the next sprint

**Comment by slemeur** [comment]
Yes, I think this one is pretty important as it allows us to better know what the users are doing and also qualify the level of engagement. 

This issue has an higher priority than #908 .

**Comment by davidfestal** [comment]
Here are some guidelines to add the support of a new event:
- Add specific properties of the new event (ie `PROGRAMMING_LANGUAGE` is a property specific to the `edit workspace file in Che` event):
https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/EventProperties.java#L15
- Add the declaration for the new event, with the estimated duration of the event, and the related specific properties:
https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsEvent.java#L22
- Add the submission of the new event when the related action is intercepted.
https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/UrlToEventFilter.java#L116
As shown by the code example above, for now tracked actions are intercepted through a filter on the corresponding wsagent API. Though limited and subject to become obsolete (because wsagent will disappear with ws.next), this works quite well for the already defined events, and should work also for `create project`, `project import` and (possibly) for `push to GitHub` events.
So just have a look at the corresponding endpoint calls in the wsagent access log that can be found in the `/workspace_logs/ws-agent/logs/` directory, to find the precise API call that would best fit.

Of course, on could also subscribe to published events  or even intercept websockets activity to catch much more events. However I don't think it is worth the work for now because of the following upcoming  issue: https://github.com/redhat-developer/rh-che/issues/690.

**Comment by garagatyi** [comment]
@davidfestal thanks for the details!

**Comment by amisevsk** [comment]
PR https://github.com/redhat-developer/rh-che/pull/963 adds events for "commit" and "push". Create/import project is somewhat more complicated as it seems the current method of using `UrlToEventFilter` will not work.

**Comment by davidfestal** [comment]
@amisevsk don't you think we should open a new issue for the remaining part, and set this issue as PR Merged ? (for burndown chart ;-) ) ?

**Comment by amisevsk** [comment]
@davidfestal Good point :)

https://github.com/redhat-developer/rh-che/issues/988
