### ISSUE TITLE
Che workspace "Java CentOS" fails to start with anyuid addon applied

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#912]
Placeholder for https://github.com/minishift/minishift/issues/2824

**Comment by agajdosi** [comment]
Hi @ibuziuk, is there any progress on this issue?

**Comment by agajdosi** [comment]
Hi @ibuziuk, we still face this issue with OKD 3.11.0, affected workspaces:
- Java CentOS - with and without anyuid enabled
- CentOS WildFly Swarm - only with anyuid enabled

**Comment by ibuziuk** [comment]
Sorry, unfortunately it looks like we do not have capacity in the next sprint to look at this issue.
@l0rd any ideas how we should handle this issue ? could it be postponed or someone from other Che teams could give us a hand with it ?

**Comment by ibuziuk** [comment]
@agajdosi are you to also close this one ?

**Comment by agajdosi** [comment]
Hi @ibuziuk, thank you for the response and care. I have good news, we got some activity around this issue on Minishift side and recently this issue is no longer reproducible for us. I have closed the issue on Minishift side and you can close this one.
