### ISSUE TITLE
Make the repos of `sample` projects configurable in Che telemetry 

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#913]
In order to store a `source types` properties on Che telemetry events (that shows the type of sources of the projects added at workspace creation), we compare the Git URL of projects with the one of the official Che samples, and when it matches, tag the source type as a `sample`:

https://github.com/redhat-developer/rh-che/blob/master/plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/AttributesCompleter.java#L63

We should replace this fixed value with a property that would allow a list of repos to compare against. This property would take the Che samples repo URL as default value.

**Comment by ibuziuk** [comment]
closing as outdated
