### ISSUE TITLE
Provide more detailed documentation about Che telemetry implementation

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#914]
- Provide complete documentation about:
    - the design + Java implementation of Che workspaces telemetry
    - the design of Che telemetry related to client-side end2end flow
    - The various parts of Che telemetry work that  are stored in Woopra itself (trigger, segments, definition of *official* reports)
- Provide a link to this additional documentation into the HK dev guide.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/16715
