### ISSUE TITLE
rh-che addon is broken for OpenShift 3.10.0

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#919]
There are two issues currently with running rhche on minishift 1.24 + OpenShift 3.10:
1. OpenShift 3.10.0 deprecates the [`oc secrets new-basicauth`](https://github.com/redhat-developer/rh-che/blob/d3573c5336be4610e0cadf6848b4fe62eb1ce76d/openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon#L16) command, so installing the prerequisites does not work
   - this command needs to be changed to: 
     ```
     oc create secret generic openshift-identity-provider -n rhche --from-literal=username='-' --from-literal=password='-' --from-file=ca.crt=./openshift.local.config/master/ca.crt --type=kubernetes.io/basic-auth'
     ```
2. Fixing 1) will still leave us with https://github.com/minishift/minishift/issues/2825 which seems to prevent any `oc` commands from being run in a container via ssh.

**Comment by ibuziuk** [comment]
We are not planning to fix rh-che addon for OpenShift 3.10 and below. One should use 3.11 for working with addon. Closing
