### ISSUE TITLE
Adapt RhChe to the new scope limitation of the machine token signed requests in Upstream

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#927]
In the upcoming 6.12.0 upstream Che release, a new mechanism to limit the scope of the machine token signed requests was introduced.
This is a breaking change for RhChe currently since in some cases RhChe performs calls from the Workspace agent to the wsmaster, that will be out of this new restricted scope.
See https://github.com/redhat-developer/rh-che/pull/902#issuecomment-424645862 for more details.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/redhat-developer/rh-che/issues/946
