### ISSUE TITLE
Do we have RhChe memory consumption metrics on zabbix?

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#929]
**Issue problem:** 
I can not see meaningful memory consumption data on Zabbix. 
Now, Zabbix shows for prod:
![image](https://user-images.githubusercontent.com/1851863/46079410-c1316200-c19f-11e8-9798-99d5abd0dbc1.png)
Whereas OS dashboard shows:
![image](https://user-images.githubusercontent.com/1851863/46079454-d908e600-c19f-11e8-827e-719d8a4109a8.png)

Do we have proper metrics for that?

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
I believe that the zabbix metric is db, not pod related

**Comment by garagatyi** [comment]
Do we have pod related metrics?

**Comment by ibuziuk** [comment]
good question. I'm not aware of those metrics. @jfchevrette @pbergene am I correct that 
memory consumption metrics for pods on rh-idev / dsaas are not currently processed by zabbix ?

**Comment by pbergene** [comment]
Those are the metrics for the rhche  in Zabbix.  Rhche deployment and pods metrics can be found under the metrics.dsaas.openshift.com host.

**Comment by jfchevrette** [comment]
@ibuziuk sent you a link to the metrics privately.
