### ISSUE TITLE
Che: Terminal Tab default focus

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#93]
_From @burrsutter on June 7, 2017 2:6_

When I click on the Terminal tab header, I also have to click into the window to give it focus and a cursor.  This is particularly annoying when switching command tabs.  How about the Terminal tab gain focus/cursor by default when clicked on and brought to the foreground.

_Copied from original issue: openshiftio/openshift.io#202_

**Comment by joshuawilson** [comment]
@gorkem here is another Che issue.

**Comment by ibuziuk** [comment]
@l0rd need to open an issue upstream

**Comment by l0rd** [comment]
Upstream issue: https://github.com/eclipse/che/issues/5741
