### ISSUE TITLE
Change Che master logs encoding in PR check deployment to plaintext 

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#930]
**Issue problem:** 
Now logs of Che master in PR check is JSON encoded. And This is not the easiest way to read logs for a human.
We can change it from JSON to PLAINTEXT with setting [this](https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.app.yaml#L226) env var to `plaintext` [here](https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.config.yaml#L50).  

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
@ibuziuk @davidfestal @amisevsk @rhopp and others :) WDYT?

**Comment by ibuziuk** [comment]
+1 for this

**Comment by rhopp** [comment]
What about switching that to plaintext for all deployments done by `dev-scripts/deploy_custom_rh-che.sh`? We could add a new switch to that script, but do we have a scenario, where you would deploy rhche using this devscript and want json encoding?

**Comment by davidfestal** [comment]
+1 for plain text

**Comment by ibuziuk** [comment]
@rhopp well, I believe that if we change cm it would affect all the deployments created via `dev-scripts/deploy_custom_rh-che.sh` in any case. Technically, we could add some flags to the script for tuning this option, but I would probably simply opt for updating rh-che cm

**Comment by garagatyi** [comment]
Simpler is better

**Comment by rhopp** [comment]
Hmm... It should be in plaintext already...
Here's where we change that in the configmap: https://github.com/redhat-developer/rh-che/blob/master/dev-scripts/deploy_custom_rh-che.sh#L302


And looking into config map on devtools-dev cluster: 
![image](https://user-images.githubusercontent.com/1215011/46084772-bd540e80-c1a4-11e8-9487-28bfedd13724.png)
And the logs from latest PR check deployment on devtools-dev cluster:
![image](https://user-images.githubusercontent.com/1215011/46084810-d6f55600-c1a4-11e8-9dca-2c2ced09d207.png)

**Comment by ibuziuk** [comment]
@rhopp oh, looks like we can simply close the issue in this case :-)

**Comment by rhopp** [comment]
@ibuziuk I would like to wait for @garagatyi's confirmation.

**Comment by garagatyi** [comment]
you are right!
