### ISSUE TITLE
How to avoid issues with k8s service number limit in WS.NEXT

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#934]
**Issue problem:** 
In WS.NEXT we use k8s services for sidecars service discovery. This means that Theia (2 endpoints) + 3 plugin sidecars might generate 5 services. Apart from that, Che generates a service for each container in a workspace to expose public ports of servers (including sidecar's public endpoints).  
Right now we have a limit of 5 services in OSIO namespace and this leads us to a situation when WS.NEXT workspace hits quota issue. 
We can optimize the usage of services by public servers/endpoints to 1 per pod.
But we still have issues in a case when even 3 plugins with sidecars are used. An example is a WS with
- terminal/exec sidecar
- JDT.LS sidecar 
- Bayesian sidecar

Such a workspace would not be able to start because of quotas. We need to find a solution for that.

**Comment by garagatyi** [comment]
@sleshchenko @l0rd @ibuziuk FYI

**Comment by amisevsk** [comment]
@ibuziuk I feel like this could be a problem in general, if plugins are allowed to require a service. It would mean the service number quota would govern how many plugins can be added to a workspace.

**Comment by garagatyi** [comment]
We can tune it but @amisevsk is right - we need to think what solution would be the best in a long term

**Comment by l0rd** [comment]
Good catch @garagatyi. Anyway not all plugins will run in a separate container. I think that 10 services should be enough for 90% of the cases. 15 services would be even better. Let's ask SD team if we can increase it to 15.

**Comment by ibuziuk** [comment]
PR where we could start discussion with SD regarding service increase - https://github.com/fabric8-services/fabric8-tenant-che/pull/113

**Comment by amisevsk** [comment]
@garagatyi Wouldn't it be possible to have a single "plugins" service that maps all of the appropriate ports? This could avoid the issue entirely. On the provisioning end, this could be done by simply modifying `SidecarServicesProvisioner#provision()`.

**Comment by ibuziuk** [comment]
PR have been merged https://github.com/fabric8-services/fabric8-tenant-che/pull/113 now there are new `15` quota for number of services. @garagatyi if it is the last change  that is planned regarding `fabric8-tenant-che` we could request cluster wide tenant update.

**Comment by garagatyi** [comment]
I created an issue to optimize usage of l8s services https://github.com/eclipse/che/issues/11452

**Comment by ibuziuk** [comment]
can we simply close this issue since `15` services should be enough for osio until eclipse/che#11452 is fixed ?

**Comment by garagatyi** [comment]
yes, I agree
