### ISSUE TITLE
Weird font in terminal

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/rh-che#935]
<img width="1777" alt="screen shot 2018-09-28 at 09 39 46" src="https://user-images.githubusercontent.com/1636769/46197067-01602400-c309-11e8-9fe9-90c9c2aca7e3.png">

The font in the terminal looks weird.

I'm on Mac and was using chrome v69

**Comment by garagatyi** [comment]
This is upstream issue

**Comment by ibuziuk** [comment]
Upstream issue - https://github.com/eclipse/che/issues/10945

**Comment by ibuziuk** [comment]
Should be fixed in 6.13.0 - https://github.com/eclipse/che/pull/11576
