### ISSUE TITLE
Protect the End2end flow from bots

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#941]
We should protect the end2end provisioning flow of `che.openshift.io` against bots, so that they cannot sucessfully pass the regsitration flow as it is the case currently.

That's related to the following HK issues:
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2351
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2356

**Comment by garagatyi** [comment]
@davidfestal Could you add more details on what exactly is needed to be done to close this issue? Could you also label the complexity of this issue? I think it might be useful to let someone but you in the team to work on that to share knowledge about e2e flow and avoid bus-factor.

**Comment by davidfestal** [comment]
@garagatyi I created this issue after discussing with @ibuziuk and the SD team about the problem.
And it's on purpose that I didn't add technical details directly in this issue description.

Please see
https://chat.openshift.io/developers/pl/jhrpu5xfj7yqjnfrph6kirf69c

See also:
https://chat.openshift.io/developers/pl/wcbjirbottyq5mttr31sbtoqdh
https://chat.openshift.io/developers/pl/dceqbe3p83fgzjm5b8azof7bch

I didn't assign myself to the issue, so even if I'm OK to start immediately on this as a critical issue, I see no problem if another team member would work on it, and I will provide as much information as necessary for him to start with.

So let's put `intermediate` as a level, unless you have another feeling.

**Comment by davidfestal** [comment]
This has been deployed to production, but we're waiting for HK issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2377 to be fixed in order to have the protection enabled.

**Comment by ibuziuk** [comment]
@davidfestal HK issue was closed. I guess we can close this issue now ?
