### ISSUE TITLE
Need to update rh-che to 6.12.0 version and rollout it to production

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#946]
`6.12.0` version is going to contain a fix for rhche pod restarts due to `OOMKilled` https://github.com/eclipse/che/issues/5443#issuecomment-426578251

**Comment by davidfestal** [comment]
@amisevsk Quick update on this issue : I've updated the ongoing PR (https://github.com/redhat-developer/rh-che/pull/931) with my last changes. The build is successful locally, but the last changes should still be tested on dev cluster.

**Comment by amisevsk** [comment]
Thanks @davidfestal !
