### ISSUE TITLE
CHE client is not cached which causes very slow workspace startup

### ISSUE THREAD

**Issue by riuvshin** [redhat-developer/rh-che#961]
every single time I restart my workspace on che.OSIO it downloads `9.3`MB client JS file
https://che.openshift.io/_app/BB88D2F21134C170CD36477D6121D182.cache.js
it takes `59-70` seconds for me just to get this file every time I run WS.
that makes starting workspaces really slow... this file should be cached and every build of che should have new name for the script `BB88D2F21134C170CD36477D6121D182` (I believe we have this)
so clients will not be affected if new version will be shipped.

**Comment by l0rd** [comment]
@davidfestal do you think that this can be related to woopra or to something we customize in rh-ch? Or the same behavior exist in upstream che too?

**Comment by l0rd** [comment]
@riuvshin what stack have you been trying?

**Comment by davidfestal** [comment]
> @davidfestal do you think that this can be related to woopra or to something we customize in rh-ch? 

@l0rd I don't see how it could be related at all.

**Comment by riuvshin** [comment]
@l0rd any stack it is client gwt js  so it will be downloaded for any stack

**Comment by riuvshin** [comment]
<img width="1676" alt="screen shot 2018-10-09 at 17 02 07" src="https://user-images.githubusercontent.com/1636732/46674555-167c6300-cbe5-11e8-9fcc-b0ed8d5abad5.png">
two times same script...

**Comment by riuvshin** [comment]
we were fixing this for CHE5 on codenvy.io @skabasniuk knows more about this

**Comment by l0rd** [comment]
cc @skabashnyuk

**Comment by riuvshin** [comment]
this could be che upstream issue but Im not sure.

**Comment by riuvshin** [comment]
sorry guys that was incognito mode thing, i do not have "disable cache" enabled but it do not cache anyways...
in normal chrome tab caching works as expected, so closing this
