### ISSUE TITLE
Che failed to update because workspace recovering takes too much time and Che gets killed by OC 

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#966]
**Issue problem:** 
On a recent update of RhChe we had a lot of workspace active. Workspace state recovering process took too much time and the pod was killed because of not passing liveness probes.  
We need to make workspaces recovering not blocking proper Che server start. 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by amisevsk** [comment]
Should be solved by https://github.com/eclipse/che/pull/11592

**Comment by ibuziuk** [comment]
@amisevsk I believe we can close this one
