### ISSUE TITLE
Idling of a Che 7 workspace doesn't work on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#975]
**Issue problem:** 

If I start a Che 7 workspace ([stack example here](https://gist.github.com/l0rd/2ff9391d9cabbc861d9e7e9102efcaf3)) on che.openshift.io it's not idled after 15 minutes as it should.

@eclipse-che/theia-activity-tracker doesn't look to be in the image that is started (eclipse/che-theia:plugin-id-nightly)

cc @mmorhun @benoitf

**Comment by mmorhun** [comment]
I checked that `@eclipse-che/theia-activity-tracker` is included in the Theia image.
However, the extension is designed to notify Che master about activity in workspaces to prevent its stopping, so its purpose is to prevent stop of workspace if user is doing something in Theia IDE (but not stop idling workspaces).

**Comment by l0rd** [comment]
Closing. It's currently working on production.
