### ISSUE TITLE
Regressions and errors following the deployment of the end2end flow protection

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#976]
**Issue problem:** 

- The End2End flow protection recently released to production introduced a regression that makes a new requirement for the user to disable popups on his browser. 
- There are a number of log entries in Sentry that show some cleaning / enhancements to be done in the way errors are caught on the client-side and sent back on the server-side.

**Red Hat Che version:** 

OSIO production and prod-preview

**Comment by ibuziuk** [comment]
@davidfestal do you think we can close this issue now ?

**Comment by ibuziuk** [comment]
I believe this issue can be closed now

**Comment by davidfestal** [comment]
This HK issue should be fixed before deploying the last PR to production:

https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2414
