### ISSUE TITLE
Add docs on what is the process of updating deployment yamls.

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#979]
**Issue problem:** 
It is not clear what deployment files are used directly and what files have copies for some environments.
For example:
- to do an update of the deployment config we update file directly. It applies to environments: local/dev cluster/PR tests/prod-preview/prod.
- to do an update of the config map we:
 - update <file> for environments: local/dev cluster/PR tests
 - update <another file> for environments: prod-preview
 - create PR with a description of a change for environments: prod

Would be also cool to have in this doc how to update plugin registry version. 

Since we have different policies/strategies for different environments it would provide needed info in a case new team member join, another team member want to contribute or even when some of the existing team members keep forgetting the process :wink: 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
Added addition of che plugin registry update docs to the description.

**Comment by ibuziuk** [comment]
PR with che-plugin-registryupdated docs - https://github.com/redhat-developer/rh-che/pull/1220

**Comment by ibuziuk** [comment]
Docs for updating template / cm for deployment on different infrastructure - https://github.com/redhat-developer/rh-che/pull/1223

**Comment by ibuziuk** [comment]
Both PRs have been merged. Closing
