### ISSUE TITLE
Fix daily CI job https://ci.codenvycorp.com/job/rh-che-ci-master/

### ISSUE THREAD

**Issue by apupier** [redhat-developer/rh-che#989]
**Issue problem:** 
 the job is launched daily and has always failed (#720 right now)

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by rhopp** [comment]
@apupier The job is technically correct, per se. There was a change upstream, which breaks the rh-che build: https://github.com/eclipse/che/issues/10617
But as far as we are currently based on upstream version 6.12.2, we cannot fix this in our side until we switch to 6.13 (WIP here: https://github.com/redhat-developer/rh-che/pull/965)

And another note - we are working on switching this job to ci.centos.org and extending to not only build/compile rh-che, but also deploying and running some tests against it (if the build succeeds of course) (issue here: https://github.com/redhat-developer/che-functional-tests/issues/368)

**Comment by ibuziuk** [comment]
Ci is currently working just fine. Also potential breaking changes are tracked as part of the https://github.com/redhat-developer/rh-che/issues/1015 for 6.14.0 release

[1] https://ci.codenvycorp.com/job/rh-che-ci-master/
